flytekit/__init__.py
flytekit/clis/flyte_cli/main.py

* Name is not a required parameter in the API, thus it shouldn't be on the CLI
* Allow urns-only as a flag for piping to update-launch-plan

Improve List Launch Plan Versions CLI

---

flytekit/common/tasks/sdk_runnable.py
flytekit/configuration/resources.py
tests/flytekit/unit/configuration/configs/good.config
tests/flytekit/unit/configuration/test_resources.py
tests/flytekit/unit/sdk/tasks/test_sidecar_tasks.py
tests/flytekit/unit/sdk/tasks/test_tasks.py

Allow users to specify default resource requests and limits via config.

Implement Default Configurations for Resource Limits

---

scripts/flytekit_install_spark.sh

Patch latest k8sclient for https://issues.apache.org/jira/browse/SPARK-28921. Ref: https://github.com/apache/spark/pull/25640/

Patch latest K8s-client

---

flytekit/__init__.py

* Remove `sloth-import` dependency
* Fix hive unit test behavior
* Add default configurations for resources

[Release] v0.2.1

---

flytekit/__init__.py

* Upgraded Spark install script
* Loosened Protobuf Requirement

Update Version for Release

---

flytekit/clients/friendly.py
flytekit/clients/raw.py

As the title says, implements support for the RelaunchExecution API - https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/service/admin.proto#L221

Add support for relaunch_execution API

---

flytekit/clis/sdk_in_container/launch_plan.py
tests/flytekit/unit/cli/pyflyte/test_launch_plans.py

Adding the sub command activate-all to the launch plan

Adding the sub command activate-all to the launch plan

---

flytekit/common/exceptions/user.py
flytekit/common/tasks/task.py
flytekit/engines/common.py
flytekit/engines/flyte/engine.py
flytekit/engines/unit/engine.py
tests/flytekit/unit/common_tests/tasks/test_task.py
tests/flytekit/unit/engines/flyte/test_engine.py

The use case is alway fetching and running the latest task.
@kumare3 wdty?

fetch latest task

---

.travis.yml
README.md
scripts/flytekit_build_image.sh
scripts/flytekit_spark_entrypoint.sh

As commented https://github.com/lyft/flytekit/pull/55/files#r356599004

fix IMAGE_NAME and enforce shellcheck

---

flytekit/__init__.py

Bump flytekit version

---

flytekit/__init__.py

Remove the travis version of pypi push now that we have github workflows #85
[bug fix] Append '/' to remote_path for gcs #84

Release: v0.5.1

---

pull_request_template.md

Adds a standardized pull request template from boilerplate
Added a new pull_request_template.md. As there is no boilerplate for flytekit, I manually copied over the pull_request_template.md. 
https://github.com/lyft/flyte/issues/194
NA

Adding pull request template for flytekit

---

flytekit/__init__.py
flytekit/common/workflow.py
tests/flytekit/unit/common_tests/test_workflow_promote.py

Add metadefaults to workflow constructor and uncomment subworkflow tests
_NA_
OR

add metadata_defaults to workflow constructor

---

flytekit/__init__.py

Nothing, just bump the version for release.
https://github.com/lyft/flyte/milestone/2
NA

Bump to a non-beta version (v0.6.0)

---

.travis.yml
README.md
setup.py

This PR fixes 2 problems
1. Ensure that the PYPI page is correctly formatted
2. Ensures that a code coverage report is published for Flytekit
https://github.com/lyft/flyte/issues/258
NA

PYPI readme fix and publish coverage to Codecov

---

flytekit/__init__.py
flytekit/clis/sdk_in_container/register.py
flytekit/clis/sdk_in_container/serialize.py
flytekit/common/launch_plan.py
flytekit/common/mixins/registerable.py
flytekit/common/tasks/task.py
flytekit/common/workflow.py
flytekit/models/core/identifier.py
tests/flytekit/unit/common_tests/tasks/test_task.py
tests/flytekit/unit/common_tests/test_launch_plan.py
tests/flytekit/unit/common_tests/test_workflow.py
tests/flytekit/unit/common_tests/test_workflow_promote.py

This is step 1 of the issue linked below.  This corrects the serialization component of pyflyte.
* Minor update to the registration code to just aggregate everything into a list first, and then run register.
* This PR basically copies the registration process, but instead of registering against admin, will create the objects necessary for registration at a later time.
* The same topo sort is used to correctly ascertain the order in which things should be registered later, enforced by adding an index to the start of the filename.
* This code path does not rely on the engine.
https://github.com/lyft/flyte/issues/225
NA

Serialization to produce registerable entities

---

tests/flytekit/unit/models/test_dynamic_wfs.py

Minor PR - this just keeps master up to date with changes on 0.7 branch.

Merge release 0.7.1

---

flytekit/__init__.py

Just bumping the version for release.

Version v0.8.0

---

flytekit/__init__.py
flytekit/clients/raw.py

Minor bug with logging.
NA
NA
NA

Fix logging

---

flytekit/clients/friendly.py
flytekit/clients/raw.py

In cases where we have a registration conflict, we should print out what it is that the user was trying to register so that the user can compare against what's stored in Admin.
In the future, we should have Admin return a proper diff.
Adding logging.
Auto-formatted
https://github.com/lyft/flyte/issues/340
NA

Improve logging in friendly client

---

flytekit/__init__.py
flytekit/common/tasks/presto_task.py

Somehow I accidentally reverted the changes in `presto_task.py` made here: https://github.com/lyft/flytekit/pull/126/files
when I pushed to this PR here: https://github.com/lyft/flytekit/pull/107/commits/cebd511b29d7cc48756f3d32176d19104eb6df39
_NA_
OR

Reapply presto change

---

README.md
flytekit/__init__.py
flytekit/plugins/__init__.py
flytekit/tools/lazy_loader.py
scripts/flytekit_install_spark3.sh
setup.py

Add support for Spark 3.0 : pyspark + install script 
https://github.com/lyft/flyte/issues/426
_NA_
OR

Support Spark 3.0

---

flytekit/__init__.py

Adds an init file.
Added file.
NA
NA

Sagemaker folder missing init

---

flytekit/__init__.py

Init file missing
Added file.
NA
NA

More sagemaker init

---

flytekit/clis/flyte_cli/main.py

LInk to existing documentation for setting cluster resources in cli command.
_NA_
OR

More documentation for update_cluster_resource_attributes cli command

---

flytekit/__init__.py
flytekit/models/launch_plan.py
tests/flytekit/unit/models/test_launch_plan.py

Handle old style deprecated auth in launch plans

---

flytekit/__init__.py
flytekit/clis/sdk_in_container/register.py

This is the master branch version of the same change done here:
https://github.com/lyft/flytekit/pull/176

Remove double-iteration (legacy code fix)

---

flytekit/annotated/context_manager.py
flytekit/annotated/executors.py
flytekit/annotated/stuff.py
flytekit/bin/entrypoint.py
flytekit/common/promise.py
flytekit/engine.py
tests/flytekit/unit/use_scenarios/unit_testing/test_type_hints.py

wip ignore

---

flytekit/__init__.py
flytekit/interfaces/data/s3/s3proxy.py

Fix S3 proxy settings get (release 0.12)

---

flytekit/__init__.py
flytekit/interfaces/data/s3/s3proxy.py

The configuration options were not being read correctly.
_NA_
OR

Fix S3 proxy settings get

---

flytekit/__init__.py
flytekit/interfaces/data/s3/s3proxy.py
setup.cfg
tests/flytekit/unit/interfaces/data/s3/test_s3_proxy.py

Add loop to S3 retries (v0.12)

---

flytekit/__init__.py
flytekit/interfaces/data/s3/s3proxy.py
tests/flytekit/unit/interfaces/data/s3/test_s3_proxy.py

Add loop to S3 proxy

---

flytekit/annotated/promise.py
flytekit/annotated/task.py
flytekit/annotated/workflow.py
flytekit/engine.py
tests/flytekit/unit/use_scenarios/unit_testing/test_type_hints.py

Annotations promise implementation

Replace with promises throughout and allow tuples to be returned

---

Makefile
dev-requirements.txt
flytekit/clis/sdk_in_container/serialize.py
flytekit/common/nodes.py
flytekit/common/tasks/sagemaker/hpo_job_task.py
flytekit/common/tasks/sagemaker/types.py
flytekit/common/types/base_sdk_types.py
flytekit/common/types/proto.py
flytekit/models/literals.py
flytekit/models/sagemaker/hpo_job.py
flytekit/models/sagemaker/parameter_ranges.py
flytekit/plugins/__init__.py
flytekit/sdk/types.py
flytekit/type_engines/default/flyte.py
requirements-spark3.txt
requirements.txt
tests/flytekit/common/workflows/sagemaker.py
tests/flytekit/unit/common_tests/types/test_proto.py
tests/flytekit/unit/models/sagemaker/test_hpo_job.py
tests/flytekit/unit/models/sagemaker/test_parameter_ranges.py
tests/flytekit/unit/sdk/tasks/test_sagemaker_tasks.py
tests/flytekit/unit/type_engines/default/test_flyte_type_engine.py

basically ran
```
git co annotations
git pull
git co -b merge-again
git fetch origin
git merge origin/master
```
and resolved conflicts

[ignore] Annotations - try to merge master again

---

flytekit/annotated/task.py
flytekit/annotated/testing.py
tests/flytekit/unit/annotated/test_type_hints.py

Any task can be mocked and mocking behaviour should be altered based on
inputs

Mocking support for tasks

---

dev-requirements.txt
flytekit/__init__.py
requirements-spark3.txt
requirements.txt

Run make requirements.
Run make requirements so as to pick up a newer version of the cryptography package.  We got a notice saying that cryptography 3.1.1 had a vulnerability.
NA

Run make requirements

---

flytekit/annotated/task.py
tests/flytekit/unit/annotated/test_type_hints.py

Better handling of Task Plugins

Task plugins

---

flytekit/__init__.py
flytekit/annotated/task.py
flytekit/taskplugins/spark/__init__.py
flytekit/taskplugins/spark/task.py
tests/flytekit/unit/annotated/test_type_hints.py

Spark Plugin is now in a contained module

Contained taskplugins

---

dev-requirements.txt
flytekit/__init__.py
flytekit/clients/friendly.py
flytekit/clients/raw.py
flytekit/clis/flyte_cli/main.py
flytekit/models/project.py
requirements-spark3.txt
requirements.txt
setup.py
tests/flytekit/unit/cli/test_flyte_cli.py
tests/flytekit/unit/clients/test_friendly.py
tests/flytekit/unit/clients/test_raw.py
tests/flytekit/unit/models/test_project.py

Support archive and activate a project.
The client side implementation of https://github.com/lyft/flyteadmin/pull/138
https://github.com/lyft/flyte/issues/569
_NA_

Archive and activate project

---

dev-requirements.txt
flytekit/__init__.py
requirements-spark3.txt
requirements.txt

Re-generate requirements
Alternative to #250. But instead of limit urllib3, this bumps requests to 2.25.0 and that should be sufficient.
_NA_
_NA_

Re-generate requirements

---

setup.cfg

I think it's best to have this.

Add license to distribution

---

flytekit/__init__.py
flytekit/annotated/base_sql_task.py
flytekit/annotated/task.py
flytekit/taskplugins/hive/task.py
flytekit/types/schema.py
setup.py
tests/flytekit/unit/annotated/test_hive_task.py
tests/flytekit/unit/annotated/test_type_hints.py

https://github.com/lyft/flyte/issues/631

Annotations - Hive

---

dev-requirements.txt
flytekit/__init__.py
flytekit/clients/friendly.py
flytekit/clis/flyte_cli/main.py
flytekit/models/filters.py
requirements-spark3.txt
requirements.txt
setup.py
tests/flytekit/unit/cli/test_flyte_cli.py
tests/flytekit/unit/clients/test_friendly.py
tests/flytekit/unit/clients/test_raw.py
tests/flytekit/unit/models/test_filters.py

List projects with filter and sort_by.
`flyte-cli` currently doesn't support listing projects. This PR adds support of that.
This PR also fixes the mismatching non-equal filter between flytekit and flyteadmin.
https://github.com/lyft/flyte/issues/625
https://github.com/lyft/flyte/issues/418
_NA_

List projects with filter and sort_by

---

flytekit/annotated/promise.py
tests/flytekit/unit/annotated/test_conditions.py

ConjunctionExpression mistakenly evaluates the left hand side twice

Fix conditions 'ConjunctionExpression' evaluation

---

tests/flytekit/unit/cli/pyflyte/conftest.py
tests/flytekit/unit/cli/pyflyte/test_register.py
tests/flytekit/unit/cli/test_flyte_cli.py

Missed these because of all the mypy errors

Fix tests from serialize change

---

flytekit/annotated/base_task.py
flytekit/annotated/context_manager.py
flytekit/annotated/python_function_task.py
flytekit/annotated/task.py
flytekit/clis/sdk_in_container/serialize.py
flytekit/taskplugins/hive/task.py
flytekit/taskplugins/pod/task.py
flytekit/taskplugins/pytorch/task.py
flytekit/taskplugins/sagemaker/hpo.py
flytekit/taskplugins/sagemaker/training.py
flytekit/taskplugins/spark/task.py
flytekit/taskplugins/tensorflow/task.py

Python instance task makes it possible to run an execution of a module
variable (like an airflow operator)
Also reduced the constructor args to be minimal

Support for PythonInstanceTask and better constructor args

---

flytekit/annotated/base_task.py
flytekit/annotated/constants.py
flytekit/annotated/container_task.py
flytekit/clis/flyte_cli/main.py

also rm flytekit.annotated.constants and override get_fast_registerable_entity in ContainerTask instead

refactor register and fast-register commands

---

flytekit/annotated/python_function_task.py
tests/flytekit/unit/annotated/test_task.py

When filling in template values.

Annotations - tiny change to support plural images

---

flytekit/annotated/reference_entity.py

Simplify reference entity classes.
Use abstract property to simplify reference entity.
_NA_
_NA_

Simplify reference entity

---

flytekit/annotated/base_task.py
flytekit/annotated/container_task.py
flytekit/annotated/context_manager.py
flytekit/annotated/python_function_task.py
flytekit/bin/entrypoint.py
flytekit/clis/sdk_in_container/serialize.py
flytekit/common/translator.py
flytekit/taskplugins/hive/task.py
flytekit/taskplugins/pod/task.py
flytekit/taskplugins/pytorch/task.py
flytekit/taskplugins/sagemaker/hpo.py
flytekit/taskplugins/sagemaker/training.py
flytekit/taskplugins/spark/task.py
flytekit/taskplugins/tensorflow/task.py
tests/flytekit/unit/annotated/test_conditions.py
tests/flytekit/unit/annotated/test_dynamic_conditional.py
tests/flytekit/unit/annotated/test_node_creation.py
tests/flytekit/unit/annotated/test_references.py
tests/flytekit/unit/annotated/test_serialization.py
tests/flytekit/unit/annotated/test_task.py
tests/flytekit/unit/annotated/test_type_hints.py
tests/flytekit/unit/annotated/test_workflows.py
tests/flytekit/unit/common_tests/test_translator.py
tests/flytekit/unit/taskplugins/hive/test_hive_task.py
tests/flytekit/unit/taskplugins/pod/test_pod.py
tests/flytekit/unit/taskplugins/pytorch/test_pytorch_task.py
tests/flytekit/unit/taskplugins/sagemaker/test_training.py
tests/flytekit/unit/taskplugins/spark/test_spark_task.py
tests/flytekit/unit/taskplugins/tensorflow/test_tensorflow_task.py

it's only used in a serialization context now anyways

rename RegistrationSettings to SerializationSettings

---

dev-requirements.txt
requirements-spark3.txt
requirements.txt
setup.py

* Add a dependency to pyarrow - it's wide because they seem to bump major versions pretty frequently - https://pypi.org/project/pyarrow/2.0.0/#history
* Ran `make requirements` after adding dependency.

Annotations pyarrow as dependency

---

flytekit/__init__.py
flytekit/bin/entrypoint.py
flytekit/clis/flyte_cli/main.py
flytekit/tools/fast_registration.py
setup.py

Minor fixes for fast register in new flytekit
Discovered while testing.
_NA_
OR

Fixes for fast register

---

dev-requirements.in
dev-requirements.txt
plugins/Makefile
plugins/run_all_plugins.sh
requirements-spark3.txt
requirements.txt

This adds a small bash script to help manage the new set of plugins
* Added bash script
* Ran `make requirements` which got rid of the weird `extra="all"` in the requirements file that was giving us problems earlier.

Plugins - Minor util script

---

.gitignore
dev-requirements.in
dev-requirements.txt
doc-requirements.in
requirements-spark3.txt
requirements.txt

RTD failing because sphinx libraries are missing.  Adding to dev requirements.
Added sphinx libraries to dev requirements.
Ran make requirements.

Add sphinx to dev requirements

---

flytekit/__init__.py
setup.py

Align pyarrow dependency between old style and new.
Changed setup to match.
https://flyte-org.slack.com/archives/CREL4QVAQ/p1612222522057200

Align pyarrow dependency between old style and new

---

README.md

Fix codecov link after moving orgs

Update codecov link

---

README.md

Updates readme to add Badge for supported python versions

README updated to add supported versions

---

docs/source/conditions.rst
docs/source/dynamic.rst
docs/source/tasks.extend.rst
docs/source/tasks.rst
docs/source/types.rst

Minor fixes to rst files only.

[Docs only] RST fixes

---

docs/source/conf.py
docs/source/tasks.rst
flytekit/core/dynamic_workflow_task.py
flytekit/core/task.py
flytekit/core/workflow.py

[Docs only] Better docstrings for task, workflow, dynamic

---

doc-requirements.in
doc-requirements.txt

One last fix to get RTD working.  Previous doc-requirements.in missed some stuff since I was working off of an older commit.  This should just pull in everything.
https://readthedocs.org/projects/flytekit/builds/13007488/

[Docs] One last fix

---

plugins/awssagemaker/flytekitplugins/awssagemaker/training.py

Correct import path for ExecutionParameters in sagemaker plugin
_NA_
OR

Correct import path

---

flytekit/core/dynamic_workflow_task.py
plugins/tests/pod/test_pod.py

Remove unused dynamic task code. Dynamic tasks behavior is modified by execution_mode rather than config.
_NA_

Remove unused dynamic task code

---

flytekit/common/nodes.py
flytekit/common/translator.py
tests/flytekit/unit/core/test_serialization.py
tests/flytekit/unit/core/test_type_hints.py

SDKNode serialization bugfix

---

flytekit/clis/sdk_in_container/serialize.py
flytekit/common/translator.py
flytekit/core/python_function_task.py
plugins/tests/hive/test_hive_task.py
tests/flytekit/unit/common_tests/test_translator.py
tests/flytekit/unit/core/test_conditions.py
tests/flytekit/unit/core/test_map_task.py
tests/flytekit/unit/core/test_node_creation.py
tests/flytekit/unit/core/test_references.py
tests/flytekit/unit/core/test_serialization.py
tests/flytekit/unit/core/test_type_hints.py
tests/flytekit/unit/core/test_workflows.py

[ignore] - PR into #405

---

.github/workflows/pythonbuild.yml
Makefile
docs/source/contributing.rst
plugins/kftensorflow/flytekitplugins/kftensorflow/task.py
plugins/pandera/flytekitplugins/pandera/schema.py
plugins/tests/pod/test_pod.py
setup.cfg
setup.py

- fixes some plugin unit tests
- updates linting make target to report all mypy errors
- adds plugin test suite to the github actions CI
- updates the contributing docs with more instructions on development environment setup
_NA_
OR

Fix flytekit setup

---

flytekit/common/translator.py
flytekit/core/reference_entity.py
tests/flytekit/unit/core/test_references.py

This diff aligns `Workflow` and `ReferenceWorkflow` properties that have to do with `interface`
https://github.com/flyteorg/flyte/issues/802

bugfix: create launchplan from reference workflow

---

dev-requirements.txt
doc-requirements.txt
flytekit/common/tasks/task.py
flytekit/common/translator.py
flytekit/core/base_task.py
flytekit/models/task.py
plugins/pod/flytekitplugins/pod/task.py
plugins/pod/setup.py
plugins/tests/pod/test_pod.py
requirements-spark3.txt
requirements.txt
setup.py
tests/flytekit/unit/models/test_tasks.py

Revamp pod tasks to use the [OpenAPI spec for PodSpec](https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec)s, increment the task_type_version accordingly and utilize the new config field in the task template to set the primary container name
https://github.com/flyteorg/flyte/issues/816
_NA_

Revamp pod tasks

---

Makefile
flytekit/__init__.py
plugins/Makefile
plugins/awssagemaker/setup.py
plugins/hive/setup.py
plugins/kfpytorch/setup.py
plugins/kftensorflow/setup.py
plugins/pandera/setup.py
plugins/papermill/setup.py
plugins/pod/setup.py
plugins/spark/setup.py
setup.py

Make placeholder compatible with 440
Make placeholder compatible with 440.

Make placeholder compatible with PEP 440

---

flytekit/contrib/notebook/tasks.py
flytekit/plugins/__init__.py

Please see
https://github.com/flyteorg/flytekit/pull/430/

Lazy load papermill in legacy plugins - 0.16 patch

---

README.md

Signed-off-by: Jeev B <jeev.balakrishnan@freenome.com>

Remove beta version from readme install instructions

---

docs/source/_static/custom.css
docs/source/conf.py

Update dark theme styles for readthedocs search bar
_NA_
OR

dark theme updates

---

flytekit/core/launch_plan.py
tests/flytekit/unit/core/test_composition.py
tests/flytekit/unit/core/test_type_hints.py

Signed-off-by: Jeev B <jeev.balakrishnan@freenome.com>
_NA_
OR

Do not omit variables without defaults from parameter map when constructing launch plan

---

tests/flytekit/unit/core/test_node_creation.py

Just adding a quick unit test for `create_node` using a dynamic task.

Unit test for dynamic create node

---

flytekit/control_plane/tasks/executions.py

Fix imports and don't use TypeEngine in executions.py
_NA_
OR

fix control_plane imports

---

tests/flytekit/unit/core/test_type_hints.py
tests/flytekit/unit/core/test_workflows.py

Just adding a couple unit tests that are a bit more complicated.

Unit tests

---

docs/source/index.rst

Signed-off-by: Samhita Alla aallasamhita@gmail.com
Added `Concepts` to the sidebar.
_NA_
OR

Update main sidebar section

---

flytekit/__init__.py
flytekit/core/dynamic_workflow_task.py
flytekit/core/resources.py
flytekit/core/schedule.py
flytekit/core/workflow.py

This PR fixes intersphinx references for pages that need to be update due to https://github.com/flyteorg/flytesnacks/pull/200
_NA_
OR

Update flytesnacks links

---

flytekit/clients/raw.py
flytekit/clis/auth/auth.py
flytekit/clis/auth/credentials.py
flytekit/clis/flyte_cli/main.py
flytekit/configuration/creds.py
flytekit/loggers.py
tests/flytekit/unit/clients/auth_deprecation.config
tests/flytekit/unit/clients/auth_deprecation2.config
tests/flytekit/unit/clients/auth_deprecation3.config
tests/flytekit/unit/clients/test_raw.py
tests/flytekit/unit/core/test_serialization.py

Signed-off-by: Haytham Abuelfutuh <haytham@afutuh.com>
Fixing multiprocessing stuff for auth for 3.8.
* Use explicit fork context when creating the Process, had to move the queue around.
* Added better loggers.
* Deprecated the old scope in favor of a new scope since it needs to be a list.
* Cleaned up imports
NA

Update auth to work with python 3.8

---

doc-requirements.in
doc-requirements.txt
docs/source/conf.py
docs/source/index.rst

add icons to main nav docs

---

flytekit/control_plane/tasks/executions.py
tests/flytekit/integration/control_plane/test_workflow.py

Fixes https://github.com/flyteorg/flyte/issues/974, this PR https://github.com/flyteorg/flytekit/pull/486 missed the `FlyteTaskExecution` class.
_NA_
OR

convert flyte to python literals in task execution

---

flytekit/common/nodes.py
flytekit/control_plane/nodes.py
flytekit/models/node_execution.py
tests/flytekit/unit/models/admin/test_node_executions.py

Bringing in changes from https://github.com/flyteorg/flyteidl/pull/72/files basically into the model files only.  This is leftover work from https://github.com/flyteorg/flyte/issues/218
https://github.com/flyteorg/flyte/issues/985

Add in NodeExecutionMetaData into models

---

.github/workflows/pythonpublish.yml
Dockerfile.py37
Dockerfile.py38

- Added dockerfile for flytekit (Py version 3.7 and 3.8)
- Release flytekit docker images in github registry 
https://github.com/lyft/flyte/issues/978
_NA_
OR

Added dockerfile for flytekit

---

dev-requirements.txt
flytekit/clis/flyte_cli/main.py
flytekit/common/launch_plan.py
flytekit/models/common.py
flytekit/models/launch_plan.py
requirements-spark2.txt
requirements.txt
setup.py
tests/flytekit/unit/models/test_common.py

Support passing an iam role AND a k8s service account
https://github.com/flyteorg/flyte/issues/1057
_NA_

Support passing an iam role AND a k8s service account

---

.github/workflows/pythonpublish.yml

Didn't realize what was happening in https://github.com/flyteorg/flytekit/pull/469/files, reverting a few lines in the GH workflow.

Add back plugins to ci/cd

---

.github/workflows/pythonpublish.yml

- Added 60s wait after publishing pip package
_NA_
OR

Added wait after publishing pip package

---

.github/workflows/pythonpublish.yml

1. Fix the flytekit docker image name 
Tested Action Result : https://github.com/users/evalsocket/packages/container/package/flytekit
_NA_
OR

fix flytekit docker image name 

---

flytekit/extras/sqlite3/task.py

Bump to Sqlite3 task image to release version

---

.github/workflows/pythonbuild.yml
dev-requirements.txt
doc-requirements.txt
docs/source/index.rst
requirements-spark2.txt
requirements.txt

update flyteidl dep in doc-requirement.txt, fix main nav links,
add doc build step to GH actions
- X ] Docs
_NA_
OR

fixes flytekit docs build

---

.github/workflows/pythonpublish.yml

- wait time increase by 2 minutes after flytkit publish. Registry take some time to reflect the changes 
_NA_
OR

wait time increase by 2 minute after flytkit publish 

---

dev-requirements.txt
doc-requirements.txt
flytekit/common/launch_plan.py
flytekit/common/translator.py
flytekit/core/launch_plan.py
flytekit/models/execution.py
flytekit/models/launch_plan.py
requirements-spark2.txt
requirements.txt
setup.py
tests/flytekit/unit/core/test_launch_plan.py
tests/flytekit/unit/models/test_execution.py
tests/flytekit/unit/models/test_launch_plan.py

Makes max_parallelism available as a configuration option for launch plans (and execution models).
https://github.com/flyteorg/flyte/issues/1099
_NA_

Add max_parallelism to launch plans

---

tests/flytekit/unit/core/test_serialization.py

This just verifies that the bug is indeed not a bug.
In case of nested sub-workflows, only one copy of the subworkflows exist. In case of namedreturn you can use them for workflows as well
https://github.com/flyteorg/flyte/issues/1139

Unit tests to verify NamedReturn and Nested Subworkflows

---

docs/source/index.rst

add deployment to the top TOC #patch

---

doc-requirements.in
doc-requirements.txt
docs/source/conf.py

algolia search

---

dev-requirements.txt
doc-requirements.txt
requirements-spark2.txt
requirements.txt
setup.py

We've been getting dependabot security warnings because there's some issue with urllib3 v1.25.  Let's remove the 1.26 restriction and see.

Loosen urllib3

---

flytekit/clis/flyte_cli/main.py

During registration read Auth from flytekit config file
- [ x] Code completed
_NA_
OR

read auth from flytekit config file

---

plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/requirements.in
plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/requirements.txt
plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py

Modify sqlalchemy version

---

flytekit/core/python_function_task.py
tests/flytekit/unit/core/test_dynamic.py

Wrong thing called in fast dynamic execute.  Added a test to test the full run-time dispatch_execute starting function.  Added new file cuz I have a hard time finding dynamic tests.

Use serialization settings instance for builder.

---

plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/requirements.in
plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/requirements.txt
plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py

Undo SQLAlchemy changes

---

flytekit/clients/raw.py
tests/flytekit/unit/clients/test_raw.py

Was missing, added.  This feature is already in flytectl but may as well keep it working as well here.

Update project missing metadata in raw client

---

flytekit/core/context_manager.py

Ensure tmp directory present in local execution.
mkdir.

Ensure tmp directory present in local execution

---

CODEOWNERS

Due to my current situation (change of focus temporarily), as you have seen, I have not been able to provide any help reviewing code changes, so I will remove myself from the list for now. Sorry about this and hope you can understand.
_NA_
_NA_

Remove myself from codeowners temporarily

---

plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py
plugins/tests/pod/test_pod.py

Fix sanitization of resource name in pod tasks
_NA_
OR

Fix sanitization of resource name in pod tasks

---

flytekit/__init__.py
flytekit/extend/__init__.py
plugins/flytekit-data-fsspec/README.md
plugins/flytekit-data-fsspec/flytekitplugins/fsspec/__init__.py
plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py
plugins/flytekit-data-fsspec/setup.py

This plugin overrides all default data persistence plugins and uses fsspec for these plugins.
Depends on https://github.com/flyteorg/flytekit/pull/559

Fsspec DataPersistence plugin

---

dev-requirements.txt
doc-requirements.txt
flytekit/clis/sdk_in_container/local_cache.py
flytekit/core/base_task.py
flytekit/core/local_cache.py
requirements-spark2.txt
requirements.txt
setup.py
tests/flytekit/unit/core/test_local_cache.py

Replace local cache backing store with `diskcache.Cache`
The previous package used to implement local caching, `joblib`, didn't provide a way to inspect the cache prior to fetching values from it, this prevented us from logging when we were seeing cache hits and misses. This PR re-implements local caching using [diskcache](https://github.com/grantjenks/python-diskcache).
https://github.com/flyteorg/flyte/issues/761
_NA_

Local caching using diskcache

---

flytekit/core/base_task.py
flytekit/extras/persistence/gcs_gsutil.py
flytekit/extras/persistence/s3_awscli.py
plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py
plugins/flytekit-greatexpectations/setup.py
plugins/tests/pandera/test_plugin.py
tests/flytekit/unit/core/test_data_persistence.py

Insert modifies in place, doesn't return the modified value.
* Also removing the `from e` bit, it hides the stack trace which makes it super hard to investigate.
_NA_
OR

Insert doesn't return value

---

docs/source/design/control_plane.rst

Video URL will be updated to be properly referenced to the Flyte YouTube channel.
_NA_
OR

Updating Video URL

---

setup.py

0.15 pin idl to <0.20

---

setup.py

0.16 pin idl to <0.20

---

setup.py

0.17 pin idl to <0.20

---

setup.py

0.18 pin idl to <0.20

---

setup.py

0.21 pin idl to <0.20

---

setup.py

0.20 pin idl to <0.20

---

setup.py

0.19 pin idl to <0.20

---

dev-requirements.txt
doc-requirements.txt
requirements-spark2.txt
requirements.txt
setup.py

0.22 beta pin idl to <0.20

---

flytekit/__init__.py

Forgot to bump the version for 0.15.5

[0.15.x] Forgot to bump version for 15.5

---

flytekit/clis/flyte_cli/main.py
flytekit/remote/remote.py
tests/flytekit/unit/remote/test_remote.py

Misunderstood the API, there's no need to loop.
Just call the client directly.

Minor bug fix for remote listing

---

flytekit/clients/raw.py

Add debug log

---

flytekit/core/context_manager.py
flytekit/types/directory/types.py
flytekit/types/file/file.py
flytekit/types/schema/types_pandas.py
tests/flytekit/unit/core/test_flyte_directory.py
tests/flytekit/unit/core/test_flyte_file.py
tests/flytekit/unit/core/test_interface.py

Signed-off-by: Sean Lin <sean@union.ai>
Fix class name is not defined error in mypy. Some errors are fixed by importing necessary modules and placing forward reference with normal reference; Others are fixed by introducing forward reference to avoid circular dependency https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING
https://github.com/flyteorg/flyte/issues/1428
_NA_

[mypy] Fix class name is not defined error

---

plugins/flytekit-papermill/flytekitplugins/papermill/task.py

Signed-off-by: Haytham Abuelfutuh <haytham@afutuh.com>
Cherry picking https://github.com/flyteorg/flytekit/pull/650 into release-0.22

Cherry-Pick Make internal task unique per papermill task (#650) into v0.22.x

---

plugins/README.md
plugins/flytekit-data-fsspec/README.md
plugins/flytekit-greatexpectations/README.md

Better documentation explaining plugin structure

Adding better docs for plugins

---

flytekit/core/promise.py
flytekit/loggers.py

Silence logs and remove erroneous print

Silence logs

---

flytekit/models/task.py
plugins/flytekit-kf-mpi/flytekitplugins/kfmpi/task.py
plugins/flytekit-kf-mpi/tests/test_mpi_task.py

Read replica resources from task decorator
_NA_
OR

Read replica resources from task decorator

---

README.md
docs/source/contributing.rst
plugins/README.md
plugins/flytekit-greatexpectations/README.md

Updated contribution guide, README, plugin README, and added one plugin README as an example.
_NA_
OR

Update Flytekit Contribution Guide

---

flytekit/clis/flyte_cli/main.py

https://github.com/flyteorg/flytekit/pull/678
Cherry-pick c2473c092a3ea9d0f1deeb9ddb4f2b2ace09f2e3 onto release-0.22

Cherry pick #678 onto 0.22

---

docs/source/contributing.rst

Updated Flytekit contribution guide.
_NA_
OR

Add Documentation Guidelines

---

dev-requirements.txt
doc-requirements.txt
plugins/flytekit-papermill/flytekitplugins/papermill/task.py
requirements-spark2.txt
requirements.txt
tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.in
tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt

Bump flytekit in integration tests and regenerate requirements
Integration tests pin the flytekit version here. We regenerated the requirements files with the newly released version of flytekit.
__
_NA_
OR

Fix master

---

flytekit/remote/remote.py

Fix lint error in remote.py

---

flytekit/clis/flyte_cli/main.py

Just a small validation check on top of https://github.com/flyteorg/flytekit/pull/783

Add validation check

---

dev-requirements.txt
doc-requirements.txt
requirements-spark2.txt
requirements.txt
setup.py
tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt

Removing the pytz constraint as that is no longer needed for our purposes
I removed the pytz constraint from `setup.py` and regenerated requirements files.
_NA_
OR

Remove pytz constraint

---

flytekit/clis/flyte_cli/main.py

Lint: remove f-string misuse
_NA_
OR

Lint: remove f-string misuse

---

.github/workflows/pythonbuild.yml
.github/workflows/pythonpublish.yml
Dockerfile.py310
plugins/flytekit-aws-athena/setup.py
plugins/flytekit-aws-sagemaker/setup.py
plugins/flytekit-data-fsspec/setup.py
plugins/flytekit-dolt/setup.py
plugins/flytekit-greatexpectations/setup.py
plugins/flytekit-hive/setup.py
plugins/flytekit-k8s-pod/setup.py
plugins/flytekit-kf-mpi/setup.py
plugins/flytekit-kf-pytorch/setup.py
plugins/flytekit-kf-tensorflow/setup.py
plugins/flytekit-pandera/setup.py
plugins/flytekit-papermill/setup.py
plugins/flytekit-snowflake/setup.py
plugins/flytekit-spark/setup.py
plugins/flytekit-sqlalchemy/setup.py
setup.py

Support python 3.10 officially.
_NA_
OR

Support python 3.10

---

flytekit/common/translator.py
tests/flytekit/unit/common_tests/test_translator.py

Remove node's input which is fixed input
https://github.com/flyteorg/flyte/issues/2008
_NA_

Parent workflow serialization fails when calling a launch plan with fixed inputs

---

tests/flytekit/unit/core/test_imperative.py
tests/flytekit/unit/core/test_shim_task.py

Add some tests

---

flytekit/__init__.py

flytekit.Checkpoint is a useful interface and should be available to users.
_NA_

Expose Checkpoint as a top-level interface in flytekit

---

flytekit/core/condition.py

Fixes a bug in which condition outputs are ordered incorrectly
Use List instead of sets

Fixing out of order for conditional outputs

---

flytekit/extras/persistence/s3_awscli.py
plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py
tests/flytekit/unit/extras/persistence/test_s3_awscli.py

Add anonymous retry

---

flytekit/extras/persistence/s3_awscli.py
plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py
tests/flytekit/unit/extras/persistence/test_s3_awscli.py

Cherry pick [f6e38dd2a16949642e9a7ba3df78c1be0f313b48](https://github.com/flyteorg/flytekit/pull/854) into v0.30

Cherry-pick #854 into v0.30

---

docs/source/design/authoring.rst

Added the directive correctly
Signed-off-by: SmritiSatyanV <smriti@union.ai>

Updated authoring.rst

---

flytekit/clis/sdk_in_container/pyflyte.py
flytekit/clis/sdk_in_container/serialize.py

Nit: fixed lint errors in GitHub action
https://github.com/flyteorg/flytekit/runs/5426228797?check_suite_focus=true
_NA_

Fixed lint errors

---

docs/source/configuration.rst
docs/source/design/authoring.rst
docs/source/index.rst
flytekit/clients/raw.py
flytekit/configuration/__init__.py
flytekit/remote/__init__.py
flytekit/remote/component_nodes.py
flytekit/remote/remote.py

Cleanup docs, config docs

---

README.md
docs/source/contributing.rst

Signed-off-by: Alekhya Sai Punnamaraju <alekhyasaip@gmail.com>
Migrating Images to Static resources.
Related PR - https://github.com/flyteorg/static-resources/pull/3

Migration of images to static resources

---

flytekit/core/type_engine.py
flytekit/remote/executions.py
flytekit/remote/remote.py
tests/flytekit/integration/remote/test_remote.py
tests/flytekit/unit/core/test_literals_resolver.py
tests/flytekit/unit/remote/test_sandbox.py

use literalsresolver directly instead of raw_inputs/outputs

pr into #900

---

flytekit/core/map_task.py

Setting the map task security context to that of the underlying task (if exists).
^^^
https://github.com/flyteorg/flyte/issues/2122
_NA_

Setting map task security context

---

flytekit/configuration/file.py
flytekit/core/type_engine.py
flytekit/remote/remote.py
tests/flytekit/integration/remote/test_remote.py
tests/flytekit/unit/core/functools/test_decorators.py
tests/flytekit/unit/remote/test_remote.py

Updates methods to name them more appropriately
```python
r = FlyteRemote()
r.get_execution(...)
...
r.sync_execution(...)
```
Also makes literalResolver into a dict, so that it is possible to walk through the var-names
```python
exe = r.get_execution(...)
print(r.inputs.keys())
print(r.outputs.keys())
```
_NA_

updated ux for flyteremote

---

flytekit/configuration/__init__.py
flytekit/configuration/file.py
flytekit/core/data_persistence.py

Lower logging, pass data_config to plugin

---

flytekit/clients/raw.py
flytekit/clis/auth/auth.py
tests/flytekit/unit/cli/auth/test_auth.py

write back updates to singleton

---

docs/source/design/control_plane.rst

Added examples to showcase FlyteRemote API.
Fixes https://github.com/flyteorg/flyte/issues/1844
_NA_
OR

FlyteRemote API examples

---

flytekit/tools/script_mode.py
tests/flytekit/unit/tools/test_script_mode.py

Deterministically hash for fast register.
Tested with pyflyte run on remote.
User reported bug
https://github.com/flyteorg/flyte/issues/2241
_NA_

Deterministically hash for fast register

---

flytekit/clis/sdk_in_container/run.py
flytekit/core/tracker.py

clean up `run.py` parse workflow inputs for dataframes
_NA_
OR

clean up run.py cli module

---

flytekit/remote/remote.py

Hardcode console url

---

flytekit/remote/remote.py

add support for reference entity

---

flytekit/clis/sdk_in_container/run.py
flytekit/configuration/__init__.py
flytekit/configuration/default_images.py
tests/flytekit/unit/configuration/test_image_config.py

Use python and flytekit version both in image picking

---

flytekit/core/map_task.py
flytekit/tools/translator.py

Support for Fast serialize, map and dynamic workflows for pod tasks

Pod Task improvements: Map, Dynamic & Fast serialize

---

.github/workflows/sqlachemy_publish.yml

Missing config in `sqlalchemy_publish.yml`
_NA_
OR

add needs:deploy to sqlalchemy_publish.yml

---

flytekit/clis/sdk_in_container/run.py

Signed-off-by: Prafulla Mahindrakar <prafulla.mahindrakar@gmail.com>
_NA_
OR

Making default value of service account empty

---

flytekit/core/launch_plan.py
flytekit/models/launch_plan.py
flytekit/remote/remote.py
flytekit/tools/translator.py
tests/flytekit/unit/remote/test_remote.py

Updates LaunchPlans to use security context instead of auth_role, while maintaining backwards compatibility

Lp security context

---

flytekit/types/structured/basic_dfs.py
flytekit/types/structured/structured_dataset.py
tests/flytekit/unit/core/test_structured_dataset.py

Don't set default for GCS, add test to fix

---

flytekit/clients/raw.py
flytekit/clis/auth/auth.py

Fixing a small issue where we have to run commands twice.

Always try to refresh token, start flow if fail

---

.pre-commit-config.yaml
codecov.yml
dev-requirements.in
dev-requirements.txt
doc-requirements.in
doc-requirements.txt
flytekit/clients/raw.py
flytekit/common/tasks/generic_spark_task.py
plugins/flytekit-greatexpectations/setup.py
plugins/flytekit-papermill/requirements.txt
plugins/flytekit-papermill/setup.py
requirements-spark2.txt
requirements.txt
tests/flytekit/common/parameterizers.py
tests/flytekit/common/workflows/batch.py
tests/flytekit/common/workflows/spark.py
tests/flytekit/integration/remote/test_remote.py
tests/flytekit/loadtests/cp_spark.py
tests/flytekit/unit/cli/test_cli_helpers.py
tests/flytekit/unit/core/test_serialization.py
tests/flytekit/unit/core/test_type_hints.py
tests/flytekit/unit/extras/sqlite3/test_task.py
tests/flytekit/unit/models/test_tasks.py

Architecture tests

---

flytekit/core/data_persistence.py
tests/flytekit/unit/core/test_type_hints.py

Linting master

---

plugins/flytekit-papermill/dev-requirements.in
plugins/flytekit-papermill/dev-requirements.txt

Set flyteidl>=1.0.0 in papermill dev-requirements

---

flytekit/remote/remote.py

Don't try to register fetched entities.
_NA_
OR

Skip RemoteEntity in _serialize_and_register

---

flytekit/remote/remote.py

Flyte remote is no longer beta

---

flytekit/core/base_sql_task.py
flytekit/core/python_auto_container.py
flytekit/core/python_customized_container_task.py
flytekit/core/shim_task.py
plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py

Signed-off-by: Alekhya Sai Punnamaraju <alekhyasaip@gmail.com>
Minor edits to sqlalchemy.SQLAlchemyTask

Minor edits to sqlalchemy.SQLAlchemyTask

---

flytekit/core/map_task.py

Signed-off-by: Alekhya Sai Punnamaraju <alekhyasaip@gmail.com>
Adding map task plugins in flytekit.map_task.
https://github.com/flyteorg/flyte/issues/2413

Map task updates

---

flytekit/core/data_persistence.py
flytekit/core/type_engine.py
flytekit/remote/remote.py

Flyte remote context save ctx

---

plugins/README.md
plugins/flytekit-aws-athena/setup.py
plugins/flytekit-aws-batch/setup.py
plugins/flytekit-aws-sagemaker/setup.py
plugins/flytekit-bigquery/setup.py
plugins/flytekit-data-fsspec/setup.py
plugins/flytekit-deck-standard/setup.py
plugins/flytekit-dolt/setup.py
plugins/flytekit-greatexpectations/setup.py
plugins/flytekit-hive/setup.py
plugins/flytekit-k8s-pod/setup.py
plugins/flytekit-kf-mpi/setup.py
plugins/flytekit-kf-pytorch/setup.py
plugins/flytekit-kf-tensorflow/setup.py
plugins/flytekit-modin/setup.py
plugins/flytekit-pandera/setup.py
plugins/flytekit-papermill/setup.py
plugins/flytekit-snowflake/setup.py
plugins/flytekit-spark/setup.py
plugins/flytekit-sqlalchemy/setup.py

Bump plugin pins to 1.1-> 1.2

---

.github/workflows/pythonbuild.yml
Makefile

Fix the tests on windows in GitHub workflow.
_NA_

Fix the tests on windows

---

docs/source/data.extend.rst

Signed-off-by: SmritiSatyanV <smriti@union.ai>

Changed 'design' to 'designed'

---

flytekit/configuration/internal.py

Skip config checking if no ini config file present (#1016)

---

CODEOWNERS

Adding owner

---

flytekit/core/type_engine.py
tests/flytekit/unit/core/test_type_engine.py

https://flyte-org.slack.com/archives/CNMKCU6FR/p1654691601702159
_NA_
OR

Add support list of flytetype in dataclass

---

flytekit/clis/sdk_in_container/run.py
flytekit/core/promise.py
flytekit/core/type_engine.py
tests/flytekit/unit/cli/pyflyte/test_run.py
tests/flytekit/unit/cli/pyflyte/workflow.py

Add support union type for pyflyte run
_NA_

Add support union type for pyflyte run

---

dev-requirements.txt
doc-requirements.txt
plugins/flytekit-aws-athena/requirements.txt
plugins/flytekit-aws-batch/requirements.txt
plugins/flytekit-aws-sagemaker/requirements.txt
plugins/flytekit-bigquery/requirements.txt
plugins/flytekit-data-fsspec/requirements.txt
plugins/flytekit-dolt/requirements.txt
plugins/flytekit-greatexpectations/requirements.txt
plugins/flytekit-hive/requirements.txt
plugins/flytekit-k8s-pod/requirements.txt
plugins/flytekit-kf-mpi/requirements.txt
plugins/flytekit-kf-pytorch/requirements.txt
plugins/flytekit-kf-tensorflow/requirements.txt
plugins/flytekit-modin/requirements.txt
plugins/flytekit-modin/setup.py
plugins/flytekit-pandera/requirements.txt
plugins/flytekit-papermill/dev-requirements.txt
plugins/flytekit-papermill/requirements.txt
plugins/flytekit-polars/requirements.txt
plugins/flytekit-snowflake/requirements.txt
plugins/flytekit-spark/requirements.txt
plugins/flytekit-sqlalchemy/requirements.txt
requirements-spark2.txt
requirements.txt
tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt

ref: https://github.com/flyteorg/flyte/issues/2619 and https://github.com/flyteorg/flyte/issues/2486
GRPC 1.47.0 release: https://github.com/grpc/grpc/releases/tag/v1.47.0
_NA_
OR

Bump grpcio to 1.47.0

---

plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py
plugins/flytekit-sqlalchemy/tests/test_task.py

https://flyte-org.slack.com/archives/CP2HDHKE1/p1655783218305799
_NA_
OR

Add support insert in SQLAlchemyTask

---

dev-requirements.txt
doc-requirements.txt
requirements-spark2.txt
requirements.txt
setup.py

Upgrade click to latest version
_NA_
OR

Upgrade click to latest version

---

flytekit/clis/sdk_in_container/run.py
flytekit/configuration/__init__.py
flytekit/configuration/internal.py
tests/flytekit/unit/configuration/configs/no_images.yaml
tests/flytekit/unit/configuration/test_image_config.py
tests/flytekit/unit/configuration/test_yaml_file.py

trying to address some of the comments i had.

pr into #1106

---

MANIFEST.in

See https://github.com/flyteorg/flytekit/pull/1122

[v1.1] #1122 - Remove py.typed

---

doc-requirements.in
doc-requirements.txt
docs/source/plugins/index.rst
docs/source/plugins/onnxpytorch.rst
docs/source/plugins/onnxscikitlearn.rst
docs/source/plugins/onnxtensorflow.rst
plugins/flytekit-onnx-pytorch/flytekitplugins/onnxpytorch/__init__.py
plugins/flytekit-onnx-pytorch/flytekitplugins/onnxpytorch/schema.py
plugins/flytekit-onnx-scikitlearn/flytekitplugins/onnxscikitlearn/__init__.py
plugins/flytekit-onnx-scikitlearn/flytekitplugins/onnxscikitlearn/schema.py
plugins/flytekit-onnx-tensorflow/flytekitplugins/onnxtensorflow/__init__.py
plugins/flytekit-onnx-tensorflow/flytekitplugins/onnxtensorflow/schema.py

Adds onnx plugin docs to api reference.
_NA_
OR

ONNX plugin docs

---

plugins/flytekit-polars/setup.py
plugins/flytekit-whylogs/setup.py

Backporting #1120 to 1.1
_NA_
OR

[v1.1] Backporting "Add entrypoint to setup.py in flytekit plugins (#1120)"

---

flytekit/clis/sdk_in_container/register.py
tests/flytekit/unit/cli/pyflyte/test_register.py

Add support pyflyte non-fast register.
Skip zipping and uploading the package when enabling non-fast mode.
^^^
NA
_NA_

pyflyte non-fast register

---

flytekit/clis/sdk_in_container/run.py
tests/flytekit/unit/cli/pyflyte/test_run.py
tests/flytekit/unit/cli/pyflyte/workflow.py

Use `json.loads` to read the JSON string if the python type is dict because `dict` doesn't have the attribute `from_json`. 
^^^
https://github.com/flyteorg/flyte/issues/3004
_NA_

Add support using dict in pyflyte run

---

Dockerfile

Install fsspec plugin in default image

---

flytekit/models/literals.py
tests/flytekit/unit/core/test_dynamic.py

The type engine fails to produce the literals @dynamic tasks if the dictionaries are returned.
Here's the error message:
```
File "/usr/local/lib/python3.9/site-packages/flytekit/exceptions/scopes.py", line 165, in system_entry_point
return wrapped(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/flytekit/core/base_task.py", line 483, in dispatch_execute
raise e
File "/usr/local/lib/python3.9/site-packages/flytekit/core/base_task.py", line 480, in dispatch_execute
native_outputs = self.execute(**native_inputs)
File "/usr/local/lib/python3.9/site-packages/flytekit/core/python_function_task.py", line 163, in execute
return self.dynamic_execute(self._task_function, **kwargs)
File …
```

Add support dict in @dynamic

---

flytekit/clis/sdk_in_container/init.py
tests/flytekit/unit/cli/pyflyte/test_init.py

Get the cookie-cutter to use the main branch and add tests
_NA_
OR

Update cookiecutter checkout branch

---

plugins/flytekit-dbt/README.md
plugins/flytekit-dbt/flytekitplugins/dbt/schema.py
plugins/flytekit-dbt/flytekitplugins/dbt/task.py
plugins/flytekit-dbt/tests/test_schema.py
plugins/flytekit-dbt/tests/test_task.py

This PR adds support for the DBT command `dbt source freshness` to test the data availability at loaded fields.
_NA_
OR

add support for dbt freshness

---

flytekit/core/promise.py
tests/flytekit/unit/core/test_promise.py

Signed-off-by: Hongxin Liang <honnix@users.noreply.github.com>
Add node output for VoidPromise returned from remote task.
Closes https://github.com/flyteorg/flyte/issues/3100
_NA_

Add node output for VoidPromise

---

flytekit/bin/entrypoint.py
flytekit/core/python_auto_container.py
flytekit/tools/script_mode.py
plugins/flytekit-spark/flytekitplugins/spark/models.py
plugins/flytekit-spark/flytekitplugins/spark/task.py

Update databricks branch

---

flytekit/clis/sdk_in_container/register.py

Updated register docs since register command supports both fast and non-fast versions

docs: update register help, non-fast version is supported

---

CODEOWNERS

Add Niels to code owners

---

flytekit/remote/remote.py
tests/flytekit/integration/remote/test_remote.py

FlyteRemote has a bug when trying to fetch a single task execution and sync nodes.   Thanks @honnix for the find and the fix.
fixes https://github.com/flyteorg/flyte/issues/3261
[slack](https://flyte-org.slack.com/archives/CREL4QVAQ/p1674579008084379).

Wrap flyte entity in TaskNode

---

.pre-commit-config.yaml

what title says
We're seeing issues while installing `isort` in the venv created by pre-commit (e.g. https://github.com/flyteorg/flytekit/pull/1426 and https://github.com/flyteorg/flytekit/pull/1420).
_NA_
OR

Bump isort to 5.12.0

---

flytekit/bin/entrypoint.py
tests/flytekit/unit/bin/test_python_entrypoint.py

This reverts commit b3bfef5815623ba3e717540ce700b21d494fefe9.
This change broke dynamic workflows
https://github.com/flyteorg/flyte/issues/3324
_NA_
OR

Revert "Remove project/domain from being overridden with execution values in serialized context (#1378)"

---

flytekit/core/data_persistence.py
tests/flytekit/unit/bin/test_python_entrypoint.py
tests/flytekit/unit/core/test_checkpoint.py
tests/flytekit/unit/core/test_data.py

windows tests

---

flytekit/core/type_engine.py
plugins/flytekit-data-fsspec/setup.py

fsspec 2023.3.0 seems to have broken something in the old code.  We are pinning to less than that while we work out the new code.
Pin
https://flyte-org.slack.com/archives/CP2HDHKE1/p1678209398640519

Pin fsspec to <=2023.1

---

plugins/flytekit-data-fsspec/setup.py

Please see https://github.com/flyteorg/flytekit/pull/1537/files

Pin fsspec

---

doc-requirements.txt
flytekit/types/structured/structured_dataset.py
plugins/flytekit-spark/tests/test_pyspark_transformers.py
tests/flytekit/unit/core/test_structured_dataset.py
tests/flytekit/unit/core/test_structured_dataset_handlers.py
tests/flytekit/unit/core/test_type_hints.py

Use fsspec placeholder for structured dataset

---

flytekit/clis/sdk_in_container/backfill.py
flytekit/clis/sdk_in_container/package.py
flytekit/clis/sdk_in_container/register.py
flytekit/clis/sdk_in_container/run.py
flytekit/clis/sdk_in_container/serialize.py

Update docs formatting for pyflyte. RestructuredText is a little bit different to Markdown... 😢

Pyflyte docs formatting

---

flytekit/clis/sdk_in_container/backfill.py
flytekit/clis/sdk_in_container/package.py
flytekit/clis/sdk_in_container/register.py
flytekit/clis/sdk_in_container/run.py
flytekit/clis/sdk_in_container/serialize.py
flytekit/core/type_engine.py
flytekit/tools/serialize_helpers.py
plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py
plugins/flytekit-data-fsspec/tests/test_persist.py
tests/flytekit/unit/cli/pyflyte/test_package.py

Backport be24c52f3fb8f7949db172f490cca95fa0f0e413 through e90ee2576c87298826b1ba702cf7569f43f737ba

[v1.2 Backport] be24c52 through e90ee25

---

flytekit/clis/sdk_in_container/backfill.py
flytekit/clis/sdk_in_container/package.py
flytekit/clis/sdk_in_container/register.py
flytekit/clis/sdk_in_container/run.py
flytekit/clis/sdk_in_container/serialize.py
flytekit/tools/serialize_helpers.py
plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py
plugins/flytekit-data-fsspec/tests/test_persist.py
tests/flytekit/unit/cli/pyflyte/test_package.py

7c3c255655d25e70988028d8773b034c7519d6e8 thru e90ee2576c87298826b1ba702cf7569f43f737ba

[v1.4] Patch in recent changes

---

.pre-commit-config.yaml
flytekit/extras/tensorflow/__init__.py
flytekit/extras/tensorflow/model.py
flytekit/extras/tensorflow/record.py
tests/flytekit/unit/extras/tensorflow/model/test_model.py
tests/flytekit/unit/extras/tensorflow/model/test_transformations.py

This PR enables `tf.keras.Model` to be utilized as a Flyte type. The code's adapted from https://github.com/flyteorg/flytekit/pull/1241.
Fixes https://github.com/flyteorg/flyte/issues/2570
_NA_
OR

TypeTransformer for TensorFlow model

---

setup.py

[v1.3 Backport] Less strict docker dependency versions (#1536)

---

flytekit/clis/sdk_in_container/run.py
flytekit/core/data_persistence.py
flytekit/remote/remote.py
tests/flytekit/unit/cli/pyflyte/test_register.py
tests/flytekit/unit/cli/pyflyte/test_run.py
tests/flytekit/unit/cli/pyflyte/workflow.py
tests/flytekit/unit/remote/test_remote.py

Fixes https://flyte-org.slack.com/archives/CP2HDHKE1/p1680845682408899
Add support nested FlyteFile in pyflyte run.
https://flyte-org.slack.com/archives/CP2HDHKE1/p1680845682408899
_NA_

Add support nested FlyteFile in pyflyte run

---

.pre-commit-config.yaml
flytekit/tools/translator.py

Remove extraneous debug statement

---

doc-requirements.in
doc-requirements.txt
docs/source/conf.py

Use a maintained package for the sphinx youtube plugin

update sphinx youtube plugin

---

flytekit/core/node.py
tests/flytekit/unit/core/test_node_creation.py

Fixed https://github.com/flyteorg/flyte/issues/3608
Convert the node name into a DNS-compliant.
^^^
https://github.com/flyteorg/flyte/issues/3608
_NA_

Override node name with a name containing underscore

---

.github/workflows/pythonpublish.yml

update GH workflow for external plugin service
^^^
_NA_
_NA_

update GH workflow for external plugin service

---

flytekit/remote/remote.py
flytekit/tools/repo.py

Pass verify tag to `upload_file`

Improve flytekit register

---

flytekit/core/promise.py
flytekit/core/type_engine.py
tests/flytekit/unit/core/test_promise.py

Remove ensure literal

---

flytekit/extend/backend/base_agent.py
plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
plugins/flytekit-bigquery/tests/test_agent.py

- Add bigquery project and location to metadata
- Return PERMANENT_FAILURE state if there is an error in `BigQurey.job`
Fixed https://flyte-org.slack.com/archives/CP2HDHKE1/p1683133259253529
^^^
https://flyte-org.slack.com/archives/CP2HDHKE1/p1683133259253529
_NA_

Add bigquery project and location to metadata

---

flytekit/__init__.py
flytekit/types/iterator/__init__.py
flytekit/types/iterator/iterator.py
tests/flytekit/unit/types/iterator/test_iterator.py

Add support using `typing.Iterator` in the type annotation
^^^
_NA_
_NA_

Add Iterator Transformer

---

.github/workflows/pythonbuild.yml
plugins/flytekit-huggingface/flytekitplugins/huggingface/sd_transformers.py
plugins/flytekit-huggingface/tests/test_huggingface_plugin_sd.py

Update pythonbuild.yml: add hugging face plugin to CI

---

tests/flytekit/unit/core/test_references.py
tests/flytekit/unit/remote/test_mocked.py
tests/flytekit/unit/remote/wf_with_remote.py

Add a couple tests

---

flytekit/clis/sdk_in_container/run.py

This PR updates docs around the pyflyte run command to indicate that it is no longer limited to single-script execution.
Fixes https://github.com/flyteorg/flyte/issues/3757
_NA_
OR

update docs around pyflyte run

---

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py

`torchrun` has an argument called `--nproc-per-node` which can be either `"auto"`, `"cpu"`, `"gpu"` or an integer (see [here](https://github.com/pytorch/pytorch/blob/979f826015cbd2b353f02e93865a9b9a8877b414/torch/distributed/run.py#L414C62-L414C81)). The argument controls the size of the local worker groups on each worker node.
Accordingly, the `ElasticPolicy` of the `PyTorchJob` CRD in the kubeflow training operator (which is used by the `flytekitplugins.kfpytorch` plugin) [states](https://github.com/kubeflow/training-operator/blob/a3a297213ada205dcf786e3eff4272a4b9343de1/pkg/apis/kubeflow.org/v1/pytorch_types.go#L109):
```go
type ElasticPolicy struct {
...
// Number of workers per node; supported values: [auto, cpu, gpu, int].
...
```
When building the torch elastic/torchrun Flyte …

Fix: Remove broken option to pass str value as `nproc_per_node` in `task_config=Elastic`

---

flytekit/extras/tasks/shell.py
tests/flytekit/unit/extras/tasks/test_shell.py

Cherry pick #1732 to release v1.2 branch
See #1732
https://github.com/flyteorg/flyte/issues/3559
_NA_

Cherry pick #1732 to release v1.2 branch

---

plugins/flytekit-mlflow/flytekitplugins/mlflow/tracking.py

https://github.com/flyteorg/flytekit/pull/1727 broke the mlflow tests. 
^^^
_NA_
_NA_

Fix mlflow test error

---

setup.py

[v1.8 Patch] Restrict grpcio<1.53.1

---

flytekit/configuration/__init__.py
flytekit/core/task.py

Make comment consistent with docs. Just barely a bug fix. Really just for code-readers.
Attn: @ppiegaze
_NA_
_NA_

Use phrase 'git revision SHA1' in comments and docs

---

.gitignore
doc-requirements.in
doc-requirements.txt
setup.py

Backport dep fixes
These dep fixes seem to be reasonable to backport to v1.8.
_NA_
_NA_

Backport dep fixes to v1.8

---

doc-requirements.txt
flytekit/configuration/__init__.py
flytekit/extend/backend/base_agent.py

As the title.
(Sorry for my git issue, I have to reopen a pull request)
Is adding the unit test necessary?
Exiting the program is good enough for the function, if we need to return an empty structured dataset instead, please let me know.
https://github.com/flyteorg/flytekit/pull/1687
https://github.com/flyteorg/flytekit/pull/1778
_NA_
OR

Add agent ctrl-c handler to call the delete function. (Reupload)

---

flytekit/core/base_task.py

Add type annotations for base task compile method

---

flytekit/core/base_task.py
tests/flytekit/unit/extras/tensorflow/model/test_transformations.py

Add type annotations for tensorflow model test transformation

---

flytekit/extend/backend/base_agent.py

As title.
Async Delete Function
_NA_

Add async delete function in base_agent

---

README.md

Add total download badge. I think it is worth adding to the readme since we have 2M downloads.
^^^
_NA_
_NA_

Add download badges to the readme

---

.github/workflows/pythonbuild.yml
README.md
codecov.yml

update codecov config in pythonbuild ci

---

flytekit/clis/sdk_in_container/run.py
flytekit/core/gate.py
flytekit/interaction/parse_stdin.py
tests/flytekit/unit/cli/pyflyte/test_run.py

Improved gate node handling and fix in pyflyte run to remove progress bar

Improved gate node handling

---

codecov.yml
tests/flytekit/unit/experimental/test_eager_workflows.py

Update codecov config to ignore with correct key name, make eager wf unit tests more stable

update codecov yaml, make eager wf test more stable

---

Dockerfile.agent

Fix flyteagent image build

---

flytekit/core/data_persistence.py
flytekit/types/file/file.py
flytekit/types/structured/basic_dfs.py
setup.py
tests/flytekit/unit/bin/test_python_entrypoint.py

PR into https://github.com/flyteorg/flytekit/pull/1674/files
Also skip a lint.
Limit fsspec for now - see discussion: https://flyte-org.slack.com/archives/CP2HDHKE1/p1698044484843609
https://github.com/fsspec/filesystem_spec/commit/7036b5a79894ed5f1b9bf230d3f1acd30a66dbcc

pa.arrow, issue with windows

---

flytekit/clis/sdk_in_container/fetch.py
flytekit/core/type_engine.py
flytekit/interaction/string_literals.py
flytekit/models/types.py
flytekit/remote/remote.py
tests/flytekit/unit/interaction/test_string_literals.py

Useful in pyflyte fetch
Also useful in new agents soon

Improved rendering of output literals

---

.github/workflows/docs_build.yml
.github/workflows/pythonbuild.yml

as title, always run the latest workflow in the PR.
https://stackoverflow.com/a/72408109/9574775
_NA_

Cancel a currently running workflow from the same PR when a new workflow is triggered

---

Dockerfile
Dockerfile.dev

Update Flytekit Dockerfile

---

.github/workflows/pythonpublish.yml

Try a different syntax for the publish wait.

change the wait

---

dev-requirements.txt
doc-requirements.txt
setup.py

Related to https://github.com/flyteorg/flyte/issues/4418
`wheel` is not used during runtime, so it is not needed as a requirement.

Remove wheel dependency

---

pull_request_template.md

This is a better PR template suggested by @ByronHsu !
Note: I move the Docs link to the bottom because it isn't used frequently.

Add `Why, What, Tests Sections` in PR Template

---

flytekit/clis/sdk_in_container/build.py
flytekit/clis/sdk_in_container/run.py
flytekit/clis/sdk_in_container/utils.py

This PR splits out independent refactors from https://github.com/flyteorg/flytekit/pull/1941 
This PR makes it easier to review future PRs that make the CLI pluggable.
1. Renames `make_field` to be more explicit: `make_click_option_field`
2. Simplifies `RunCommand` and `BuildCommand` hierarchy.
Since this PR does not introduce any behavior changes, the current unit tests should be sufficient.
https://github.com/flyteorg/flytekit/pull/1941

Simplify CLI implementation for build and run

---

.github/workflows/pythonpublish.yml

Fixes version issue in https://github.com/flyteorg/flytekit/actions/runs/7187240991/job/19576949461#logs

Inject version into the build environment

---

flytekit/models/literals.py
tests/flytekit/unit/models/test_literals.py

Forgot to add the new `metadata` field into the Literal model.

Literal metadata model update

---

pyproject.toml

NA
Python 3.12. is supported so it should be in the classifier
Add 3.12 as classifier

Add 3.12 as classifier

---

flytekit/models/literals.py
tests/flytekit/unit/models/test_literals.py

NA
Add metadata attribute to `Literal` class, so users can add arbitrary information to the literal.
Update literal class
Unit tests
NA
NA

Add metadata to literal

---

.github/workflows/pythonbuild.yml

NA
Not all CI checks ran before we merged https://github.com/flyteorg/flytekit/pull/2164. This PR fixes the lint error caused by that PR.

Fix lint error caused by #2164

---

flytekit/extras/tasks/shell.py
tests/flytekit/unit/extras/tasks/test_shell.py

fixes https://github.com/flyteorg/flyte/issues/4664
`executable` enables modification of the shell when using `ShellTask`. by default, subprocess in the `ShellTask` uses `/bin/sh`.
`ShellTask` accepts `executable` as an argument.

add executable to shell task

---

plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/vscode_lib/decorator.py

N/A
When we connect to the vscode server, it will show a workspace trust warning window.
Disable workspace trust for the vscode server.

feat(flyteinteractive): Disable workspace trust for vscode server

---

Makefile
plugins/flytekit-greatexpectations/setup.py
pyproject.toml
tests/flytekit/unit/core/test_local_cache.py

This PR pins the Great Expectations version, as the latest version is resulting in test failures.

pin great expectations version and run local cache tests serially

---

.github/workflows/pythonpublish.yml
Dockerfile.agent

Add a slim image for the sandbox
Build and push another agent image (flyteagent-slim)
Build locally
NA
NA

Add agent slim image

---

.github/workflows/monodocs_build.yml
flytekit/extend/backend/base_agent.py
plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py

Fix Monodocs build errors in CI

Fix Monodocs build

---

.github/workflows/pythonbuild.yml

NA
In https://github.com/flyteorg/flytekit/pull/2237 we modified how CI checks are run, going from running the same tests in PRs and on merges to master. However, the check to get the python versions is not correct, skipping merges to master. This PR simplifies that expression (and cover all cases, including merges to master).

Simplify version calculation

---

tests/flytekit/unit/core/test_flyte_file.py

NA
The test `test_file_type_in_workflow_with_bad_format` has been failing due to an invalid assumption that a path is writable. 
Rewrite the test to use python's stdlib to get a temporary file.

Rewrite test to work better on all platforms

---

flytekit/core/artifact_utils.py

Fix docs.
thank you @eapolinario @pingsutw

Fix monodocs

---

flytekit/clis/sdk_in_container/utils.py

_https://github.com/flyteorg/flyte/issues/4762_
We can omit too verbose debugging message when we merge 
https://github.com/flyteorg/flyte/pull/4924

Remove verbose debug message

---

flytekit/image_spec/image_spec.py
plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
plugins/flytekit-envd/tests/test_image_spec.py
tests/flytekit/unit/cli/pyflyte/test_run.py

_https://github.com/flyteorg/flyte/issues/5046_
Closes flyteorg/flyte#5046
This enables users to specify multiple extra-index-urls
ImageSpec gets a new field `pip_extra_index_url: Optional[List[str]]`, that will allow a user to specify multiple extra-index-urls.
The envd builder plugin is extended to process this list into an appropriate string that envd accepts.
A test is added  to check if the generated envd config file is correct.

Add extra-index-url to ImageSpec

---

.pre-commit-config.yaml

NA
`[Errno 86] Bad CPU type in executable: '/Users/austin/.cache/pre-commit/repo0642mtko/py_env-python3.12/bin/shellcheck'`
upgrade shellcheck-py to version `0.10.0.1`
https://pypi.org/project/shellcheck-py/

pre-commit: upgrade hook `shellcheck-py`

---

tests/flytekit/unit/core/test_local_cache.py

Fix flaky tests
https://github.com/flyteorg/flytekit/actions/runs/8456639230/job/23167844945?pr=1808

Add serial marker to cache related tests

---

flytekit/__init__.py

Makes artifact documentation visible on Flyte docs website.

Make artifact documentation visible

---

plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/agent.py
plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
plugins/flytekit-aws-sagemaker/tests/test_inference_agent.py

This PR removes secrets in the sagemaker agent as users can set environment variables when running the agent locally and the boto API uses IAM role by default in production cluster.

remove secrets in sagemaker agent

---

CODEOWNERS

Add @samhita-alla to CODEOWNERS

Add @samhita-alla to CODEOWNERS

---

plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/__init__.py
plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
plugins/flytekit-aws-sagemaker/tests/test_boto3_mixin.py

This is useful to specify the tritonserver image version.
Make `triton_image_uri` a function that accepts version.

allow specifying version for the tritonserver image in sagemaker agent

---

flytekit/models/task.py

Ran into an error in create method of Databricks agent when testing v1.11.0.
```
Last Error: USER:: rpc error: code = Internal desc = failed to create spark task with error: Object of type RepeatedScalarContainer is not JSON serializable
```
The parameter `spark_python_task` contains reference to container.args which is of type `RepeatedScalarContainer` from protobuf library
https://github.com/flyteorg/flytekit/blob/4d42399079535c3582c9adfad5791253dcbd045e/plugins/flytekit-spark/flytekitplugins/spark/agent.py#L51
This is not JSON serializable, resulting in error when converting the job request to json.
https://github.com/flyteorg/flytekit/blob/4d42399079535c3582c9adfad5791253dcbd045e/plugins/flytekit-spark/flytekitplugins/spark/agent.py#L62
Modified `Container.from_flyte_idl` method to …

Fix databricks job request serialization

---

.github/workflows/pythonbuild.yml
plugins/flytekit-mlflow/setup.py

NA
`mlflow` has had a bunch of CVEs in the recent past. This PR bumps it to the minimal version that's not affected by any critical or high risk CVE.

Set a minimum version to mlflow in flytekit plugin

---

flytekit/core/python_customized_container_task.py
tests/flytekit/unit/core/test_shim_task.py

_https://github.com/flyteorg/flyte/issues/4854_
Replace self.container_image with self.get_image() to accommodate the error caused by the placeholder string.

Accept template strings for SQLAlchemyTask container_image

---

flytekit/clis/sdk_in_container/run.py
tests/flytekit/unit/cli/pyflyte/test_run.py

N/A
It isn't reasonable that `pyflyte` can only run files under current and nested directories.
Remove the limit that pyflyte can only run files in current and nested directories

feat(pyflyte): Remove the limit that pyflyte can only run files in current and nested directories

---

flytekit/configuration/__init__.py

This PR fixes slight visual issue with dropdowns:
Before:
After:

fix dropdown formatting

---

flytekit/clis/sdk_in_container/register.py

Signed-off-by: chinghongfang <fjh7777@gmail.com>
https://github.com/flyteorg/flyte/issues/4576

[Docs] Pyflyte package --output should say tar file

---

Dockerfile.agent

The agent image [requires](https://github.com/flyteorg/flytekit/blob/master/Dockerfile.agent#L16) the sagemaker plugin, but that requires python >= 3.10.

Use python 3.10 as agent base image

---

plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/utils.py
plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/vscode_lib/decorator.py

NA
Module not found since file name is incorrect
Replace `.` with `/`
remote
NA
NA

Fix get_task_inputs in flytekitpluugins-interactive

---

pyproject.toml

NA
CI is failing. https://github.com/flyteorg/flytekit/actions/runs/9177694104/job/25237189502?pr=2353
https://github.com/docker/docker-py/issues/3256
Exclude broken `requests` versions in the pyproject.yaml
`requests` community will fix it in the next release. https://github.com/docker/docker-py/pull/3257#discussion_r1608653470
unit test
NA
NA

build: Exclude broken requests versions

---

pyproject.toml

Trying to make both work by user request.
https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html

Expand urllib3 to include v2

---

flytekit/types/iterator/json_iterator.py
plugins/flytekit-openai/flytekitplugins/openai/batch/task.py

https://github.com/flyteorg/flyte/issues/5274
* The blob type format should be "jsonl" as lowercase jsonl is used in the jsonl flytefile.
* `find_image_for` uses the openai batch image, whereas `default_image` uses the flytekit image.

convert jsonl to lowercase and update default image

---

flytekit/extend/backend/agent_service.py
flytekit/extend/backend/base_agent.py
plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
plugins/flytekit-aws-sagemaker/setup.py
plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
pyproject.toml

This PR adds `output_prefix` to the sync agent's `do()` method, allowing the use of the raw output prefix. It also updates the boto agent to account for the output prefix and updates the context.

add output prefix to `do()` method in sync agent & update boto agent

---

pyproject.toml

test requests

---

pyproject.toml

Remove upper bound for dependencies `click`.

Remove upper bound for deps `click`

---

pyproject.toml

Remove upper bound for dependencies `urllib3`.

remove upper bound for deps `urllib3`

---

pyproject.toml

Remove upper bound for dependencies `statsd`.

Remove upper bound for deps `statsd`

---

plugins/flytekit-huggingface/setup.py

Update flytekitplugins-huggingface dependency

---

plugins/flytekit-pydantic/setup.py

remove upper bound of plugin dependencies for flytekit-pydantic

remove upper bound of plugin dependencies for flytekit-pydantic

---

plugins/flytekit-whylogs/setup.py

remove upper bound of plugin dependencies for flytekit-whylogs

remove upper bound of plugin dependencies for flytekit-whylogs

---

plugins/flytekit-wandb/setup.py

remove upper bound of plugin dependencies for flytekit-wandb

remove upper bound of plugin dependencies for flytekit-wandb

---

.github/workflows/pythonbuild.yml
plugins/flytekit-envd/tests/test_image_spec.py

NA
To fix unit test
Install numpy<2.0.0 for pandera plugin

Install numpy<2.0.0 for pandera plugin

---

CODEOWNERS

Add thonmas and future outlier to CODEOWNERS

---

plugins/flytekit-papermill/tests/conftest.py

NA
unit tests in the papermill plugin are failing
Disable rich traceback temporarily until we figure out why it fails 
unit test
NA
NA

Disable rich traceback for papermill plugin

---

plugins/flytekit-sqlalchemy/setup.py

remove upper bound of plugin dependencies for flytekit-sqlalchemy

remove upper bound of plugin dependencies for flytekit-sqlalchemy

---

.github/workflows/pythonbuild.yml

We install flyteidl from master in core tests but not plugins. This unblocks https://github.com/flyteorg/flytekit/pull/2480.
Install flyteidl in flyteplugins tests CI.

Install flyteidl from master in plugins tests

---

tests/flytekit/unit/core/test_workflows.py

NA
Fix test errors on the master
run test_missing_return_value on python 3.10+
https://github.com/flyteorg/flytekit/pull/2623#discussion_r1698036808
unit test
NA
NA

run test_missing_return_value on python 3.10+

---

flytekit/types/structured/snowflake.py

Fix Snowflake Agent Secret Bug

---

flytekit/image_spec/default_builder.py

The latest `uv` fixes an issue with using a cache when using `git` and subdirectories.
Update `uv`.
Build an image with the new `uv`.

Update uv to 0.2.37 in default image builder

---

flytekit/core/base_task.py
flytekit/core/task.py

decorate function

---

plugins/flytekit-perian/README.md
plugins/flytekit-perian/flytekitplugins/perian_job/__init__.py
plugins/flytekit-perian/flytekitplugins/perian_job/agent.py
plugins/flytekit-perian/flytekitplugins/perian_job/task.py
plugins/flytekit-perian/setup.py
plugins/flytekit-perian/tests/test_perian.py

Adding a new agent to run Flyte tasks on the Perian Job Platform (perian.io).
* Unit tests
* Testing against local sandbox cluster
See README.md

Add Perian Job Platform agent

---

tests/flytekit/unit/configuration/test_yaml_file.py

Fix `test_real_config` func by unset `FLYTE_AWS_ENDPOINT` env

---

tests/flytekit/unit/core/test_type_hints.py

https://github.com/flyteorg/flyte/issues/5687
If caching, it will store the faulty execution and cannot be fixed if the `make unit_test` is rerun locally.
Remove caching.
```
make unit_test
```
Run it locally

fix local test `test_list_containing_multiple_annotated_pandas_dataframes` fail

---

docs/source/design/clis.rst
flytekit/clis/sdk_in_container/serialize.py

`pyflyte serialize` has long been functionally deprecated by `pyflyte package`.  This PR just adds some notes that informs users what they should do.

Add deprecation note to pyflyte serialize

---

dev-requirements.in

revert the changes since CI is failing
related PR:
https://github.com/flyteorg/flytekit/pull/2766

Revert dev-requirements.in change for MacOS

---

.github/workflows/monodocs_build.yml

Monodocs build is failing.
Adds a random `DOCSEARCH_API_KEY` to get docs to build

Adds a random DOCSEARCH_API_KEY to get monodocs build to succeed

---

plugins/flytekit-bigquery/setup.py

Various mentions have been made about a `error: Protocol not known: bq` error when trying to use the bigquery agent. Installing `google-cloud-bigquery-storage` fixes this issue. 
Example of an occurrence: https://discuss.flyte.org/t/12921874/hello-i-am-running-bigquery-task-locally-i-am-using-the-late
Update the requirements of the big query agent so it works out of the box.
1. `pip install flytekitplugins-bigquery` - install current version
2. Observe error in a local run of an example like [this](https://docs.flyte.org/en/v1.10.7/flytesnacks/examples/bigquery_plugin/bigquery.html#bigquery-query).
```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /Users/danielsola/miniconda3/envs/wine-classification/lib/python3.11/site-pa │
│ …
```

update bigquery plugin reqs

---

flytekit/core/type_engine.py
tests/flytekit/unit/core/test_type_engine.py

Cherry pick of https://github.com/flyteorg/flytekit/pull/2802

Instance generic empty case (#2802)

---

flytekit/core/type_engine.py
tests/flytekit/unit/core/test_dynamic.py
tests/flytekit/unit/core/test_type_engine.py

https://github.com/flyteorg/flyte/issues/5804
We don't need to check the types of the values, just the container.  The types of the values are checked recursively.

More instance generic checks

---

docs/source/plugins/index.rst
docs/source/plugins/perian.rst
plugins/flytekit-perian/flytekitplugins/perian_job/__init__.py
plugins/flytekit-perian/flytekitplugins/perian_job/agent.py
plugins/flytekit-perian/flytekitplugins/perian_job/task.py

Add docs for PERIAN agent. Flytesnacks example is added in [another PR](https://github.com/flyteorg/flytesnacks/pull/1746).
https://github.com/flyteorg/flytesnacks/pull/1746

Add PERIAN agent docs

---

flytekit/core/type_engine.py
tests/flytekit/unit/core/test_type_engine.py

Backport #2824 to release v1.13

fix is_optional_type or not return true for all union types (#2824)

---

.github/workflows/pythonbuild.yml

Porting https://github.com/flyteorg/flytekit/pull/2826/ to the main branch.

Run tests on merges to release branches

---

tests/flytekit/unit/interaction/test_click_types.py

Small change to clean up unit test.

Small change to clean up unit test.

---

flytekit/clis/sdk_in_container/run.py
flytekit/remote/remote.py

Ability to run Locally defined launchplans from the CLI

Support executing launchplans from CLI

---

flytekit/core/tracker.py
flytekit/remote/remote.py
tests/flytekit/unit/remote/test_remote.py

https://github.com/flyteorg/flyte/issues/5881
We should not create new tasks for each updated code in Jupyter Notebook's cells. We should aggregate the same tasks or workflows and update the version only.
1. Create a new hash function for the pickled entity, and compute the version if the version is not specified before fetching the entities. Therefore, if we don't update the entity, we will use the one with the same version. However, if we update the code (to be specific, re-executing the unchanged cell will also count as an update), the version will be different, and new version will be registered.
2. Make the module names of entities from Jupyter Notebook empty string so that it doesn't create multiple tasks for the same task.
3. I found that sometimes Jupyter Notebook's virtual file …

Fix Jupyter Versioning 

---

flytekit/core/type_engine.py
tests/flytekit/unit/core/test_enum_type.py

Backports https://github.com/flyteorg/flytekit/pull/2873 to 1.13 branch.

fix enum type assertion with python versions less than 3.12 (#2873)

---

flytekit/core/type_engine.py

https://github.com/flyteorg/flytekit/pull/2823#issuecomment-2430523586
https://github.com/flyteorg/flyte/issues/5633
now in flytekit, we only support python 3.9 to python 3.12, so we can delete code for python 3.8.
unit test, local execution, and remote execution.
unit test is written here:
https://github.com/flyteorg/flytekit/blob/804dae1e9ba8cb8060c919b4bde7421db41bc20d/tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py#L502-L504
local execution and remote execution python file:
```python
import typing
from pathlib import Path
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
from flytekit import FlyteContext, ImageSpec, StructuredDatasetType, kwtypes, task, workflow
from flytekit.models import …
```

Remove `_fix_structured_dataset_type` to deprecate python 3.8

---

flytekit/extend/backend/base_agent.py
tests/flytekit/unit/extend/test_agent.py

See discussion on [slack](https://flyte-org.slack.com/archives/CP2HDHKE1/p1730498307566449)
Unit tested.

Agent - missing type hint

---

flytekit/extend/backend/base_agent.py
tests/flytekit/unit/extend/test_agent.py

Backport of https://github.com/flyteorg/flytekit/pull/2896

Agents - missing type hint (#2896)

---

docs/source/experimental.rst
flytekit/experimental/__init__.py

Array node map tasks are the default map task since 1.12.0.

Remove array node map task from experimental

---

flytekit/clis/sdk_in_container/run.py

Wait for execution with an interval
```
pyflyte run --remote --wait -i 1 schedule.py say_hello --name test --t now
```

Adds support for wait for execution with a configurable interval

---

flytekit/core/promise.py

NA
Update error message for nested task and workflow

Improve error message for nested tasks

---

pyproject.toml

NA
The new version of mashumaro is breaking the decoding of dictionaries. This PR only unblocks CI checks while we investigate the proper fix.

Skip mashumaro 3.15 temporarily

---

flytekit/core/context_manager.py
flytekit/extend/backend/base_agent.py
flytekit/sensor/sensor_engine.py
flytekit/utils/asyn.py

Set signal handler in the main thread

---

pyproject.toml

https://github.com/flyteorg/flytekit/pull/2952

mashumaro>=3.15

---

plugins/flytekit-inference/flytekitplugins/inference/nim/serve.py

This PR enables storing the NIM model in the cache mounted in the model server container.
Mount a cache volume in the model server container.

mount cache dir to the NIM model server container

---

.github/actions/clear-action-cache/action.yml

Skip clear-action-cache gh action on windows

---

.github/actions/clear-action-cache/action.yml
flytekit/extend/backend/base_agent.py
flytekit/extend/backend/utils.py

pr into async/tasks branch.  it seems like there is additional logic in airflow that depends on being run on the main thread.

revert changes for base agent

---

flytekit/tools/fast_registration.py

During fast registration, the digest computation happens even if one of the branches do not use it.
This PR moves the digest computation to the branch that uses it.
The current unit tests should cover this, since the behavior has not changed.

Move digest computation

---

flytekit/core/type_engine.py
flytekit/lazy_import/lazy_module.py
flytekit/types/structured/__init__.py
flytekit/types/structured/structured_dataset.py
tests/flytekit/unit/core/test_generice_idl_type_engine.py
tests/flytekit/unit/core/test_type_engine.py
tests/flytekit/unit/lazy_module/test_lazy_module.py
tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py

https://github.com/flyteorg/flytekit/pull/2987

[v1.14] Backport Fix lazy import (#2987)

---

docs/source/experimental.rst

Remove eager exception doc

---

.github/workflows/pythonbuild.yml
flytekit/core/data_persistence.py
flytekit/remote/remote.py
plugins/flytekit-dbt/setup.py
plugins/flytekit-inference/flytekitplugins/inference/ollama/serve.py
plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py
plugins/flytekit-polars/tests/test_polars_plugin_sd.py
tests/flytekit/unit/core/test_data_persistence.py
tests/flytekit/unit/remote/test_remote.py

https://github.com/flyteorg/flytekit/pull/2989
https://github.com/flyteorg/flytekit/pull/2992
https://github.com/flyteorg/flytekit/pull/2997
https://github.com/flyteorg/flytekit/pull/2998
https://github.com/flyteorg/flytekit/pull/3001

Backport changes for 14.1

---

flytekit/remote/remote.py
tests/flytekit/unit/remote/test_remote.py

Backport of https://github.com/flyteorg/flytekit/pull/3049
related to https://github.com/flyteorg/flyte/issues/6062

Prevent register_launch_plan from re-registering already registered workflows

---

flytekit/core/type_engine.py
tests/flytekit/unit/core/test_type_hints.py

We should provide more detail error messages for users, so that they can know how to debug.
before
```python
Message:
ValidationError: 1 validation error for XXX
transporter
Input should be an object [type=model_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.10/v/model_type
```
after
```python
Message:
TypeTransformerFailedError: Error converting input 'input_data' at position 0:
Literal value: Flyte Serialized object (Literal):
scalar:
binary:
value: [...]
tag: msgpack
Literal type: None
Expected Python type: <class 'flyte_example.XXX'>
Exception: 1 validation error for XXX
transporter
Input should be an object [type=model_type, input_value=None, input_type=NoneType]
For further information visit …
```

Improve Type Engine Error Msg

---

flytekit/bin/entrypoint.py
flytekit/clis/sdk_in_container/run.py
flytekit/core/array_node_map_task.py
flytekit/core/node.py
flytekit/core/type_engine.py
flytekit/exceptions/user.py
flytekit/image_spec/default_builder.py
flytekit/remote/remote.py
flytekit/tools/translator.py
plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
tests/flytekit/integration/remote/test_remote.py
tests/flytekit/integration/remote/workflows/basic/signal_test.py
tests/flytekit/unit/bin/test_python_entrypoint.py
tests/flytekit/unit/core/test_array_node_map_task.py
tests/flytekit/unit/core/test_type_engine.py
tests/flytekit/unit/exceptions/test_user.py

Backports the following commits:
- 4b50681badb3e3ce2fd641f775b74ac9ff7014f1
- 0bb8bad5954b1c5edd22da4362c605b6b3f84d3b
- 30088c2c970aff0b76c0bdd4db72b3c3e1d6fd18
- abf0d411e57c942cb4ed708feb9383f0aa4a6be6
- 665c44df3dae88d33f5b32ac3d5d25711de899ed
- 3260ddfea32b0a772cf002da643a02299be1021a
- a86048a094ee0d474c11a641a33d9288ff5e4bf8
This PR enhances Flytekit with improved error handling through timestamp support and custom error codes, introduces better node metadata management for array tasks, and adds new signal management features for remote execution. The changes include Docker build optimizations and comprehensive test coverage across all new functionality.
<br>
<br>
<br>
<br>
<b>Estimated effort to review …

Backport changes up to 2025/01/21

---

flytekit/core/data_persistence.py
flytekit/core/type_engine.py
tests/flytekit/unit/core/test_data_persistence.py
tests/flytekit/unit/core/test_list.py

Backport https://github.com/flyteorg/flytekit/pull/3080
https://github.com/flyteorg/flyte/issues/6188

v1.14 - Backport 3080 async coroutine batch fix 

---

flytekit/clis/sdk_in_container/run.py
tests/flytekit/integration/remote/test_remote.py
tests/flytekit/integration/remote/workflows/basic/pydantic_wf.py

* Fix pydantic default input
https://github.com/flyteorg/flyte/issues/6186
This PR implements support for both Pydantic v1 and v2 BaseModel serialization in Flytekit's CLI input handling. The changes focus on enhancing JSON encoding logic for Pydantic models' default values, with a unified approach using duck typing for version compatibility. The implementation includes refactoring of serialization logic and improved error handling in tests.
<br>
<br>
<br>
<br>
</div>

Backport for pydantic basemodel CLI input

---

flytekit/core/type_engine.py
flytekit/remote/remote_fs.py
flytekit/types/structured/structured_dataset.py
tests/flytekit/unit/core/test_dataclass.py
tests/flytekit/unit/extras/pydantic_transformer/test_pydantic_basemodel_transformer.py
tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py

Backport https://github.com/flyteorg/flytekit/pull/3086

v1.14 Backport 3086 - StructuredDatasets inside dc/pydantic

---

.github/workflows/pythonbuild.yml

N/A
Linux arm64 github runners finally [hit GA](https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/). We sometimes receive bug reports that only repro on arm, so let's get ahead of those and enable unit tests on arm in CI.
Run a portion of unit-tests on arm64.

Also run unit tests on arm64

---

flytekit/remote/remote.py
tests/flytekit/integration/remote/test_remote.py

Add return type hint in PR #3102
Add `ReferenceWorkflow` into return type hint for function `register_script()`.
This PR enhances type hint support by adding ReferenceWorkflow to the return type of register_script() in FlyteRemote class. The changes include updating function signatures with Union type and adding ReferenceWorkflow handling logic, along with corresponding test updates to verify the new functionality.
<br>
<br>
<br>
<br>
</div>

add ReferenceWorkflow into return type hint

---

flytekit/__init__.py
flytekit/core/cache.py
tests/flytekit/unit/core/test_cache.py

https://github.com/flyteorg/flyte/issues/6143
We should instruct users on how to handle the case of failures coming from the application of cache policies.
Have a try-except block in the for loop used to process cache policies and in case a failure is detected we raise a more specific exception that instructs the user what they need to do.
unit tests and local tests.
This PR enhances error handling in cache policy implementation by improving exception handling and error messages. The changes include adding a try-except block for cache policy version generation, implementing more descriptive ValueError messages, and providing clear instructions for users when version generation fails.
<br>
<br>
<br>
<br> …

 Add instructions for how to handle failures coming from cache policies

---

.github/workflows/pythonbuild.yml

NA
Similar to https://github.com/flyteorg/flyte/pull/6256, we need to update all of our uses of the `actions/cache` gh action to v4.

Update actions/cache to v4

---

.github/workflows/build_image.yml
.github/workflows/pythonpublish.yml

NA
Just a general update of the actions used to build cross-platform images.

Update qemu in gh workflows

---

plugins/flytekit-spark/flytekitplugins/spark/agent.py
plugins/flytekit-spark/tests/test_agent.py

Closes flyteorg/flyte#6253
At the moment, the Databricks agent expects the users to provide a databricks instance as part of their task configuration when running Databricks tasks. Considering that databricks tokens are tied to the a specific instance and that the token is always provided through secrets to the agent, this PR adds the option to provide a default instance so that users don't need to specify it themselves, simplifying the user experience. This means that users don't have to register a task for each databricks instance that might be available for them.
Modify the `create` method of the Databricks agent to use a default databricks instance provided through an environment variable if available and if the users haven't specified an instance themselves.
The following tests were …

Add support for providing a default instance to the databricks agent

---

flytekit/core/data_persistence.py
flytekit/core/type_engine.py

There are HTML entities in the markdown. That poses a security issue. Removing them.
Documentation changes.
N/A
N/A
This pull request enhances code security by implementing safer string formatting in the data persistence module. Documentation clarity is improved with better markdown formatting in the type engine module, including added code block markers. These changes address security vulnerabilities while improving overall code maintainability and documentation usability.
<br>
<br>
<br>
<br>
</div>

Update documentation to generate site.

---

CODEOWNERS

Adding myself as codeowner to be able to help with reviews
This PR updates the CODEOWNERS file by adding @davidmirror-ops as an additional code owner. The change is focused solely on expanding the review team's coverage to enhance the code review process. The modification is minimal and only affects the code review configuration.
<br>
<br>
<br>
<br>
</div>

Add new codeowner

---

.github/workflows/pythonpublish.yml

fix the github action error here
https://github.com/flyteorg/flytekit/actions/runs/14389193551/job/40352428573

[connector] CI fix

---

flytekit/clients/auth/token_client.py

Fix the type annotation of scope in the poll_token_endpoint function. It should be a list of string instead of a single string.
The type annotation of the function is not correct, not only cause confusion, but potentially dangerous in the future:
for a List of string v.s. string, if there is anything like a `for loop` against, the expected behavior would be different. By then, it would be difficult to detect.
Fix the type annotation from single string to List of strings.
The unit tests are correct w.r.t to the scope type. The current behavior are the same.
This pull request enhances the type safety of the 'poll_token_endpoint' function by updating the 'scopes' parameter type annotation from a …

Fix type annotation of poll_token_endpoint

---

.github/workflows/pythonbuild.yml

CI can't pass and PR cannot be merged
Change `flytectl demo start` to `flytectl demo start --disable-agent --image cr.flyte.org/flyteorg/flyte-sandbox-bundled:sha-3a102b9f4f9b83a150a01d885df1654d89561ce7 ` (use v1.16.0 image) for now to make CI pass

build: change flyte demo start command to make CI work
