flyteorg/flytekit

- dev-requirements.txt
- doc-requirements.txt
- flytekit/models/execution.py
- flytekit/models/literals.py
- flytekit/models/node_execution.py
- plugins/flytekit-airflow/tests/test_agent.py
- setup.py
- tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
- tests/flytekit/unit/models/test_execution.py
- tests/flytekit/unit/models/test_literals.py
This PR removes the `pytz` dependency.
`pytz` was only used to get `UTC`, which can be directly replaced with `timezone.utc`.
Towards https://github.com/flyteorg/flyte/issues/4418
> MAINT Remove pytz dependency

- dev-requirements.txt
- doc-requirements.txt
- flytekit/configuration/__init__.py
- setup.py
- tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
This PR removes the `docker-image-py` dependency.
Instead of using `docker-image-py`, we can use the `docker` library, to parse the tag.
Towards https://github.com/flyteorg/flyte/issues/4418
> Removes docker-image-py dependency

- .github/workflows/pythonbuild.yml
This PR fixes codecov upload.
When looking at the codecov job on the [ci](https://github.com/flyteorg/flytekit/actions/runs/6896084495/job/18761450916), it fails to detect the xml file. This PR explicitly sets the xml file for the codocov GitHub Action to pick up.
> FIX Fixes codecov upload

- tests/flytekit/unit/extras/tasks/test_shell.py
- tests/flytekit/unit/extras/tasks/testdata/long-running.sh
This test is flakey on CI and can sometimes fail between runs with:
```
FAILED tests/flytekit/unit/extras/tasks/test_shell.py::test_long_run_script - Failed: Timeout >10.0s
```
Increasing the timeout should help.
> MAINT Adds more timeout for flakey test

- flytekit/clients/friendly.py
- flytekit/remote/remote.py
We had removed the artifact spec from the data proxy endpoint.  forgot to remove here.
> [pr] remove stale spec in data proxy

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
There is an error when using imageSpec for dynamic task.
The builder should only be checked if the image does not exist 
```python
from flytekit import ImageSpec, task, dynamic, workflow
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@90c7750b99d53b44dd92633fb8225b3bed51fb21"
repro_img = ImageSpec(
name="repro",
apt_packages=["curl", "git"],
packages=[new_flytekit],
)
@task(container_image=repro_img)
def foo():
print("foo")
@dynamic(container_image=repro_img)
def bar():
foo()
@workflow
def wf():
bar()
if __name__ == '__main__':
wf()
```
_NA_
> Do not check if image builder exists in the dynamic task

- plugins/flytekit-flyin/flytekitplugins/flyin/vscode_lib/decorator.py
https://github.com/flyteorg/flyte/issues/4284
Originally, we used the root logger imported from flytekit. However, it doesn't show the info level logs. The default level is a warning.
Switch to use the logger from flytekit current_context, which is used to print logs during execution. By default, it uses [user-space logger](https://github.com/flyteorg/flytekit/blob/a6f9991952f6f95a2de99cf187e0778f3abff4e8/flytekit/core/context_manager.py#L868), whose level is [INFO](https://github.com/flyteorg/flytekit/blob/a6f9991952f6f95a2de99cf187e0778f3abff4e8/flytekit/loggers.py#L78), so it can also print logs >= INFO level.
The usage is simple. We call `logger = flytekit.current_context().logging` to get the logger.
```python
IMAGE="localhost:30000/flytekit:0.0.4"
@task(
container_image=IMAGE,
) …
```
> [flyin] Use current context logger instead of root logger to show info level logs

- flytekit/interaction/click_types.py
this PR converts datetime objects to date objects when the Python type is specified as  `datetime.date`.
> convert datetime to date when the type is specified as date

- pyproject.toml
Configure `exclude_lines` for Codecov. There are certain lines that shouldn't affect code velocity of a PR.
See: https://github.com/nedbat/coveragepy/issues/831#issuecomment-517778185
Apparently this isn't configurable through `codecov.yml` 🙈 : https://github.com/codecov/codecov-python/issues/107#issuecomment-793976712
I opened this because I noticed this issue was affecting an existing PR: https://github.com/flyteorg/flytekit/pull/1818#discussion_r1357847730
> Add codecov exclude_lines configuration

- plugins/flytekit-flyin/flytekitplugins/flyin/vscode_lib/decorator.py
- plugins/flytekit-flyin/tests/test_flyin_plugin.py
https://github.com/flyteorg/flyte/issues/4284
This PR introduces two enhancements to the Flyin VSCode decorator:
1. Conditional VSCode Server Launching: The VSCode server launch behavior is now context-sensitive:
- Local Execution: When a task is executed locally (using commands like python xxx.py or pyflyte run xxx), the VSCode server will not be initiated.
- Remote Execution: In contrast, when a task is run remotely (using pyflyte run --remote ...), the VSCode server will be launched.
2. New Argument - run_task_first: A new argument has been added to the decorator:
- Functionality: When set to True, this argument ensures that the user's task is executed first.
- Server Launching Condition: The VSCode server will only be launched if the user's task execution fails.
> Run task first and detect local execution

- flytekit/core/promise.py
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
Return None type instead of exception for list subtype
More details in https://github.com/flyteorg/flyte/issues/4270
Fixes https://github.com/flyteorg/flyte/issues/4270
_NA_
> Return None type instead of exception

- setup.py
Attempt to resolve https://github.com/flyteorg/flyte/issues/4465 by removing the upper bound on pyarrow dependency.
> Remove upper bound on pyarrow

- flytekit/core/checkpointer.py
- tests/flytekit/unit/core/test_checkpoint.py
Closes #4478
https://github.com/flyteorg/flyte/issues/4478
Make flytekit restore handle existing tmp dir if one tries to restore multiple times from a corrupt checkpoint.
> Fix: Restore of corrupt checkpoints

- flytekit/core/launch_plan.py
- tests/flytekit/unit/core/test_launch_plan.py
Fix default parameters when launching launchplans from within other workflows. 
Save the default inputs during `LaunchPlan.get_default_launch_plan` the same as in `LaunchPlan.create`
https://github.com/flyteorg/flyte/issues/4444
_NA_
> Fix default paramaters when launching launchplans from within other workflows

- flytekit/core/node.py
- tests/flytekit/unit/core/test_array_node_map_task.py
- tests/flytekit/unit/core/test_map_task.py
https://github.com/flyteorg/flyte/issues/4493
This PR allows users to override the `python_function_task` inside of map task.
`with_override` doesn't work with map task since we didn't override the `python_function_task` inside of map task.
```python
import typing
from flytekit import task, workflow, map_task
@task
def my_mappable_task(a: int) -> typing.Optional[str]:
return str(a)
@workflow
def wf(x: typing.List[int]=[1, 2, 3, 5]) -> typing.List[typing.Optional[str]]:
map_task(my_mappable_task, concurrency=10, min_success_ratio=0.75)(a=x)
a = map_task(my_mappable_task, concurrency=10, min_success_ratio=0.75)(a=x).with_overrides(container_image="random:image")
return a
if __name__ == '__main__':
wf(x=[1, 2, 3])
```
> Override the container image of map task

- Dockerfile
- Dockerfile.dev
- plugins/flytekit-flyin/Dockerfile
Fix envd unit test. https://github.com/flyteorg/flytekit/actions/runs/7118907266/job/19383987236?pr=2025
Use default permission `777` for `/tmp`
Manually build an image
> changing permissions of /tmp

- plugins/flytekit-flyin/Dockerfile
FlyIn Image is not able to build because python version variable is empty
Set python version to 3.10
local build
> Fix flyin image by setting py to 3.10

- plugins/flytekit-flyin/Dockerfile
https://github.com/flyteorg/flyte/issues/4284
https://github.com/flyteorg/flytekit/pull/2036
```Dockerfile
FROM python:3.10-slim-buster
MAINTAINER Flyte Team <users@flyte.org>
LABEL org.opencontainers.image.source https://github.com/flyteorg/flytekit
WORKDIR /root
ENV PYTHONPATH /root
ARG VERSION
ARG TARGETARCH
RUN apt-get update \
&& apt-get install build-essential git wget -y \
&& mkdir -p /tmp/ \
&& mkdir -p /tmp/code-server \
&& wget --no-check-certificate -O /tmp/code-server/code-server-4.19.0-linux-${TARGETARCH}.tar.gz https://github.com/coder/code-server/releases/download/v4.19.0/code-server-4.19.0-linux-${TARGETARCH}.tar.gz \
&& tar -xzf /tmp/code-server/code-server-4.19.0-linux-${TARGETARCH}.tar.gz -C /tmp/code-server/ \
&& wget --no-check-certificate …
```
> Fix Flyin Dockerfile

- plugins/flytekit-flyin/flytekitplugins/flyin/vscode_lib/constants.py
- plugins/flytekit-flyin/flytekitplugins/flyin/vscode_lib/decorator.py
_https://github.com/flyteorg/flyte/issues/4284_
Current implementation of vscode decorator wrongly assumes that _current working dir_ == the directory of task function module. For example, the working dir of imagespec is `/`. Therefore, when we run
```python
shutil.copy(
f"{task_function.__module__}.py",
os.path.join(context_working_dir, f"{task_function.__module__}.py"),
)
```
wf.py will not be found because it is actually at /root/wf.py.
1. Use inspect.getsourcefile(self.fn) to get the path of the source of the task function.
2. In `exit_handler`, `prepare_interactive_python`, `prepare_resume_task_python`, and `prepare_launch_json`, use this path instead of _current working dir_, which we wrongly assumed before.
> Flyin - fix vscode task path

- .github/workflows/monodocs_build.yml
Fixes [_https://github.com/flyteorg/flyte/issues/<number>_](https://github.com/flyteorg/flyte/issues/4557)
With the monodocs build process in `flyteorg/flyte`, we need a way of making sure upstream changes in the `flytekit` repo do not break the overall build.
Adds a github action workflow to build the docs.
> add monodocs ci build in flytekit

- .github/workflows/pythonpublish.yml
Fixes deployment issue seen in https://github.com/flyteorg/flytekit/actions/runs/7186707178/job/19572701206
The plugins still require `setuptool` and `wheel` to be installed to build.
> Adds setuptools and wheel back in the CI for plugins

- flytekit/models/core/execution.py
None afaik
So that we can access all possible phases returned by Flyte within `flytekit`.
Also suggesting a refactoring to `enum_to_string()` in the [second commit](https://github.com/flyteorg/flytekit/pull/2022/commits/c3ed4e6f0d7fa7bbb3fe72dddffd909949347e7f). Happy to drop that if it's deemed unnecessary.
I ran `make test` locally and it ran through. I didn't add any more tests because as much as I could find everything would fall apart already if I messed up `enum_to_string()`, so expecting that that is still functional after this PR :)
> Add various executions phases which are available in flyteidl, but not in flytekit

- flytekit/models/literals.py
- plugins/flytekit-flyin/flytekitplugins/flyin/vscode_lib/decorator.py
_https://github.com/flyteorg/flyte/issues/4284_
Previously, when users accessed the VSCode server by navigating to `http://localhost:8080` in their web browser, they were not directed to a specific directory. This could be confusing, especially for those who are not familiar with VSCode, as they might not see their code files immediately.
The proposed change sets a default directory for the VSCode server. Now, when users connect to the server without setting the folder argument such as `http://localhost:8080`, VSCode server will automatically open the directory where the task function's source files are located, which is `http://localhost:8080/?folder=/root`.
> Flyin - VSCode default directory

- pyproject.toml
Fixes warnings seen in https://github.com/flyteorg/flytekit/actions/runs/7187240991/job/19636434972 when building the wheel.
> Fix warnings in package building

- plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py
- plugins/flytekit-deck-standard/setup.py
- plugins/flytekit-deck-standard/tests/test_renderer.py
Because Data Engineers sometimes open the console (UI) with stakeholders to discuss business logic in the data pipeline, at this time, in addition to the expression of data graphics, they can also present source code to discuss program architecture design if necessary.
This is the idea from @pingsutw, I also agree with this idea very much, so I implemented this function.
- Add `pygments` to the list of plugin requirements in `setup.py`
- Add `pygments` import in `renderer.py`
- Add CSS styling to the rendered HTML code in `renderer.py`
- Update the `to_html` method to include the CSS styling in the returned HTML
- Add a new static method `_get_css` in `renderer.py` to extract CSS from the provided `HtmlFormatter` instance and replace a specific color code
- Add a new test method …
> feat: add `source code` deck

- flytekit/bin/entrypoint.py
- flytekit/clients/raw.py
- flytekit/clis/sdk_in_container/helpers.py
- flytekit/clis/sdk_in_container/pyflyte.py
- flytekit/clis/sdk_in_container/register.py
- flytekit/clis/sdk_in_container/run.py
- flytekit/clis/sdk_in_container/utils.py
- flytekit/loggers.py
- flytekit/remote/entities.py
- flytekit/remote/remote.py
- flytekit/remote/remote_callable.py
- flytekit/tools/ignore.py
With this change, flytekit now has 2 loggers, one for framework and one for user code.
Logger is default initialized based on environment. This logger is usually a json logger.
But, when a user runs any pyflyte command, the logger is switched (upgraded) to a rich logger. this can be turned off, but the logging is way more readable. the format is also adjusted
using `pyflyte -vvv` or `pyflyte -v` changes verbosity level of the log
```
pyflyte -vv run test2.py wf --n 10
```
The PR also simplifies the logging setup. Now, everywhere in the framework, `logger` should be used. There is work to be done to make the logging less verbose and more meaningful, that will be done as a follow up
Better logging when using the CLI
Logger setup for flytekit
locally and remotely
> Logger improvements

- flytekit/clis/sdk_in_container/utils.py
Giving a try on printing Traceback when errors are raised in `pyflyte`
Note:
Only included printing tracebacks when it's not `FlyteException` or `grpc` errors.
https://github.com/flyteorg/flyte/issues/4248
```pyflyte run workflow.py
Usage: pyflyte run workflow.py [OPTIONS] COMMAND [ARGS]...
Run a [workflow|task] from workflow.py
╭─ Options ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --help      Show this message and exit. …
```
> Preserve stacktrace

- flytekit/core/data_persistence.py
- flytekit/extend/backend/base_agent.py
Agent failed to run a `PythonFunctionTask` remotely since `input.pb` was not found. 
Upload empty input.pb even if the input is None since `--inputs` is required by the `pyflyte-execute` command
https://github.com/flyteorg/flytekit/blob/47e15b607c67aee2274190cf90877c4cead859b3/flytekit/bin/entrypoint.py#L454
Run an agent task locally
NA
NA
> Agent uploads input.pb even if task input is None

- flytekit/extend/backend/base_agent.py
Bug fix.
We should input `literal_map` instead of a `dictionary` to execute the agent task locally.
```python
from flytekit.sensor.file_sensor import FileSensor
sensor = FileSensor(name="test_sensor")
@task()
def t1():
return
@workflow()
def wf():
sensor(path="/tmp") >> t1()
wf()
```
Before
After
> Fix Base Agent Bug

- flytekit/configuration/plugin.py
The `pyflyte` `main` command is passed in here which is a `Group` object:
https://github.com/flyteorg/flytekit/blob/fccf7c7bd0c3aba180cc040c96818c6e951523a2/flytekit/clis/sdk_in_container/pyflyte.py#L29
> Fixes type hint for configure_pyflyte_cli in plugin

- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
We recently observed many pytorch elastic training jobs failing with the following "user error":
```console
File ".../flytekitplugins/kfpytorch/task.py", line 391, in _execute
out = elastic_launch(
...
File ".../torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
Message:
Process 107 got signal: 15
User error.
```
This `SignalException` [is raised by pytorch when the elastic launch agent process (which launches the worker processes within a Pod) receives SIGTERM etc](https://github.com/pytorch/pytorch/blob/f170d6665ca7dea844d20b06bd4dcb82d28f2879/torch/distributed/elastic/multiprocessing/api.py#L62). This in turn happens for instance when a multi pod distributed …
> Fix: Handle SIGTERM in kubeflow pytorch elastic training plugin

- plugins/flytekit-flyin/flytekitplugins/flyin/utils.py
Fix the wrong usage of context.
> Flyin - fix the wrong usage of context.

- flytekit/configuration/plugin.py
- tests/flytekit/unit/cli/pyflyte/test_plugin.py
For the initial release, I think it's better to be strict and disallow multiple plugin installed.
I updated the code and tests to have the more restricted behavior.
I updated the unit test to check for the error when multiple multiples are installed.
> Error when multiple configuration plugins are installed

- flytekit/core/context_manager.py
In the current design of flytekit, we have two ways to retrieve secrets:
1. Get the secret from the OS's environment variables.
2. Get the secret from a specified file path. (Usually use kubectl to create secret value)
If you choose the first method, you will encounter an issue: the retrieved secret value needs to have `whitespace characters` removed.
This update aims to fix errors that occur when using `flytekit.current_context().secrets.get` along with the first method above, especially in `Single Binary Mode`.
Call `strip` method to remove whitespace characters in `context manager` get secret function.
Note: The type of variable from os environment is python pickle object, maybe that's why we have this error.
I've tried to return `type` of the secret value.
Use code like below. …
> Fix Get the Secret Bug from OS Environment Variable

- flytekit/extras/tasks/shell.py
- tests/flytekit/unit/extras/tasks/test_shell.py
subproc_execute was too restrictive, this allows passing of arbitrary kwargs with sensible defaults
modified subproc_execute and 2 tests for shell and non-shell exec
2 unit tests
> Generalized subproc_execute and added tests

- flytekit/clis/sdk_in_container/utils.py
- flytekit/core/base_task.py
- flytekit/core/workflow.py
- flytekit/extend/backend/base_agent.py
- plugins/flytekit-pandera/tests/test_plugin.py
- tests/flytekit/unit/core/test_type_conversion_errors.py
- tests/flytekit/unit/core/test_type_hints.py
NA
Improve error messages
- Remove duplicate error message
- Remove traceback from `user_entry_point`
```python
pyflyte run pyflyte run train_wf.py wf
```
Before:
After:
```python
pyflyte --verbose run pyflyte run train_wf.py wf
```
Before:
After:
> Improve error handling for local execution

- flytekit/core/workflow.py
- flytekit/types/directory/types.py
- flytekit/types/file/file.py
- flytekit/types/structured/structured_dataset.py
- tests/flytekit/unit/core/test_flyte_directory.py
NA
flytekit downloads the entire directory when calling `os.listdir(FlyteDirectory(...))`. However, users may only want to download the specific files they will use when the task is running.
Add a new method called listdir in `FlyteDirectory` that can list all the files and folders in the given directory. `listdir` only returns either `flytefile` or `FlyteDirectory`
```python
import os
import tempfile
from flytekit import workflow, task, ImageSpec
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@a5171380ea8a1aa55e20647a06e4313cbc19bec4"
image_spec = ImageSpec(registry="pingsutw", apt_packages=["git"], packages=[new_flytekit])
def t1() -> FlyteDirectory:
temp_dir = …
```
> Download specific files in FlyteDirectory

- pyproject.toml
Closes https://github.com/flyteorg/flyte/issues/4665
Described in https://github.com/flyteorg/flyte/issues/4665
Use the same constraint for all packages from fsspec family
Through CI probably.
> Constraint the full fsspec family

- flytekit/core/array_node_map_task.py
_NA_
Currently, ArrayNode does not support operating over tasks that use PodTemplates. This is a very powerful resource that should be enabled.
Updating the ArrayNode construct to use underlying function config.
locally / cloud / etc with many workflows, for example:
```
@task(pod_template=PodTemplate(
primary_container_name="primary",
labels={"mylabel": "myvalue"},
))
def echo_2(x: int) -> int:
time.sleep(1)
return x
@workflow
def gen_wf_2() -> typing.List[typing.Optional[int]]:
return map_task(echo_2)(x=list(range(5)))
```
_NA_
_NA_
_NA_
_NA_
> Support PodTemplate in ArrayNode

- flytekit/core/data_persistence.py
_https://github.com/flyteorg/flyte/issues/4470_
flyteorg/flyte#4470
Flytekit should raise a file not found error instead of Access denied
Raise an exception if the path doesn't exist on the filesystem when `dst = file_system.get(from_path, to_path, recursive=recursive, **kwargs)` catches OSError.
> As per mentioned by flyteorg/flyte#4470
1. pyflyte run --remote workflow.py wf
2. remove script_mode.tar.gz from s3 bucket (e.g., via `minio`)
3. pyflyte run --remote workflow.py wf # run the workflow again
> Fix file not found error

- docs/source/conf.py
This PR adds a banner at the top of the flytesnacks docs (the `flytekit` readthedocs project), pointing users to the main flyte docs site, which will contain the monodocs.
> add monodocs redirect banner

- flytekit/extend/backend/base_agent.py
Show the log link during local executions
> Print log links in local execution

- plugins/flytekit-airflow/flytekitplugins/airflow/task.py
- plugins/flytekit-airflow/setup.py
- plugins/flytekit-bigquery/setup.py
Fixes https://github.com/flyteorg/flyte/issues/3936
- need to install the flyteidl package to ensure the airflow plugin works properly
- add flyteidl package in `setup.py`
- add type annotation for `is_deferrable` function
pytest
https://github.com/flyteorg/flytekit/pull/1725
> Enhance Airflow Plugin

- flytekit/image_spec/image_spec.py
- plugins/flytekit-envd/README.md
- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
- plugins/flytekit-envd/tests/test_image_spec.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
This PR adds `conda` support to `envd`. This makes it simple to use Nvidia's runtime environment for PyTorch:
```python
base_image="ubuntu:20.04",
python_version="3.11",
packages=["flytekit"],
conda_packages=["pytorch", "pytorch-cuda=12.1"],
conda_channels=["pytorch", "nvidia"]
)
```
which is inline with PyTorch's [docs](https://pytorch.org/get-started/locally/). 
Furthermore, I do not think it is possible to install `cuda=12.1` with `envd`. Using `conda` allows for `cuda=12.1` and makes it simple to switch between Nvidia runtimes.
This PR adds `conda_packages` and `conda_channels` to `ImageSpec` to specific the conda packages and channels.
I added a unit test to check the expected behavior.
> Adds conda support to envd plugin

- flytekit/clis/sdk_in_container/run.py
https://github.com/flyteorg/flyte/issues/4638
In the absence of this change `pyflyte run` configures the default destination directory - the path where the code should be installed within a container to be `/root`. This does not work for cases in which the user may want a directory other than `/root`. Though it is possible to pass in this directory, it fails in case you have a task with multiple tasks, each uses a different container and separate paths.
A propose solution by @vkaiser-mb is to set it on a per task basis
```
@task(working_dir="/home/user_a", container_image="a")
def do_a():
...
@task(working_dir="/home/user_b", container_image="a")
def do_b():
...
@workflow
def wf():
do_a()
do_b()
```
This complicates the process, as it is one more argument on the task and is not simple to …
> Changes default destination dir to be "working dir"

- flytekit/image_spec/image_spec.py
Remove duplicate logs
Add `@lru_cache` to ImageBuildEngine.build
```bash
pyflyte run --remote flyte-example/wf.py wf
```
Before:
After:
> Add @lru_cache to ImageBuildEngine.build

- flytekit/clis/sdk_in_container/register.py
- flytekit/tools/repo.py
Failed to register certain workflows due to the below errors
```bash
"task-module",
"basics.workflow",
"task-name",
"slope"
],
"resources": {}
}
},
"description": {
"longDescription": {
"format": "DESCRIPTION_FORMAT_RST"
}
}
}
}
RPC Failed, with Status: StatusCode.INVALID_ARGUMENT
details: task with different structure already exists with id resource_type:TASK project:"flytesnacks" domain:"development" name:"basics.workflow.slope" version:"v0.3.257" 
Debug string UNKNOWN:Error received from peer  {grpc_message:"task with different structure already exists with id resource_type:TASK project:\"flytesnacks\" domain:\"development\" name:\"basics.workflow.slope\" version:\"v0.3.257\" ", grpc_status:3, created_time:"2024-01-17T00:21:33.186053-08:00"}
```
Skip errors and continue resisting the …
> Skip errors when running pyflyte register

- flytekit/configuration/__init__.py
- flytekit/configuration/internal.py
- flytekit/core/base_task.py
- tests/flytekit/unit/core/test_local_cache.py
Closes https://github.com/flyteorg/flyte/issues/4395
While local caching is useful in some cases, it has often led to unexpected errors for users not being aware. Especially in large codebases this can lead to unexpected test failures, etc.
This PR introduces a new config section `local` with one value `cachen_enabled` (which defaults to true):
```
[local]
cache_enabled = True
```
Added a test which confirms that setting `FLYTE_LOCAL_CACHE_ENABLED=false` prevents the local use of the cache.
Changed in https://github.com/flyteorg/flytesnacks/pull/1425
https://flyte--1425.org.readthedocs.build/projects/cookbook/en/1425/auto_examples/development_lifecycle/task_cache.html#how-does-local-caching-work
> Option to disable local caching

- flytekit/remote/remote.py
- tests/flytekit/unit/remote/test_remote.py
N/A
We've received feedback that the auto-generated versions are difficult to copy due to the extra '=' that show at the end of each version.
The '=' is a padding character used by the base64 algorithm to encode data, as per https://datatracker.ietf.org/doc/html/rfc4648#section-3.2. In this PR we omit those characters without loss of functionality, since those characters don't increase the entropy, while solving the original problem that a simple double-click wouldn't select those characters.
Added one test.
> Omit '=' from auto-generated version

- flytekit/remote/remote.py
The `FlyteRemote.register_script` function is useful for registering local code to remote during integration tests of workflows. It does not allow the user to pass in environment variables to the serialization though, even though it should be easy to support this.
Make it possible to pass in environment variables using a `dict[str,str]` which can be passed directly to `SerializationSettings`.
Don't think `register_script` is covered by unit tests at the moment.
> Pass in env vars in FlyteRemote register_script

- flytekit/image_spec/image_spec.py
- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
NA
This [PR](https://github.com/flyteorg/flytekit/pull/2108) changes the default `destination-dir` to `.`, so flytekit will download the code to the `workdir` specified in the Dockerfile. However, envd<0.3.39 replace the `workdir` to /, and flytekit may not have permission to download a file to `/`. Therefore, we should force people to use envd>0.3.39 to build the image.
Check `envd` version before building images. Raise an error if it is lower than 0.3.39.
```python
base_image="ghcr.io/flyteorg/flytekit:py3.11-1.10.2",
packages=["flytekit>=1.6.0", "numpy", "mypy"],
python_version="3.11"
)
@task(container_image=image_spec, cache_version="1.0", cache=True)
def get_data() -> str:
return "hello dgx.." …
```
> Check envd version before building images

- dev-requirements.in
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
The mashumaro `DataClassORJSONMixin` class works like the mashumaro `DataClassJSONMixin` class. Additionally, it allows for serializing dataclasses with a wider variety of attributes types, including:
- [numpy](https://numpy.org/)
- [datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime)
- [date](https://docs.python.org/3/library/datetime.html#datetime.date)
- [time](https://docs.python.org/3/library/datetime.html#datetime.time)
- [uuid.UUID](https://docs.python.org/3/library/uuid.html#uuid.UUID)
Currently, flytekit does not yet support the `DataClassJSONMixin` class and throws an error when classes derived from `DataClassORJSONMixin` are serialized.
This PR introduces support for classes derived from the mashumaro `DataClassORJSONMixins` class.
Added …
> Support mashumaro DataClassORJSONMixin

- flytekit/image_spec/image_spec.py
- plugins/flytekit-envd/tests/test_image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
This PR:
- Extends the image spec plugin to allow `ImageSpecBuilder.build_image` to return an image name. This allows image spec plugins to point to images in it's own registry.
- Changes the default builder to `None` and introduce a priority. This allows the default builder to be the one with the higher priority.
The changes are backward compatible since returning an image name in `ImageSpecBuilder.build_image` is optional. If an plugin returns a name, it will be used by `ImageSpec.image_name()` when referencing the same image.
I added unit tests to check the expected behavior.
> Extends ImageSpec to accept image names from plugin and have priority for plugins

- flytekit/core/data_persistence.py
NA
Flytekit logs could get confusing as it's possible that logs produced by calls to `print` might get buffered which will cause them to show up unformatted in a completely different place. 
Change the log message in `get` in `data_persistence.py` to use the flytekit logger.
Built a local flytekit image and confirmed the log message shows up in the right place.
> Use logger in data_persistence.py

- flytekit/exceptions/scopes.py
- tests/flytekit/unit/exceptions/test_scopes.py
https://github.com/flyteorg/flyte/issues/4777
Makes it easier to debug failures. 
Add the exception name to the error message that flytekit generates. This message gets displayed in the flyte UI. 
Updated unittests
Deployed on our flyte cluster
> Include exception type in error messages

- flytekit/configuration/default_images.py
- flytekit/configuration/plugin.py
- tests/flytekit/unit/configuration/test_image_config.py
This PR allows a third party plugin to override the default images.
This PR extends the configuration plugin API with a `get_default_image` method:
- If plugin returns `None`, then nothing changes and the images are pulled from flytekit's `DefaultImages`.
- If the plugin returns a string, then that string is used as the default image.
I added unit test to check the plugin's behavior with `DefaultImage`.
> Adds get_default_image into configuration plugin

- flytekit/clis/sdk_in_container/run.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
- tests/flytekit/unit/cli/pyflyte/workflow.py
Closes https://github.com/flyteorg/flyte/issues/4503
We introduced the ability to pass environment variables from the command line when using `pyflyte run` in https://github.com/flyteorg/flytekit/pull/1617, however that only works for remote executions. This PR enables this for local executions as well.
Set environment variables prior to executing Flyte entities locally.
Unit tests and local.
> Envvars local execution

- flytekit/core/node.py
```py
@task(
requests=Resources(
cpu="3",
mem="3Gi",
),
)
def foo():
...
@workflow
def my_wf():
foo().with_overrides(
requests=Resources(
cpu="5",
mem="5Gi",
),
)
```
As a user, I would expect that the resulting task pod has 5 vCPUs and 5Gi or RAM. Turns out, the task pod has 3 each!
This behaviour is *very* unintuitive, the reason being as follows:
* When one doesn't explicitly set limits on a task, the requests are taken as limits as well.
* When one only overrides the requests, the requests are clamped to the old limits[ in the backend](https://github.com/flyteorg/flyte/blob/ffd3ab2e4784733a446a3440eab066852819f5fe/flyteplugins/go/tasks/pluginmachinery/flytek8s/container_helper.go#L107).
In this PR I add a warning so that at least users are warned to set limit as well.
Running the …
> Warn user when overriding requests but not limits

- flytekit/clis/sdk_in_container/run.py
Improve error message
raise an error if file not found
Before:
```bash
(flytekit-3.10) ➜  plugins git:(improve-error-message-1) ✗ pyflyte run --remote flyte-example/airflow_example/time_sensor.py wf
Failed with Unknown Exception <class 'ModuleNotFoundError'> Reason: No module named 'time_sensor'
Traceback:
File "/Users/kevin/git/flytekit/flytekit/clis/sdk_in_container/utils.py", line 139, in invoke
return super().invoke(ctx)
File "/Users/kevin/anaconda3/envs/flytekit-3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/Users/kevin/anaconda3/envs/flytekit-3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```
> Improve error message for pyflyte run

- pyproject.toml
Allow users to use the latest `grpc` by removing the upper-bound.
remove the upper-bound
> Remove upper version bound from protobuf

- flytekit/core/workflow.py
- tests/flytekit/unit/core/test_type_hints.py
- tests/flytekit/unit/experimental/test_eager_workflows.py
```py
@workflow
def wf() -> tuple[str, str, str]:
return "foo", "bar", None
```
When registering this workflow, one gets the following obvious error:
```console
~ pyflyte register test_wf.py
...
Python value cannot be None, expected <class 'str'>/<FlyteLiteral simple: STRING>
```
However, the exception does not hint which workflow/output is causing the error. In a large workflow with numerous sub workflows and dozens of tasks, it took one of our ML engineers quite some time to figure out where exactly the `return` was missing. They asked whether we could make this simpler.
I propose to catch errors raised by `binding_from_python_std` in the `PythonFunctionWorkflow`'s `compile` function just as is done e.g. [here](https://github.com/flyteorg/flytekit/blob/c559e2649f9ed0de02e9fe0151d491bb7dd …
> Fix: Improve error handling in workflow compilation when output binding fails

- flytekit/core/base_task.py
NA
Add `_literal_map_to_python_input` base tasks. It allows people to override it, and preprocess the input before deserializing the literal map.
Add `_literal_map_to_python_input` method the base tasks
Unit tests
NA
NA
> Add _literal_map_to_python_input to base task

- flytekit/core/tracker.py
Flyte tasks have to be importable from the module level so that the so-called task resolver can import them when executing a task in a K8s pod. This means they cannot be inner or nested functions.
One exemption from this rule is testing.
```py
def test_foo():
@task
def foo():
...
foo()
```
When the file is called `test_*.py`, inner test functions are allowed by flytekit.
The above test works with `pytest test_foo.py` but fails with `pytest foo_test.py`:
```console
ValueError: TaskFunction cannot be a nested/inner or local function. It should be accessible at a module level for Flyte to execute it. Test modules with names beginning with `test_` are allowed to have nested tasks. If you're decorating your task function with custom decorators, use functools.wraps or …
```
> Fix: Allow both '*_test.py' and '*test_.py' test module naming convention for nested tasks

- plugins/flytekit-identity-aware-proxy/setup.py
*This only affects Flyte users who protect flyteadmin with GCP Identity Aware Proxy.*
In this PR I limit the `grpcio` version required by `flytekit-identity-aware-proxy`.
There is a regression in `grpcio` where a channel breaks if the server doesn't respond with the content-type `application/grpc`.
The same problem was fixed for the nginx ingress recently by including the `accept=application/grpc` header in requests to flyteadmin from flytekit (see https://github.com/flyteorg/flytekit/pull/1841). (The grpc go client doesn't have this issue so flytectl is not affected.)
When flyteadmin is protected with GCP Identity Aware Proxy, this `accept` header doesn't help - unauthenticated requests still get a `text/html` response by the proxy.
[Lazy …
> Fix: Limit grpcio version in flytekit-identity-aware-proxy due to regression

- .github/workflows/monodocs_build.yml
This PR installs the latest development version of flyteidl on CI monodocs build so that the docs build process picks up the latest proto definitions.
> install latest flyteidl with monodocs build

- .github/workflows/pythonbuild.yml
- Makefile
- pyproject.toml
- tests/flytekit/unit/bin/test_python_entrypoint.py
- tests/flytekit/unit/configuration/test_internal.py
- tests/flytekit/unit/core/test_checkpoint.py
- tests/flytekit/unit/core/test_context_manager.py
- tests/flytekit/unit/core/test_local_cache.py
- tests/flytekit/unit/core/test_serialization.py
NA
flytekit unit tests started failing in the last couple of days due to the use of global shared state in `test_local_cache.py`. Tests are run using `pytest-xdist` and this PR makes it so that we run all tests in the same module in the same worker
We specify `--dist loadscope` to force tests in the same module to be picked by the same pytest worker.
I'm also:
1. removing the pinned version of flyteidl from the `setup` make target.
2. setting defaults for PYTEST_OPTS in the makefile
3. fixing a bunch of assumptions in the unit tests that didn't play well with pytest-xdist
> Force tests in a module to be run by the same worker

- .github/workflows/pythonpublish.yml
NA
We forgot to add 3.12 to the list of python versions used to produce the default flytekit images in the original [PR](https://github.com/flyteorg/flytekit/pull/2005) to add support for 3.12 . This PR fixes this.
> Build python 3.12 default flytekit image

- flytekit/extend/backend/base_agent.py
The input of `create` function in base_agent is wrong, we should fix it.
Before:
After:
> Fix Base Agent Input Bug

- Dockerfile
- Dockerfile.dev
NA
Rich is useful when running locally but not on remote cluster
Disable rich logger by default in the default image.
local & remote
```python
import os
from airflow.sensors.time_sensor import TimeSensor
image = ImageSpec(apt_packages=["git"], packages=["pandas"], registry="pingsutw", env={"FLYTE_SDK_RICH_TRACEBACKS": "0"})
def get_env() -> str:
return str(os.environ)
@workflow
def wf() -> str:
return get_env()
```
Before:
After:
NA
NA
> Disable rich logger in the default image

- flytekit/remote/remote.py
When running a remote workflow that fails on file upload, the following error logs are given.
```sh
$ pyflyte run --remote hello-world/example.py hello_world_wf
Running Execution on Remote.
Failed with Exception Code: USER:ValueError
Value error!  Received: 403. Request to send data https://... failed
```
The user can determine it is a 403 error and the corresponding URL. However, by enhancing the logs to also include the text of the response, the user sees:
```sh
...
Value error!  Received: 403. Request to send data https://... failed
Response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>
User: arn:... is not authorized to perform: kms:GenerateDataKey on resource:
arn:... because no identity-based policy allows the kms:GenerateDataKey action …
```
> Enhance error logging in pyflyte

- plugins/flytekit-spark/flytekitplugins/spark/pyspark_transformers.py
https://github.com/flyteorg/flyte/issues/4877
Spark tasks are currently broken on version 1.10.3 and 1.10.2 of the flytekit spark plugin.
Do not lazy-load the `pyspark.ml` module.
Built an image that used that and tested on a real Flyte cluster using a slightly modified version of https://github.com/flyteorg/flytesnacks/blob/master/examples/k8s_spark_plugin/k8s_spark_plugin/pyspark_pi.py.
> Do not lazy-load pyspark.ml

- flytekit/clients/auth/default_html.py
- flytekit/configuration/plugin.py
- tests/flytekit/unit/clients/auth/test_default_html.py
This PR allows configuration plugins to return a customized default OAuth success HTML page.
This PR extends the configuration plugin API to change the default OAuth success HTML.
Unit tests was added to check the behavior.
> Extends config plugin API to customize the default OAuth success html

- plugins/flytekit-airflow/flytekitplugins/airflow/task.py
We should not access the key if the key doesn't exist in dict in python.
> Fix Airflow Agent kwargs bug

- flytekit/clis/sdk_in_container/run.py
- flytekit/configuration/__init__.py
- flytekit/configuration/internal.py
- flytekit/core/base_task.py
- flytekit/core/local_cache.py
- tests/flytekit/unit/core/test_local_cache.py
Closes _https://github.com/flyteorg/flyte/issues/4727_
We can't overwrite the cache when using `pyflyte run --overwrite-cache` in local runs.
* Once the argument `--overwrite-cache` is added, we get `run_level_params.overwrite_cache=True` and set the environment variable `FLYTE_LOCAL_CACHE_OVERWRITE=true` accordingly. 
* With `FLYTE_LOCAL_CACHE_OVERWRITE=true`, the task will be executed and overwrite the existing cache.
* The cache `add` function in `LocalTaskCache`  is changed to `set` as the previous one can't update the cache if there's already an existing one.
Added a test which confirms that setting `FLYTE_LOCAL_CACHE_OVERWRITE=true` can successfully overwrite the existing cache.
> Fix local overwrite cache

- plugins/flytekit-flyteinteractive/README.md
_https://github.com/flyteorg/flyte/issues/4918_
There is no `--push` flag for the `docker build` command in Linux machine.
Change `docker build` to `docker buildx build`
> docs(flyteinteractive): Change docker build to docker buildx build

- .github/workflows/pythonbuild.yml
- Makefile
NA
The fix proposed in https://github.com/flyteorg/flytekit/pull/2177 was not enough, as we're seeing what seems to be a bug in the `pytest-xdist` where tests in the same module are not running in the same worker. Notice this example: https://github.com/flyteorg/flytekit/actions/runs/7948242800/job/21698066555?pr=2198
Use `loadfile` as the distribution method in the call to `pytest`.
> Distribute tests by file

- .github/workflows/pythonbuild.yml
- Makefile
* We shouldn't use beta packages generally for testing.  We were only trying to pick up latest versions of flyteidl.
* Also move tests under `extend/` to the extras make target.  These tests are currently failing (and correctly so) because of backwards-incompatible changes being made to alpha portions of the idl (agent api).  The plugin failures are also related to that change.  The code and relevant tests will be fixed soon.
> Move agent (extend) tests to extras

- flytekit/extend/backend/base_agent.py
- plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
- plugins/flytekit-bigquery/tests/test_agent.py
- plugins/flytekit-spark/flytekitplugins/spark/agent.py
- plugins/flytekit-spark/tests/test_agent.py
- tests/flytekit/unit/extend/test_agent.py
Temporarily remove test_sync_dummy_agent. More comprehensive tests will be added in the separate PR.
> Fix CI error

- .github/workflows/pythonpublish.yml
`::set-output` has been deprecated a while back: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This PR switches over the CI to use the new API: https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
> CI Uses GITHUB_OUTPUT in github actions

- .github/workflows/pythonbuild.yml
To make CI run faster, use disk-space-reclaimer only when running envd tests.
> Use disk-space-reclaimer only when running envd tests

- flytekit/core/node.py
- flytekit/models/core/workflow.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_array_node_map_task.py
- tests/flytekit/unit/core/test_map_task.py
- tests/flytekit/unit/core/test_node_creation.py
https://github.com/flyteorg/flyte/issues/4543
The `container_image` task node override, among others, is currently broken (doesn't work with `pyflyte register` and only once with `pyflyte run`, see [tracking issue](https://github.com/flyteorg/flyte/issues/4543).
Don't override container image of `run_entity` in `.with_overrides` but actually in flyteidl's `TaskNodeOverride` so that the container image is overridden in the backend.
In combination with https://github.com/flyteorg/flyte/pull/4858 I ensured that the resulting pod in the cluster has the correct image. I also adapted the unit tests.
https://github.com/flyteorg/flyte/pull/4858
> Fix: Handle overriding of container image in backend

- flytekit/models/core/workflow.py
Follow up to https://github.com/flyteorg/flytekit/pull/2176
Fixes failing test:
https://github.com/flyteorg/flytekit/blob/eb204594a5f8cd4a662d4bd44ab7e8d7dea22a98/tests/flytekit/unit/models/core/test_workflow.py#L301-L308
Failing tests should pass now.
> Fixes failing test related to TaskNodeOverrides

- Dockerfile.agent
- flytekit/clis/sdk_in_container/serve.py
Add this service so we can use gRPC container probes to check if agent is healthy
Add HealthServicer
NA
NA
> Add health check servicer for agent

- .github/workflows/pythonbuild.yml
- Dockerfile.agent
- flytekit/extend/backend/base_agent.py
- plugins/flytekit-openai/README.md
- plugins/flytekit-openai/flytekitplugins/chatgpt/__init__.py
- plugins/flytekit-openai/flytekitplugins/chatgpt/agent.py
- plugins/flytekit-openai/flytekitplugins/chatgpt/task.py
- plugins/flytekit-openai/setup.py
- plugins/flytekit-openai/tests/test_agent.py
- plugins/flytekit-openai/tests/test_chatgpt.py
We want to support chatgpt agent and provide example for users to develop sync agent.
- add openai-chatgpt plugin
0. Set up my local single binary environment. (use `pyflyte serve agent`)
1. Build a docker image with sync agent proto and chatgpt agent's gitsha.
2. Test the chatgpt task in both local and remote scenarios.
```yaml
tasks:
task-plugins:
enabled-plugins:
- container
- sidecar
- K8S-ARRAY
- agent-service
default-for-task-types:
chatgpt: agent-service
custom_task: agent-service
container: container
container_array: K8S-ARRAY
plugins:
agent-service:
supportedTaskTypes:
- sensor
- spark
- default_task
- custom_task
- chatgpt
- sensor
- airflow
defaultAgent:
endpoint: "dns:///localhost:8000"
insecure: true
timeouts:
GetTask: 100s …
```
> ChatGPT Agent

- flytekit/configuration/__init__.py
- flytekit/configuration/default_images.py
Provides context for https://flyte-org.slack.com/archives/CP2HDHKE1/p1709158841281599
Some CLI paths like `pyflyte run, pyflyte register` do not use the image specified by the environment variable `FLYTE_INTERNAL_IMAGE` in the manner one might expect
> Enhance default image to check FLYTE_INTERNAL_IMAGE

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
To remove `=` directly is more clarity
- remove trailing '=' character
- Add an assertion to check if the tag does not contain equal signs
`FLYTE_SDK_LOGGING_LEVEL=20 pyflyte run --remote -p flytesnacks --domain development my_workflows/dev_image_spec.py wf`
```
flytekit_git_version = "git+https://github.com/jasonlai1218/flytekit.git@remove-equal-sign#commit=4c9ff81992692dbf5331fe8a04851cf36cb3761b"
py_image_spec = ImageSpec(
name="test_version_1",
registry="jasonlai1218",
packages=[flytekit_git_version],
env={"FLYTE_SDK_LOGGING_LEVEL": "20"},
)
@task(container_image=py_image_spec)
def t(a: int, b: int) -> int:
return a + b
@workflow
def wf(a: int=5, b: int=3) -> int:
out = t(a=a, b=b)
return out
```
> Remove trailing '=' character from generated image tag hash value

- Dockerfile.dev
- Makefile
NA
This PR proposes a simpler way to build dev images by exposing a make target and piping the setuptools pseudo version in.
> Simpler dev images

- flytekit/deck/__init__.py
- flytekit/deck/renderer.py
- plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py
- plugins/flytekit-deck-standard/tests/test_renderer.py
- pyproject.toml
- tests/flytekit/unit/deck/test_deck.py
This PR introduces a `MarkdownRender` to core. This makes `FlyteDeck` more useful without needing to install a plugin. 
I added `markdown-it-py` as a direct dependency, but it does not increase our overall dependency count. `markdown-it-py` is a direct dependency of `rich`:
https://github.com/flyteorg/flytekit/blob/329aea8545aa9ea9f903acd7e006f3f12efb9cbb/dev-requirements.txt#L241-L242
And I do not think we will be removing the `rich` dependency.
I added a unittest to check the renderer. I also ran this workflow built with this PR and the Flyte deck appears.
```python
from flytekit import task, workflow, current_context, Deck
@task(
enable_deck=True,
container_image="ghcr.io/thomasjpfan/flytekit:deck-markdown-0.0.1",
)
def write_to_deck():
from flytekit.deck.renderer import …
```
> Adds a FlyteDeck markdown renderer to core

- flytekit/extend/backend/agent_service.py
NA
`agent.delete` returns None for now and causes the gPRC server to fail to parse the response.
`DeleteTask` should return an empty `DeleteTaskResponse`
local / cloud
NA
NA
> DeleteTask should return DeleteTaskResponse

- flytekit/extend/backend/utils.py
- plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
- plugins/flytekit-spark/flytekitplugins/spark/agent.py
- plugins/flytekit-spark/tests/test_agent.py
- tests/flytekit/unit/extend/test_agent.py
To support more phases in the databricks agent.
At before, we only have `RUNNING` and terminal phase, which doesn't provide good user experience to users.
1. fix bug in bigquery agent
2. Implement the databricks plugin's `Status` function's logic to decide databricks agent's phase.
databricks plugin implementation: https://github.com/flyteorg/flyte/blob/master/flyteplugins/go/tasks/plugins/webapi/databricks/plugin.go#L251-L283
1. Unit tests
2. return `Initializing` Phase, messages and logs to flytepropeller, show messages in the flyteconsole.
https://github.com/flyteorg/flytekit/pull/1797
> Refactor Databricks Agent Phase

- flytekit/core/resources.py
- tests/flytekit/unit/core/test_resources.py
If one would like to pass Resources instances as configuration to workflows, they need to be serializable.
Following https://github.com/flyteorg/flytekit/pull/1735, declare Resources and ResourceSpec to inherit from DataClassJSONMixin
- Unit tests that (de)serialize Resources instances are added.
- Preliminary successful [CI execution on fork](https://github.com/cameronraysmith/flytekit/actions/runs/8208258128/job/22451306570).
- https://github.com/flyteorg/flytekit/pull/2196
> feat(resources): support serialization of Resources dataclasses

- flytekit/types/structured/basic_dfs.py
- plugins/flytekit-sqlalchemy/Dockerfile
- plugins/flytekit-sqlalchemy/setup.py
https://github.com/flyteorg/flyte/issues/749
1. why we restrict sql_alchemy plugin < = 2.1.4?
if you use latest pandas version, you will find that there's a bug or interface is changed when running example.
(not sure which is the answer yet.)
2. why we use `from pandas.io.common import is_fsspec_url`?
from @pingsutw 's advice, we found that some of pandas module need to be loaded entirely.
1. Use a python example
```python
from flytekit import kwtypes, task, workflow
from flytekit.types.schema import FlyteSchema
from flytekitplugins.sqlalchemy import SQLAlchemyConfig, SQLAlchemyTask
DATABASE_URI = "postgresql://reader:NWDMCE5xdipIjRrp@hh-pgsql-public.ebi.ac.uk:5432/pfmegrnargs"
DataSchema = FlyteSchema[kwtypes(sequence_length=int)]
sql_task = SQLAlchemyTask(
"rna",
query_template=""" …
```
> Fix sql alchemy plugin error `module 'pandas.io' has no attribute 'common' `

- flytekit/extras/tasks/shell.py
- tests/flytekit/unit/extras/tasks/test_shell.py
Fixes #4888.
_https://github.com/flyteorg/flyte/issues/4888_
followed by @eapolinario 
- Creation of a structure named `ProcessResult` to store a subprocess return code, stdout and stderr
- Functions now return an instance of `ProcessResult` instead of `Tuple[str, str]`
- `ShellTask` stores an instance of `ProcessResult`
- `./tests/flytekit/unit/extras/tasks/test_shell.py`:
- `test_shell_task_access_to_result` added
- `test_subproc_execute()` adapted to accommodate `subproc_execute` new return type
> ShellTask: stores process return code, stdout and stderr for later use.

- plugins/flytekit-spark/setup.py
Fixed https://github.com/flyteorg/flytekit/actions/runs/8180551482/job/22369426364
> Bump flyteidl for spark plugin

- flytekit/bin/entrypoint.py
[entrypoint.py calls exit(1) when the env var "FLYTE_FAIL_ON_ERROR" is set](https://github.com/flyteorg/flytekit/blob/d7c60296cf4fd75f608f950361f35b2d90310114/flytekit/bin/entrypoint.py#L180).
When using the Spark plugin for Databricks jobs,
this results in `NameError: name 'exit' is not defined` exception,
where a successful exit with return code 1 was expected.
Behavior confirmed for both Databricks Runtime 13.3 LTS (Apache Spark 3.4.1, python 3.10)
and Databricks Runtime 10.4 LTS (Apache Spark 3.2.1, python 3.8)
Explicitly importing the `exit` function from the `sys` module should fix this.
> entrypoint.py: Explicitly import exit from sys

- flytekit/core/base_task.py
- flytekit/core/context_manager.py
- plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
- tests/flytekit/unit/deck/test_deck.py
This makes the header formatting in FlyteDeck consistent with the sidebar, which is also capitalized:
The header strings were updated.
> Capitalize flyte deck header names

- flytekit/bin/entrypoint.py
- flytekit/core/context_manager.py
- flytekit/core/mock_stats.py
- flytekit/core/utils.py
- flytekit/experimental/eager_function.py
- flytekit/remote/remote.py
- plugins/flytekit-deck-standard/tests/test_renderer.py
- plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py
- plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/task.py
- plugins/flytekit-identity-aware-proxy/tests/test_flytekitplugins_iap.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/unit/core/test_context_manager.py
- tests/flytekit/unit/deck/test_deck.py
- tests/flytekit/unit/models/test_literals.py
`datetime.utcnow()` is deprecated:
> DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
This PR migrates over to using `datetime.now(timezone.utc)` everywhere. (We can not use `datetime.UTC` yet because it was introduced in requires Python >= 3.11.)
This PR does not change functionally, thus the existing test should cover the changes.
> Migrate over to using datetime.now(timezone.utc)

- pyproject.toml
> Fix CI Error by restricting s3fs version

- flytekit/extend/backend/base_agent.py
- flytekit/types/directory/types.py
- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_type_engine.py
NA
Can not use Union[FlyteFile, FlyteDirectory] as input
Check the metadata in the literal before deserializing FlyteFile/FlyteDirectory
local/remote
```python
import os
import tempfile
from typing import Union
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@d6ae58fb1ee6a7509d15fb1022d294bc2978e1dd"
image_spec = ImageSpec(packages=[new_flytekit], registry="pingsutw", apt_packages=["git"])
def t1() -> FlyteFile:
temp_dir = tempfile.mkdtemp(prefix='temp_example_')
file1_path = os.path.join(temp_dir, 'file1.txt')
with open(file1_path, 'w') as file1:
file1.write('Content of file1.txt')
return file1_path …
```
> Add support for Union[FlyteFile, FlyteDirectory] as input

- flytekit/core/array_node_map_task.py
- tests/flytekit/unit/core/test_array_node_map_task.py
_NA_
If a task is labeled as `interruptible` that attribute is not persisted when executing within an ArrayNode.
Maintain the `interruptible` setting from the internal task in the sub node metadata.
locally
_NA_
_NA_
> Setting interruptible on ArrayNode sub node metadata

- dev-requirements.in
- flytekit/core/data_persistence.py
- tests/flytekit/unit/core/test_data.py
NA
Failed to upload a file to s3
```bash
File "/usr/local/lib/python3.11/site-packages/s3fs/core.py", line 719, in _lsdir
raise translate_boto_error(e)
Message:
OSError: [Errno 16] Please reduce your request rate.
User error.
```
Catch the error `Please reduce your request rate`, and retry the request.
Remote cluster
```python
import asyncio
import os
from typing import List, Dict, Any, Coroutine
import s3fs
from flytekit import ImageSpec, task, workflow, Resources, FlyteContextManager
NUMBER_OF_REQUESTS: int = 100000
BUCKET_NAME: str = 's3://xxx/load-test/'
OBJECT_KEY: str = 'your_object_key'
DATA: str = 'abcsfsdfsdfsfdsdf'
s3fs = s3fs.S3FileSystem()
def write_data(source_file: str, object_key: str):
ctx = FlyteContextManager.current_context()
ctx.file_access.put(source_file, …
```
> feat: Add retry mechanism to file access methods

- flytekit/core/container_task.py
- flytekit/core/python_auto_container.py
- flytekit/remote/remote.py
- plugins/flytekit-spark/flytekitplugins/spark/task.py
NA
Since only the Spark driver downloads the workflow code, pyflyte run doesn't work with Spark tasks as the Spark executors also need the workflow code.
Always copy the code into the image if the task is a spark task.
remote cluster
```bash
pyflyte run --remote flyte-example/test2.py spark_wf
```
```python
import random
from flytekitplugins.spark import Spark
from flytekit import ImageSpec, task, Resources, workflow
from operator import add
name="flytekit",
registry="pingsutw",  # your docker registry
)
def f(_):
x = random.random() * 2 - 1
y = random.random() * 2 - 1
return 1 if x**2 + y**2 <= 1 else 0
@task(
task_config=Spark(
spark_conf={ …
```
> pyflyte run spark task

- .github/actions/clear-action-cache/action.yml
- .github/workflows/pythonbuild.yml
- Dockerfile.dev
`insightsengineering/disk-space-reclaimer@v1`takes ~3mins to run, which is very slow
Add a custom action to remove the cache from the runner
CI
NA
NA
> [CI] Add an action to remove cache from runners

- flytekit/image_spec/image_spec.py
- plugins/flytekit-envd/tests/test_image_spec.py
NA
It enables users to easily reuse the ImageSpec and merge different ImageSpecs together.
ImageBuildEngine will build the base image if the base image is an ImageSpec.
pyflyte run --remote ..
```python
from flytekit import task, workflow, ImageSpec, dynamic
new_flytekit = "git+https://github.com/flyteorg/flytekit@64730c8ffb4e76cb268817e30d31c6d209452e75"
image_sklearn = ImageSpec(packages=["scikit-learn", new_flytekit], apt_packages=["git"], registry="pingsutw")
image_tensorflow = ImageSpec(base_image=image_sklearn, packages=["tensorflow"], registry="pingsutw")
@task(container_image=image_sklearn)
return a + 2
@workflow
def wf(a: int = 3):
t1(a=a)
print(f"Running my_wf: {wf(a=50)}")
```
NA
NA
> feat: Support ImageSpec as base image

- flytekit/clients/auth/authenticator.py
Currently, device flow requires one to copy over the user code:
```bash
To Authenticate, navigate in a browser to the following URL:
https://signin.mydomain/activate and enter code: THISISACODE
```
This changes the URL one click with device-flow:
```bash
To Authenticate, navigate in a browser to the following URL:
https://signin.mydomain/activate?user_code=THISISACODE
```
My concern is if using `user_code=` is generic enough.
> Makes the deviceflow auth URL simplier

- flytekit/core/interface.py
- flytekit/core/type_engine.py
- flytekit/core/type_helpers.py
- plugins/flytekit-pydantic/flytekitplugins/pydantic/commons.py
- pyproject.toml
- tests/flytekit/unit/core/test_interface.py
- tests/flytekit/unit/core/test_type_engine.py
Closes https://github.com/flyteorg/flyte/issues/4706
Python 3.10 introduced the ability to write union types using | rather than importing from typing (e.g., int | str instead of typing.Union[int, str]), and I believe this should be supported. See [PEP 604](https://peps.python.org/pep-0604/).
Added unit tests and registered a large code base with the updated Flytekit and tested a workflow on remote. Ran a small test locally on Python 3.8 too to ensure correct error is bubbled up:
```console
│ ❱  5 def process(a: int | None) -> int:                                                                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
> feat: Support pep604 union operator

- flytekit/core/artifact.py
- tests/flytekit/unit/core/test_artifacts.py
> Partition limit

- plugins/flytekit-ray/flytekitplugins/ray/models.py
- plugins/flytekit-ray/flytekitplugins/ray/task.py
- plugins/flytekit-ray/setup.py
- plugins/flytekit-ray/tests/test_ray.py
The description is consolidated at https://github.com/flyteorg/flyte/pull/5067. Also, need to wait for flyte PR merged because this PR relies on flyte PR's flyteidl change
> Adapt flytekit ray plugin to kuberay 1.1.0

- plugins/flytekit-ray/flytekitplugins/ray/task.py
Issue: https://github.com/ray-project/kuberay/issues/1975
`ray.shutdown()` will always be automatically called (registered through `atexit` [here](https://github.com/ray-project/ray/blob/f79a9a720807ae7d50fd99d8b801627bbaba7cf9/python/ray/_private/worker.py#L1853) at ray import time). We should rather rely on the one registered with `atexit` hook instead of explicitly calling it again especially as we don't set `_exiting_interpreter=True` which may result in disconnecting too soon before worker logs are flushed to driver.
remove the `post_execute` of ray task
test with a simple example:
```python
import typing
commit_hash = "03fd5605996e53e848ba77e48608e3395189319a"
ray_plugin = …
```
> Remove post-execute hook from ray task

- flytekit/core/data_persistence.py
- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_data.py
- tests/flytekit/unit/core/test_flyte_file.py
Short of scanning the file using something [like this](https://github.com/flyteorg/flytekit/pull/1893/) which is already merged, we can do a simple extension check for gzip specifically.  As/if this grows out of hand, we can refactor.
Just a simple file extension match for now.
Tested locally.
> Gz encoding

- flytekit/clis/sdk_in_container/run.py
https://github.com/flyteorg/flyte/issues/5086
closes #5086
To remove misleading options in `pyflyte run`. For more details, please refer to https://github.com/flyteorg/flyte/issues/5086
1. removed `--limit` option in `RemoteEntityGroup`
2. set `--limit` in `RunLevelParams` to show up instead of hidden. 
`make test`
Output of `pyflyte run`
> fix limit option

- flytekit/core/base_task.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/agent.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/task.py
agent failed to encode the metadata
Move SageMakerEndpointMetadata to agent.py and override encode()/decode() method
Remote
NA
NA
> Move SageMakerEndpointMetadata to agent.py

- flytekit/types/directory/types.py
- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_flyte_directory.py
- tests/flytekit/unit/core/test_flyte_file.py
Add a couple of class methods
```
def from_source(cls, source: str | os.PathLike) -> FlyteFile
def from_source(cls, source: str | os.PathLike) -> FlyteDirectory
```
meant to be used with remote paths.  This is because if you create a file with an s3/gs link as the path using the normal constructor, it doesn't come with a download function, forcing users to manually call into the data persistence layer manually.
> Add way to create FlyteFile/Directory from remote location

- flytekit/core/type_engine.py
- flytekit/types/structured/structured_dataset.py
- tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
If the user registers a custom structured dataset encoder/decoder before the lazy import is run for the first time, the default transformers will fail because they don't run with override.  flytekit should swallow those errors.
> Ignore duplicate handler errors when lazy loading

- Dockerfile.agent
NA
We renamed the chatpgt plugin to open ai in https://github.com/flyteorg/flytekit/pull/2263 but didn't update its use in the agent dockerfile. This is preventing the agent image from being built, e.g. https://github.com/flyteorg/flytekit/actions/runs/8527491443/job/23366399747.
> Use correct plugin in agent image

- .github/workflows/pythonbuild.yml
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_dataclass.py
- tests/flytekit/unit/core/test_type_engine.py
NA
The original exception in the `DictTransformer` was put in place to catch the case of `FlyteAnnotation` being set passed to annotated dictionary, e.g. `Annotated[dict, FlyteAnnotation("annotation-1")]` is invalid. A similar argument applies to the dataclass type transformer.
Keep the original exception, but only raise it if the annotation contains a `FlyteAnnotation` in both the dataclass and the dictionary transformers.
> Ensure that annotations are dropped in the case of the dataclass and dict type transformers

- flytekit/clis/sdk_in_container/run.py
- flytekit/core/artifact.py
- flytekit/interaction/click_types.py
- tests/flytekit/unit/interaction/test_click_types.py
When a query is detected, don't do anything, and just say that it'll be resolved.  If running locally though, it must be specified.
Make it so that pyflyte just doesn't pass along queries.
Tested locally, tested against union, and tested with local data
Working
Help screen
Local error
> Run ignore query

- flytekit/interaction/click_types.py
If you had a union type, `pyflyte run` was failing when you ran `--help` with
```
File "/Users/ytong/envs/experiments/lib/python3.11/site-packages/click/core.py", line 2220, in make_metavar
metavar = self.type.name.upper()
^^^^^^^^^^^^^^
'UnionParamType' object has no attribute 'name'
```
This just adds the name property.
> Add name to union param

- flytekit/core/type_engine.py
- pyproject.toml
Follow up to https://github.com/flyteorg/flytekit/pull/2298
We do not need to add a new dependency to check if a type is `Union`. Based our tests `UnionTransformer.is_optional_type` should return True if `t` is a Union type **or** an Optional:
https://github.com/flyteorg/flytekit/blob/e121d35009b6b91112c1ba1a007edcce2e18d7d7/tests/flytekit/unit/core/test_type_engine.py#L1532-L1537
I added our own version of `_is_union_type` to our codebase. 
Existing test covers the feature.
> Remove typing-inspect dependency

- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/__init__.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_task.py
`functools.partial` is not JSON serializable. hence, replacing partial with string.
> don't return triton image as a functools.partial

- plugins/flytekit-airflow/flytekitplugins/airflow/agent.py
It will show the log link on FlyteConsole
Get the log link in agent and return to Propeller
```python
from datetime import datetime, timedelta
from airflow.operators.bash import BashOperator
from airflow.providers.google.cloud.operators.dataproc import DataprocDeleteClusterOperator, \
DataprocSubmitSparkJobOperator, DataprocCreateClusterOperator
from airflow.utils import trigger_rule
from pytz import UTC
from flytekit import workflow
x = (datetime.now(tz=UTC) + timedelta(seconds=21)).time()
cluster_name = "flyte-dataproc-demo"
@workflow
def airflow_wf():
BashOperator(task_id="airflow_bash_operator", bash_command="echo hello")
create_cluster = DataprocCreateClusterOperator(
task_id="create_dataproc_cluster1",
image_version="2.0.27-debian10", …
```
> Show a dataproc link on FlyteConsole

- flytekit/core/workflow.py
- tests/flytekit/unit/core/test_workflows.py
https://github.com/flyteorg/flyte/issues/1506
Better user experience.
unit tests, local execution and debugger
reference: https://realpython.com/lessons/mocking-print-unit-tests/
```bash
pyflyte run kevin_example.py wf2 
```
```python
import typing
from flytekit import task, workflow, WorkflowFailurePolicy
from flytekit.types.error.error import FlyteError
@task()
def create_cluster(name: str):
print(f"Creating cluster: {name}")
@task()
def t1(a: int, b: str):
print(f"{a} {b}")
raise ValueError("Fail!")
@task()
def delete_cluster(name: str, err: typing.Optional[FlyteError] = None):
print(f"Deleting cluster {name}")
print(err)
@task()
def clean_up(name: str, err: typing.Optional[FlyteError] = None): …
```
> [easy] Show `failed_node_id` in failure node local execution

- flytekit/clis/sdk_in_container/serve.py
- plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py
- tests/flytekit/unit/extend/test_agent.py
Let users can observe available agents in the agent pod.
add a function `print_agents_metadata`
```python
def print_agents_metadata():
from flytekit.extend.backend.base_agent import AgentRegistry
agents = AgentRegistry.list_agents()
for agent in agents:
name = agent.name
task_type = "sync" if agent.is_sync else "async"
for task_category in agent.supported_task_categories:
click.secho(
f"Starting {name} supports {task_type} task {task_category.name} with version {task_category.version}",
fg="blue",
)
```
1. Use the `pyflyte serve agent` command to print output to the terminal.
2. unit tests
`pyflyte serve agent`
> Log Agents In The Agent Server

- flytekit/core/promise.py
- tests/flytekit/unit/core/test_dynamic.py
https://github.com/flyteorg/flyte/issues/5164
> Explicitly disallow iteration on Promises

- flytekit/remote/remote.py
- flytekit/tools/repo.py
- flytekit/tools/translator.py
- tests/flytekit/integration/remote/test_remote.py
NA
To make register  `task`, `workflow`, and `launchplan` **x2.5 ~ x4 faster**  in `pyflyte run` and  `pyflyte register` by leveraging `asyncio`.
- https://github.com/flyteorg/flytekit/pull/2267: A neat workaround by @pingsutw for sync grpc clients.
- Entities serialization is not enough in async approach.
- It's necessary to separate registered entities into "task" and "non-task" categories in orders. This is because we can ensure flyteadmin returns a task registration response before registering workflows that depend on it.
After introducing localhost network latency to `1000ms` per request, we can simulate network IO-intensive operations to cloud services (e.g., object storage, Kubernetes cluster, FlyteAdmin) on your own desktop. This way, we can finally evaluate performance …
> pyflyte `run`& `register` asynchronously

- docs/source/docs_index.rst
- docs/source/imagespec.rst
- flytekit/image_spec/__init__.py
Adds changes needed to add ImageSpec reference docs to the Flyte docs site.
TK
> Add ImageSpec reference docs to flyte docs

- flytekit/core/artifact.py
- tests/flytekit/unit/core/test_data_persistence.py
- tests/flytekit/unit/types/pickle/test_flyte_pickle.py
The new artifact ID causes weird issues with the metadata field.  The field itself is not used I don't think for the vast majority of Flyte, but is included in Admin's digest check, which is causing repeat registrations to fail with
```
task with different structure already exists with id resource_type:TASK  project:"flytesnacks"  domain:"development"  name:"ingest_data.merge_embeddings"  version:"GHP2gevxt5ywddhM92TU9A"
```
Had to amend an unrelated Azure FS test because of https://github.com/fsspec/adlfs/issues/270.  We started picking up the latest version of [adlfs](https://pypi.org/project/adlfs/) over the weekend which is causing the test to fail.
Add a pretty print to the object, which should remediate the conflict at least.
Unit tested and tested register with previously failing …
> Consistent formatting for artifact id spec

- flytekit/configuration/__init__.py
- flytekit/core/python_auto_container.py
- plugins/flytekit-spark/tests/test_remote_register.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
- tests/flytekit/unit/configuration/configs/sample.yaml
- tests/flytekit/unit/configuration/test_image_config.py
- tests/flytekit/unit/configuration/test_internal.py
- tests/flytekit/unit/core/test_context_manager.py
- tests/flytekit/unit/core/test_python_function_task.py
Closes: [#5132](https://github.com/flyteorg/flyte/issues/5132)
When you want to be confident what code your are running without worrying about cached images its very useful to reference an image using its digest instead of by tag. 
1. Add a separate `digest` field on `Image`. 
1. Disallow specifying `digest` and `tag` at the same time. 
1. Add a `version` property that will return either digest or tag whichever is present. 
1. Update docstring. 
1. Update `Image.look_up_image_info()` so that it sets either `digest` or `tag` derived automatically.
1. Unfortunately this can be done easily with `docker.utils.parse_repository_tag` because it hides whether its returning a digest or a tag. 
1. `parse_repository_tag` is a tiny function though so I just copy pasted it and adjusted so that it …
> Support referencing docker images by digest in addition to by tag

- flytekit/core/utils.py
- tests/flytekit/unit/core/test_python_auto_container.py
_https://github.com/flyteorg/flyte/issues/5220_
Avoid an exception in a valid scenario.
1. Defer call to `get_registerable_container_image` until we know it is actually needed. There is no point computing this value if its not needed and if it raises an exception in blocks a valid scenario. 
2. Add tests. Specifically I updated `test_minimum_pod_template` so that it runs with 3 different serialisation settings. Importantly one of these uses an `ImageConfig` with no `default_image`. 
Add unittests
Deployed this in real Flyte setup
> Fix `_serialize_pod_spec` with no default image

- flytekit/clis/sdk_in_container/run.py
- flytekit/exceptions/scopes.py
- flytekit/loggers.py
- plugins/conftest.py
- tests/flytekit/conftest.py
NA
It's difficult to debug since flytekit generates lots of irrelevant log messages.
Only print the traceback raised from the user code.
```python
from flytekit import task, workflow, ImageSpec, StructuredDataset
new_flytekit = "git+https://github.com/flyteorg/flytekit@44479af966f979ededd4b1aeabd1915027740231"
image = ImageSpec(registry="ghcr.io/unionai-oss", packages=["flytekitplugins-flyteinteractive"])
@task()
def t1() -> int:
sd = StructuredDataset(uri="s3://abc")
sd.open(pd.DataFrame).all()
return 3 + 2
@task()
def t2() -> int:
raise ValueError("failed")
@workflow
def wf():
t1()
t2()
t1()
```
Before:
After:
NA
NA
> refactor: Improve error handling and logging

- dev-requirements.in
- flytekit/core/container_task.py
- tests/flytekit/unit/core/Dockerfile.raw_container
- tests/flytekit/unit/core/return_same_value.py
- tests/flytekit/unit/core/test_container_task.py
- tests/flytekit/unit/core/test_local_raw_container.py
- tests/flytekit/unit/core/write_flytedir.py
- tests/flytekit/unit/core/write_flytefile.py
https://github.com/flyteorg/flyte/issues/3876
We want to support users to run `raw-container` task locally.
Note: I didn't support ~~`datetime.timedelta`~~, `List` and `Dict`.
Since I found that copilot has bug to deal with that, so I will support them until those bugs are fixed.
(This implies that we have to fix flytecopilot for nested types and collections types first)
1.  override `local_execute` function in `class ContainerTask(PythonTask)`
2. use `docker` python library to execute docker command
3. support int, str, float, bool, datetime.datetime, FlyteDirectory and FlyteFile
~~4. I will strip white space because it will be too complicated to support string with white space.~~
~~(datetime.datetime will be affected)~~
5. I've supported FlyteDirectroy and FlyteFile as input, ~~however, …
> Raw Container Task Local Execution

- pull_request_template.md
This PR updates the PR template to properly link to issue in `flyteorg/flyte` to auto close the original issue.
REF: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> Update template to link issue for closing

- dev-requirements.in
- dev-requirements.txt
- flytekit/clis/sdk_in_container/init.py
- pyproject.toml
Closes https://github.com/flyteorg/flytekit/pull/1665
Related to https://github.com/flyteorg/flyte/issues/4418
This PR removes the `cookiecutter` dependency from flytekit.
This PR replaces the `cookiecutter` code with a HTTP request, extracting the files from the template, and replacing `{{cookiecutter.project_name}}` in the contents and file names.
I reran `pyflyte init` for every template and checked that the behavior is the same as before.
> Removes cookiecutter dependency

- flytekit/configuration/plugin.py
- flytekit/core/context_manager.py
- tests/flytekit/unit/core/test_context_manager.py
- tests/flytekit/unit/models/core/test_security.py
With this PR, secret managers that do not require groups, can configure the client to disable the secret group check and have it work remotely without changing the `flytekit` base image.
On main, the secrets groups are checked during registration time and runtime. This PR keeps the registration time check and removes the runtime check. 
Unit tests that check for the groups were removed. I added a new test to make sure that groups are checked during registration time.
> Do not check for secret groups during runtime

- flytekit/clients/raw.py
https://github.com/flyteorg/flyte/issues/5224
Admin already gates large error messages, but flytekit does not set the max metadata size.  The default is 16KB, so now we're bumping it up to roughly 32KB, in line with the cutoff from Admin.
Add a grpc dial option to the channel to configure max metadata size.
This was tested by artificially creating a fake large error message in Admin (larger than 32KB in size) and confirming that it was received correctly by flytectl but not by flytekit.  Adding this option lets flytekit receive the error correctly.
> Use grpc metadata limit from Admin

- docs/source/extras.accelerators.rst
- flytekit/configuration/__init__.py
- flytekit/core/base_task.py
- flytekit/core/promise.py
- flytekit/core/python_function_task.py
- flytekit/core/type_engine.py
- flytekit/deck/__init__.py
- flytekit/extend/__init__.py
- flytekit/extras/accelerators.py
- flytekit/image_spec/__init__.py
- flytekit/testing/__init__.py
- flytekit/types/error/__init__.py
- flytekit/types/iterator/__init__.py
- flytekit/types/pickle/__init__.py
We are currently using [sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/) for various documentation elements like dropdowns and tabs. However, `sphinx-panels` is no longer maintained and is restricting the version of sphinx we use to `4.5.0`. The up-to-date solution for this is [sphinx-design](https://sphinx-design.readthedocs.io/en/latest/).
NOTE: We'll have to merge the related PRs in the following order:
1. https://github.com/flyteorg/flytekit/pull/2364, https://github.com/flyteorg/flytesnacks/pull/1652, https://github.com/flyteorg/flytectl/pull/471
2. https://github.com/flyteorg/flyte/pull/5254
This PR:
- Makes changes to the docs to use `sphinx-design` directives
- Cleans up API docs to leverage the upgraded furo version that displays the right sidebar
Build the docs …
> use sphinx-design directives instead of sphinx-panels

- flytekit/models/admin/task_execution.py
- flytekit/remote/remote.py
NA
Failed to register a workflow when serialization settings is None
```bash
if create_default_launchplan:
if not og_entity:
raise user_exceptions.FlyteValueException(
"To create default launch plan, please pass in the original flytekit workflow `og_entity`"
)
self.file_access._get_upload_signed_url_fn = functools.partial(
>                   self.client.get_upload_signed_url, project=settings.project, domain=settings.domain
)
E               AttributeError: 'NoneType' object has no attribute 'project'
```
Create a default serialization settings if it's None
```python
def t2(second: int):
sleep(second)
@workflow
def wf(second: int = 60):
for i in range(10):
t2(second=second)
flyte_workflow = remote.register_workflow(
entity=wf, version=version
)
exe = …
```
> Use default serialization settings if serialization_settings is None

- flytekit/core/promise.py
- tests/flytekit/unit/core/test_promise.py
https://github.com/flyteorg/flyte/issues/5270
These changes are needed to use remote LP without fixed inputs when input + default inputs are provided.
In line comment
Unit test and manual test
> Fix use default inputs with remote LaunchPlan

- flytekit/core/checkpointer.py
- flytekit/core/context_manager.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
- tests/flytekit/unit/core/test_checkpoint.py
N/A
In `pathlib`, `joinpath` and the `/` operator have the same functionality, but the `/` operator is easier to read.
Replace all `joinpath` with `/` operator.
> refactor(pathlib): Replace joinpath with slash

- flytekit/image_spec/image_spec.py
- flytekit/remote/executions.py
- flytekit/tools/fast_registration.py
- flytekit/tools/ignore.py
- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
- plugins/flytekit-envd/tests/.dockerignore
- plugins/flytekit-envd/tests/test_image_spec.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
- tests/flytekit/unit/tools/test_fast_registration.py
- tests/flytekit/unit/tools/test_ignore.py
NA
Pycache, Venv, and some other irreverent files are copied to the docker image.
Use `.dockerignore` file to exclude files and directories from images built from ImageSpec
local sandbox
NA
NA
> Add .gitignore and .dockerignore behavior to ImageSpec

- flytekit/core/artifact.py
- flytekit/core/interface.py
- tests/flytekit/unit/core/test_artifacts.py
This is just a convenience change.
> Query by default when missing

- flytekit/remote/remote.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/integration/remote/workflows/basic/default_lp.py
- tests/flytekit/unit/remote/test_remote.py
NA
Failed to run a workflow again when using `datetime.datetime` as default input because flytekit will try to register the same version of LP with the different default input
Add default inputs to version hash
Integration test and pyflyte run 
NA
NA
> Add default inputs to version hash

- flytekit/models/security.py
- tests/flytekit/unit/models/core/test_security.py
Follow up to https://github.com/flyteorg/flytekit/pull/2355
This is required to make sure that the secrets groups check never happens during execution time.
With this PR, the secrets group check only happens during registration time.
There are current tests that checks `Secrets` construction when `Execution.mode` is `None`. I added more tests to make sure that the groups are not checked during execution time.
> Only check for secret groups during registration context

- flytekit/tools/repo.py
None
CLI (`flytekit/tools/repo.py`) shows redundant status message when registration.
Remove redundant `secho()`.
Register with and without this `secho()`.
`pyflyte register wf.py`
1. Before removing
2. afte removing
> Remove redundant `secho()`

- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
NA
Failed to run docker login in the CI if the PR is opened from the folk outside of flyteorg. 
https://github.com/flyteorg/flytesnacks/actions/runs/8903067316/job/24456342759
push image only if `FLYTE_PUSH_IMAGE_SPEC` equal to true. Default is True.
local
NA
NA
> feat(flytekit-envd): Add conditional push based on env var

- flytekit/models/common.py
- tests/flytekit/unit/core/test_promise.py
- tests/flytekit/unit/core/test_type_hints.py
- tests/flytekit/unit/models/test_common.py
When interacting with `FlyteRemote`, it's hard to see the actual types of the returned objects. I frequently will call `type` to get the actual class:
Adds the actual type to the `repr` so it's easier to distinguish between `FlyteLiterals`.
I added a unit test to make sure the class name is in the repr.
> Adds type information to flytekit.models in repr

- flytekit/bin/entrypoint.py
- flytekit/configuration/__init__.py
- flytekit/configuration/internal.py
- flytekit/core/data_persistence.py
These changes allow easy attribution of cost in storage to particular executions, workflows, etc., without needing to parse data out of the path or correlate with flyteadmin and the data catalog.
Since this may have cost implications (at least in GCS, metadata of this sort is added to the total file size billed), I made it configurable in case folks would like to turn it off.
I have tested that this works on GCS, and verified that the same metadata option exists for S3 in fsspec. I did not check Azure.
I'd like to follow this up with another PR to allow user-specified metadata to be attached to all writes as well.
I ran workflows in our development environment hooked up to GCS.
```
gcloud storage objects list --raw gs://<bucket>/metadata/propeller/sandbox-development-atcf27bztrw2ptb62n94/p …
```
> Add optional execution metadata to objects written to storage for easy attribution

- flytekit/types/structured/structured_dataset.py
cc @pingsutw 
The error happened from some Python version (like `3.10.13`) but worked in some others.
`Failed with Unknown Exception <class 'KeyError'> Reason: '__annotations__'`
However, I can't reproduce the error on my python environment with version `3.10.13`.
There might be other package version issues, because it works in different python environment with different set of packages installed.
In spite of the unknown root cause of the error, we can still eliminate error by simply using `.` to select attribute path, `aa.__annotations__`.
Original approach returns the `__dict__` of a class as type Dictionary via `vars()` then get it by `obj['__annotations__']`, see https://docs.python.org/3/library/functions.html#vars .
As the usage of selecting attribute `__annotations__`, please check …
> Fix `__annotations__` key not found

- flytekit/clis/sdk_in_container/run.py
N/A
Running `pyflyte run examples/basics/basics/documenting_workflows.py` in the `flytesnacks` repo raises error.
Because `documenting_workflows.py` has relative imports in it, the `additional_path` should be its parent folder's parent folder.
> fix(import): Fix relative import path error

- flytekit/core/promise.py
- flytekit/core/type_engine.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_task.py
- plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
- tests/flytekit/unit/core/test_local_cache.py
- tests/flytekit/unit/core/test_type_engine.py
This is useful for serializing dictionaries that aren't JSON serializable. To enable pickling the data, the `dict` type needs to be annotated with `allow_pickle` set to `True`:
```python
@task
def t1() -> Annotated[dict, kwtypes(allow_pickle=True)]
...
```
Pickling only happens if the dict isn't JSON serializable. 
Modify `DictTransformer` to add support for pickling dictionaries and include relevant test cases. I've also updated the `BotoTask` output type to allow pickling when the dict isn't JSON serializable.
> pickle dictionary when it isn't JSON serializable

- .github/workflows/pythonbuild.yml
- Dockerfile
- Dockerfile.dev
- Makefile
- dev-requirements.in
- plugins/flytekit-greatexpectations/dev-requirements.in
- plugins/flytekit-papermill/dev-requirements.in
https://github.com/flyteorg/flyte/issues/5346
As described in the issue, let's adopt [`uv`](https://github.com/astral-sh/uv) as the package installer for flytekit.
Use `uv` in a few places:
1. when setting up a dev environment via the new make target `setup-uv`. This assumes that a virtual environment (e.g. `uv venv`) is already setup prior to calling this. This keeps the tradition of not being too prescriptive about venvs.
i. we can make this the default once we're satisfied with it. This will require a slight change to the docs.
2. the default flytekit image is now built using `uv`
i. Notice the use of `--system` to ensure the packages are installed in the global environment.
4. the dev flyte image is also built using `uv`
5. We should probably also build the agent image with `uv`. …
> Use uv in CI and to build images

- flytekit/core/data_persistence.py
Closes https://github.com/flyteorg/flyte/issues/5352
FTP is still used in bioinformatics
Add FTP to supported protocols of FlyteFile. If anyone is using path as a kwarg to `get_filesystem`, this will remove it from kwags - I would not expect this to be the case though.
```python
ff = FlyteFile.from_source("ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz")
local = ff.download()
print(local)
```
> feat: Support ftp when using FlyteFile

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
NA
image.exists() return None when the docker client raises an error & the error code is not 404
Always return true if error code is not 404
local sandbox
```python
from flytekit import ImageSpec, task, dynamic
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@285148f1189cd1b14503b50caf60ba63222272e9"
repro_img = ImageSpec(
name="flytekit",
base_image="ghcr.io/flyteorg/flytekit:py3.11-latest",
builder="envd",
packages=[new_flytekit],
apt_packages=["curl", "git"],
)
@task(container_image=repro_img)
def foo():
print("foo")
@dynamic(container_image=repro_img)
def bar():
foo()
print("image", repro_img.exist())
```
NA
NA
> fix(ImageSpec): Ensure all APIErrors return a value

- pyproject.toml
Follow up to https://github.com/flyteorg/flytekit/pull/2360
In https://github.com/flyteorg/flytekit/pull/2360, we removed the cookiecutter dependency, which also removed `jinja2`. We require `jinja2` to construct Flyte Decks.
This PR adds `jinja2` as as a direct dependency.
I built a Flytekit image without jinja2 installed and got this error:
```
{"asctime": "2024-05-14 16:16:05,571", "name": "flytekit", "levelname": "ERROR", "message": "Failed to write flyte deck html with error No module named 'jinja2'.", "taskName": null}
```
Once `jinja2` is installed, the FlyteDeck button appears.
For reference the code is here:
https://github.com/flyteorg/flytekit/blob/cc3a7a9277852dc06bc1b2c041a962be973d8faf/flytekit/deck/deck.py#L162-L176
> Adds jinja2 to dependnecies

- flytekit/clis/sdk_in_container/run.py
- flytekit/interaction/click_types.py
NA
Default workflow inputs are serialized twice in the flytekit
1. https://github.com/flyteorg/flytekit/blob/6d881a8321908a4ea9cf56fbfdfe38a11aef18d2/flytekit/interaction/click_types.py#L389
2. https://github.com/flyteorg/flytekit/blob/93f690c2124d1c15c6c65cd98d384f881dba41fb/flytekit/core/interface.py#L243
Skip serialization if the input matches the default value in the launch plan.
`pyflyte run` & `pyflyte run --remote ...`
NA
NA
> refactor(click_types): skip serialization for default values

- plugins/flytekit-wandb/README.md
- plugins/flytekit-wandb/flytekitplugins/wandb/__init__.py
- plugins/flytekit-wandb/flytekitplugins/wandb/tracking.py
- plugins/flytekit-wandb/setup.py
- plugins/flytekit-wandb/tests/test_wandb_init.py
Related to https://github.com/flyteorg/flyte/issues/2798
This PR adds a `wandb` plugin to better integrate with Weights and Biases.
This PR proposes a simple `wandb_init` task decorator that gives the user full control on how the `project`, `entity` are named in Weights and Biases. If the `id` is not given, then the `HOSTNAME` is used for wandb's run id. Currently, `HOSTNAME` is set to `{.executionName}-{.nodeID}-{.taskRetryAttempt}`, which is unique to the node.
This PR adds unit tests and docs to help users enable the feature.
For local testing, I've built an image with this plugin installed at `ghcr.io/thomasjpfan/wandb:0.0.4` and ran:
<details><summary>Workflow contents</summary>
```python
from flytekit import task, Secret, workflow
from flytekitplugins.wandb import wandb_init …
```
> Adds flytekitplugin.wandb 

- plugins/flytekit-envd/setup.py
NA
[pip_extra_index_url ](https://github.com/flyteorg/flytekit/blob/master/flytekit/image_spec/image_spec.py#L69) is added to ImageSpec in flytekit 1.12.0, so we should set the flytekit's lower bound to 1.12.0 as well.
Set lower bound for flytekit
Unit test
NA
NA
> Set lower bound for flytekit in envd plugin

- flytekit/lazy_import/lazy_module.py
Related to https://github.com/flyteorg/flyte/issues/4877
From time to time, I get this error locally or remotely:
```
File "/opt/conda/envs/envd/bin/pyflyte-execute", line 5, in <module>
from flytekit.bin.entrypoint import execute_task_cmd
File "/opt/conda/envs/envd/lib/python3.11/site-packages/flytekit/__init__.py", line 242, in <module>
from flytekit.deck import Deck
File "/opt/conda/envs/envd/lib/python3.11/site-packages/flytekit/deck/__init__.py", line 22, in <module>
from .renderer import MarkdownRenderer, SourceCodeRenderer, TopFrameRenderer
File "/opt/conda/envs/envd/lib/python3.11/site-packages/flytekit/deck/renderer.py", line 13, in <module>
pandas = lazy_module("pandas")
^^^^^^^^^^^^^^^^^^^^^
File …
```
> Check for None before lazy loading

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
Partly address https://github.com/flyteorg/flyte/issues/4374
Dynamic workflows will try to build the image spec during execution.
This PR stops the image builder from building during any execution mode.
I added unit test to check that the image builder does not launch. I also ran the following to check that it worked in the sandbox. 
```python
from flytekit import ImageSpec, task, dynamic
repro_img = ImageSpec(
name="flytekit",
base_image="ghcr.io/flyteorg/flytekit:py3.11-latest",
builder="envd",
packages=[
"git+https://github.com/thomasjpfan/flytekit.git@3700c4710a606f5b1e13f3c815c233c39cc9f425"
],
)
@task(container_image=repro_img)
def foo():
print("foo")
@dynamic(container_image=repro_img)
def bar():
foo()
```
Note that this does not …
> fix(ImageSpec): Do not build image during executions

- plugins/flytekit-spark/flytekitplugins/spark/models.py
- plugins/flytekit-spark/flytekitplugins/spark/task.py
- plugins/flytekit-spark/tests/test_agent.py
- plugins/flytekit-spark/tests/test_spark_task.py
Related to https://github.com/flyteorg/flyte/issues/5385
The token in the task config is stored in the database and exposed in the UI, which is not secured. We should not allow users to do that.
Remove databricks token in the task config
unit test
NA
NA
> Remove databricks token from the task config

- .github/workflows/pythonbuild.yml
- Makefile
- flyrs/Cargo.toml
- flyrs/pyproject.toml
- flyrs/src/lib.rs
- flytekit/clients/auth_helper.py
- flytekit/clients/friendly_rs.py
- flytekit/clients/grpc_utils/auth_interceptor.py
- flytekit/clients/grpc_utils/default_metadata_interceptor.py
- flytekit/clients/grpc_utils/wrap_exception_interceptor.py
- flytekit/clients/raw.py
- tests/flytekit/integration/remote/test_rust_remote.py
https://github.com/flyteorg/flyte/issues/5344
To add a integration test for the Rust Remote Client, we have to add Github Action Jobs for building and installing compiled Python extension, `flyrs`, from Rust through PyO3 bindings.
> [!CAUTION]
> This PR depends on the previous work done in https://github.com/flyteorg/flytekit/pull/2414 .
It cannot be executed before https://github.com/flyteorg/flytekit/pull/2414 is merged.
We add two CI/CD jobs,
1. `build-without-grpcio`
- Run Rust Remote without installing Python `grpcio`, `grpcio-status`.
3. `build-with-grpcio`
- Make sure the outputs of the Rust Remote and Python remote are the same.
Both of them are only being tested against integration test `test_rust_remote.py` that installed `flyrs` via `maturin develop` (compiled and installed), …
> Add GA workflow to test Rust Remote without installing Python gRPC

- flytekit/core/launch_plan.py
When registering their applications (tasks, workflows, launchplans), our users are regularly confused by the following exception:
```console
~ pyflyte register ...
...
File ".../wf.py", line 22, in <module>
lp = LaunchPlan.get_or_create(
File ".../flytekit/core/launch_plan.py", line 284, in get_or_create
raise AssertionError("The cached values aren't the same as the current call arguments")
```
Often, our users think this was related to Flyte's caching mechanism, steering their debugging in the wrong direction.
Actually, the problem occurs when ...
1. ... trying to use the same launch plan name for two different workflows
```py
@workflow
def wf():
@workflow
def wf2():
lp = LaunchPlan.get_or_create(
wf,
"my_wf",
)
lp = LaunchPlan.get_or_create(
wf2,
"my_wf",
)
```
2. ... or trying to …
> Make error messages in LaunchPlan.get_or_create actionable

- Dockerfile
The flytekit pod plugin has been deprecated for a while and scikit used to be part of the getting started guide (emphasis on used to be).
Remove pod plugin and scikit-learn packages from the flytekit image.
> Remove pod-plugin and scikit-learn from official docker image

- .github/workflows/pythonbuild.yml
- dev-requirements.in
Related to https://github.com/flyteorg/flyte/issues/5448
All the details are explained in the linked issue, but essentially, we have certain dependencies that are not ready yet to run the new major version of the protobuf library.
> Only run CI checks using protobuf 4

- flytekit/interaction/click_types.py
- tests/flytekit/unit/interaction/test_click_types.py
https://github.com/flyteorg/flyte/issues/4486
Currently, we don't support `passing dataclass values via command line` after this [PR](https://github.com/flyteorg/flytekit/pull/2279).
For example, using this command line will raise an error.
`pyflyte run --remote --image localhost:30000/any:0528-1445 dataclass_task.py foo_wf  --a '{ "x": 1, "y": "2", "z": { "1": "one", "2": "two" }, "w": [1, 2, 3] }'`
If we use only `dataclass` decorator only for our dataclass value, convert it to `dataclass_json`.
local execution, remote execution and unit test.
```python
@dataclass
class Datum:
x: int
y: str
z: dict[int, str]
w: list[int]
@task
def foo_dataclass(a: Datum) -> int:
if type(a) == Datum:
return a.x
return 0
@workflow
def …
```
> [MINOR] Support Passing Dataclass Values via Command Line

- plugins/flytekit-huggingface/setup.py
I just saw that the datasets module had its latest release, so I guess it is the root cause of the CI failure, and it works now.
https://pypi.org/project/datasets/#history
> Fix CI by restricting hugging face dataset version

- flytekit/core/promise.py
- tests/flytekit/unit/core/test_promise.py
- tests/flytekit/unit/core/test_type_engine.py
Related to https://github.com/flyteorg/flyte/issues/5321.  This was discovered while implementing [that PR](https://github.com/flyteorg/flytekit/pull/2401).
The main issue is highlighted in the test added to the test type engine file.  When you call `TypeEngine.to_literal` on a Union type, you should get back a Flyte literal with a `Union` [message](https://github.com/flyteorg/flyte/blob/9ffc54fa4d69f3058ce635a53ce2fa594a9cc5d9/flyteidl/protos/flyteidl/core/literals.proto#L56).  This was happening correctly in the Type Engine but for some reason this wasn't happening for Binding Data.
That is, if you had
```python
@task
def say_hello(a: int | str) -> str:
print(f"Type is {type(a)}")
if type(a) == str:
return f"Hello, {a}!"
return "Hello, World!"
@workflow
def hello_world_wf()-> str:
res = …
```
> add escape hatch to binding union handling

- flytekit/core/promise.py
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_composition.py
- tests/flytekit/unit/core/test_dynamic.py
- tests/flytekit/unit/core/test_promise.py
- tests/flytekit/unit/core/test_serialization.py
- tests/flytekit/unit/types/pickle/test_flyte_pickle.py
- tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
Resolves: flyteorg/flyte#5321
See the issue description for details.
if the key is not in `kwargs` but in `interface.inputs_with_defaults`, add the value in `interface.inputs_with_defaults` to `kwargs`.
> feat(bindings): Task arguments default value binding

- flytekit/bin/entrypoint.py
COR-982
In cases where the python interpreter is not shut down between executions, we need to make sure we don't accidentally pick up an old errors.pb file.
When starting a new execution, we run the `setup_execution` context manager. One of the things it does is create a new execution state object, which [creates](https://github.com/flyteorg/flytekit/blob/c03eaadd72fbe302003baf98e3e8e2fac237eaac/flytekit/core/context_manager.py#L512) a new engine dir based on the working dir.  This working dir is based on the file access provider [local_sandbox_dir](https://github.com/flyteorg/flytekit/blob/c03eaadd72fbe302003baf98e3e8e2fac237eaac/flytekit/core/context_manager.py#L694).  That local sandbox dir is [created anew](https://github.com/flyteorg/flytekit/pull/2452/files#diff-932d345851356237c198d …
> Use new fileaccess to build execution state

- flytekit/extend/backend/base_agent.py
As this [PR](https://github.com/flyteorg/flytekit/pull/2457) mentioned,
we should make `SyncAgentBase` and `AsyncAgentBase` have the same interface
https://github.com/flyteorg/flytekit/blob/master/flytekit/extend/backend/base_agent.py#L123
> Async Agent Interface Refactor

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
closed https://github.com/flyteorg/flyte/issues/5450
When metadata is None, DictTrasformer will fail to deserialize literal.
Always use `json.loads` in DictTrasformer if metadata['format'] is not equal to pickle
unit test
NA
NA
> fix(core): Handle missing metadata in DictTransformer

- flytekit/interaction/string_literals.py
- tests/flytekit/unit/interaction/test_string_literals.py
If attempting to create a string representation of a literal whose scalar contains a `schema` (e.g. pandera DataFrames), an "Unknown scalar type" `ValueError` is raised.
It is often nice to just print out the outputs of a workflow execution, but that's currently not possible if a pandera-typed DataFrame is one of them. 
We simply return the schema's URI, similarly to how `structured_dataset` is handled.
I expanded on the existing unit test
> Enable string conversion for `Scalar` objects that contain a `schema`

- flytekit/clis/sdk_in_container/run.py
- flytekit/interaction/click_types.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
https://github.com/flyteorg/flyte/issues/3960
Currently, Users can't specify a key-only label
Add labels_callback for labels, which allows the value in the label to be None
hello=world => {"hello": "world"}
rust => {"rust": ""}
sandbox
```bash
pyflyte run --remote --label hello=world --label rust flyte-example/getting_started.py wf
```
NA
NA
> Make the value in the label optional

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
https://github.com/flyteorg/flytekit/actions/runs/9475012693/job/26105636011
Unit test is failing
if image registry is `localhost:30000`, we should not use `request` to check if the image exists on docker hub
unit test
NA
NA
> Fix test_image_spec

- flytekit/core/type_engine.py
- flytekit/interaction/click_types.py
- flytekit/types/pickle/pickle.py
https://github.com/flyteorg/flyte/issues/5426
Previously, the `to_literal()` function of the `FlytePickleTransformer` class had the output prefix information in the `ctx` argument. However, the `to_pickle()` function of the `FlytePickle` class did not utilize this information and instead used `FlyteContextManager.current_context()`. The output prefix from `FlyteContextManager.current_context()` did not reflect the correct path for workflows running remotely.
Pass the `ctx` value to the `to_pickle()` function. This will ensure the correct path is given.
I tested this task with customized code running in both the local environment and the sandbox cluster.
- `remote_uri.py`: This code tests the correctness of the upload path in the `to_pickle()` function in different settings, including …
> Fix the `uri` value of the input with Any type in the workflow when running remotely.

- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_flyte_file.py
Closes flyteorg/flyte#5445
Currently, if the input argument contains a `FlyteFile` whose name contains special characters, the execution fails. This PR fixes this bug, and enables filenames with special characters.
The PR introduces the `unquote` function from the `urllib.parse` library, that replaces the percent encoded special characters with their single character equivalent on the `uri` param of the `Literal` class. 
This was tested by replicating the steps mentioned in the issue flyteorg/flyte#5445
> fix: include remote file paths with special characters

- flytekit/types/schema/types.py
- flytekit/types/structured/structured_dataset.py
- pyproject.toml
Today, `numpy==2.0.0` was released. This new release broke the [sandbox-bundled-functional-tests](https://github.com/flyteorg/flyte/actions/runs/9536915121/job/26284633221?pr=4726#logs) in https://github.com/flyteorg/flyte/pull/4726:
```console
Collecting numpy>=1.26.0 (from pandas->flytekitplugins-deck-standard)
Downloading numpy-2.0.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
...
Failed with Unknown Exception <class 'AttributeError'> Reason: `np.string_` was removed in the NumPy 2.0 release. Use `np.bytes_` instead.
...
File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/flytekit/types/schema/types.py", line 340, in FlyteSchemaTransformer
_np.string_: SchemaType.SchemaColumn.SchemaColumnType.STRING,
^^^^^^^^^^^
```
The [docs of …
> Fix: Fix deprecated numpy type and make numpy<2 explicit dependency

- flytekit/tools/fast_registration.py
- tests/flytekit/unit/tools/test_fast_registration.py
We had the erroneous assumption that all files are accessible during fast registration.
Verify that the file exists before trying to open it.
> Skip broken symlinks during calculation of digest (during fast registration)

- flytekit/clis/sdk_in_container/utils.py
- flytekit/image_spec/image_spec.py
NA
The error message is cryptic
```python
import os
from flytekit import task, workflow, WorkflowFailurePolicy, ImageSpec
registry="ghcr.io/flyteorg",
packages=["mlflow", "pandas", "mypy", "flytekit", "requests"],
apt_packages=["wget", "git"],
)
@task(container_image=custom_image, enable_deck=True)
os.getenv("FLYTE_INTERNAL_EXECUTION_ID")
return 3 + a
@task(container_image=custom_image, enable_deck=True)
def t2(a: int) -> int:
return 3 + a
@workflow(failure_policy=WorkflowFailurePolicy.FAIL_AFTER_EXECUTABLE_NODES_COMPLETE)
def wf():
t1(a=3)
t2(a=3)
runner = CliRunner()
result = runner.invoke(
pyflyte.main,
[
"run",
"--remote", …
```
> Improve error handling for docker client

- pyproject.toml
Remove upper bound for dependencies `pytimeparse`.
> Remove upper bound for deps `pytimeparse`

- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_flyte_file.py
Fixed minor bug in FlyteFile.new_remote_file tested with unit test
> Made FlyteFile.new_remote_file use name arg

- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
NA
People cannot use custom envd context.
Add an env var `FLYTE_ENVD_CONTEXT`, which allows people to use custom envd context.
```bash
FLYTE_ENVD_CONTEXT=flyte pyflyte run --remote flyte-example/getting_started.py wf
```
NA
NA
> feat(envd): Add switch for custom envd context

- flytekit/configuration/default_images.py
- flytekit/core/constants.py
- tests/flytekit/unit/configuration/test_image_config.py
NA
When unionai is installed, it will ignore `FLYTE_INTERNAL_IMAGE`, and always use the default [flytekit image](https://github.com/flyteorg/flytekit/blob/739d379029a12428171bab601f7f7f61ef86ed43/flytekit/configuration/default_images.py#L21-L27).
That's because flytekit will call `get_plugin().get_default_image()`, and then `DefaultImages.find_image_for()`. Thus, it skip the FLYTE_INTERNAL_IMAGE.
Move `os.getenv("FLYTE_INTERNAL_IMAGE")` to `find_image_for()`
unit test
NA
NA
> FLYTE_INTERNAL_IMAGE should have higher precedence

- plugins/flytekit-wandb/flytekitplugins/wandb/tracking.py
- plugins/flytekit-wandb/tests/test_wandb_init.py
Follow up to https://github.com/flyteorg/flytekit/pull/2405
With this PR, a backlink is injected into the notes. This allows user to go from wandb interface back to the execution. In the wandb UI, it will end up here:
This PR looks for `FLYTE_EXECUTION_URL` and injects it into the notes if it is available.
The unit tests were updated to check this change.
> Adds support for wandb backlinks through FLYTE_EXECUTION_URL

- tests/flytekit/unit/core/test_data_persistence.py
NA
This test is flaky. Seems like `os.env` was overridden by other tests
> The @mock.patch.dict decorator patches the dictionary in place, while the with @mock.patch.dict decorator creates a temporary copy of the dictionary and patches that.
Use `with mock.patch.dict` instead
unit test
NA
NA
> Fix flaky test_initialise_azure_file_provider_with_default_credential

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
NA
The Flytefile is not uploaded to S3 when having that ​​`from ­­­future­­­ import annotations`​​ import inside the file. 
That's because `dataclasses.fields(python_type)[0].type` will return a string ('flytefile') instead of the actual type when postponed annotations is enabled.
Use `typing.get_type_hints` to explicitly get the type from dataclass.
remote cluster
```python
from __future__ import annotations
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@c5e6cefbc99f8db1190a87c10d921445f3e7b7d1"
registry="ghcr.io/flyteorg",
packages=[new_flytekit],
)
@dataclass
class DebugOutput:
file: FlyteFile
def …
```
> refactor(core): Improve dataclass attribute serialization

- flytekit/remote/remote.py
NA
Users can't specify `filter` when listing executions
Add filter arg to recent_executions
flytekit remote
NA
NA
> Add filter support to recent_executions

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
Modifying the name to "Python Dictionary" requires users to re-register their reference tasks and launch plans, which would otherwise lead to errors such as:
```
Error 0: Code: MismatchingTypes, Node Id: n4, Description: Variable [o0] (type [union_type:{variants:{simple:STRUCT  structure:{tag:"Typed Dict"}}  variants:{simple:NONE  structure:{tag:"none"}}}]) doesn't match expected type [union_type:{variants:{simple:STRUCT  structure:{tag:"Python Dictionary"}}  variants:{simple:NONE  structure:{tag:"none"}}}].
```
Same as title.
> modify the name of the dict transformer to typed dict

- flytekit/extras/tasks/shell.py
- tests/flytekit/unit/extras/tasks/test_shell.py
Under some circumstances, subproc_execute will exit with 0 but have a non-null stderr.
Adds an assert statement to handle 0 exit with stderr.
Unit test to capture AssertionError and ensure the message contains the right content.
`make setup`
`make unit_test`
> Catch silent subproc_execute failures

- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_flyte_file.py
N/A
When running local executions, local files that exist should not need to be copied. When running large files, this can become a bottleneck.
Check if running a local task execution when converting FlyteFile to literal.
```python
@task
def example(ff: FlyteFile) -> str:
downloaded_path = ff.download()
print(downloaded_path)
return str(ff.path)
example(ff=__file__)
```
Before the fix, this printed:
```console
/var/folders/d1/n1tj86t11pj_drgfg7_br5n00000gn/T/flyte-qd4bk3t0/raw/0fee47924014b3cb5f12295a48330c0f/tmp.py
```
After the fix, this printed:
```console
/Users/ggydush/dev/delve/flytekit/flytekit/types/file/tmp.py
```
> fix: Prevent local files from being moved when using FlyteFile on local executions

- flytekit/core/interface.py
- tests/flytekit/unit/core/test_interface.py
https://github.com/flyteorg/flyte/issues/5511
Rationale: flyte inputs names are "like" python variable names, which should not use special characters like . (see my.value in the repro code
Expected behavior: The workflow should actually fail at compile time at step 1. (e.g. perform extra validation)
Workflow should fail at compile time at step 1, when python-invalid variable name is used like "my.value".
```
import logging
from flytekit import ContainerTask, kwtypes, task, workflow
logger = logging.getLogger(__file__)
calculate_ellipse_area_shell = ContainerTask(
name="ellipse-area-metadata-shell",
input_data_dir="/var/inputs",
output_data_dir="/var/outputs",
inputs=kwtypes(**{"my.value": float, "c": float}),
outputs=kwtypes(area=float, metadata=str), …
```
> [fix] Validate interface variable names are python-valid

- flytekit/core/promise.py
- tests/flytekit/unit/core/test_serialization.py
Resolves: flyteorg/flyte#5320
The the issue description for details.
- Change the `inputs` and `outputs` attributes in the `Interface` class to `OrderedDict` to preserve the order.
- Write values in positional arguments to `kwargs`.
> [Feature] Support positional arguments

- plugins/flytekit-pandera/tests/test_plugin.py
Closes [flyteorg/flyte#999](https://github.com/flyteorg/flyte/issues/5531)
Pandera's `SchemaModel` API was removed in 0.20
Use the newer `DataFrameModel` in tests.
> Fix pandera plugin for 0.20

- flytekit/image_spec/image_spec.py
- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
NA
To improve the error message
```python
scraper_image_spec3 = ImageSpec(
base_image="python:3.11-slim-bookworm",
packages=["pandas", "flytekit"],
apt_packages=["vim"],
)
@task(container_image=scraper_image_spec3)
def t3(a: int) -> int:
return a + 2
@workflow
def wf(a: int = 3):
t3(a=a)
```
Before:
After:
NA
NA
> Improve error message for ImageSpec

- flytekit/interaction/click_types.py
- tests/flytekit/unit/interaction/test_click_types.py
We only support local directory for click Dir param type, now we want to support remote s3 path also. 
Use `FileAccessProvider.is_remote` to check if the path is remote or not.
remote execution and unit test.
```python
import os
@task
def list_dir(d: FlyteDirectory):
for fname in os.listdir(d):
print(f"Found file {fname}")
@workflow
def dir_wf(d: FlyteDirectory):
list_dir(d=d)
@task
def list_file(f: FlyteFile):
print(f)
with open(f, "r") as wf:
print(wf.read())
@workflow
def file_wf(f: FlyteFile):
list_file(f=f)
runner = CliRunner()
result = …
```
> Support s3 path for click Dir param type

- plugins/flytekit-greatexpectations/setup.py
remove upper bound of plugin dependencies for flytekit-greatexpectations
> remove upper bound of plugin dependencies for flytekit-greatexpectations

- CODEOWNERS
Would it be ok for you if I add myself to the code owners for the `flytekit-kf-pytorch` plugin (distributed pytorch training tasks)?
I authored the `task_config=Elastic(...)` task type of this plugin (https://github.com/flyteorg/flytekit/pull/1603, https://github.com/flyteorg/flyteidl/pull/394, https://github.com/flyteorg/flyteplugins/pull/343, https://github.com/flyteorg/flytesnacks/pull/987) and later contributed the following additional PRs to it:
* https://github.com/flyteorg/flytekit/pull/1677
* https://github.com/flyteorg/flytekit/pull/1678
* https://github.com/flyteorg/flytekit/pull/1697
* https://github.com/flyteorg/flytekit/pull/1736
* https://github.com/flyteorg/flytekit/pull/1739
* https://github.com/flyteorg/flytekit/pull/1837
* https://github.com/flyteorg/flytekit/pull/1846
* …
> Add myself to code owners of flytekit-kf-pytorch

- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
- plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
`Elastic` tasks currently do not expose a run policy. As such, the run policy of a `PyTorchJob` created via an `Elastic` task cannot be configured. The same functionality exists for a `PyTorchJob` created via a `PyTorch` task. 
We are adding the same run policy configuration support from `PyTorch` tasks to `Elastic` tasks.
Unit tests added
> Add run_policy to ElasticTask 

- flytekit/core/type_engine.py
- flytekit/loggers.py
- tests/flytekit/loggers.py
- tests/flytekit/unit/test_translator.py
NA
Cannot get the terminal size in the subprocess
Set default width if fail to get terminal size
unit test
NA
NA
> Set default width if fail to get terminal size

- flytekit/experimental/eager_function.py
```python=
[3/3] currentAttempt done. Last Error: SYSTEM::Traceback (most recent call last):
File "/flytekit/flytekit/bin/entrypoint.py", line 103, in _dispatch_execute
outputs = asyncio.run(outputs)
File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/flytekit/flytekit/core/base_task.py", line 666, in _async_execute
native_outputs = await native_outputs
File "/flytekit/flytekit/experimental/eager_function.py", line 517, in wrapper
out = await _fn(*args, **kws)
File "/root/test_async.py", line 68, in simple_async_workflow
res = await coro
File "/flytekit/flytekit/experimental/eager_function.py", line 184, in __call__ …
```
> fix datetime in eager workflow

- flytekit/deck/html/template.html
The Flyte Deck's width extends past the width of the window:
With this PR, the bounds are properly set:
I build an image with the new changes and ran a simple workflow.
> Fix CSS with Flyte decks

- flytekit/remote/remote_fs.py
- tests/flytekit/unit/remote/test_fs_remote.py
https://github.com/flyteorg/flyte/issues/5541
`FlyteDirectory` is broken on Azure.
Fix `FlyteDirectory` on Azure by avoiding the need to initialise an `adlfs.AzureBlobFileSystem()` during `FlyteFS.extract_common`
Added unittest coverage
> Fix `FlyteDirectory` on Azure

- flytekit/image_spec/default_builder.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
For some images, the $HOME directory does not exists yet. With this PR, it gets created. For example, if one specifies the normal flyte base image, it'll fail to build.
```
base_image="ghcr.io/flyteorg/flytekit:py3.12-1.13.0",
packages=["pandas==2.2.2"],
)
def get():
return
```
Note that the default image builder does not use the python environment from the `base_image` and creates its own Python environment.
Unit test was updated in this PR.
> Default image builder: Creates HOME if it does not exists

- dev-requirements.txt
- pyproject.toml
`isodate` is not used anywhere in `flytekit`.
This PR removes `isodate` from `pyproject.toml`
> Removes isodate requirement

- flytekit/loggers.py
NA
Read FLYTE_SDK_DEV_LOGGING_LEVEL from env for pass it to the logger
unit test
> Read FLYTE_SDK_DEV_LOGGING_LEVEL from env

- flytekit/core/base_task.py
literal value is hard to read in the console.
Print native input/output when cache hit
pyflyte run
> print native input/output when cache hit

- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
- plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
- plugins/flytekit-kf-pytorch/tests/test_pytorch_task.py
`torchrun` sets the environment variable `OMP_NUM_THREADS` automatically if not specified ([code](https://github.com/pytorch/pytorch/blob/main/torch/distributed/run.py#L791)). If it is not set, we saw some special cases in which our experiments were stuck for several minutes with high CPU load.
Also see https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#utilize-openmp for more details.
To make `Elastic` tasks behave the same as executions started with `torchrun`, I would propose copying this behavior over to flytekit.
See above
1. Added unit tests
2. Tested with internal workflows to check the behavior of `OMP_NUM_THREADS`.
> Fix: Set OMP_NUM_THREADS by default in Elastic

- flytekit/loggers.py
Use logging level in env for dev logger by default. If it's None, use level.info by default.
> Use logging level in env for default dev logger

- flytekit/image_spec/default_builder.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
With `1.13.0`, the default image builder does not allow `flytekit` to be specified to a specific version. For example, the following will fail:
```
image1 = ImageSpec(
packages=["numpy==1.26.4", "flytekit==1.12.3"],
)
@task(container_image=image1)
def work():
pass
```
```shell
pyflyte build build_flyte.py work
```
with:
```
0.220   × No solution found when resolving dependencies:
0.221   ╰─▶ Because you require flytekit==1.13.0 and flytekit==1.12.3, we can
0.221       conclude that the requirements are unsatisfiable.
```
With this PR, we check for `flytekit` first. If it is not detected in `requirements`, then we inject `flytekit` into the requirements with the version used during registration.
Unit test was added to this PR.
> Allow for flytekit version to be specified in default image builder

- flytekit/image_spec/default_builder.py
Currently, the micromamba python environment is located in `/root`. `/root` is normally used for user code, so it's a little strange that the python environment is there too.
This PR moves the `micromamba` directory into `/opt/micromamba`.
Tested by building a simple image with this PR:
```python
packages=["numpy==2.0.0"],
)
def my_task() -> int:
import numpy as np
X = np.asarray([1, 2, 3])
return int(X[1])
@workflow
def wf() -> int:
return my_task()
```
> Use /opt/micromamba for default image builder

- docs/source/_templates/file_types.rst
https://linear.app/unionai/issue/DOC-480/fix-rendering-of-flytedirectory-api-doc-page-in-flyte-docs
[FlyteDirectory API docs page](https://docs.flyte.org/en/latest/api/flytekit/generated/flytekit.types.directory.FlyteDirectory.html) is rendering incorrectly
Adding FlyteDirectory to the if then logic of the template that produces the rendered page
Local build
Equivalent in flyte repo:
https://github.com/flyteorg/flyte/pull/5564
> Fix FlyteDirectory docs rendering

- plugins/flytekit-openai/flytekitplugins/openai/batch/task.py
- plugins/flytekit-openai/flytekitplugins/openai/batch/workflow.py
- plugins/flytekit-openai/flytekitplugins/openai/chatgpt/task.py
It's optional now.
chatgpt agent: unit test, local execution, and single binary remote execution
batch agent: unit test
I can't run the batch agent task in my local execution.
It will start an infinite event loop.
```python
import os
from typing import Iterator
from flytekit import Secret, workflow
from flytekit.types.file import JSONLFile
from flytekit.types.iterator import JSON
from flytekitplugins.openai import BatchResult, create_batch
def jsons():
for x in [
{
"custom_id": "request-1",
"method": "POST",
"url": "/v1/chat/completions",
"body": {
"model": "gpt-3.5-turbo",
"messages": [
{"role": "system", "content": "You are a helpful assistant."},
{"role": "user", "content": "What is 2+2?"},
],
},
},
{
"custom_id": "request-2",
"method": …
```
> Make `openai_organization` Optional in OpenAI plugins

- plugins/flytekit-spark/flytekitplugins/spark/agent.py
- plugins/flytekit-spark/flytekitplugins/spark/task.py
NA
DatabricksAgentV2 is calling the wrong parent class
Replace super(AsyncAgentBase) with super(DatabricksAgent)
remote
NA
NA
> Replace super(AsyncAgentBase) with super(DatabricksAgent)

- Dockerfile
as it is needed in order to use pod templates.
This was indirectly removed with #2455
needed to use pod templates with the official image
install kubernetes package in image
> add kubernetes package to official docker image again

- flytekit/interaction/click_types.py
- tests/flytekit/unit/interaction/test_click_types.py
Improves the Parsing system for CLI when using datetime or date
```
(flytekit) ➜  flytekit git:(cli-date-support) ✗ pyflyte run test.py foo --x today                                                                                                                                                
Running Execution on local.
2024-07-21
```
```
(flytekit) ➜  flytekit git:(cli-date-support) ✗ pyflyte run test.py foo --x "today + 10d"                                                                                                                                         
Running Execution on local.
2024-07-31
```
```
(flytekit) ➜  flytekit git:(cli-date-support) ✗ pyflyte run test.py foo --x now …
```
> Improved date parsing in CLI with meta variables

- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/agent.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/task.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/workflow.py
- plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
- plugins/flytekit-aws-sagemaker/tests/test_inference_agent.py
- plugins/flytekit-aws-sagemaker/tests/test_inference_task.py
- To return the relevant outputs and discard the irrelevant entries from the output dictionary. 
- To make specifying the idempotence token optional in the config and delegate the heavy lifting to the plugin.
This PR truncates the SageMaker agent outputs to only return the ARNs. It also adds a new `idempotence_token` parameter to the `create_sagemaker_deployment` function, which, when set to `True`, appends an idempotence token to the relevant fields.
I've run the example locally. New output format: `[{'ModelArn': 'arn:aws:sagemaker:us-east-2:123456789:model/stable-diffusion-model-0b2634d258f999f6'}, {'EndpointConfigArn': 'arn:aws:sagemaker:us-east-2:123456789:endpoint-config/stable-diffusion-model-5825e66eb1014642'}, {'EndpointArn': …
> truncate sagemaker agent outputs and automate idempotence token handling

- flytekit/core/array_node_map_task.py
- tests/flytekit/unit/core/test_array_node_map_task.py
fixes: https://linear.app/unionai/issue/COR-1565/problem-with-array-node-map-tasks-and-gpu-accelerators-pod-toleration
gpu_accelerator is not set for tasks that are subtasks of ArrayNodes 
(also impacts legacy map tasks - if we want to fix that too)
Return the underlying python function task's extended resources to be set when serializing an array node map task
- added unit test
Confirmed that the GPU Accelerator was set under the task's extended resources
```
from flytekit import Resources, task, workflow, map_task
from flytekit.extras.accelerators import T4, V100, L4, GPUAccelerator
@task(
limits=Resources(gpu="1"),
interruptible=False,
accelerator=GPUAccelerator("nvidia-l4"),
)
def with_defined_gpu_accelerator_l4(input: str) -> str:
return f"Hello {input}!"
@workflow
def wf() -> str: …
```
> [BUG] support setting extended resources for array node map tasks

- flytekit/core/interface.py
- tests/flytekit/unit/core/test_interface.py
NA
Got the below error
```
│   397 │   │   outputs[k] = v  # type: ignore                                                     │
│   398 │   inputs: Dict[str, Tuple[Type, Any]] = OrderedDict()                                    │
│                                                                                                  │
│ /Users/kevin/git/flytekit/flytekit/core/interface.py:515 in extract_return_annotation            │
│                                                                                                  │
│   512 │   ):  # type: ignore                                                                     │
│   513 │   │   # isinstance / issubclass does not work for Namedtuple.                            │
│   514 │   │   # Options 1 and 2 …
```
> refactor(core): Enhance return type extraction logic

- flytekit/clients/grpc_utils/auth_interceptor.py
Flytekit's grpc client for flyteadmin has a grpc channel interceptor for lazy authentication which does the following:
```py
class AuthUnaryInterceptor(grpc.UnaryUnaryClientInterceptor, grpc.UnaryStreamClientInterceptor):
...
def intercept_unary_unary(...):
"""
Intercepts unary calls and adds auth metadata if available. On Unauthenticated, resets the token and refreshes
and then retries with the new token
"""
...
fut: grpc.Future = continuation(updated_call_details, request)
e = fut.exception()
if e:
if e.code() == grpc.StatusCode.UNAUTHENTICATED ...:
self._authenticator.refresh_credentials()
...
return continuation(updated_call_details, request)
```
1. Try request without refreshing credentials
2. If this fails (401), refresh credentials
3. Try again
---
Since …
> Fix: Properly re-raise non-grpc exceptions during refreshing of proxy-auth credentials in auth interceptor

- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_mixin.py
- plugins/flytekit-aws-sagemaker/tests/test_boto3_mixin.py
To validate the idempotence token length in subsequent tasks in the SageMaker workflow.
- Updates helper method in the mixin file to truncate idempotence token when the length exceeds 63.
- Adds additional test cases.
Triggered a SageMaker deployment workflow locally.
> validate idempotence token length in subsequent tasks

- flytekit/extras/accelerators.py
The suffix `-vws` in the definition of the L4 gpu accelerator causes some confusion. According to google cloud [docs](https://cloud.google.com/compute/docs/gpus#l4-gpus), we can specify either `nvidia-l4` or `nvidia-l4-vws` to use L4 GPUs.
Rename the existing `L4` constant to `L4_VWS` just to be safe and define a new `L4` gpu accelerator with the value set to `nvidia-l4`.
> Add nvidia-l4 gpu accelerator

- flytekit/clis/sdk_in_container/run.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
This change is necessary to enable sending an iterator as a default workflow input. Without this change, the iterator is iterated over twice, resulting in an `iterator is empty` error during literal conversion.
Added a conditional to skip selecting the default value when the type is `Iterator[JSON]` and the entity is a workflow. This bug in iterator/openai batch agent, introduced in flytekit 1.13.0, was caused by https://github.com/flyteorg/flytekit/pull/2525.
- Verified with OpenAI batch agent.
- Tested task and workflow with iterator as default input.
- Confirmed task and workflow with list of integers work correctly.
> eliminate redundant literal conversion for `Iterator[JSON]` type

- flytekit/core/type_engine.py
- flytekit/interaction/click_types.py
- flytekit/types/schema/types.py
- plugins/flytekit-envd/tests/test_image_spec.py
- tests/flytekit/unit/core/test_dataclass.py
- tests/flytekit/unit/interaction/test_click_types.py
If we import `FlyteSchema` when using flytekit, we don't want to import `numpy`.
We have to do it by `try ... catch`
Unit Tests, local execution and remote execution.
```python
from typing import Union, List
flytekit_hash = "8a982ccae43c2ce7e08b36af883c81eb080b9712"
flytekit = f"git+https://github.com/flyteorg/flytekit.git@{flytekit_hash}"
python_version="3.10",
packages=[flytekit],
)
@dataclass
class MyDataClass:
output_file: FlyteFile
output_directory: FlyteDirectory
def my_flyte_workflow(b: bool) -> …
```
> [FlyteSchema] Fix numpy problems

- flytekit/core/container_task.py
Closes flyteorg/flyte#5436
Added a boolean flag variable local_logs that controls if local container tasks output logs to the terminal.
> Boolean flag to show local container logs to the terminal

- plugins/flytekit-ray/flytekitplugins/ray/task.py
Today, when launching a Ray job in Flyte only the Head Node is retrieving fast register data - no applying for Ray Worker Nodes. This results in the need for the user of copy the source code into the containers working dir & rebuilding the container image for every change on the ray user code.
This PR utilizes rays functionality of adding files to the ray job on runtime passing the `runtime_env {"working_dir":"some_path"}`.
⚠️ There is an ray gcs storage limit of 500MiB. Thats why ray supports adding an `excludes` variable along with `working_dir` which functions as a .ignore file. This PR introduces a `excludes_working_dir` to the RayJobConfig, which allows control over what files to upload to the ray cluster.
- Adding `working_dir` & `excludes` init parameter when running remotely
- …
> Enable Ray Fast Register

- flytekit/core/artifact.py
- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
- tests/flytekit/unit/core/test_artifacts.py
This relates to an issue we found when using the artifact class with Elastic while also specifying partitions.
As far as I can tell, what's happening is that the kfpytorch plugin [serializes](https://github.com/flyteorg/flytekit/blob/5bc5d5c0db193fdeea1bcaa2af6ee1af2316499c/plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py#L408), using cloud pickle, and then [deserializes](https://github.com/flyteorg/flytekit/blob/5bc5d5c0db193fdeea1bcaa2af6ee1af2316499c/plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py#L276) within the worker.  Because of how cloudpickle works, this was causing an infinite recursion in the `__getattr__` call of the partitions object.  Basically the getattr function is called only if the field is missing from the object, but cloudpickle doesn't run …
> [Artifacts/Elastic] Skip partitions

- flytekit/core/artifact.py
- flytekit/core/type_engine.py
- flytekit/models/types.py
- tests/flytekit/unit/core/test_artifacts.py
Just improving the experience.
Adding  `__rich_repr__` and `_repr_html_` to TimePartition, Partition, and Partitions objects.
Also adding `__rich_repr__` to LiteralType.
Tested in jupyter locally, along with the corresponding change, it now looks like
> Richer printing for some artifact objects

- flytekit/core/data_persistence.py
- flytekit/types/directory/types.py
- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_data_persistence.py
- tests/flytekit/unit/types/directory/test_types.py
- tests/flytekit/unit/types/file/test_types.py
SE-75
Sometimes it would be nice to write to a non-default bucket from within a task. Being able to create a `new_remote` with an alt bucket provides that.
New arg to `new_remote`
unit tests
> Added alt prefix head to FlyteFile.new_remote

- flytekit/core/interface.py
- tests/flytekit/unit/core/test_workflows.py
closed https://github.com/flyteorg/flyte/issues/5608
CPython versions <3.10.10 https://github.com/python/cpython/issues/102647 in the inspect module, which causes missing source lines for certain decorated functions.
Check if function has a return value only for python >=3.10 since `inspect` doesn't work correctly in python 3.8/3.9
unit test
NA
NA
> Feature gate for FlyteMissingReturnValueException

- flytekit/clients/auth/auth_client.py
Multiprocessing in Python is a bit fraught with issues, as it requires that every dependency in the transitive dependency tree of your project supports multiprocessing. We've noticed issues with the way that this code interacts with concurrent task registration that results in trying to open multiple instances of the server, which fails due to listening on the same port.
The multiprocessing usage here didn't actually bring any real benefit, as the intended use was to simply block the requestor's control flow anyways with the use of a queue. This retains the same behavior without the use of any multiprocessing.
> Remove use of multiprocessing from the OAuth client

- .pre-commit-config.yaml
- docs/source/design/index.rst
- flytekit/clients/auth_helper.py
- flytekit/models/core/workflow.py
Use newer version of `codespell` which has an extended dictionary 
Run `make lint`
> Update codespell in precommit to version 2.3.0

- flytekit/core/interface.py
- flytekit/core/task.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/unit/core/test_imperative.py
- tests/flytekit/unit/core/test_references.py
- tests/flytekit/unit/remote/test_remote.py
https://flyte-org.slack.com/archives/CP2HDHKE1/p1722549808159589
> AttributeError: 'ReferenceTask' object has no attribute '_container_image'
reference_task should just inherit from PythonTask since it could be a reference bigquery / non python function task.
Unit test / pyflyte run
```python
import typing
from flytekit import task, workflow, reference_task, StructuredDataset
outputs = typing.NamedTuple("Outputs", results=StructuredDataset)
@reference_task(
project="flyte-conformance",
domain="development",
name="bigquery",
version="e2ZYwgh3ZzI7Q56rJjSN1g",
)
def ref_bq(version: int) -> outputs:
...
@reference_task(
project="flyte-conformance",
domain="development",
name="flytesnacks.examples.basics.basics.workflow.slope",
version="e2ZYwgh3ZzI7Q56rJjSN1g",
)
def ref_basic(x: …
```
> reference_task should inherit from PythonTask

- flytekit/extend/backend/utils.py
If we install union sdk, when using `get_agent_secret`, we will ignore the group, and right now we use `group` to retrieve the agent's secret.
> Fix Get Agent Secret Using Key

- .github/workflows/monodocs_build.yml
- flytekit/clients/raw.py
For large messages from the get data endpoint, grpc would error otherwise.
> Bump grpc receive message size

- flytekit/core/base_task.py
- flytekit/core/promise.py
- flytekit/core/type_engine.py
Related to flyteorg/flyte#5353
1. To raise `TypeTransformerFailedError` directly and provide clearer feedback on unsupported type transformations instead of internal `AttributeError` messages like `AttributeError: 'NoneType' object has no attribute 'string_value'`.
2. To validate the literal for each registered SimpleTransformer, ensuring more robust type handling.
1. Remove the try-except code block that raises an `AttributeError` when a SimpleTransformer receives an incorrect literal format.
2. Add individual checks for each SimpleTransformer currently supported by flytekit.
Executed unit tests using:
```bash
pytest /flytekit/tests/flytekit/unit/core/test_type_engine.py
```
-> No additional errors occur.
N/A
N/A
> Update error message for TypeTransformerFailedError

- flytekit/extras/tasks/shell.py
Stubbed my toe on some rather arcane behavior of `subprocess.run` so I decided to log a warning under this circumstance. More details here: https://medium.com/python-pandemonium/a-trap-of-shell-true-in-the-subprocess-module-6db7fc66cdfd
> Added warning for command list and shell true

- tests/flytekit/unit/core/test_array_node.py
We run nightly tests in all supported python versions (e.g. https://github.com/flyteorg/flytekit/actions/runs/10249523395), but tests have been failing in python 3.8. This PR fixes the remaining ones.
Use the deprecated `typing.List` to define a list. Once we [drop support for python 3.8](https://github.com/flyteorg/flyte/issues/5633) later in the year we can go back to using the native collections everywhere in the codebase.
Ran tests locally using python 3.8.
> Modify test_array_node.py to support running in python 3.8

- flytekit/core/promise.py
- tests/flytekit/unit/core/test_serialization.py
- tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
In https://github.com/flyteorg/flytekit/pull/2401 we added a check against mutable default arguments where we simply confirmed that the object was hashable. This works, but it's too restrictive as it prevents other commonly used objects (e.g. dataclasses) from being used as default values.
Even sophisticated linters like ruff only detect mutable default arguments for lists, dictionaries, and sets. For example, this sample code:
```
from mashumaro import DataClassDictMixin
@dataclass
class DC(DataClassDictMixin):
a: int
b: str
def f(dc: DC = DC(42, "43"), xs: list[int] = [1,2], d: dict[str, int] = {"abc": 42}, s: set(int) = set([1,2,3])):
...
```
returns this error in ruff:
```
❯ ruff check example
example/dc.py:9:46: B006 Do not use mutable data …
```
> Handle common cases of mutable default arguments explicitly

- flytekit/types/numpy/ndarray.py
- tests/flytekit/unit/types/numpy/test_ndarray.py
Closes flyteorg/flyte#5630
See above issue.
Code diff is minimal, changes were made in a consistent way, following code from `structured_dataset.py`, specifically the `extract_cols_and_format` function.
I only tested this with my custom setup, modifying the files in the `site-packages` in place. I'll leave proper testing up to the devs.
> allow a hash method to be present for numpy arrays

- flytekit/remote/remote.py
https://flyte-org.slack.com/archives/CP2HDHKE1/p1722624663458609
If an exception is encountered while registering tasks, continue to register launch plans/workflows if all the exceptions were just Registration Skipped.
Tested locally by recreating the community provided example.
> return exceptions when gathering

- flytekit/types/file/file.py
DOC-161 Document file and directory streaming
Corrected example code and description
> Correct FlyteFile docstring

- Dockerfile
The final docker image includes the the pip cache in `~/root/.cache/pip`
With this PR, the cache directory is removed. Container size went from `800MB` to `788MB`.
> Remove pip cache after install

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
Closes https://github.com/flyteorg/flyte/issues/5632
Validation helps users avoid common mistakes.
This PR adds validation to all `Optional[List[str]]` in `ImageSpec
Unit tests were added to this PR.
> Adds validation to image_spec for parameters that are list of strings

- plugins/flytekit-kf-mpi/flytekitplugins/kfmpi/task.py
- plugins/flytekit-kf-mpi/tests/test_mpi_task.py
The default elastic timeout to wait for worker pod to be ready is 60s https://github.com/horovod/horovod/blob/55a73d4f662bf637f6994a61f62b517ad9554dc1/horovod/runner/launch.py#L452C32-L452C51
This PR is to make it configurable
Changes:
* Increased elastic_timeout to 20 min;
* make elastic_timeout configurable by user
- [ X ] I updated the documentation accordingly.
- [ X ] All new and existing tests passed.
> Make elastic timeout configurable for HorovovJob.

- plugins/flytekit-papermill/flytekitplugins/papermill/task.py
- plugins/flytekit-papermill/tests/test_task.py
In https://github.com/flyteorg/flytekit/pull/1859/ (which was released in flytekitplugins-papermill 1.10.0) we ended up overriding the task resolver's `loader_args` method in order to generate the correct `NotebookTask` container arguments. However we never restored that function to its original value, which has the side effect that in the case of shared task resolvers (e.g. the `default_task_resolver` used for regular tasks) we end up reusing the last `NotebookTask` registered as the task name.
This PR restores the loader_args in papermill plugin's `get_container` and `get_k8s_pod`.
> Fix overriding of loader_args task resolver in papermill plugin

- flytekit/deck/renderer.py
Related to https://github.com/flyteorg/flyte/issues/5618
I think any execution in the renderer should not crash the execution. With this PR, it will always be caught.
With this PR, all exceptions are caught.
> Catch all exceptions when rendering python dependencies

- flytekit/core/launch_plan.py
- tests/flytekit/unit/core/test_references.py
NA
can not register a reference LP because it doesn't have `return` statement
```
@reference_task(
project="flyte-conformance",
domain="development",
name="flytesnacks.examples.basics.basics.workflow.slope",
version="e2ZYwgh3ZzI7Q56rJjSN1g",
)
def ref_basic(x: typing.List[int], y: typing.List[int]) -> float:
...
```
Don't check the return statement for reference_launch_plan
unit test/pyflyte run
NA
NA
> Don't check the return statement for reference_launch_plan

- flytekit/image_spec/default_builder.py
Small adjustments to the default image builder to extend support for prerelease wheels.
The changes are:
- Add `UV_LINK_MODE=copy` which removes a warning from `uv`. In a docker env, it needs to copy over files from the uv cache into the image.
- `UV_PRERELEASE=allow` allows for prerelease builds to be included.
- Change the environment name to "runtime".
I ran:
```bash
export _FLYTEKIT_TEST_DEFAULT_BUILDER=1
pytest tests/flytekit/unit/core/image_spec/test_default_builder.py::test_build
```
and also ran workflows with the builder.
> Update env variables and runtime name for default image buidler

- flytekit/clis/sdk_in_container/run.py
- flytekit/remote/remote.py
- flytekit/tools/script_mode.py
- tests/flytekit/unit/tools/test_script_mode.py
Related to https://github.com/flyteorg/flyte/issues/5343
Currently, `pyflyte run` requires `--copy-all` when the workflow imports files from other directories. This is a common gotcha because `pyflyte run workflow.py` works, but `pyflyte run --remote workflow.py` does not.
With this PR:
- We look at all the modules in `sys.modules` and copy over all files that are necessary for the workflow to run.
- This way `pyflyte run --remote workflow.py` will work out of the box most of the time.
- Less copying than `--copy-all` because it only copies over the required files. If you have a project with tests or docs, it will not be copied.
I think the new coping mechanism does what `copy_module_to_destination` does, but I did not want to adjust it just in case I break anything. I added a new …
> Copy user files that were imported by workflow in pyflyte run

- flytekit/clis/sdk_in_container/run.py
- flytekit/core/interface.py
- tests/flytekit/unit/core/test_interface.py
https://github.com/flyteorg/flyte/issues/5640
Click does not support uppercase in option names: https://github.com/pallets/click/issues/837
This causes an unintuitive error in flytekit when uppercase is used in task input names:
```
$ pyflyte run --remote wf.py wf --A 1
Failed with Unknown Exception <class 'flytekit.core.type_engine.TypeTransformerFailedError'>
Reason: Python value cannot be None, expected <class 'int'>/<FlyteLiteral(LiteralType) simple: INTEGER>
```
This PR aims to improve the error message. A long-term fix might be to support uppercase in workflow input names, but this seems to be incompatible with the click.Option implementation. Lowercase+snake_case is a convention that click aims to follow.
Add validation against the workflow input names to ensure it is lowercase. …
> [fix] Validate workflow input name is lowercase

- flytekit/image_spec/default_builder.py
The `micromamba` lock file may cause install to stall and wait a long time. This can happen when one quits a image build and the lockfile from the previous run is left in the cache. The default image builder uses a shared=locked, which means the cache is already locked. This means we do not need micromamba specific lock files.
Use `micromamba config set use_lockfiles False` to disable micromamba lock fiels.
Ran an image builder and works.
> Do not use micromamba lockfiles

- flytekit/core/data_persistence.py
- flytekit/exceptions/user.py
- flytekit/tools/fast_registration.py
- tests/flytekit/unit/core/test_checkpoint.py
If data stored in S3 bucket is deleted, we want flytekit to handle not found error in a more explicit and self-descriptive way.
Tested against local sandbox setup and got following task output
```python
[1/1] currentAttempt done. Last Error: USER::
[al2j8c22ppzrgd924jqk-n0-0] terminated with exit code (1). Reason [Error]. Message: 
in fun
return caller(func, *(extras + args), **kw)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/flytekit/flytekit/core/data_persistence.py", line 122, in retry_request
raise e
File "/flytekit/flytekit/core/data_persistence.py", line 115, in retry_request
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/flytekit/flytekit/core/data_persistence.py", line 303, in get
raise FlyteDataNotFoundException(from_path) …
```
> Return explicit task execution code not found

- flytekit/bin/entrypoint.py
- flytekit/clients/auth/auth_client.py
- flytekit/core/array_node.py
- flytekit/core/base_sql_task.py
- flytekit/core/base_task.py
- flytekit/core/class_based_resolver.py
- flytekit/core/node_creation.py
- flytekit/core/promise.py
- flytekit/core/python_auto_container.py
- flytekit/core/python_function_task.py
- flytekit/core/reference_entity.py
- flytekit/core/testing.py
- flytekit/core/workflow.py
- flytekit/extras/tasks/shell.py
- flytekit/remote/remote.py
- flytekit/tools/subprocess.py
- flytekit/tools/translator.py
- plugins/flytekit-airflow/flytekitplugins/airflow/task.py
- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/agent.py
- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
NA
We raise `Exception` in many places, which does not allow users to catch specific errors from Flytekit."
```python
try:
...
except RuntimeError:
...
except ValueError:
...
```
Replace `Exceptions` with specific errors
unit test
NA
NA
> Replace Exceptions with specific errors

- flytekit/image_spec/default_builder.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
Related to https://github.com/flyteorg/flytesnacks/pull/1721
The default builder is not following `FLYTE_PUSH_IMAGE_SPEC`, so it'll end up pushing the image in the flytesnacks repo.
This PR enables the default image builder to use `FLYTE_PUSH_IMAGE_SPEC`.
A nit test was added to this PR
> Follow FLYTE_PUSH_IMAGE_SPEC in default image builder

- Dockerfile
- Dockerfile.agent
- Dockerfile.dev
Warning are annoying and eventually lead to errors. Better to nip them in the bud.
Here's how they manifest in the agent dockerfile:
```
❯ docker --debug build -f Dockerfile.agent . --build-arg VERSION=1.13.2
...
4 warnings found:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
The 'as' keyword should match the case of the 'from' keyword
More info: https://docs.docker.com/go/dockerfile/rule/from-as-casing/
Dockerfile.agent:1
--------------------
1 | >>> FROM python:3.10-slim-bookworm as agent-slim
2 |
3 |     MAINTAINER Flyte Team <users@flyte.org>
--------------------
- MaintainerDeprecated: Maintainer instruction is deprecated in favor of using label (line 3)
The MAINTAINER instruction is deprecated, use a label instead to define an image author
More info: …
```
> Fix docker warnings

- flytekit/image_spec/default_builder.py
On master, the UV install command runs before the `ENV` is set. 
This PR moves `ENV` before the UV command runs.
I ran pytest with `_FLYTEKIT_TEST_DEFAULT_BUILDER=1`.
> Move UV install to after the ENV is set

- flytekit/core/node_creation.py
- flytekit/core/promise.py
- flytekit/core/python_function_task.py
NA
Got below error when running the dynamic task
```python
{"asctime": "2024-06-24 17:21:38,715", "name": "flytekit", "levelname": "ERROR", "message": "You are not supposed to nest @Task/@Workflow inside a @Task!", "taskName": null}
{"asctime": "2024-06-24 17:21:38,716", "name": "flytekit", "levelname": "ERROR", "message": "You are not supposed to nest @Task/@Workflow inside a @Task!", "taskName": null}
{"asctime": "2024-06-24 17:21:38,716", "name": "flytekit", "levelname": "ERROR", "message": "You are not supposed to nest @Task/@Workflow inside a @Task!", "taskName": null}
{"asctime": "2024-06-24 17:21:38,716", "name": "flytekit", "levelname": "ERROR", "message": "You are not supposed to nest @Task/@Workflow inside a @Task!", "taskName": null}
{"asctime": "2024-06-24 17:21:38,717", …
```
> Remove false error inside dynamic task in local executions

- plugins/flytekit-duckdb/flytekitplugins/duckdb/task.py
On `main`, the `duckdb` connection is created during registration time.
This moves the duckdb connection to happen during execution time.
The current unit test covers the functionality.
> Create duckdb connection during execution

- flytekit/clients/auth/auth_client.py
Related: https://github.com/flyteorg/flytekit/pull/2626
The AuthorizationClient may need to pop up a webbrowser for human interaction to auth, and may do so from multiple threads and multiple grpcio channels. This manifested for us in race conditions during `pyflyte register` because it uses concurrent registration https://github.com/flyteorg/flytekit/blob/1cc2b110806f7cf16cd2cf404e04538b97ac1a7f/flytekit/tools/repo.py#L310-L311
We block all threads and allow a single request through for authorization and cache that result for a short window to make sure that we don't need a separate request per-thread, and avoid the race condition on setting up the local HTTP server for handling the redirect.
Lots of calls to pyflyte register in a repository with a large number of workflows.
> Fix race conditions in the Authentication client

- flytekit/clients/friendly.py
- flytekit/clients/grpc_utils/wrap_exception_interceptor.py
- flytekit/clis/sdk_in_container/utils.py
- flytekit/exceptions/system.py
NA
The error message is not clear.
Add a new exception (FlyteSystemUnavailableException). flytekit will raise this exception when the cluster is not available.
pyflyte register without running a cluster locally
Before
After:
NA
NA
> Improve error message for get signed url failure

- flytekit/core/workflow.py
- flytekit/exceptions/user.py
- tests/flytekit/unit/core/test_type_hints.py
NA
The error message is not clear enough.
```
/Users/kevin/git/flytekit/flytekit/core/promise.py:1213 in flyte_entity_call_handler             │
│                                                                                                  │
│   1210 │   # Make sure arguments are part of interface                                           │
│   1211 │   for k, v in kwargs.items():                                                           │
│   1212 │   │   if k not in entity.python_interface.inputs:                                       │
│ ❱ 1213 │   │   │   raise AssertionError(f"Received unexpected keyword argument '{k}' in functio  │
│   1214 │                                                                                         │
│   1215 │   # Check if we have more arguments …
```
> Better error message for FailureNodeInputMismatch error

- flytekit/image_spec/default_builder.py
Using the prerelease flag will instead prerelease versions by default, which is unexpected. If users want to use prerelease builds they can set `ImageSpec(env=dict(UV_PRERELEASE="allow"))`.
This PR removes the option.
I ran image builder with this change.
> Remove prerelease flag with uv in image builder

- flytekit/core/array_node_map_task.py
- tests/flytekit/unit/core/test_array_node_map_task.py
Map node array tasks allow mapping a `@task` over a list of inputs. They do not support `@dynamic` or `@eager` tasks though.
However, using unsupported task types is not being caught during registration.
* Detect when a user tries to map an `@eager` or `@dynamic` task
* Add a unit test that would have caught this bug
> Fix: Catch unsupported node types in map node array task

- plugins/flytekit-k8s-pod/README.md
- plugins/flytekit-k8s-pod/flytekitplugins/pod/__init__.py
The pod plugin functionality has been in the core task code for a while now.  Users no longer need this plugin.
Add a deprecation notice to the init file and readme.
> Deprecation notice for pod plugin

- Dockerfile.dev
We stopped setting PYTHONPATH in the dev image in https://github.com/flyteorg/flytekit/pull/2673, but that broke integration tests because `flytekit` and can no longer be found (consequently the integration tests modules shipped alongside flytekit can't be found).
Add `/flytekit` back to PYTHONPATH in dev image.
I also took the time and removed the deprecated pod plugin from the image.
> Fix integration tests

- flytekit/image_spec/default_builder.py
`pip_extra_index_url` was added in https://github.com/flyteorg/flytekit/pull/2636, but the warning was not removed.
This PR adds `pip_extra_index_url` as a supported option.
Ran image builder with no warning.
> Add pip_extra_index_url as a supported parameter in default builder

- plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py
- plugins/flytekit-polars/setup.py
- plugins/flytekit-polars/tests/test_polars_plugin_sd.py
1. `polars.DataFrame.describe()` is not recommended to be used programmatically as suggested by [Polars's official documentation](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.describe.html), causing the behavior difference in different `polars` version.
2. `frame_equal()` is renamed to `equals()` in version [0.19.16](https://github.com/pola-rs/polars/releases/tag/py-0.19.16)
1. Use `to_pandas()` directly.
2. I changed it into another testing function [polars.testing.assert_frame_equal](https://docs.pola.rs/api/python/stable/reference/api/polars.testing.assert_frame_equal.html).
> remove upper bound of plugin dependencies for flytekit-polars

- flytekit/image_spec/image_spec.py
ImageSpec builders currently do not support pushing images to repositories on Harbor. For new repositories (i.e. ones that do not exist yet on the registry), the `APIError` except block in `ImageSpec.exist` only checks for 404 errors before returning `False`. However, unlike other registries such as GitLab's, Harbor raises a 500 error not a 404. Therefore, the existence check fails and returns `None` which leads `ImageSpec` to conclude that the image should not be built.
In `ImageSpec.exist` I added an additional check after the 404 status code check that compares the error's explanation against a simple regex pattern aligned with what Harbor produces in this case. If there is a match, then the method returns `False`. 
Utilizing an on-prem Harbor instance, I first attempted to run …
> fix: cover 500 errors for new Harbor repos

- tests/flytekit/unit/configuration/test_file.py
https://github.com/flyteorg/flyte/issues/5687
The `get_config_file` will check some default paths if the function's input is `None`, while the assert function in the unit test didn't consider it. This will not throw errors in Github actions since it is building a clean environment, but when developers test it locally, it often throws errors.
Check the path in the unit-test.
```
make unit_test
```
Run it locally
I'll open another PR to fix the other 2 unit tests.
https://github.com/flyteorg/flytekit/pull/2706
https://github.com/flyteorg/flytekit/pull/2707
> Fix local test `test_get_config_file` fail

- tests/flytekit/unit/cli/pyflyte/test_register.py
https://github.com/flyteorg/flyte/issues/5687
`FlytekitPlugin.get_remote(None, ...)` will call `get_config_file` if the first argument is `None`.
As described in https://github.com/flyteorg/flytekit/pull/2705, `get_config_file` will not always return `None` in developers' local environments.
Add a mock function that forces the return value of `get_config_file` to `None`.
```
make unit_test
```
Run it locally
I'll open other PRs to fix the other 2 unit tests.
https://github.com/flyteorg/flytekit/pull/2705
https://github.com/flyteorg/flytekit/pull/2707
> Fix local test `test_get_remote` fail

- tests/flytekit/unit/cli/pyflyte/test_register.py
https://github.com/flyteorg/flyte/issues/5687
`get_and_save_remote_with_click_context(...)` will call `get_remote(cfg_file_location, ...)`, which will call `get_config_file` if the first argument is `None`.
As described in https://github.com/flyteorg/flytekit/pull/2705, `get_config_file` will not always return `None` in developers' local environments.
Add a mock function that forces the return value of `get_config_file` to `None`.
```
make unit_test
```
Run it locally
I'll open other PRs to fix the other 2 unit tests.
https://github.com/flyteorg/flytekit/pull/2705
https://github.com/flyteorg/flytekit/pull/2706
> Fix local test `test_saving_remote` fail

- flytekit/types/schema/types.py
Given that NumPy is not a dependency for `flytekit`, this warning will always show up with the default `flytekit` install.
This PR changes the logger to use `debug` instead.
> Use logger.debug when numpy is not found

- .github/workflows/pythonbuild.yml
- plugins/flytekit-neptune/README.md
- plugins/flytekit-neptune/flytekitplugins/neptune/__init__.py
- plugins/flytekit-neptune/flytekitplugins/neptune/tracking.py
- plugins/flytekit-neptune/setup.py
- plugins/flytekit-neptune/tests/test_neptune_init_run.py
This PR adds a [Neptune.ai](https://neptune.ai/) plugin for experiment tracking. This is similar to the Comet and Weights & Biases plugin. 
This PR adds a `neptune_init_run` decorator that starts a Neptune Run. Given the Neptune integration with third party libraries passes the `run` object around, this PR injects the `neptune_run` object into `current_context()`.
This PR includes unit tests. I also ran the example in https://github.com/flyteorg/flytesnacks/pull/1723:
[
](https://github.com/flyteorg/flytesnacks/pull/1723)
> Adds neptune plugin for experiment tracking

- flytekit/clients/friendly.py
- flytekit/remote/remote.py
Launch plans are not included in closures fetched from Admin because they always refer to and are defined by the ones in Admin.  When FlyteRemote scans for launch plan definitions, it should scan for both the primary as well as any subworkflows.
In addition to the primary workflow template, also check subworkflow templates.
* Also add an lru cache to the get launch plan/wf/task call in the friendly clients, ideally we go through all the friendly client functions and cache all the ones that make sense to, but this determination should be done in a separate pr.
* Note that the lru cache does not cache exceptions, so if the underlying entity is missing, it will not be cached.
Tested against a live control plane.
> [Remote] check subworkflows for launch plan nodes

- flytekit/models/common.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_promise.py
- tests/flytekit/unit/core/test_type_hints.py
- tests/flytekit/unit/models/test_common.py
Improves jupyter repr for `flytekit.models`.
This PR adds a `_repr_html_` that generically renders any `flytekit.model`. Internally it uses `_repr_idl_yaml_like` that renders any flyteidl as a yaml like repr.
I added a simple unit test.
> Improve jupyter repr and `__repr__` for Flyte models

- flytekit/clis/sdk_in_container/run.py
- flytekit/exceptions/user.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
NA
error message is not clear for users
Improve error message for entity not found in flytekit cli
```bash
pyflyte -vv run --remote flyte-example/getting_started.py wf1
```
Before:
After:
NA
NA
> Improve error message for entity not found in flytekit cli

- plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py
- plugins/flytekit-polars/tests/test_polars_plugin_sd.py
Fixes https://github.com/flyteorg/flyte/issues/5678
The flytekit plugin for polars only supports `polars.DataFrame`. Many polars users rely on the `LazyFrame` API to make data handling more memory efficient.
This PR:
- Adds and registers a `LazyFrame` encoder/decoder to the `StructuredDataset` type.
Unit tests run on CI.
> Polars lazyframe

- plugins/flytekit-greatexpectations/setup.py
Fixes CI issue with a breaking change in great expectations 1.0.0.
> Provide upper bound to great expectations

- flytekit/bin/entrypoint.py
- flytekit/clis/sdk_in_container/serialize.py
- flytekit/core/array_node_map_task.py
- flytekit/core/base_task.py
- flytekit/core/legacy_map_task.py
- flytekit/core/promise.py
- flytekit/core/python_function_task.py
- flytekit/core/type_engine.py
- flytekit/core/workflow.py
- flytekit/exceptions/scopes.py
- flytekit/exceptions/user.py
- flytekit/extend/backend/base_agent.py
- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
- plugins/flytekit-pandera/tests/test_plugin.py
- tests/flytekit/conftest.py
- tests/flytekit/unit/bin/test_python_entrypoint.py
- tests/flytekit/unit/conftest.py
- tests/flytekit/unit/core/test_conditions.py
- tests/flytekit/unit/core/test_dynamic.py
- tests/flytekit/unit/core/test_type_hints.py
- tests/flytekit/unit/core/test_workflows.py
NA
Error messages are not clear in both remote and local execution.
- Add `FlyteUserRuntimeException`. it is thrown when a user code raises an exception.
- Non-FlyteUserRuntimeException errros are system errors
- remove `system_entry_point` and `user_entry_point` in the code
- deprecate FlyteScopedException
unit test / remote
```python
new_flytekit = "git+https://github.com/flyteorg/flytekit@14ab38ca17d3b9a5bb70e5ae9a61955b01f573e4"
sd_finetuning_image = ImageSpec(
packages=[
new_flytekit,
],
builder="envd",
)
@task(enable_deck=True, container_image=sd_finetuning_image)
raise ValueError("error")
return a + 1
@workflow
def wf() -> int:
return t1(a=3)
```
Before:
- User error
- …
> Deprecate scopes

- plugins/flytekit-duckdb/flytekitplugins/duckdb/__init__.py
- plugins/flytekit-duckdb/flytekitplugins/duckdb/task.py
- plugins/flytekit-duckdb/tests/test_task.py
We would like to integrate motherduck support with the current duckdb plugin such that a `DuckDBQuery` can query the motherduck data warehouse and/or in memory files at the same time.
Simply add a connection to motherduck and authenticate via a secret. `duckdb` handles the rest.
Tested on a motherduck free trial with a combinarion query like:
```
"""
WITH db1 AS (
SELECT
SUM(a) AS sum_a,
FROM mydf
),
db2 AS (
SELECT
MEAN(trip_time) AS mean_tt
FROM sample_data.nyc.rideshare
)
SELECT
db1.sum_a + db2.mean_tt AS total_sum,
FROM db1, db2;
"""
```
> add motherduck support for duckdb plugin

- flytekit/remote/remote.py
NA
Failed to run backfill command
```bash
│    785 │   │   │   │   identifiers_or_exceptions.append(                                         │
│ ❱  786 │   │   │   │   │   self.raw_register(cp_entity, serialization_settings, version, og_ent  │
│    787 │   │   │   │   )                                                                         │
│    788 │   │   │   except RegistrationSkipped as e:                                              │
│    789 │   │   │   │   logger.info(f"Skipping registration... {e}")                              │
│                                                                                                  │
│ /Users/kevin/git/flytekit/flytekit/remote/remote.py:661 in raw_register                          │
│ …
```
> Fix backfill command

- flytekit/bin/entrypoint.py
- flytekit/experimental/eager_function.py
Currently, the `@eager` workflows are too strict with its handling of the client secret values. Both secret group and key need to be specified for the secret request to be passed down to the underlying task. There is also an issue with the async event loop not being available for the downstream data persistence step in the task execution.
This PR loosens this requirement to be compatible with Flyte backends that do not require secret groups. This PR also:
- Allows the user to bind the client secret to an environment variable in cases where the `FlyteRemote` object can authenticate with just the client secret
- Makes sure that an async loop is available for downstream data persistence step in the task execution
The following workflow was tested on flyte sandbox
```python
from flytekit …
```
> Update eager: make sure client secret can be specified as env var

- docs/source/design/clis.rst
- flytekit/tools/fast_registration.py
In an (admittedly large) repository, fast registration has become quite slow for us. The culprit appears to be the compression of the code tarball which I have observed to take up to a minute. (I'm already ignoring non-relevant parts of the code base using a `.flyteignore`.)
In the fast package helper, where we currently compress the code tarball using cpython's `gzip`, I propose to check whether the user has [`pigz`](https://zlib.net/pigz/) installed and if yes, leverage it to speed up the compression.
In our case, I'm seeing a speedup from ~60s to ~1-2s.
I expect that the majority of users will not run into these performance issues but for those that might, I propose to add a log message with a hint to install `pigz` in case the default compression mechanism takes to long.
I see that …
> Feat: Optionally use pigz to speed up tarball compression

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
NA
If the base image is an ImageSpec, the flytekit image builder pushes the image to an unexpected place because the tag is not calculated based on the image spec's name.
use the name of base ImageSpec to calculate the tag.
```python
image_sklearn = ImageSpec(
packages=["scikit-learn"],
registry="ghcr.io/unionai",
name="flyte-conformance",
)
image_tensorflow = ImageSpec(
base_image=image_sklearn,
packages=["tensorflow"],
registry="ghcr.io/unionai",
name="flyte-conformance",
)
@task(container_image=image_sklearn)
return a + 2
@task(container_image=image_tensorflow)
def t2(a: int) -> int:
return a + 2
@workflow
def composition_image_wf(a: int = 3):
t1(a=a)
t2(a=a) …
```
> fix: Calculate the tag based on the name of the base image

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
Closes: https://github.com/flyteorg/flyte/issues/5732
Lack of thread safety in `TypeEngine.lazy_import_transformers()` can cause errors when triggering Flyte executions simultaneously from concurrent threads. 
- Add a lock to make it threadsafe. 
- I considered just moving `cls.has_lazy_import = True` to the end of the function but I decided against it for 2 reasons:
- Its possible that importing transformers twice could cause issues - though currently I don't think it does. 
- Apparently python variable assignments are not always atomic https://github.com/google/styleguide/blob/91d6e367e384b0d8aaaf7ce95029514fcdf38651/pyguide.md#218-threading - though in practice I doubt this will be a problem. 
- Write a test
Wrote a test
> GH-5732: Make `TypeEngine.lazy_import_transformers()` thread safe

- flytekit/core/tracker.py
https://github.com/flyteorg/flytekit/pull/2303#issuecomment-2322364266
1.  This change is leading to some weird behavior and I think part of it is working by coincidence. We noticed this because of a test that was failing in Pycharm but passing in CI. But you can reproduce a similar error just with pytest.
2. Cannot submit a task from the notebook after this commit
Revert some of the changes in https://github.com/flyteorg/flytekit/pull/2303
unit test
NA
NA
> Revert #2303

- docs/source/design/control_plane.rst
We would like added clarification for how to extract I/O from reference launchplans using FlyteRemote
Added an example of a reference launchplan and flyte remote usage to extract output.
Registered example, ran it and using the code in the example.
> reference lp example for flyteremote

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
> Fix Get Literal Type Error for Attribute Access Compile in Flytepropeller

- flytekit/core/type_engine.py
- flytekit/interaction/click_types.py
- tests/flytekit/unit/core/test_type_engine.py
https://github.com/flyteorg/flyte/issues/5737
Please see issue.  This only fixes the TypeEngine's assert type.  Not sure what other issues there are with generic aliases yet.  Please keep the GH issue open.
> Types/generic alias - assert fix only

- flytekit/extras/pytorch/native.py
- tests/flytekit/unit/extras/pytorch/test_transformations.py
```py
@task
def foo() -> Union[list[torch.Tensor], torch.Tensor]:
return [torch.tensor([1, 2, 3])]
@workflow
def wf():
foo()
```
This example fails with:
```console
TypeError: Failed to convert outputs of task 'wf.foo' at position 0.
Failed to convert type <class 'list'> to type typing.Union[list[torch.Tensor], torch.Tensor].
Error Message: Ambiguous choice of variant for union type.
```
The type transformer choice should, however, not be ambiguous. 
The problem arises as follows:
[Here](https://github.com/flyteorg/flytekit/blob/839f555f497c29bac6f12897697a5a93a182fc8d/flytekit/core/type_engine.py#L1526) in the `UnionTransformer` we test all union variants and raise the observed error if more than one of the union variants work.
In this case, the two union working variants are:
* Call the …
> Fix: Prevent UnionTransformer type ambiguity in combination with PyTorchTypeTransformer

- plugins/flytekit-duckdb/setup.py
Motherduck required duckdb v1.0.0 to work. Without pinning it we can install duckdb 1.1.0 which is incompatible. 
pin duckdb version in plugin
tested using the plugin after duckdb released 1.1.0
https://github.com/flyteorg/flytekit/pull/2680
> pin duckdb version in plugin

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
closes https://github.com/flyteorg/flyte/issues/5689
It's better to check if the registry name is valid or not before building and pushing it.
validate the name in `__post__init__`
unit test
```
registry="localhost:30000/UNIONAI",
packages=["pandas"],
builder="default"
)
@task(enable_deck=True, container_image=image_spec)
return a + 1
@workflow()
def wf() -> int:
return t1(a=3)
```
Before:
After:
NA
NA
> feat(image_spec): validate container registry names

- plugins/flytekit-inference/flytekitplugins/inference/ollama/serve.py
- plugins/flytekit-inference/flytekitplugins/inference/sidecar_template.py
To prevent this error from occurring: `failed quota: project-quota: must specify limits.cpu for: input-downloader; limits.memory for: input-downloader` error.
This PR adds resources to the input downloader init container, without which it results in `failed quota: project-quota: must specify limits.cpu for: input-downloader; limits.memory for: input-downloader` error.
On a prod cluster.
> add resources to input downloader in the ollama plugin

- plugins/flytekit-identity-aware-proxy/flytekitplugins/identity_aware_proxy/cli.py
The cli `flyte-iap` provided by [`flytekitplugins-identity-aware-proxy`](https://pypi.org/project/flytekitplugins-identity-aware-proxy/) can be used by `flytekit` and `flytectl` as a so-called `proxyCommand` to generate a token sent as `proxy-authorization` header to a flyteadmin protected by [GCP Identity Aware Proxy](https://cloud.google.com/security/products/iap). See original [issue](https://github.com/flyteorg/flyte/issues/3965).
We currently don't catch when users try to generate a token for a service account when logged in with their user account.
This PR catches this and raises an actionable error.
> Fix: Make  flyte-iap catch when trying to generate token for service account from user credentials

- flytekit/core/array_node.py
- flytekit/core/promise.py
- tests/flytekit/unit/core/test_array_node.py
- tests/flytekit/unit/core/test_promise.py
fixes: https://linear.app/unionai/issue/COR-1822/mapping-over-launch-plans-w-default-inputs-doesnt-compile
Compiling a workflow fails when evaluating an ArrayNode that maps over a LaunchPlan contains a default input. This occurs since we don't set the input bindings for the node.
https://github.com/unionai/flyte/blob/926cadac9a8cf406b85c8e7443668a13a3f60dfe/flytepropeller/pkg/compiler/validators/interface.go#L76-L86
Get errors such as:
```
pyflyte run --remote tests/flytekit/integration/map_ref_lp.py map_regression_line_wf
Running Execution on Remote.
Request rejected by the API, due to Invalid input.
RPC Failed, with Status: StatusCode.INVALID_ARGUMENT
details: failed to compile workflow for [resource_type:WORKFLOW project:"flytesnacks" domain:"development" …
```
> [Bug] Set bindings for ArrayNode

- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
- plugins/flytekit-bigquery/flytekitplugins/bigquery/agent.py
- plugins/flytekit-bigquery/tests/test_agent.py
- plugins/flytekit-openai/flytekitplugins/openai/batch/agent.py
- plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py
[https://github.com/flyteorg/flyte/issues/3936](https://github.com/flyteorg/flyte/issues/3936)
When users trace the code, they tend to follow patterns we use in Flytekit's agent. By allowing them to use `dict` instead of `LiteralMap`, we can improve their development experience. This way, they don't need to understand the details of how `LiteralMap` works or what a literal is.
In the agent's `get` request:
**Before:**
- Returns a `LiteralMap`.
**After:**
- Returns a `dict`.
Note: We will automatically handle the conversion from `dict` to `LiteralMap` for the user.
- In local execution: 
[flytekit base_agent.py](https://github.com/flyteorg/flytekit/blob/9bce7c37e950d33688820849b127d1b8ee8af7aa/flytekit/extend/backend/base_agent.py#L315-L316)
- In remote execution: 
[flytekit …
> [flyteagent] All agents return dict instead of literal map

- flytekit/clis/sdk_in_container/run.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
- tests/flytekit/unit/cli/pyflyte/workflow.py
Closes [flyteorg/flyte#999](https://github.com/flyteorg/flyte/issues/5768)
The current boolean parsing behaviour is confusing for default True arguments. 
Add `--no_...` and `--no-...` variants for boolean flags as per the recommendation at https://click.palletsprojects.com/en/8.1.x/options/#boolean-flags
Wrote new unit tests to cover it.
> GH-5768: Better pyflyte boolean parsing

- plugins/flytekit-perian/flytekitplugins/perian_job/agent.py
This fixes a bug in how the agent read secrets using the Flyte API.
* Use the correct `key` parameter for `secrets.get`
* Add secrets the to the `secrets` parameter sent to PERIAN API to handle them as secrets properly.
Manually tested
https://github.com/flyteorg/flytekit/pull/2537
> Fix reading Flyte secrets and using PERIAN secrets param

- .github/workflows/pythonbuild.yml
- Dockerfile.dev
- dev-requirements.in
- dev-requirements.txt
- plugins/flytekit-deck-standard/README.md
- plugins/flytekit-deck-standard/dev-requirements.in
- plugins/flytekit-deck-standard/flytekitplugins/deck/__init__.py
- plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py
- plugins/flytekit-deck-standard/setup.py
- [ydata-profiling](https://github.com/ydataai/ydata-profiling/issues/1510) is supported now!
- pillow is added because we have [Image renderer](https://docs.flyte.org/en/latest/user_guide/development_lifecycle/decks.html#image-renderer)
(We need `PIL` module for image renderer)
1. add 2 requirements in `flytekit-deck-standard`, `ydata-profiling` and `pillow`.
2. remove `exclude flytekit-deck-standard in python 3.12 CI`
local execution and remote execution
- code: [all examples from flytesnacks](https://docs.flyte.org/en/latest/user_guide/development_lifecycle/decks.html#image-renderer)
- python: 3.12.4 
- flytekit: this branch
```python
from flytekit.deck.renderer import MarkdownRenderer
from sklearn.decomposition import PCA …
```
> [Flyte Decks] support ydata-profiling in python 3.12

- flytekit/clis/sdk_in_container/package.py
- flytekit/clis/sdk_in_container/register.py
- flytekit/clis/sdk_in_container/run.py
- flytekit/remote/remote.py
- flytekit/tools/fast_registration.py
- flytekit/tools/repo.py
This is the last of a series of PRs to clean up the fast register switches in the various `pyflyte` commands.  The main change was https://github.com/flyteorg/flytekit/pull/2690
This PR changes the default behavior for fast registration (invoked by `run`, `register`, and `package` to use the [new logic](https://github.com/flyteorg/flytekit/blob/fb55841f8660b2a31e99381dd06e42f8cd22758e/flytekit/tools/fast_registration.py#L116) instead.  Previously if the `--copy` command was not specified, the old logic was still used.  Only the `serialize` command after this PR will use the old logic.
* Change messaging, exception raising, and defaults to trigger the new logic.
Locally tested and local executions run.
https://github.com/flyteorg/flytekit/pull/2690 …
> Update pyflyte defaults to use --copy behavior

- flytekit/bin/entrypoint.py
- flytekit/core/tracker.py
- flytekit/tools/script_mode.py
- plugins/flytekit-spark/Dockerfile
- plugins/flytekit-spark/flytekitplugins/spark/task.py
- plugins/flytekit-spark/setup.py
- plugins/flytekit-spark/tests/test_spark_task.py
- tests/flytekit/unit/bin/test_python_entrypoint.py
NA
When we fast-register a Spark task, we will always get a `module not found` error in the Spark executors.
Archive the current directory into a zip file and send it to the spark executor. Exectors will load the module from that zip file.
```
pyflyte run --remote fast_spark.py my_spark
```
```python
import datetime
import random
from operator import add
from flytekitplugins.spark import Spark
from long_description import hello  # local module 
from misc.ignore_pattens import hello123  # local module
flytekit_hash = "be5d8eac263fc8e5d57de110f9648b696d48f20d"
new_flytekit = f"git+https://github.com/flyteorg/flytekit@{flytekit_hash}"
spark_plugins = f"git+https://github.com/flyteorg/flytekit.git@{flytekit_hash}#subdire …
```
> Enable Spark Fast Register

- flytekit/extend/backend/agent_service.py
- flytekit/extend/backend/base_agent.py
- tests/flytekit/unit/extend/test_agent.py
See also https://github.com/flyteorg/flyte/pull/5391
- The agent defines a Resource return type with values:
* outputs
* message
* log_links
* phase
These are all a part of the underlying protobuf contract defined in
flyteidl.
However, the message field custom_info from the protobuf is not here
google.protobuf.Struct custom_info
https://github.com/flyteorg/flyte/blob/519080b6e4e53fc0e216b5715ad9b5b5270f35c0/flyteidl/protos/flyteidl/admin/agent.proto#L140
This field was added in https://github.com/flyteorg/flyte/pull/4874
but never made it into the corresponding flytekit PR
https://github.com/flyteorg/flytekit/pull/2146
- It's useful for agents to return additional metadata about the job,
and it looks like custom_info is the intended location
- Make a minor refactor to how the agent …
> Propagate custom_info Dict through agent Resource

- plugins/flytekit-spark/tests/test_spark_task.py
NA
To fix the spark unit test
Mock addPyFile since the CI machine doesn't seem to have enough disk space
related issue: https://stackoverflow.com/a/25707870/9574775
unit test
NA
NA
> Mock addPyFile in spark test

- flytekit/remote/remote.py
- tests/flytekit/unit/remote/test_remote.py
One should be able to utilize `--copy-all` via `FlyteRemote.fast_register_workflow`
I expose `--copy-all` to fast-registration.
> enabled copy-all for programmatic fast-registration via FlyteRemote

- flytekit/tools/script_mode.py
When writing a workflow from the root `flytekit` directory, the flytekit is automatically picked up and bundled it during fast registration. This upload is incomplete because `flytekit` depends on `flytekit.bin.entrypoints`, which is not imported by the workflow but required by the workflow to work. When this partial copy of `flytekit` is copied into `/root`, then will look for `flytekit.bin.entrypoints` here first, but it does not exist.
With this PR, any files that share the root with `flytekit` will not be uploaded.
Create a workflow in the root directory and run `pyflyte run --remote`.
> Do not copy flytekit itself during fast registration

- flytekit/models/literals.py
This allows type-checkers like Pyright to properly type-check the constructors of these types.
Add `Optional[...]` to constructor arguments that default to `None`.
CI + Local type-checking using VS Code and Pyright.
> Add correct types to `Scalar` and `Primitive` constructors in `literals.py`

- flytekit/bin/entrypoint.py
- tests/flytekit/unit/experimental/test_eager_workflows.py
The `entrypoint._dispatch_execute` function used `asyncio.run` to run the coroutine. The problem with this is that it closes the event loop, which cause the following error related to task data persistence:
```
[1/1] currentAttempt done. Last Error: USER::
[ajwx7zsjbghhfzhpzhnv-f4usdeia-0] terminated with exit code (1). Reason [Error]. Message: 
micromamba/envs/runtime/bin/pyflyte-execute", line 8, in <module>
sys.exit(execute_task_cmd())
^^^^^^^^^^^^^^^^^^
File "/opt/micromamba/envs/runtime/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/micromamba/envs/runtime/lib/python3.11/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File …
```
> eager workflow: use event loop instead of asyncio.run

- flytekit/core/base_task.py
- flytekit/core/context_manager.py
- flytekit/core/promise.py
- flytekit/core/type_engine.py
- flytekit/utils/async_utils.py
- plugins/flytekit-flyteinteractive/tests/test_flyteinteractive_vscode.py
- tests/flytekit/unit/core/test_data.py
- tests/flytekit/unit/core/test_promise.py
- tests/flytekit/unit/core/test_type_hints.py
- tests/flytekit/unit/interactive/test_flyteinteractive_vscode.py
This is a PR into https://github.com/flyteorg/flytekit/pull/2752
Changes in this PR (move notes if merging)
* Create a new loop at module load time that is stored in the FlyteContext but is
* not started
* `asyncio.set_event_loop` is intentionally not called.
The idea here is that the loop is protected because it's stored in a contextvar and is not associated directly with the asyncio library.  However I've seen already one error associated with not calling `set_event_loop` and others may crop up.  Not sure what Jupyter is doing, but if you try to create a new loop in Jupyter, and call asyncio.set_event_loop, it doesn't actually overwrite the event loop.  If you call get_running_loop before and after set, it remains the same.  Been looking through their code but not sure how they achieved …
> wip Flyte loop in FlyteContext & multi-threaded loops

- plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py
- plugins/flytekit-deck-standard/setup.py
https://github.com/flyteorg/flyte/issues/5792
if we install `flytekitplugins-deck-standard` and `flytekit`, when import `flyetkit`, it will raise an error about `ModuleNotFoundError` or `ImportError`
1. add double quotes for `pandas` in `pd.DataFrame` type hint.
2. use `import plotly.express as px` in the function `to_html` for each class instead of using lazy import, since lazy import will require user to install `plotly`.
```python
pip list | grep -iE "flyte|panda|mark|plotly|pillow|ydata|pygment"
flyteidl                                 1.13.5.dev12+gc0fc6d463             /Users/future-outlier/code/flyte/flyteidl
flytekit                                 1.13.6b3.dev46+gf50b1eeaa.d20240926
flytekitplugins-airflow                  0.0.0+develop …
```
> [Flyte Deck] Fix Lazy Import Error for Pandas and Plotly

- Dockerfile.agent
Agent image builds are broken since [flytekit 1.13.5](https://github.com/flyteorg/flytekit/actions/workflows/pythonpublish.yml): 
All failures related to the agent image failing to build.
Use uv to build the image, which is able to satisfy all version requirements (and it's also blazing fast).
> Use uv in agent image

- flytekit/core/array_node_map_task.py
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_array_node_map_task.py
When the input to a map task array node is offloaded literal then the current condition breaks out and fails the task.
Adds support to check for offloaded literal in array node and download the literal before the condition checks are done 
Tested this on sandbox by passing an offloaded literal to map task and using the fix from here https://github.com/flyteorg/flyte/pull/5771 and removing the input overwriting and saw flytekit correctly downloaded offloaded metadata for the passed in literal
example used here for integration test:
```
import typing
from flytekit import task, workflow, map_task
from mashumaro.mixins.json import DataClassJSONMixin
@dataclass
class InnerDC:
a: bool
b: int
c: float
d: list[int]
e: …
```
> Fix array node map task for offloaded literal

- flytekit/core/launch_plan.py
- flytekit/core/options.py
- flytekit/core/workflow.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_launch_plan.py
Close flyteorg/flyte#5774
As mentioned in the tracking issue, users need to manually adjust launch plans or toggle settings in the Flyte Console, which is prone to accidents. This PR simplifies the process by allowing labels and annotations to be defined directly in the workflow definition, reducing the need for manual interventions.
Right now, fields in the [Options](https://github.com/flyteorg/flytekit/blob/8bcb9d0cd3f2eea179dd35385bbf9ed6eebba840/flytekit/tools/translator.py#L65) class are used to set values for a LaunchPlan during registration or execution overrides. When a workflow is registered, it automatically creates a default LaunchPlan, but there is currently no way to set default values for these fields in the workflow itself. Adding this capability will allow users to …
> Support default label/annotation for the default launch plan creating from workflow definition

- flytekit/clients/friendly.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/integration/remote/workflows/basic/basic_workflow.py
This is a new API for Flyte to get the signed URL for the deck artifact.
add a method called `get_download_deck_signed_url` using the IDL `CreateDownloadLinkRequest` and `CreateDownloadLinkResponse`.
1. flyte sandbox
```python
from flytekit.clients.friendly import SynchronousFlyteClient as _SynchronousFlyteClient
from flytekit.configuration import PlatformConfig, AuthType
client = _SynchronousFlyteClient(PlatformConfig.for_endpoint("localhost:30080", True))
signed_url = client.get_download_deck_signed_url(
node_id="n1",
project="flytesnacks",
domain="development",
execution_id="awzmsq9jbjfz8p6jksdg",
)
print(signed_url.signed_url)
```
- sandbox
> [FlyteClient][FlyteDeck] Get Downloaded Artifact Signed URL via Data Proxy

- README.md
The quickstart guide link is broken.
Fix the link.
Click the link.
Pending
> Fix getting started link, remove extra parenthesis

- plugins/flytekit-deck-standard/setup.py
Related to flyteorg/flyte#5805
[flytekit-deck-standard](https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-deck-standard)'s dependency is only flytekit now, however, there are some renders that require requirements and we want the user experience to be more smoothly.
For example, if you import ImageRenderer, you have to also install pillow in your Python environment.
But usually users will raise an error than know that they should install pillow.
We want the user to install flytekitplugins-deck like pip install "flytekit-deck-standard[pandas, ydata-profiling]".
I only changed the setup.py on flytekit/plugins/flytekit-deck-standard. This change enables user to have a smooth user experience for package installation. Like they can now write pip install …
> Related to flyteorg/flyte#5805 [Flyte Deck] Extras has been added

- flytekit/core/array_node_map_task.py
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_array_node_map_task.py
Bring https://github.com/flyteorg/flytekit/pull/2772 to the `release-v1.13` branch.
> Backport to v1.13 - Fix array node map task for offloaded literal (#2772)

- flytekit/core/type_engine.py
- flytekit/tools/script_mode.py
- tests/flytekit/unit/cli/pyflyte/test_script_mode.py
- tests/flytekit/unit/core/test_type_engine.py
https://github.com/flyteorg/flyte/issues/5804
Issue checking instance generics.
* Also bringing in a change from master to sort files before hashing them.
Will need to cherrypick the merge commit of this PR onto master after.
> Instance generic empty case

- tests/flytekit/unit/core/test_type_hints.py
Just adding one more unit test for pickling.
> Add unit test for pickling

- flytekit/image_spec/default_builder.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
If both `--index-url` and `--extra-index-url` are set, a space is missing between the 2, resulting in an error.
Added unit test and visualized the docker command output.
> ensure a space is added if both args are set in ImageSpec

- flytekit/clis/sdk_in_container/register.py
- flytekit/remote/remote.py
- flytekit/tools/repo.py
When entities are registered there is no helpful link to the UI like there is when entities are run. This helps users navigate to the entity in the UI after they register something in the CLI.
When registering we fetch the entity with flyte remote and then get the console url for the entity.
`union register docs_examples/flyte_file.py`
Before:
```
Successfully serialized 4 flyte objects
[✔] Registration flyte_file.t1 type TASK successful with version GxQbXiMnIdiRYRxg6I_B2Q
[✔] Registration flyte_file.t2 type TASK successful with version GxQbXiMnIdiRYRxg6I_B2Q
[✔] Registration flyte_file.wf type WORKFLOW successful with version GxQbXiMnIdiRYRxg6I_B2Q
[✔] Registration flyte_file.wf type LAUNCH_PLAN successful with version GxQbXiMnIdiRYRxg6I_B2Q
Successfully registered 4 entities
```
After: …
> add links to register

- .pre-commit-config.yaml
- flytekit/core/array_node_map_task.py
- flytekit/core/python_auto_container.py
- flytekit/core/type_engine.py
- flytekit/types/structured/structured_dataset.py
mypy 1.11.2 catches new errors in flytekit:
```
❯ make lint
mypy flytekit/core
flytekit/core/type_engine.py:439: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
flytekit/core/type_engine.py:942: error: Argument 1 to "append" of "list" has incompatible type "tuple[Any, type[Any]]"; expected "tuple[Any,
GenericAlias]"  [arg-type]
flytekit/core/type_engine.py:951: error: Argument 1 to "append" of "list" has incompatible type "tuple[Any, type[Any]]"; expected "tuple[Any, GenericAlias]"  [arg-type]
flytekit/core/type_engine.py:2166: error: Argument 1 to "append" of "list" has incompatible type "tuple[Any, type[Any]]"; expected "tuple[Any, GenericAlias]"  [arg-type]
flytekit/core/python_auto_container.py:211: error: …
```
> Fix mypy errors caught in 1.11.2

- flytekit/configuration/__init__.py
- flytekit/core/promise.py
- flytekit/core/python_auto_container.py
- flytekit/core/tracker.py
- flytekit/remote/remote.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_array_node_map_task.py
- tests/flytekit/unit/core/test_context_manager.py
- tests/flytekit/unit/core/test_promise.py
- tests/flytekit/unit/core/test_python_auto_container.py
- tests/flytekit/unit/core/test_resolver.py
- tests/flytekit/unit/test_translator.py
https://github.com/flyteorg/flytekit/pull/2733
As discussed in the comments of flyteorg/flytekit#2733, the current design of the Jupyter Notebook is not well considered.
- I updated the pickled object from entity to a dictionary of entity, where the key of the dictionary is the name of the task entity. 
Testing code is exactly the same as flyteorg/flytekit#2733
| version 1 | version 2-1 | version 2-2 (run again without modification)|
| - | - | - |
| <img width="816" alt="image" src="https://github.com/user-attachments/assets/b9c35991-ce8d-4354-9a48-046eec6b93c6"> | <img width="818" alt="image" src="https://github.com/user-attachments/assets/28d3b7e1-699a-4221-8926-766ebc7b5046"> | <img width="814" alt="image" src="https://github.com/user-attachments/assets/9ab43db0-c272-4c2c-ac2c-a6c5b3a4e …
> Revise Pickle Remote Task for Jupyter Notebook Environment

- docs/source/plugins/index.rst
- docs/source/plugins/neptune.rst
- docs/source/plugins/wandb.rst
- plugins/flytekit-neptune/flytekitplugins/neptune/__init__.py
- plugins/flytekit-wandb/flytekitplugins/wandb/__init__.py
Adds docs pages for Neptune and W&B plugins.
This is one of three PRs we need to merge in the following order to get the neptune and wandb flytekit plugin docs onto the docs site:
1. [flytesnacks PR](https://github.com/flyteorg/flytesnacks/pull/1748) to fix refs in neptune and wandb plugin docs
1. [flyte PR](https://github.com/flyteorg/flyte/pull/5842) to update monodocs dependencies
1. flytekit PR (this one) to add new flytekit plugin docs for neptune and wandb plugins (after re-running monodocs build)
> DOC-648 Add pages for Neptune and W&B plugins

- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
- plugins/flytekit-envd/tests/test_image_spec.py
Related to #2715, after adding support for extra copy commands in the default builder, we also want to extend this support to the envd builder.
When creating images with ImageSpec on a remote cluster, we may need to copy additional files or directories required during the container build process. To address this, we aim to support extra copy commands in ImageSpec for copying files and directories into the container’s `/root` directory.
1. Now we support ImageSpec with `copy` commands to be built by the envd builder.
Example Usage:
`input.txt`
```
test for document example
```
`build_image.py`
```py
from flytekit.image_spec import ImageSpec
name="envd-copy-cmds",
apt_packages=["git", "gh"], …
```
> [Flytekit] Envd builder with extra copy commands

- flytekit/clis/sdk_in_container/init.py
The docs link from `pyflyte init` is a 404!
Fix the docs link.
> Fix docs URL in pyflyte init

- flytekit/bin/entrypoint.py
- flytekit/core/constants.py
- flytekit/models/task.py
- plugins/flytekit-spark/flytekitplugins/spark/agent.py
- plugins/flytekit-spark/setup.py
- plugins/flytekit-spark/tests/test_agent.py
NA
The task status shows failed on Flyte Console, but succeeded on the Databricks UI. That's because `pyflyte-execute` always returns an exit code 0, whether the job succeeds or fails.
Set `FLYTE_FAIL_ON_ERROR` in the databricks job, and it will force flytekit to return a non-zero exit code on failure.
Run a dummy databricks task that raises an error and then check if the task fails on databricks UI.
NA
NA
> Add FLYTE_FAIL_ON_ERROR env to the databricks job

- flytekit/types/structured/bigquery.py
Closes flyteorg/flyte#3339
While `BQToPandasDecodingHandler` reads data using the `_read_from_bq` function, its current implementation only reads from a single stream (the first stream). Since we do not set the `max_stream_count` to 1, querying larger datasets causes multiple streams to be used automatically. As a result, data from other streams will not be loaded into the dataframe.
1. In the `_read_from_bq` function, we read from all streams rather than only the first stream.
1. Query large datasets with local execution. 
- `bq_test.py`
```py
from flytekit import StructuredDataset, kwtypes, task, workflow
from flytekitplugins.bigquery import BigQueryConfig, BigQueryTask
from typing_extensions import Annotated
DogeCoinDataset = Annotated[StructuredDataset, …
```
> [BUG] `BQToPandasDecodingHandler` only reads partial data when dataset > 100MB

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
fixes: https://linear.app/unionai/issue/COR-2132/launch-plan-w-union-type-param-breaks
registering a workflow fails if it contains param of type union 
```
@task
def calculate_interest(principal: int, rate: typing.Union[float, int], time: int) -> float:
return (principal * rate * time) / 12
@workflow
def interest_workflow(principal: int, rate: typing.Union[float, int], time: int) -> float:
return calculate_interest(principal=principal, rate=rate, time=time)
```
```
Request rejected by the API, due to Invalid input.
RPC Failed, with Status: StatusCode.INVALID_ARGUMENT
Details: Type mismatch for Parameter rate in default_inputs has type union_type:{variants:{simple:FLOAT  structure:{tag:"float"}}  variants:{simple:INTEGER  structure:{tag:"int"}}}, expected simple:NONE
```
This occurs due …
> [BUG] fix is_optional_type to not return true for all union types

- flytekit/bin/entrypoint.py
- tests/flytekit/unit/bin/test_python_entrypoint.py
See https://flyte-org.slack.com/archives/CP2HDHKE1/p1728515674311849
User errors that have exception chains are not reported with the full stack trace, including the causes
Fix to the stack trace exporting function.
Unit tests.
> Make sure user errors contain the entire chain of the stack trace

- flytekit/interaction/click_types.py
In case when we use a python pickle object from a local path, we have to insert the current directory as the first lookup path for importlib to work
> Supports importing modules in current path

- flytekit/core/promise.py
- tests/flytekit/unit/core/test_promise.py
https://github.com/flyteorg/flyte/issues/5856
We should support this:
```
@dataclass
class DC:
a: int
@dataclass
class DC2:
a: DC
b: int
def task_1(in1: int) -> typing.List[int]:
return list(range(max(2, in1)))
def task_2(in1: int, in2: typing.List[int]) -> int:
return in1 + sum(in2)
def task_3() -> DC2:
return DC2(a=DC(a=1), b=2)
@workflow
def my_wf(in1: int, in2: int) -> int:
a = task_1(in1=in1)
a1 = a[0]
dc = task_3()
b = task_2(in1=5, in2=[a1, dc["b"], dc.a["a"], in2])
return b
```
If the input is the list, call `resolve_attr_path_in_promise` for each element of that.
1. Run the code above locally & remotely.
2. A new unit test is added
> Enable Resolve Attr Path for List or Dict of Promise

- flytekit/interaction/click_types.py
Follow up to https://github.com/flyteorg/flytekit/pull/2830
I think it's slightly better to add the absolute path for the current working directory. Also as a maintainer, it's easier to see what the code is doing with `os.getcwd()`.
> Adds actual current working directory path

- flytekit/types/structured/structured_dataset.py
- tests/flytekit/unit/core/test_type_engine.py
Adds an error message to try to catch a common mistake users make, when they request a transformer for the `StructuredDataset` type, but just pass in the raw dataframe.
> Catch mistake in structured dataset

- flytekit/tools/fast_registration.py
Tree printing was showing duplicate roots.
Locally.
Before:
After:
> Fix tree printing

- flytekit/core/base_task.py
- tests/flytekit/unit/core/test_workflows.py
Running a task locally, if an exception is thrown that does not have args, an `IndexError: tuple index out of range` is actually thrown.
A simple example that causes the issue:
```python
@task
def task_1(val: int) -> None:
assert val > 0
```
If this assert fails and an `AssertionError` is thrown, it will not have any `args` and therefore cause the above behaviour.
Parameterized an existing test w/ more cases.
The issue was first introduced here - https://github.com/flyteorg/flytekit/pull/2671
> handle case where error may not have args

- flytekit/core/context_manager.py
- flytekit/core/task.py
- tests/flytekit/unit/core/test_context_manager.py
When running locally, it is not natural to have a `_FSEC_` prefix on your secrets.
With this PR, the `_FSPEC_` prefix is not used anymore for local execution.
I added unit tests to this PR to check the new behavior and ran this test:
```python
from flytekit import task, Secret
from flytekit import current_context
@task(
secret_requests=[Secret(key="apikey", group="mygroup")],
container_image="localhost:30000/flytekit:dev",
)
def check_secret() -> str:
ctx = current_context()
secret = ctx.secrets.get(key="apikey", group="mygroup")
return secret
```
```bash
export MYGROUP_APIKEY=my-secret
pyflyte run --remote main.py check_secret
```
> Pull secrets from environment when running locally

- flytekit/__init__.py
- flytekit/remote/remote.py
FlyteRemote, FlyteFile and FlyteDirectory are all very commonly used, but are not available as top-level imports.
This commit exposes them to the top-level of flytekit.
Additionally, it adds support for FlyteRemote classmethods. 
```python
FlyteRemote.for_endpoint
FlyteRemote.auto
FlyteRemote.for_sandbox
```
> Add top-level access to FlyteRemote, FlyteFile, and FlyteDirectory and convenience class methods for FlyteRemote

- .github/workflows/pythonbuild.yml
- tests/flytekit/unit/core/test_artifacts.py
- tests/flytekit/unit/core/test_protobuf.py
- tests/flytekit/unit/core/test_type_engine.py
https://github.com/flyteorg/flytekit/pull/2811
1. PyO3 not support pickling in Python:
As it's not currently supported by PyO3. So it's tricky to support pickling with `flyteidl_rust` exposed class.
For more details on supporting pickle serialization in PyO3, please check https://github.com/PyO3/pyo3/issues/100 (One of the oldest lasting issues..).
I decided to temporarily mark them as `flyteidl_rust` and skip these tests at first. Then @pingsutw told me is reasonable to just remove these tests because they are not used anymore like pickling `flyteidl.core.ContainerError`.
1. Remove build `vcpkg` `OpenSSL` executable in CI.
2. Remove `flyteidl.core.ContainerError` unit tests that need `pickle` protocol.
> Remove `flyteidl.core.ContainerError` tests

- flytekit/configuration/__init__.py
- tests/flytekit/unit/configuration/test_file.py
The `Config.for_endpoint` function was not respecting values passed in via a config file for the platform config, overriding it with just an endpoint and insecure setting.  If the `config_file` argument is going to be there, it should be respected.
Fixing to pull in values other than endpoint and insecure.
Unit tested.
> Config for_endpoint doesn't respect config file

- docs/source/design/control_plane.rst
Update docs for `FlyteRemote`.
`FlyteRemote` is now accessible at the top-level (`from flytekit import FlyteRemote`).
`FlyteRemote` also has several class methods (`for_endpoint`, `auto()`, and `for_sandbox`).
> update docs for FlyteRemote

- plugins/flytekit-pandera/flytekitplugins/pandera/pandas_renderer.py
- plugins/flytekit-pandera/flytekitplugins/pandera/pandas_transformer.py
https://github.com/flyteorg/flyte/issues/5882
The current deck renderer for the flytekit pandera is super basic, see [here](https://github.com/flyteorg/flytekit/blob/61b58966188d5d33bc6ab4af209f647de0b51995/plugins/flytekit-pandera/flytekitplugins/pandera/pandas_renderer.py). We could provide more value to users by showing them a more visually rich report, highlighting schema-level and data-level errors.
1. Adds `great_tables` as a dependency to the pandera flytekit plugin
2. Updates the pandera deck renderer to show a prettier data validation report:
Run the following workflow:
```python
import typing
from typing import Annotated
import json
import pandera as pa
from flytekitplugins.pandera import ValidationConfig
from …
```
> add great_tables renderer

- flytekit/remote/remote.py
- tests/flytekit/unit/remote/test_remote.py
Dynamic workflow is not supported in interactive mode now, so we should throw an error when executing workflow that contains dynamic workflow.
Create a dynamic workflow and execute it in interactive mode.
> Restrict Dynamic Workflow for Interactive Mode

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_unions.py
Backport https://github.com/flyteorg/flytekit/pull/2845/files
> Backport 2845 v1.13

- flytekit/types/directory/types.py
- flytekit/types/file/file.py
- tests/flytekit/unit/types/directory/test_types.py
- tests/flytekit/unit/types/file/test_types.py
I feel like it is verbose to get the working directory (`flytekit.current_context().working_directory`) in a task. I find myself doing this very, very frequently, primarily to write files. I use the working directory so that files won’t get written to my local working directory during local execution.
I had thought about this for a while, and the more I thought about what exactly I wanted to accomplish, I feel like it should be accomplished with a few new classmethod for `FlyteFile` / `FlyteDirectory`...
-----
This task...
```python
@task
def my_task() -> FlyteFile:
local_path = os.path.join(current_context().working_directory, "data.txt")
with open(local_path, mode="w") as file:
file.write("Here is some sample data.")
return FlyteFile(path=local_path)
```
Should ideally be replaced with …
> add class methods, unit tests for flytefile and flytedirectory

- pull_request_template.md
We use `setuptools_scm` to define the version file used to produce the flytekit wheels. Unfortunately it doesn't handle the case of multiple tags pointing to the same commit, it always picks up the earliest.
So, in order to publish 1.13.11, let's just push a no-op change to the release-v1.13 branch.
Tested it locally by doing:
```
~/repos/flytekit #v1.13.10
❯ python -m setuptools_scm
1.13.10
~/repos/flytekit #v1.13.10
❯ git tag v1.13.11
~/repos/flytekit #v1.13.11
❯ python -m setuptools_scm
1.13.10
...
~/repos/flytekit @0233cfea
❯ python -m setuptools_scm
1.13.11.dev1+g0233cfea6
~/repos/flytekit @0233cfea
❯ git tag v1.13.11
fatal: tag 'v1.13.11' already exists
~/repos/flytekit @0233cfea
❯ git tag -d v1.13.11
Deleted tag 'v1.13.11' (was 83474c67d)
~/repos/flytekit @0233cfea
❯ git tag …
```
> No-op commit to trigger new version

- flytekit/core/array_node_map_task.py
- flytekit/core/type_engine.py
- flytekit/types/pickle/__init__.py
- flytekit/types/pickle/pickle.py
- tests/flytekit/unit/core/test_array_node_map_task.py
- tests/flytekit/unit/core/test_promise.py
- tests/flytekit/unit/core/test_type_engine.py
- tests/flytekit/unit/types/pickle/test_flyte_pickle.py
Removing support for the BatchSize in the list of flyte pickle use-case.  This is a breaking change, but we think this feature was rarely used, and should be less needed now that the uploading/downloading of pickles is done through async.
> Remove pickle batching

- flytekit/core/type_engine.py
Closes flyteorg/flyte#5905
Since all Flyte types are now serializable, the current usage of the `_make_dataclass_serializable` function is unclear and may seem to be no longer necessary. Therefore, we have requested an update to the comments in this function to clarify its purpose.
1. Update the comments under the function `_make_dataclass_serializable`
2. Provide example usage on Flyte files and its lifecycle
None
```
gh pr checkout 2856
```
None
None
None
> Update comments in _make_dataclass_serializable

- flytekit/models/core/execution.py
- flytekit/remote/executions.py
- flytekit/remote/remote.py
Simplified interaction with executions from Jupyter.
1. Automatic detection of Interactive Mode / Jupyter Environment, with ability to Force disable
2. for exe = remote.execute(...)
3. Explicitly get execution url  `exe.execution_url`
4. Jupyter automatically pretty prints execution to point to URL and if failed shows error
5. Wait for execution to complete `exe = exe.wait(poll_interval=1)`
6. OR sync manually `exe.sync`
> Updated jupyter interaction

- README.md
Related to flyteorg/flyte#5894
The link here is not working, so I proposed this PR to change it.
Change the not working link to [this](https://github.com/flyteorg/flyte/issues)
flyteorg/flyte#5894
> [Docs] Flytekit README link not working in the File an Issue section

- flytekit/clis/sdk_in_container/utils.py
- flytekit/exceptions/user.py
NA
The error message is not helpful in some cases when verbosity is 0.
print the traceback by default
```python
from flytekit.configuration import Config
from flytekit.remote import FlyteRemote
remote = FlyteRemote(Config.auto(), default_project="flytesnacks", default_domain="development", interactive_mode_enabled=True)
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@8017ae825b7c4cc3913971fab5308b172370d335"
img = ImageSpec(registry="pingsutw", packages=[new_flytekit], apt_packages=["git"])
@dataclass
class MyDatclass:
id: int
name: str
age: int
@task(container_image=img)
def hello(dc: MyDatclass) -> str:
return f"Hello {dc.name}"
@workflow
def wf(dc: MyDatclass = MyDatclass(id=1, name="foo", …
```
> Show traceback by default

- flytekit/remote/remote.py
- flytekit/tools/repo.py
Follow up to https://github.com/flyteorg/flytekit/pull/2804
I do not think we should have another `generate_url_from_*` public API in `FlyteRemote`. We can add `Identifier` support into `generate_console_url`
This PR adds identity support to `generate_console_url`.
Ran `pyflyte register` and returned the correct URLs.
> Support Identifier in generate_console_url

- flytekit/core/array_node.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_array_node.py
fixes: https://linear.app/unionai/issue/COR-2090/enable-caching-when-mapping-over-launchplans
with_overrides doesn't work for array node. 
solution:
`map_task(my_wf_lp)(a=[1, 2, 3], b=[4, 5, 6]).with_overrides(cache=True, cache_version="3.0")`
overrides node metadata for the node that encompasses the array node. This is then copied down into the array node's subnode causing for the node metadata to then be utilized when the nodes are executed. Note, the parent node's node metadata isn't utilized in propeller.
```
class NodeMetadata(_common.FlyteIdlEntity):
def __init__(
self,
name,
timeout=None,
retries=None,
interruptible: typing.Optional[bool] = None,
cacheable: typing.Optional[bool] = None,
cache_version: typing.Optional[str] = None,
cache_serializable: typing.Optional[bool] = None, …
```
> Support overriding node metadata for array node

- flytekit/remote/executions.py
- flytekit/remote/remote.py
- flytekit/remote/remote_callable.py
This adds native capability of retrieving outputs in the right type - for example a dataframe or a tensor as the notebook remembers the original interface.
For example if you have a method that produces a dataframe
it can be directly accessed in correct type - it is also possible to retrieve it as another type like - polars dataframe etc
and can be passed to a downstream function
> improved output handling in notebooks

- flytekit/remote/remote.py
- tests/flytekit/unit/remote/test_remote.py
https://github.com/flyteorg/flyte/issues/5907
Eager task is not supported in interactive mode now, so we should throw an error when executing workflow that contains eager task.
Throw an error if an entity is a eager task during interactive mode
Unit test & test run
https://github.com/flyteorg/flytekit/pull/2849
> Restrict Eager Task for Interactive Mode

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_enum_type.py
Follow up on: https://github.com/flyteorg/flytekit/pull/2845
Python versions less than 3.12 don't support using `in` with an `Enum` ([link](https://docs.python.org/3/library/enum.html#enum.EnumType.__contains__)).
> Changed in version 3.12: Before Python 3.12, a TypeError is raised if a non-Enum-member is used in a containment check. 
As a result, the linked previous PR results in a `Reason unsupported operand type(s) for 'in': 'str' and 'EnumType'` error.
Rather than checking the python version, just convert the enum items to a list and use `in` from there.
```
from enum import Enum
class Color(Enum):
RED = 'red'
GREEN = 'green'
BLUE = 'blue'
@task
def my_task(c: Color) -> Color:
print(c)
return c
@workflow
def wf(c: Color) -> Color:
return …
```
> fix enum type assertion with python versions less than 3.12

- flytekit/core/python_auto_container.py
- flytekit/remote/executions.py
- flytekit/remote/remote.py
- tests/flytekit/unit/core/test_resolver.py
- tests/flytekit/unit/remote/test_remote.py
https://github.com/flyteorg/flyte/issues/5907
In the Jupyter Notebook environment, we are using `cloudpickle` to package the entity at the binary level. When we load the pickled object with a different Python version, it will throw an unexpected error. Therefore, we should restrict loading pickled objects with the mismatched Python version.
Let's assume the Python version for the pickled object is X. 
1. If we load it in a Python version smaller than X, it is possible to crash. Therefore, we need to handle loading exceptions.
2. If we successfully load the object, we need to check whether the Python version is matched. I added a new metadata in the pickled object to store the Python version when pickling, and this will be used for validation after loading.
3. Enable logging error messages …
> Restrict Python Version Mismatch between Pickled Object and Remote Envrionment

- flytekit/core/python_auto_container.py
It's useful to the know the unpickled object and its type when loading the task with the default notebook task resolver. This just eases the debugging experience.
Updates the error message when the unpickled file is of the unexpected type.
> Default nb task resolver msg

- flytekit/bin/entrypoint.py
Backport https://github.com/flyteorg/flytekit/pull/2901
> Map/setup exec (#2898)

- flytekit/clients/friendly.py
- flytekit/clis/sdk_in_container/pyflyte.py
- tests/flytekit/integration/remote/test_remote.py
https://github.com/flyteorg/flyte/issues/5318
https://hackmd.io/@Future-Outlier/B1lBcbRgJe
This is a part of the gate feature by backend version checking.
add a method `get_control_plane_version` in `class SynchronousFlyteClient(_RawSynchronousFlyteClient)`.
local and integration test.
```python
from flytekit.configuration import PlatformConfig
from flytekit.clients.friendly import SynchronousFlyteClient as _SynchronousFlyteClient
config = PlatformConfig(endpoint="localhost:30080", insecure=True)
client = _SynchronousFlyteClient(config)
print("Control Plane Version:", client.get_control_plane_version())
```
Unknown version
Know Version
> [Client API] Get Control Plane Version

- flytekit/__init__.py
- flytekit/remote/remote.py
> Add top-level access to FlyteRemote, FlyteFile, and FlyteDirectory and convenience class methods for FlyteRemote (#2836)

- flytekit/image_spec/default_builder.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
Related to https://github.com/flyteorg/flyte/issues/5597
It's hard to use `uv` in `commands`. With this PR, using `uv` targets the install python environment and it's simple to use. For example, we can now write:
```python
name="myimage",
packages=["numpy"],
commands=["uv pip install scikit-learn"],
)
```
With this PR the `run_commands` automatically mounts the 
I ran the following workflow:
```python
name="myimage",
packages=["scikit-learn"],
pip_extra_index_url=[
"https://pypi.anaconda.org/scientific-python-nightly-wheels/simple"
],
env={"UV_PRERELEASE": "allow"},
)
def sklearn_version() -> str:
import …
```
> Make it easier to use commands with uv

- flytekit/interactive/vscode_lib/decorator.py
- plugins/flytekit-flyteinteractive/flytekitplugins/flyteinteractive/vscode_lib/decorator.py
- plugins/flytekit-flyteinteractive/tests/test_flyteinteractive_vscode.py
- tests/flytekit/unit/interactive/test_flyteinteractive_vscode.py
NA
When we resume the task in the vscode, it will send a `SIGTERM` to flytekit (main process), then flytekit will [kill](https://github.com/flyteorg/flytekit/blob/5bf0acd22623f02293a75d41952dd4ec26e025ae/flytekit/interactive/vscode_lib/decorator.py#L61) the vscode server. However, if the main process is down for some reason, the VSCode server won't shut down even if we resume the task.
Kill the vscode server itself when resuming the task.
```python
from union.actor import ActorEnvironment
from flytekit import logger
from flytekit.interactive import vscode
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@3a9afb1a88753fe3c783da91fc501b8fc7838fb8"
image_spec = ImageSpec(name="actor", registry="pingsutw", packages=["panda", …
```
> Kill the vscode server itself when resume the task

- pyproject.toml
https://github.com/flyteorg/flyte/issues/5962
As mentioned in https://github.com/pallets/click/issues/824, disabling live logs "fixes" the issue.
Disable [pytest live logs](https://docs.pytest.org/en/stable/how-to/logging.html#live-logs).
Stdout is still captured in case of failures, we just don't get the outputs as they are being written to console.
> Disable pytest live logs

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_dataclass.py
- tests/flytekit/unit/core/test_flytetypes.py
- tests/flytekit/unit/core/test_type_engine.py
Closes flyteorg/flyte#5910
While converting dataclasses from Python types to literal types through the `to_literal` function, the dataclass will pass through the `_make_dataclass_serializable` function to ensure it can be serialized later. For dataclasses with `Union` properties, under the `if UnionTransformer.is_optional_type(python_type):` statement, it uses `get_args(python_type)[0]` as the type of the property without verifying its compatibility. This will cause an error if the first argument is not the expected type.
1. Do typing matching instead of using the first type from `get_args(python_type)`
2. Add unit tests for more possible union types
1. Run on local and remote execution
- Union[None, FlyteFile]
`flytefile_serialize.py`
```py
from flytekit …
```
> Type Mismatching while Serializing Dataclass with Union 

- tests/flytekit/unit/types/directory/test_dir.py
[The unit test](https://github.com/flyteorg/flytekit/blob/master/tests/flytekit/unit/types/directory/test_dir.py) used in [this pr](https://github.com/flyteorg/flytekit/pull/2881) creates two temporary directories that won't be cleaned up after the test is passed, just shown as follows:
Automatically clean up all temporary directories after the test is passed, which is implemented with `@pytest.fixture`. Following demonstrates the result:
Pass unit test locally.
git clone https://github.com/flyteorg/flytekit.git
gh pr checkout 2917
make setup && pip install -e .
[flyteorg/flytekit#2881](https://github.com/flyteorg/flytekit/pull/2881)
> [Test] Cleanup tmp dirs in test dir

- tests/flytekit/unit/types/directory/test_dir.py
Remove temporary directories after the unit test is passed in a neat way.
Use context manager to support automatic temporary directory cleanup on the completion of the context. The test result is shown as follows:
Pass unit test locally.
[flyteorg/flytekit#2881](https://github.com/flyteorg/flytekit/pull/2881) & [flyteorg/flytekit#2917](https://github.com/flyteorg/flytekit/pull/2917)
> [Test] Use context manager for auto tmp dirs cleanup

- flytekit/core/container_task.py
- tests/flytekit/unit/core/test_local_raw_container.py
https://github.com/flyteorg/flyte/issues/5929
To make copilot task local execution syntax aligned with remote execution and avoid the not expected behaviors.
For flyte directory and flyte file,
make /var/inputs work and make "{{.inputs.inputs}}" doesn't.
- Assertion Error: Raised when using {{.inputs.inputs}} with FlyteFile and FlyteDirectory.
- Successful Run: Indicates the expected behavior when valid commands are provided.
https://github.com/flyteorg/flytekit/pull/2258
https://github.com/flyteorg/flyte/pull/5715
> Make Flytefile and Flytedirectory's copilot local execution work correctly

- flytekit/image_spec/default_builder.py
For macOS using Rosetta, sometimes installing `ca-certificates` or running `update-ca-certificates` can run into errors.
1. With this PR, we copy over the certificates from the `micromamba` image, which avoids installing `ca-certificate` and running `update-ca-certificates` all together.
2. Without the apt command + `update-ca-certifcates` the builds are faster.
I ran a simple script with the sandbox:
```python
name="flytekit-check-2",
packages=["numpy"],
)
def wow() -> float:
import numpy as np
return np.ones((30, 10)).sum().item()
```
> Copy ca-certificates from micromamba

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
Closes flyteorg/flyte#5988
When using strings as input for `FlyteTypes`, we need to convert them into `FlyteTypes` within the `_make_dataclass_serializable` function. However, this function currently fails for Union types that include a `FlyteType` alongside other non-None variants.
1. Modify the if statement to handle Union types with non-None variants for `FlyteTypes` as well
1. Test simple example on local and remote
```py
from typing import Union
from flytekit.image_spec import ImageSpec
flytekit_hash = "d4171c3cd79ed406988d4213e4e79ee2b0bd2a93"
flytekit = f"git+https://github.com/mao3267/flytekit.git@{flytekit_hash}"
name="serialize-union-1", …
```
> [Flytekit][BUG] Failed to serialize FlyteTypes within Union alongside other non-None variants

- flytekit/models/task.py
- plugins/flytekit-ray/flytekitplugins/ray/models.py
- plugins/flytekit-ray/flytekitplugins/ray/task.py
- plugins/flytekit-ray/setup.py
- plugins/flytekit-ray/tests/test_ray.py
Related to https://github.com/flyteorg/flyte/issues/5666
These changes update the flytekit-ray package such that users can configure pod specs for worker and head workloads. 
Updating the version of flyteidl and plumb k8s pods through worker and head config. 
See unit tests.
https://github.com/flyteorg/flyte/pull/5933
> Decouple ray submitter, worker, and head resources

- flytekit/clis/version.py
- tests/flytekit/integration/clis/test_version.py
Closes flyteorg/flyte#5984
When users run `pyflyte info`, they currently can't see the backend version of flyteadmin. This information is crucial for debugging and understanding the environment setup. Adding the Flyte Backend Version to the output will make it easier for users to:
1. Verify their backend version
2. Debug version-specific issues
3. Ensure compatibility between their client and server
The following changes have been made to enhance the `pyflyte info` command:
1. Added a new line `Flyte Backend Version: [cyan]{backend_version}[reset]` to the CLI output
2. Integrated with the Flyte Remote API to fetch the backend version using `remote.client.get_control_plane_version()`
3. Updated the info command's content template to display the backend version between Flytekit Version and …
> Add Flyte Backend Version to pyflyte info command

- tests/flytekit/unit/interaction/test_click_types.py
While developing another feature using Python 3.11.5, I ran `make test`, which resulted in the following error:
According to the [Python Docs](https://docs.python.org/3/library/tempfile.html), the `delete_on_close` parameter was introduced in version 3.12.
Originally:
```python
@pytest.mark.skipif(
sys.version_info < (3, 10), reason="handling for windows is nicer with delete_on_close, which doesn't exist in 3.9"
)
```
After changes:
```python
@pytest.mark.skipif(
sys.version_info < (3, 12), reason="handling for windows is nicer with delete_on_close, which doesn't exist before 3.12"
)
```
This change ensures compatibility by updating the condition to skip tests for Python versions earlier than 3.12, where delete_on_close is unavailable.
Run `make test`
> Update pytest skip condition for delete_on_close to Python 3.12

- flytekit/core/promise.py
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_generic_idl_protobuf_struct.py
Closes [flyteorg/flyte#5959](https://github.com/flyteorg/flyte/issues/5959).
When resolving the protobuf struct with the attribute path, the return values can be of type `google.protobuf.struct_pb2.Struct` or `google.protobuf.struct_pb2.ListValue`. However, `ProtobufTransformer` doesn't support converting `ListValue` to flyte `Literal`, as can be seen [here](https://github.com/flyteorg/flytekit/blob/6e4e53bb89debbeef764d3a0a16e499e0bcd18e2/flytekit/core/type_engine.py#L907-L913).
Support `ListValue` conversion from a protobuf to a flyte `Literal` following the [logic of remote execution](https://github.com/flyteorg/flyte/blob/a87585ab7cbb6a047c76d994b3f127c4210070fd/flytepropeller/pkg/controller/nodes/attr_path_resolver.go#L72-L106).
Local test in the PR, …
> [BUG] Convert protobuf to literal as remote exec

- flytekit/image_spec/image_spec.py
Related to flyteorg/flytekit#2696
The prior fix only addressed the scenario where an entire image repo did not exist on the registry. This adds coverage for when the repo exists, but the tag is missing.
Modify the regular expression that I had added on the prior PR.
Same as flyteorg/flytekit#2696
> fix: catch API errors for tags as well as whole image repos

- flytekit/image_spec/default_builder.py
Currently, the copy command happens before the `commands`. I think it's normal to want to run commands assuming that the files you copied over are available:
```python
copy=["dist/my-fun-wheel.whl"],
commands=["uv pip install /root/dist/my-fun-wheel.whl"],
)
```
This PR moves the copy command above the custom run command.
I ran the above with a custom wheel.
> Move copy up in image spec

- flytekit/bin/entrypoint.py
- flytekit/core/task.py
- flytekit/core/workflow.py
- flytekit/interaction/string_literals.py
- flytekit/models/literals.py
- flytekit/utils/pbhash.py
- tests/flytekit/unit/bin/test_python_entrypoint.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
- tests/flytekit/unit/utils/test_pbhash.py
RFC https://github.com/flyteorg/flyte/pull/5103
Backport https://github.com/flyteorg/flytekit/pull/2872 to release-v1.13 branch. Going out in flytekit 1.13.14.
> Offload literals (#2872)

- flytekit/clients/auth/auth_client.py
- flytekit/clients/auth/authenticator.py
- flytekit/clients/auth/keyring.py
- flytekit/clients/auth/token_client.py
- tests/flytekit/unit/clients/auth/test_authenticator.py
- tests/flytekit/unit/clients/auth/test_token_client.py
Closes flyteorg/flyte#6044
Device flow auth did not support refresh tokens which makes the pyflyte user experience less enjoyable since you may need to login often. 
Passes along the refresh token from the token response to the code which writes it to the keyring. Also updates the device flow authenticator to attempt to refresh the access token.
Unit tests as well as in our production environment.
> Add support for refresh_token to device flow auth

- tests/flytekit/unit/bin/test_python_entrypoint.py
None
While running CI tests locally, it turns out that the time from `datatime.now()` is not using UTC timezone, causing errors while comparing current time and error time.
1. Set the timezone to UTC using monkeypatch.
1. Using `make unit_test` to make sure all existing tests pass.
```
git clone https://github.com/flytorg/flytekit.git
gh pr checkout 2952
pip install -e .
```
None
None
> [BUG] Timezone difference in error timestamp unit tests

- plugins/flytekit-spark/flytekitplugins/spark/task.py
- plugins/flytekit-spark/tests/test_spark_task.py
NA
flytekit overwrites the `default_executor_path` when the base_image of ImageSpec is None.
When running two Spark tasks in a workflow, flytekit overwrites the `default_executor_path` only for the first task. This happens because flytekit modifies the base_image of the imageSpec during the compilation of the first task. As a result, when compiling the second task, the base_image is no longer None, preventing Flytekit from overwriting the default_executor_path for the second task.
Deep copy the image spec and modify it.
```python
import datetime
import random
import time
from operator import add
from flytekitplugins.spark import Spark
custom_image = ImageSpec(registry="ghcr.io/flyteorg", …
```
> The container image of spark task should be immutable

- flytekit/core/type_engine.py
This change replaces a print statement with logger.debug to improve logging practices in the codebase.
The changes involve:
1. Removing the line:
`print(f"Current type {get_args(python_type)[i]} old res {res_type}")`
2. Replacing it with:
`logger.debug(f"Current type {get_args(python_type)[i]} old res {res_type}")`
No testing was performed as this is a minimal-risk change from print statement to logger.debug. Will add tests if needed - please let me know.
> chore: Replace print statement with logger.debug in type_engine.py

- flytekit/core/type_engine.py
- pyproject.toml
- tests/flytekit/unit/core/test_type_engine.py
- tests/flytekit/unit/core/test_unions.py
Related to flyteorg/flyte#5986
After mashumaro release version `3.15`, it supports messagepack robust decoding with the correct type in Union. Therefore, we would like to add a unit test to show it works. Also, we should fix errors to support changes in mashumaro to version `3.15`.
1. Update the unit test for dataclass in Union to include more than two non-None variants.
2. Fix bugs while generating attribute list from `dataclass_json` in `generate_attribute_list_from_dataclass_json` function.
- Initially, we thought we should use `additionalProperties` to generate dataclass properties. However, both dataclass and dictionary type can have an `additionalProperties` field. This mismatch causes the bug of generating an incorrect attribute list for dictionaries.
1. Passing existing and …
> [Bug][TypeEngine] Unit tests for dataclass in union with more than two non-None variants

- flytekit/types/structured/structured_dataset.py
Closes [flyteorg/flyte#5956](https://github.com/flyteorg/flyte/issues/5956).
For a flyte task with python `StructuredDataset` as an input from `dataclass` attribute access (i.e., `dc.sd`), it fails to convert the task output `LiteralMap` back to flyte idl. On the highest level, the process of calling `_dispatch_execute` ([here](https://github.com/flyteorg/flytekit/blob/master/flytekit/bin/entrypoint.py#L134)) is illustrated as follows:
As can be observed, the problem (marked as orange) occurs when the input `LiteralMap` is converted to python natives, during which a `Literal` is built with python native `StructuredDataset`, instead of using the correct `literals.StructuredDataset` (please refer to this [code snippet](https://github.com/flyteorg/flytekit/blob/2e40e76d8a5614a7eedcac8399ca877 …
> [BUG] Use models literal StructuredDataset to enable sd bypass task

- flytekit/core/launch_plan.py
- flytekit/models/launch_plan.py
- flytekit/remote/remote.py
- flytekit/tools/repo.py
- flytekit/tools/translator.py
- tests/flytekit/unit/remote/test_remote.py
This PR supports automatically activating any launchplan within the python sdk, as long as it is marked so. This will use a secondary api call, so this is not atomic and may need to be retried.
```python
example_launch_plan = LaunchPlan.get_or_create(
name="talk-every-minute",
workflow=talker,
default_inputs={"name": "Flyte"},
schedule=CronSchedule(
schedule="* * * * *",  # Following schedule runs every min
kickoff_time_input_arg="t",
),
)
example_2 = LaunchPlan.get_or_create(
name="talk-every-hour",
workflow=talker,
default_inputs={"name": "Hello"},
schedule=CronSchedule(
schedule="* 1 * * *",  # Following schedule runs every min
kickoff_time_input_arg="t",
),
auto_activate=True,
)
```
In the above example using
```bash
pyflyte register
```
Only the `talk-every-hour` launchplan will be …
> Auto activating launchplans that have been marked to be auto activated

- pyproject.toml
Related to https://github.com/flyteorg/flyte/issues/6082
As explained in the issue, those two versions of grpcio cause unwanted output and pollute the result of `pyflyte` commands.
> Skip grpcio versions due to unwanted output

- flytekit/core/array_node_map_task.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_array_node_map_task.py
fixes: https://linear.app/unionai/issue/COR-2212/[bug]-setting-task-metadata-for-the-parent-array-node-causes-incorrect
Right now metadata such as task timeout is set on the ArrayNode instead of just the subnode. This causes issues as we add support for sub node timeouts as the timeout that is intended for the subnode is also applied to the parent node.
Set metadata only for the subnode
- added unit test
```
@task(timeout=timedelta(seconds=30))
def do_thing(t: int) -> str:
sleep(15)
return str(t)
@workflow
def wf():
map_task(do_thing, concurrency=1)(t=[1, 2, 3])
```
https://github.com/flyteorg/flyte/pull/6054
> Set map task metadata only for subnode

- flytekit/tools/fast_registration.py
- tests/flytekit/unit/tools/test_fast_registration.py
N/A
Unix Domain Sockets are not copyable
Skip socket files during fast registration.
Unit tests and local sandbox.
> Skip socket files during fast registration

- flytekit/core/constants.py
- flytekit/core/type_engine.py
- flytekit/extras/pydantic_transformer/transformer.py
- flytekit/models/annotation.py
- tests/flytekit/unit/core/test_generice_idl_type_engine.py
- tests/flytekit/unit/core/test_serialization.py
- tests/flytekit/unit/core/test_type_engine.py
- tests/flytekit/unit/extras/pydantic_transformer/test_pydantic_basemodel_transformer.py
https://linear.app/unionai/issue/DX-1202/add-cacke-key-attributes-to-typeannotation
This is the flytekit PR mentioned in https://github.com/flyteorg/flyte/pull/6078.
We introduce a top-level dictionary to `TypeAnnotation` under a special key called `cache-key-metadata`. 
The three transformers that produce msgpack-binary idl literals (i.e. `DictTransformer`, `DataclassTransformer`, and `PydanticTransformer`) will now emit a `TypeAnnotation` that contains that special key.
unit tests and sandbox.
> Add cache key metadata

- flytekit/tools/script_mode.py
- tests/flytekit/unit/tools/test_script_mode.py
Follow up to https://github.com/flyteorg/flytekit/pull/2980, but this time we not only skip socket files from the digest calculation but we also do not copy them to the tar file.
Skip Unix Domain Files
Unit tests and local sandbox. Pass `--copy all` to `pyflyte run` and verified that it succeeds:
```
❯ pyflyte run --remote --copy all workflows/example.py wf
```
> Follow up to 2980 - Do not copy socket files

- dev-requirements.in
Removing master idl install - contributors can install this if they so choose but I've found it causes conflicts sometimes.
> remove master idl

- flytekit/core/type_engine.py
- flytekit/lazy_import/lazy_module.py
- flytekit/types/structured/__init__.py
- flytekit/types/structured/structured_dataset.py
- tests/flytekit/unit/core/test_generice_idl_type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
- tests/flytekit/unit/lazy_module/test_lazy_module.py
- tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
closed https://github.com/flyteorg/flyte/issues/6046
We always import pandas by default if it's installed.
Fix the is_imported function to return False if the module is lazily imported
```
pyflyte run --remote flyte-example/lazy_import_wf.py wf
```
```python
from flytekit.lazy_import.lazy_module import is_imported
from flytekit import lazy_module
old_image_spec = ImageSpec(registry="ghcr.io/flyteorg", packages=["pyarrow", "pandas", "scikit-learn", "torch"], apt_packages=["git"])
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@6874a02bd1be5359079c443992ca1202ead98d16"
new_image_spec = ImageSpec(registry="ghcr.io/flyteorg", packages=["pyarrow", "pandas", "scikit-learn", "torch", new_flytekit], apt_packages=["git"]) …
```
> Fix lazy import

- plugins/flytekit-dbt/setup.py
GitHub Actions with Python 3.9 will break when running dbt tests.
Due to compatibility issues encountered when running dbt tests on Python 3.9, we need to adjust the version ranges of the dependent packages and add networkx.
why we need the networkx ?
Because the error in GitHub Actions indicates that when `import dbt` is executed, an ImportError occurred during the import of networkx. The specific reason is that networkx attempted to execute from fractions import gcd, which failed because fractions.gcd was removed in Python 3.9. 
```
Traceback (most recent call last):\n  File "/opt/hostedtoolcache/Python/3.9.20/x64/bin/dbt", line 5, in <module>\n    from dbt.main import main\n  File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/site-packages/dbt/main.py", line 25, in <module>\n …
```
> fix: dbt-test

- flytekit/core/array_node_map_task.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_array_node_map_task.py
Backport https://github.com/flyteorg/flytekit/pull/2979.
> Backport to v1.13 - Set map task metadata only for subnode

- flytekit/remote/remote.py
- tests/flytekit/unit/remote/test_remote.py
Closes flyteorg/flyte#5989
To fix directly registering tasks that use `node_dependency_hints` pointing to a workflow. 
Make `FlyteRemote._serialize_and_register` always return the remote version of the provided `entity` regardless of whether it happens to be the last entity to be registered.  
Wrote a new unittest
`node_dependency_hints` were introduced by https://github.com/flyteorg/flytekit/pull/2015
> GH-5989: Fix task registration with `node_dependency_hints`

- plugins/flytekit-inference/flytekitplugins/inference/ollama/serve.py
Must pin Ollama, as versions >= 0.4.0 result in an 'invalid digest' error due to this [issue](https://github.com/ollama/ollama-python/pull/277#discussion_r1882162770).
Pinned the Ollama version in the create model container.
> pin ollama version

- flytekit/core/data_persistence.py
- plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py
- plugins/flytekit-polars/tests/test_polars_plugin_sd.py
- tests/flytekit/unit/core/test_data_persistence.py
Syntax was always wrong.  This is not how open_async is used.
See https://github.com/fsspec/s3fs/issues/871, which may be resolved [here](https://github.com/fsspec/s3fs/pull/885).
This also affected polars.  In testing, noticed part of the logic was incorrect - updated and added a test to exercise.
Replace with a normal call - this means that writes for bytes and bytes-like objects will be blocking.  Given this seems to be fundamentally missing from fsspec at this time I think it's okay.
Unit tested and local sandbox.
> Remove open_async usage in put raw data

- .github/workflows/pythonbuild.yml
In https://github.com/flyteorg/flyte/pull/5947 we stopped emitting the config the storage section to instruct clients to use the minio credentials. This was released in flytectl 0.9.3 (which was yanked due in https://github.com/flyteorg/flyte/pull/6100) and present in 0.9.4.
We specify environment variables to instruct the flytekit boto client to hit minio.
Ran tests locally.
> Specify minio env vars in integration tests

- flytekit/clis/flyte_cli/main.py
- flytekit/configuration/__init__.py
- flytekit/extras/accelerators.py
Broken links in docstrings and comments end up surfacing in docs
These needed to be corrected
Links were fixed
Links were tested manually
> Correct links that end up surfacing in docs

- .github/workflows/pythonbuild.yml
- .github/workflows/pythonpublish.yml
- Dockerfile.agent
We're installing potentially incompatible grpcio dependencies in the flyetagent image.
Installs all dependencies in a single invocation of `uv pip install` in the flyetagent image. We also add a test at publish-time to confirm that agents can start.
Local builds.
> Unify dependencies in agent image

- flytekit/tools/ignore.py
flytekit's `GitIgnore` performs a recursive file check to detect empty / ignored folders instead of checking the folder status directly. For folders with a lot of files (e.g. a python `.venv`), this can be unnecessarily slow.
An extreme example with 1M files in an ignored folder:
```sh
Old ignore folder: 5.39s
New ignore folder: 0.000158s
```
<details>
<summary>Code</summary>
The measurements were created using this script
```py
import subprocess
import shutil
from pathlib import Path
import os
import logging
from flytekit.tools.ignore import (
GitIgnore as GitIgnoreOld,
Ignore,
)
class GitIgnoreNew(Ignore):
...
import time
start = time.perf_counter()
newIgnore = GitIgnoreNew(Path.cwd())
print(f"New ignore setup: {time.perf_counter() - start}")
start = time.perf_counter()
oldIgnore = …
```
> Faster GitIgnore directory check

- .github/workflows/pythonpublish.yml
- Dockerfile.agent
As title says. Backport https://github.com/flyteorg/flytekit/pull/3008 to unblock the Flyte 1.14.1 release.
> Backport to v1.14 - Unify dependencies in agent image (#3008)

- tests/flytekit/unit/bin/test_python_entrypoint.py
`test_get_container_error_timestamp` has been failing semi-consistently only on Windows. We all hate flaky tests.
The test relies on the function `get_container_error_timestamp` which returns a protobuf Timestamp object, which uses `time.time` to collect the current time. However, the granularity of `time.time` and `datetime.now` are different (the latter being more precise as per https://docs.python.org/3/library/datetime.html#datetime.datetime.now).
I don't have a Windows machine, but tests run fine locally. Will kick off a few runs in CI just to confirm.
> Use the same source of time in flaky test

- .github/workflows/pythonpublish.yml
I made a mistake in https://github.com/flyteorg/flytekit/pull/3008, the correct name of the image built at that stage is `flyetagent-slim` not `flyteagent` (which is only published in the next step).
> Use correct name in flyteagent test

- flytekit/extend/backend/agent_service.py
- flytekit/loggers.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
NA
Hard to debug when an error is raised from the agent.
Print the stack trace in the error message
Before:
After:
> fix: Improve error details and logging config handling

- flytekit/interactive/vscode_lib/decorator.py
This PR configures VSCode to use the Python that launched flyte.
This PR adds a `settings.json` file to the vscode configuration.
I ran `pyflyte run --remote main.py wf`
```python
new_flytekit = "git+https://github.com/thomasjpfan/flytekit@6a9506bd6fc6ee0590211c720f4e4a64ddbd2e8f"
image_spec = ImageSpec(registry="ghcr.io/thomasjpfan", packages=[new_flytekit], apt_packages=["git"])
def train():
print("forward")
print("backwardd")
raise RuntimeError("fail")
@workflow
def wf():
train()
```
When launching debug I get:
> Add python interpreter into vscode settings

- flytekit/types/directory/types.py
- tests/flytekit/unit/types/directory/test_listdir.py
Closes flyteorg/flyte#6005
Fixes bug that makes `FlyteDirectory.listdir` return file/directory names instead of paths.
Instead of the file/directory name, return full path.
Added unittest to `tests/flytekit/unit/types/directory/test_listdir.py`
> Fix bug in FlyteDirectory.listdir on local files

- plugins/flytekit-airflow/setup.py
NA
`apache-airflow-providers-google` has a new release [12.0.0](https://pypi.org/project/apache-airflow-providers-google/#history), `apache-airflow` is not compatible with it
set uppoer-bound in the setup.py
unit tests
Added version constraint in setup.py to resolve compatibility issues between apache-airflow and apache-airflow-providers-google package. The change prevents usage of apache-airflow-providers-google versions 12.0.0 and above to maintain system stability and prevent potential runtime issues due to incompatible package versions.
<br>
<br>
<br>
<br>
</div>
> Fix unit tests in airflow plugin

- flytekit/extend/backend/agent_service.py
- flytekit/extend/backend/base_agent.py
NA
`resource_meta` is misspelled as `resource_mata`.
Correct `resource_meta` spelling for async agent.
NA
```
git clone https://github.com/flyteorg/flytekit.git
gh pr checkout 3023
make setup && pip install -e .
```
NA
NA
> fix: Fix resource meta typos for async agent

- flytekit/clis/sdk_in_container/run.py
better formatting
`pyflyte run example.py --help`
```python 
"""A basic Flyte project template that uses a Dockerfile"""
import typing
@task()
def say_hello(name: str) -> str:
"""A simple Flyte task to say "Hello".
The @task decorator allows Flyte to use this function as a Flyte task,
which is executed as an isolated, containerized unit of compute.
"""
return f"Hello, {name}!"
@task()
def greeting_length(greeting: str) -> int:
"""A task the counts the length of a greeting."""
return len(greeting)
@workflow
def wf(name: str = "world"):
"""Declare workflow called `wf`.
The @workflow decorator defines an execution graph that is composed of
tasks and potentially sub-workflows. In this simple example, the workflow
is composed of just one task.
There are a …
```
> fix: format commands output

- plugins/flytekit-inference/README.md
- plugins/flytekit-inference/flytekitplugins/inference/__init__.py
- plugins/flytekit-inference/flytekitplugins/inference/vllm/serve.py
- plugins/flytekit-inference/setup.py
- plugins/flytekit-inference/tests/test_vllm.py
A vllm addition to the existing `flytekitplugins-inference` plugin which already has NIM and ollama. 
A vllm plugin that lets you easily create a pod template to serve a vllm in an init container for a flyte task. User passes a hugging face secret name and the model in hugging face they want to serve.
```python
import flytekit as fl
from openai import OpenAI
model_name = "google/gemma-2b-it"
hf_token_key = "vllm_hf_token"
vllm_args = {
"model": model_name,
"dtype": "half",
"max-model-len": 2000,
}
hf_secrets = HFSecret(
secrets_prefix="_FSEC_",
hf_token_key=hf_token_key
)
vllm_instance = VLLM(
hf_secret=hf_secrets,
arg_dict=vllm_args
)
image = fl.ImageSpec(
name="vllm_serve",
registry="...",
packages=["flytekitplugins-inference"],
)
@fl.task(
pod_template=vllm_instance.pod_template, …
```
> vllm inference plugin

- flytekit/core/array_node_map_task.py
closes https://github.com/flyteorg/flyte/issues/5961
fixes: https://linear.app/unionai/issue/DX-1155/investigate-logging-level-behavior-in-map-tasks
Logging for map tasks always defaults to default since logging library is re-imported in array node map task after being initialized in the wf code's files
remove logging import and utilize flytekit logger instead
built an image w/ the changes and ran:
```
import logging
from flytekit import task, workflow, map_task
level = logging.INFO
logging.basicConfig(level=level)
@task
def my_task(s: str) -> str:
logger = logging.getLogger()
print(f"Effective logging level: {logger.getEffectiveLevel()}")
logging.info("This is an info log message")
logging.error("This is an error log message")
return s
@workflow
def wf():
my_task(s='hello world')
strings …
```
> [BUG] Map task logging level fixed at 30 for default logger

- flytekit/core/workflow.py
- flytekit/remote/remote.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/unit/core/test_workflows.py
https://github.com/flyteorg/flyte/issues/6062
See issue please.
When FlyteRemote tries to register a launch plan without serialization settings it tries to construct them.  In order to do so it backs out the module that the launch plan object is in.
* Change FlyteRemote to use the workflow that the launch plan points to instead.  This makes more sense because if the underlying workflow is missing, the serialization settings should be based on the workflow.  Registration of the launch plan itself really only needs things like project/domain/version.
* Add an `_lhs` field to workflow.  This isn't actually useful for python function workflows, but it is implied to be set correctly as part of the `ClassStorageTaskResolver` which inherits from `TrackedInstance`.  This gets triggered inside the …
> Make launch plan registrable by removing requirement for name

- flytekit/types/directory/types.py
- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_flyte_directory.py
- tests/flytekit/unit/core/test_flyte_file.py
https://github.com/flyteorg/flyte/issues/6144
Because doing distributed training with the `Elastic` plugin fails when trying to run a task with FlyteDirectory or FlyteFile inputs.
- pulls out the `_downloader` as a module-level function that's made into a partial when converting FlyteFile/Directory literals into python values.
Unit tests were updated to test for round-trip pickling.
- ~~[ ] I updated the documentation accordingly.~~
Implementation of pickleable downloaders for FlyteFile and FlyteDirectory by replacing lambda functions with functools.partial. This critical fix addresses distributed training issues with the Elastic plugin by ensuring proper serialization of file handling objects. Changes include restructuring downloader …
> Make FlyteFile and FlyteDirectory pickleable

- pyproject.toml
As suggested in the pytest warning below:
```sh
PytestDepreca
tionWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.                                                                                      
The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous f
ixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "
class", "module", "package", "session"
```
Set the "asyncio_default_fixture_loop_scope" explicitly to "function", which is the default value (as described here: https://pytest-asyncio.readthedocs.io/en/latest/reference/config …
> fix: set asyncio_default_fixture_loop_scope

- flytekit/core/workflow.py
- flytekit/remote/remote.py
- plugins/flytekit-airflow/setup.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/unit/core/test_workflows.py
Cherry-pick [a06c4dae7](https://github.com/flyteorg/flytekit/pull/3043) 
also https://github.com/flyteorg/flytekit/pull/3024/files 
This PR backports changes from PR #3043 to version 1.14, enhancing workflow handling and remote execution capabilities. It implements proper _lhs attribute initialization in PythonFunctionWorkflow and improves remote launch plan registration. Additionally, it adds version constraint to apache-airflow-providers-google package in flytekit-airflow plugin, limiting it to versions below 12.0.0.
<br>
<br>
<br>
<br>
</div>
> Backport 3043 (remote register launch plan name) to v1.14 + 3024

- pyproject.toml
This prevents noisy grpcio warnings showing up when running `pyflyte run`: https://github.com/grpc/grpc/issues/38336 
Fixed gRPC warning messages during pyflyte run execution by pinning grpcio and grpcio-status package versions to <= 1.68.0 in pyproject.toml. This change eliminates noisy warnings that were previously reported in the grpc/grpc#38336 issue.
<br>
<br>
<br>
<br>
</div>
> pin grpcio and grpcio-status <= 1.68.0

- flytekit/remote/remote.py
- tests/flytekit/unit/remote/test_remote.py
Linking this to https://github.com/flyteorg/flyte/issues/6062 which is related.
Please see [comment](https://github.com/flyteorg/flyte/issues/6062) in the linked issue, copied here:
Assume in the past `my_wf` has already been registered with version `ksD2LBYDu5PrNtNnnpd95Q`
Now if you try to do:
```
from wfs import my_wf
lp = LaunchPlan.get_or_create(workflow=my_wf, name="other_lp_for_hello2", default_inputs={})
remote = FlyteRemote(...)
remote.register_launch_plan(entity=lp, version="ksD2LBYDu5PrNtNnnpd95Q")
...
```
The issue is that `register_launch_plan` will currently try to register the underlying workflow again.  This would be fine, except that the serialization settings that are used may be completely different.  Even if it's exactly the same, this is a waste of time because the …
> Prevent register_launch_plan from re-registering already registered workflow

- pyproject.toml
https://github.com/flyteorg/flytekit/pull/3046
> Backport 3046  - Pin grpc

- flytekit/image_spec/default_builder.py
Follow up to https://github.com/flyteorg/flytekit/pull/2929
With the poetry environment in `/root/.venv`, I think it'll be good to be consistent and have the `uv.lock` environment be there too.
```bash
mkdir uv-check
cd uv-check
uv init
uv add flytekit numpy
pyflyte run --remote main.py my_task
```
where `main.py` is:
```python
from flytekit import task, ImageSpec
name="uv-wow",
requirements="uv.lock",
env={"abc": "xyz125"},
)
def my_task() -> int:
import numpy as np
return np.asarray([1, 2, 3]).sum().item()
``` 
This PR implements standardization of virtual environment paths by relocating the uv.lock environment to /root/.venv to align with poetry …
> Place venv in /root when using uv.lock as well

- flytekit/bin/entrypoint.py
- flytekit/exceptions/user.py
- tests/flytekit/unit/bin/test_python_entrypoint.py
- tests/flytekit/unit/exceptions/test_user.py
Closes https://github.com/flyteorg/flyte/issues/6170
Makes `FlyteUserRuntimeException` to return a custom `_ERROR_CODE` if defined by fytekit users
Add the `error_code` property in `FlyteUserException` and use it when a `FlyteUserRuntimeException` is thrown
Unit tests added
This PR implements custom error codes in FlyteKit's FlyteUserRuntimeException, adding an error_code property and updating the entrypoint for enhanced error handling. The changes improve exception management and provide more structured error reporting capabilities. The implementation includes comprehensive test coverage for both main functionality and edge cases.
<br>
<br>
<br>
<br> …
> Make FlyteUserRuntimeException to return error_code in Container Error

- flytekit/image_spec/default_builder.py
Base images could have ca-certificates installed already. This PR makes it so that we only copy over the certificates if it does not already exist.
Only if `ca-certificates` is not available does the certificates gets copied over.
I built at image with `ca-certificate` installed:
```python
FROM debian:bookworm-slim
RUN apt update && apt install -y ca-certificates && update-ca-certificates
```
and verified that the RUN command does not copy the ca-cerfiticate over. Also I ran the image builder without a `base_image` and the ca-certificate still existed:
```python
import os.path
name="flyte_playground",
env={"A": "c"},
)
def wow() -> bool:
return …
```
> Only copy over cat-certificates.crt if it does not exist in base image 

- flytekit/clis/sdk_in_container/run.py
Executing either task or workflow with `--remote` will log duplicate msg "Running Execution on Remote".
Remove duplications.
`pyflyte run --remote example.py wf --name "Ada"`
`pyflyte run --remote --wait example.py wf --name "Ada"`
```python
@task()
def say_hello(name: str) -> str:
return f"Hello, {name}!"
@workflow
def wf(name: str = "world") -> str:
return say_hello(name=name)
```
---
`--wait`
Fixed duplicate 'Running Execution on Remote' message display issue in CLI execution with --remote flag. Modified task visibility settings to ensure single message display during task/workflow execution. Changes focused on SDK container run functionality and task execution process.
<br>
<br>
<br>
<br>
<b>Estimated …
> fix: remove duplication log when execute

- flytekit/exceptions/user.py
- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
- plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
Since RFC https://github.com/flyteorg/flyte/pull/5598, flytepropeller can collect error files from multiple worker pods of a distributed task in order to determine the root cause error by identifying the exception with the earliest timestamp. Before, only a single error file was used even if a task launched multiple pods that each could produce an error file.
Generally, the timestamp of the container error is measured [here](https://github.com/flyteorg/flytekit/blob/a2bcf95048962b77ba2e67052b8f4a8c956fe81f/flytekit/bin/entrypoint.py#L382) in the pod entrypoint.
In the case of the pytorch elastic plugin where each worker pod can launch multiple worker processes, [torch elastic launch determines the worker process exception with the earliest …
> Fix: Always propagate pytorch task worker process exception timestamp to task exception

- flytekit/core/python_function_task.py
Just a nit on the eager deck name. 
UI enhancement that updates the deck title from 'eager workflow' to 'Eager Executions' to improve clarity and maintain consistency in the interface presentation.
<br>
<br>
<br>
<br>
</div>
> Eager deck name

- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
Closes https://github.com/flyteorg/flyte/issues/6183
Users should be able to register user-defined dataclass type transformers.
Fallback to flytekit's dataclass type transformer after mro evaluation.
Unit tests and local tests in sandbox.
This PR enhances the TypeEngine by implementing custom dataclass transformer registration functionality. The changes allow users to override default dataclass transformers with their own implementations by modifying the MRO chain evaluation order. The implementation includes support for inheritance behavior in custom dataclass transformers.
<br>
<br>
<br>
<br>
</div>
> Allow user-defined dataclass type transformer (again)

- flytekit/image_spec/default_builder.py
- flytekit/image_spec/image_spec.py
- plugins/flytekit-envd/flytekitplugins/envd/image_builder.py
- plugins/flytekit-envd/tests/test_image_spec.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
Currently, `ImageSpec` will always create a new virtualenv to install packages. With this PR, users can specify, `python_exec` to use a Python from a `base_image`'s python to install packages into.
This PR:
- Moves the `micromamba` python install into it's own function and only uses it if `python_exec` is not set.
- Errors in `envd` when `python_exec` is set.
- Errors when any of the `conda_*` parameters are set and `python_exec` is set.
I ran the follow on sandbox:
```python
base_image="ghcr.io/flyteorg/flytekit:py3.11-1.14.4",
name="wow",
packages=[
"numpy",
"git+https://github.com/thomasjpfan/flytekit.git@176ecfbe006e00d563380d4c2638c3e550b35fbc",
], …
```
> Adds python_exec into ImageSpec

- tests/flytekit/unit/core/test_dataclass.py
* Just adding a unit test we found helpful when debugging.
* Updating new lines to not annoy some IDEs. 
Added new unit test for validating Union type behavior with dataclass_json decorated classes in Flytekit. Test specifically focuses on Union[DC, DCWithOptional] functionality in both task and workflow contexts, verifying proper serialization and deserialization based on conditional logic.
<br>
<br>
<br>
<br>
</div>
> Add a test for union/dc

- plugins/flytekit-omegaconf/flytekitplugins/omegaconf/dictconfig_transformer.py
- plugins/flytekit-omegaconf/tests/test_dictconfig_transformer.py
Explicit handling of `None` values within OmegaConf.DictConfig objects.
Currently, launching a flyte workflow locally with a DictConfig object as input, it fails with the following error if there is a null value in the DictConfig object:
```
File "/venv/lib/python3.9/site-packages/flytekit/core/workflow.py", line 308, in __call__
raise exc
File "/venv/lib/python3.9/site-packages/flytekit/core/workflow.py", line 301, in __call__
return flyte_entity_call_handler(self, *args, **input_kwargs)
File "/venv/lib/python3.9/site-packages/flytekit/core/promise.py", line 1459, in flyte_entity_call_handler
result = cast(LocallyExecutable, entity).local_execute(child_ctx, **kwargs)
File "/venv/lib/python3.9/site-packages/flytekit/core/workflow.py", line 327, in local_execute
function_outputs = …
```
> Bugfix Omegaconf plugin: Properly deal with NoneType values

- flytekit/types/file/file.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/integration/remote/utils.py
- tests/flytekit/integration/remote/workflows/basic/attr_access_sd.py
- tests/flytekit/integration/remote/workflows/basic/flytefile.py
Small quality of life improvement to FlyteFile. 
This PR enhances FlyteFile functionality by implementing direct remote path handling and delayed downloading capabilities, while also improving test infrastructure. The changes include modernized mock imports, parquet file support, and new test workflows for StructuredDataset attribute access. The implementation features enhanced type annotations and documentation, focusing on strengthening both remote file operations and structured data handling capabilities.
<br>
<br>
<br>
<br>
</div>
> backport to 1.14 - [BUG] Open FlyteFile from remote path (#2991)

- flytekit/core/data_persistence.py
- flytekit/core/type_engine.py
- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_data_persistence.py
- tests/flytekit/unit/core/test_list.py
https://github.com/flyteorg/flyte/issues/6188
Please see issue.
Because flytekit loops run on a different thread, the moment the asyncio.Task is created, it starts running, rendering any batching of coroutines moot.
In testing, we also noticed that the s3fs and gcsfs default write chunk sizes were 50MB.  We felt that was a bit high and in testing noticed no performance decrease (actually saw possibly non-statistically significant increase) in performance.  We are therefore changing it by default to 25MB.  Also this setting and the number of coroutine batches the list & dict transformers run will be configurable via environment variables.
The new env vars are:
* `_F_P_WRITE_CHUNK_SIZE` - This is the number of bytes and by default is set to `"26214400"` (25 * 2^20)
* `_F_TE_MAX_COROS` - …
> Fix async coroutine limit not respected and add s3/gcs chunk size

- flytekit/core/type_engine.py
- flytekit/remote/remote_fs.py
- flytekit/types/structured/structured_dataset.py
- tests/flytekit/unit/core/test_dataclass.py
- tests/flytekit/unit/extras/pydantic_transformer/test_pydantic_basemodel_transformer.py
- tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
https://github.com/flyteorg/flyte/issues/6189
Call the modify literals uris.
on dogfood.
Implementation of URI modification functionality for structured datasets, focusing on handling uploaded files within dataclasses and Pydantic models. Enhanced handling of flyte:// URLs and improved type imports for StructuredDataset. Added support for modifying literal URIs in StructuredDatasetTransformerEngine with comprehensive test coverage. Includes documentation fixes in HttpFileWriter and proper handling of URI transformations in container environments.
<br>
<br>
<br>
<br>
</div>
> Structured datasets in containers (dc/pydantic)

- flytekit/image_spec/default_builder.py
- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
Related to https://github.com/flyteorg/flyte/issues/6119
We have a few path dependencies in `pyproject.toml` and `poetry.lock`, and only want to install packages from external sources, which requires adding `--no-directory` to `poetry install`. This is a standard practice when installing dependencies without code.
See
https://python-poetry.org/docs/faq/#poetry-busts-my-docker-cache-because-it-requires-me-to-copy-my-source-files-in-before-installing-3rd-party-dependencies
`pip_extra_args` is a specifiable parameter for `ImageSpec`, and appended when running `poetry install`, `uv sync` and `pip install`.
I tested locally with a poetry project with internal path dependency by running `pyflyte build`. Planning to add unit tests once the implementation get LGTM. …
> Add pip_extra_args

- .pre-commit-config.yaml
- pydoclint-errors-baseline.txt
N/A
`pydoclint` is a well known linter that will help bring flytekit coding standards up a notch.
A few changes:
1. Enable `pydoclint` as a pre-commit hook.
2. Create a baseline file (here called `pydoclint-errors-baseline.txt`) to help catch issues going forward while having a path to resolving existing issues
i. this baseline file is regenerated in case a rule is fixed in a PR due to `--auto-regenerate-baseline` defaulting to `true`.
Notice that the majority of the existing failures are a DOC301 according to the count of violations by type:
```
❯ cat pydoclint-errors-baseline.txt | grep "DOC" | cut -d':' -f1 | sort | uniq -c
7     DOC001
18     DOC101
18     DOC103
12     DOC105
7     DOC106
10     DOC107
6     DOC109
5     DOC110
12     DOC201
14     DOC203
200     DOC301
2     DOC402 …
```
> Enable pydoclint

- tests/flytekit/unit/core/test_dataclass.py
An import was accidentally removed (because it was a duplicate in the commit that was cherry-picked).  Adding it back and formatting better. 
Import statements in test_dataclass.py have been reorganized for better code organization. The changes include removing duplicate imports, restoring a previously removed DataClassJsonMixin import, and grouping related imports together in a more structured manner.
<br>
<br>
<br>
<br>
</div>
> Format imports better

- flytekit/core/type_engine.py
Silence warning.  sister of https://github.com/flyteorg/flytekit/pull/3091/files 
Minor modification to logging levels in the type engine module, reducing verbosity by downgrading a union-related warning message to debug level. This change improves log clarity by ensuring only significant warnings are displayed at the warning level.
<br>
<br>
<br>
<br>
</div>
> silence union warning

- flytekit/core/resources.py
- flytekit/models/task.py
- plugins/flytekit-ray/flytekitplugins/ray/task.py
- plugins/flytekit-ray/setup.py
- plugins/flytekit-ray/tests/test_ray.py
- tests/flytekit/unit/core/test_resources.py
NA
- Improve the devx: people can easily override the request and limit for the head/worker node
- Replace K8sPod with PodTemplate to make it consistent with the parameter in `@task`
- Add resource and limit to HeadNodeConfig and WorkerNodeConfig
```python
import typing
import ray
from flytekitplugins.ray import HeadNodeConfig, RayJobConfig, WorkerNodeConfig
flytekit_hash = "234603bde982c4ece390dd77c33390c6d8db93cf"
new_flytekitplugins_ray = f"git+https://github.com/flyteorg/flytekit.git@{flytekit_hash}#subdirectory=plugins/flytekit-ray"
new_flytekit = f"git+https://github.com/flyteorg/flytekit.git@{flytekit_hash}"
packages=[new_flytekitplugins_ray, "kubernetes", new_flytekit], …
```
> Add request and limit to ray config

- flytekit/interaction/parse_stdin.py
For example like so,
```python
import flytekit as fl
from datetime import timedelta
dt = timedelta(seconds=60)
@dataclass
class MyClass:
x: int
y: str
@fl.task
def my_task(c: MyClass) -> MyClass:
return c
@fl.workflow
def my_wf():
c = fl.wait_for_input("tst", dt, MyClass)
my_task(c=c)
```
Local execution will result in failure
```
Failed to parse input: stat: path should be string, bytes, os.PathLike or integer, not MyClass
```
This fixes the local execution. Remote works fine! 
Fixed a bug in local execution where input parsing was being performed twice for gatenode interactions. The change simplifies input parsing by removing redundant type conversion in parse_stdin.py, improving handling of complex types …
> Gatenode local execution, was parsing the input twice

- flytekit/remote/remote.py
- tests/flytekit/integration/remote/test_remote.py
Related to flyteorg/flyte#6097
Return the entity itself without trying to compile if the entity is Reference workflow
Integration test
Fixed compilation error in remote.py by adding condition checks for ReferenceWorkflow entities. Enhanced the remote workflow testing framework with reference workflow testing capabilities, including new module imports and test cases. These changes ensure proper handling of reference workflow entities without compilation.
<br>
<br>
<br>
<br>
</div>
> prevent compile err for ReferenceWorkflow

- flytekit/clients/friendly.py
- flytekit/clients/raw.py
- flytekit/models/domain.py
- flytekit/remote/remote.py
- Today there is no way of querying flyte projects and domains using FlyteRemote
- Adds endpoint to FlyteRemote to query registered projects paginated
- Adds endpoint to FlyteRemote to query configured domains
- Installing this branch locally
- running this
``` python
from flytekit.remote import FlyteRemote
from flytekit.configuration import Config
r = FlyteRemote(config=Config.for_endpoint(endpoint="demo.hosted.unionai.cloud"))
print("#" * 20)
projects = r.list_projects()
print(f"length of projects {len(projects)}")
print(f"project #0: {projects[1]}")
print(f"project type #0: {type(projects[1])}")
print(f"project #0 id : {projects[1].id}")
print("#" * 20)
projects = r.list_projects(limit=2)
print(f"length of projects {len(projects)}")
print(f"project #0: {projects[1]}")
print(f"project …
```
> add project & domain endpoint for FlyteRemote

- flytekit/types/directory/types.py
Closes flyteorg/flyte#6219
Type hint wrong
Changed the output type hint from FlyteDirectory.new from the incorrect FlyteFile to the correct FlyteDirectory.
No tests. Just types affected.
Fixed incorrect return type hint in FlyteDirectory class's new() method, changing it from FlyteFile to FlyteDirectory. This is a straightforward type safety improvement that enhances code correctness without impacting runtime behavior.
<br>
<br>
<br>
<br>
</div>
> Fixed type hint

- flytekit/models/security.py
- tests/flytekit/unit/models/core/test_security.py
This PR adds validation for `Secret.env_var`, so we fail fast when the `env_var` is not a valid environment variable.
Adds validation to `Secret.env_var`.
Added a unit test for the change. 
Implementation of environment variable name validation for Secret.env_var using regex pattern validation. The validation ensures names follow the format of uppercase letters, numbers, and underscores, with proper starting character requirements. Test cases were added to verify validation behavior.
<br>
<br>
<br>
<br>
</div>
> Adds validation to Secrets.env_var

- flytekit/clients/grpc_utils/auth_interceptor.py
Relates to  [PR](https://github.com/flyteorg/flytekit/pull/2962)
All unit tests passed
PR optimizes authentication flow by removing redundant credential refresh calls in auth_interceptor.py. The changes eliminate duplicate refresh_credentials() invocations, improving performance and reducing unnecessary overhead in the authentication process.
<br>
<br>
<br>
<br>
</div>
> fix: keyring refresh twice

- flytekit/remote/remote.py
- tests/flytekit/integration/remote/test_remote.py
Related to https://github.com/flyteorg/flyte/issues/6097
Return the entity itself without trying to compile if the entity is ReferenceEntity
Integration test
https://github.com/flyteorg/flytekit/pull/3102
This PR enhances reference entity handling in Flytekit to prevent compilation errors by updating type hints in remote.py and modifying test cases. The changes focus on direct return of reference entities without compilation and improve the register_script workflow for reference entities.
<br>
<br>
<br>
<br>
</div>
> prevent compile err for all reference entities

- flytekit/core/promise.py
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_annotated_bindings.py
- tests/flytekit/unit/core/test_generice_idl_type_engine.py
- tests/flytekit/unit/core/test_type_engine.py
Internal ticket only.
Customer reported issue with internal model registry.  The issue though is that annotations don't work well with dictionary return types.
Most of the changes here are in the dict transformer.
* The `extract_types_or_metadata` function is inconsistent, returning different things in different scenarios - sometimes it would return annotations, sometimes it would return the key/value type of a dictionary.  This has been changed to always return the latter, or an empty tuple `()` in the case of an untyped dictionary.  In all cases now, the caller interprets the result as a tuple of key type,value type.  Renaming function to just `extract_types`.
* the `is_pickle` function returned both a boolean, as well as types, but the latter isn't really necessary.  Changing this to …
> Fix dict annotations

- flytekit/core/promise.py
- flytekit/core/python_function_task.py
- flytekit/core/worker_queue.py
- flytekit/core/workflow.py
- flytekit/image_spec/default_builder.py
- tests/flytekit/unit/core/test_worker_queue.py
Unable to run subworkflows, as part of eager workflows, via to_thread.  This PR only fixes the ability to run subworkflows on the backend.  Local execution still needs additional fixes.
* A return was missing from the call handler, leading to local runs of subworkflows locally run by eager to run multiple things.
* The compile step has been taken out of the workflow call handler.
* In local testing found that the behavior of the reconcile function in the worker doesn't handle the re-run case where the execution is already found. The reconcile function now will always just sync the execution, and then handle state management appropriately.
* Additional terminal states are mapped to failed in the update object.
* asserts were hard to debug - these have been changed to explicit assertion …
> Bug when calling wf in eager task with thread

- tests/flytekit/unit/bin/test_python_entrypoint.py
NA
The test test_get_container_error_timestamp has been failing on windows since its introduction. We don't get any signal from it, mainly because no one is really going to use pytorch on windows.
Skip a particular test on windows.
Added a Windows-specific skip condition for test_get_container_error_timestamp test to address unreliable timestamp granularity issues on Windows platforms. This change enhances test suite reliability by preventing failures caused by platform-specific limitations.
<br>
<br>
<br>
<br>
</div>
> Skip test_get_container_error_timestamp on windows

- flytekit/core/resources.py
- flytekit/core/task.py
- flytekit/models/task.py
- pyproject.toml
Follow up to https://github.com/flyteorg/flytekit/pull/2943
Since flytekit does not depend on `kubernetes`, importing flytekit will not work anymore if `kubernetes` is not installed.
This PR moves the imports out of the top level and into the function.
Built an image with this PR and not kubernetes and make sure it works:
```python
image = ImageSpec(registry="localhost:30000", copy=["flytekit"])
def hello() -> str:
return "hello world"
```
Ideally we also have a CI job that does not have kubernetes installed to make sure flytekit still works. 
Optimization of kubernetes dependency handling in Flytekit by making it optional and lightweight, while also enhancing the …
> Do not import kubernetes in flytekit core

- plugins/flytekit-pandera/flytekitplugins/pandera/pandas_transformer.py
- plugins/flytekit-pandera/setup.py
https://linear.app/unionai/issue/DX-1315/update-pandera-flytekit-plugin-to-use-streaming-decks
Changes support publishing the pandera deck even when a validation error is raised
Call `Deck.publish` in the pandera type transformer.
Created local flyte cluster with
- `make -C docker/sandbox-bundled build` on flyte master branch
- `flytectl demo start --image flyte-sandbox:latest`
Then ran the following script `foo.py`:
```python
import typing
from typing import Annotated
import json
import pandera as pa
from flytekitplugins.pandera import ValidationConfig
from pandera.typing import DataFrame, Series
packages=[
"git+https://github.com/flyteorg/flytekit@9ebc57e27#subdirectory=plug …
```
> publish pandera deck

- flytekit/loggers.py
`pythonjsonlogger.jsonlogger` is deprecated as of pythonjsonlogger>=3.1.0:
https://github.com/nhairs/python-json-logger/releases/tag/v3.1.0
https://github.com/nhairs/python-json-logger/blob/db04a0f9066cc331f8d6177f828fe073c7b2a4cc/src/pythonjsonlogger/jsonlogger.py
This is a warning of an impending deprecation.
To not import a deprecated module.
Running them in CI here. Let's find out if they pass.
Updated import statement in flytekit/loggers.py to handle pythonjsonlogger>=3.1.0 deprecation warning. Implemented conditional import logic to check for new module path (pythonjsonlogger.json) with fallback to legacy path (pythonjsonlogger.jsonlogger). Change ensures backward compatibility across different versions of pythonjsonlogger package. …
> Fix DeprecationWarning in `pythonjsonlogger>=3.1.0`

- flytekit/interaction/string_literals.py
- flytekit/remote/data.py
- plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
- plugins/flytekit-openai/tests/openai_batch/test_agent.py
- tests/flytekit/unit/interaction/test_string_literals.py
Closes flyteorg/flyte#6242
So that `pyflyte fetch` can process msgpack literals. Outputs JSON file.
- In the handling of `pyflyte fetch` make a special case for a binary scalar with msgpack tag.
- Added msgpack binary handling to `scalar_to_string`. Return json.
- Added test for `scalar_to_string`
- Didn't add tests for the download code, because a test is missing for the entire function. Manually ran successfully.
This PR implements msgpack-encoded binary data support in Flyte's data fetching functionality, enabling conversion of msgpack literals to JSON format in the 'pyflyte fetch' command. The implementation handles binary scalars with msgpack tags in both string conversion and download functionalities.
<br>
<br>
<b>Unit tests added</b>: …
> Added msgpack support for `pyflyte fetch`, storing as JSON

- flytekit/interaction/click_types.py
- tests/flytekit/unit/interaction/test_click_types.py
Make the code run faster and reduce redundant logic.
return python value before calling `to_literal` func here.
https://github.com/flyteorg/flytekit/pull/3134/files#diff-cc3172a3cdf60bb2ffb23b81cb5b92d6c4a89063d691e86932b312e1df09f292R530-R534
unit test
This PR enhances the Flyte Literal Converter by optimizing type conversion flow in click_types.py and improving type handling. The changes eliminate redundant type conversions in remote execution scenarios and enhance type hinting for nullable fields in dataclass test cases. The modifications streamline the conversion process by ensuring proper ordering of literal conversions and explicitly marking fields with None default values as Optional, improving type system accuracy and …
> Improve Flyte Literal Converter logic

- flytekit/remote/remote.py
- tests/flytekit/integration/remote/test_remote.py
Currently when we run
```python
r = FlyteRemote(config=Config.for_endpoint(endpoint=endpoint))
execs = r.recent_executions(project=project, domain=domain, limit=limit)
a = r.sync(execs[0], sync_nodes=True)
print("task execution", a.node_executions["n0"].task_executions)
```
if node n0 is array node, then task_executions would be an empty list.
for array node type node executions, sync task executions and store them.
- Tested locally by running
```python
r = FlyteRemote(config=Config.for_endpoint(endpoint=endpoint))
execs = r.recent_executions(project=project, domain=domain, limit=limit)
a = r.sync(execs[0], sync_nodes=True)
print("task execution", a.node_executions["n0"].task_executions)
```
and can see the correct task executions
- added integration tests. …
> Fix array node empty task executions when using remote

- plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker_inference/boto3_agent.py
- plugins/flytekit-aws-sagemaker/tests/test_boto3_agent.py
- plugins/flytekit-openai/flytekitplugins/openai/batch/agent.py
- plugins/flytekit-openai/tests/openai_batch/test_agent.py
This is necessary because although the result is already a literal, it is being converted to a literal again. Since literal isn't a valid Python type, it ends up being pickled. This issue surfaced in Flytekit 1.15.0.
Wrapping agent outputs in a `LiteralMap` so they don't get converted to literals again.
Tested the OpenAI plugin with the updated code.
Fixed a bug in agent output handling where results were being converted to literals multiple times, affecting Python type validation in Flytekit 1.15.0. Implemented proper LiteralMap wrapping for agent outputs in AWS SageMaker and OpenAI plugins to prevent double literal conversion. Modified AWS SageMaker plugin test cases to enhance output type validation and added conditional checks for …
> wrap agent outputs in a literalmap

- .github/workflows/pythonbuild.yml
- plugins/flytekit-ray/flytekitplugins/ray/task.py
NA
Failed to run the ray task with error: 
```python
File "/usr/local/lib/python3.11/site-packages/flytekit/bin/entrypoint.py", line 178, in _dispatch_execute
outputs = task_def.dispatch_execute(ctx, idl_input_literals)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flytekit/core/base_task.py", line 726, in dispatch_execute
new_user_params = self.pre_execute(ctx.user_space_params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/flytekitplugins/ray/task.py", line 81, in pre_execute
ray.init(**init_params)
File "/usr/local/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File …
```
> Exclude python_history from the Ray runtime environment.

- plugins/flytekit-ray/flytekitplugins/ray/task.py
- plugins/flytekit-ray/tests/test_ray.py
Relayed to https://github.com/flyteorg/flyte/issues/5877
In a follow up pull request I'd like to make the `worker_node_config` optional.
When submitting a job to an existing ray cluster you shouldn't need to configure details for an ephemeral cluster you will never use. 
Adds a unit test and just handles a nil pointer case since head node specs can be `None`
Unit tests
This PR implements fixes for a nil pointer issue in the Ray plugin's head node configuration and enhances test coverage for existing cluster scenarios. The changes include adding null checks for head_node_config and restructuring head group spec initialization. The PR also adds comprehensive unit testing for Ray task execution with existing cluster configurations.
<br>
<br> …
> Add unit test for ray with an existing cluster and fix nil pointer

- flytekit/remote/remote.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/integration/remote/workflows/basic/deep_child_workflow.py
N/A
There is currently a bug where the function does not recursively fetch executions on subworkflows when the subworkflow is a reference to a launch plan. Currently, it only fetch executions on launch plan only for the first layer and not deeper layer. 
E.g.
Say if your execution reference launchPlanA. launchPlanA references launchPlanB. Currently, the `sync_nodes` only gets launchPlanA.
Fix the bug so that the `sync_nodes` is truly recursive.
tested locally with a deeply nested workflow to confirm reference plans are fetched.
Implementation of recursive synchronization for launch plans in nested workflows, fixing bugs in sync_execution functionality. Added proper handling of subworkflows, launch plans synchronization, and sync_nodes …
> fix a bug where sync_execution is not calling itself recursively

- flytekit/core/type_engine.py
- plugins/flytekit-greatexpectations/tests/test_schema.py
- tests/flytekit/integration/remote/test_remote.py
NA
Fix test_invalid_ge_schema_batchrequest_pandas_config unit test
unit test
This PR enhances error handling mechanisms and test execution efficiency. Key changes include updating exception types in Great Expectations schema testing (from InvalidBatchRequestError to TypeTransformerFailedError), improving error message clarity, and adjusting remote execution test timeout from 10 to 5 minutes. These modifications aim to improve test performance and error specificity while enhancing debugging capabilities.
<br>
<br>
<br>
<br>
</div>
> Fix test_invalid_ge_schema_batchrequest_pandas_config

- flytekit/core/workflow.py
- tests/flytekit/unit/core/test_serialization.py
https://github.com/flyteorg/flyte/issues/6208
Remove the value in `input_kwargs` (which contains the default value) if the value is set in `args`, to prevent passing `kwargs` and `args` both for same argument, which cause the error described in the issue.
Add test `test_positional_args_workflow_with_default_value` extend from `test_positional_args_task` for positional arguments with default value set
This PR addresses a subworkflow argument handling issue by preventing simultaneous use of positional arguments and default values. The workflow execution logic has been modified to properly handle input_kwargs when positional arguments are provided. Test coverage has been enhanced to validate subworkflow behavior with default values and …
> Enable using positional args for workflow with default value

- flytekit/remote/remote.py
Currently if we call sync_node_execution on an execution contains map over lp in dynamic workflow, we'll get error like
```
KeyError:
LAUNCH_PLAN:flytesnacks:development:yt_dbg.scratchpad.array_node_lp_source.hello_world_w
f_for_array:hOMsbgLXveLF2C15vDjQQA
```
because we didn't inspect launch plan inside an array node in dynamic case.
- Fix sync_node_execution for map over lp in dynamic. 
- Refactor a bit to remove duplicate codes.
tested with a dynamic workflow which contains map over launch plan and I was able to call sync_node_execution and get the correct data.
> fix sync for map over lp in dynamic

- Dockerfile.agent
- flytekit/clis/sdk_in_container/serve.py
- flytekit/remote/remote.py
- pyproject.toml
This PR restructures Flytekit's dependency management by moving httpx and other dependencies (prometheus-client, grpcio-health-checking) from core to the optional 'agent' extras package. It improves the webhook agent functionality through better dependency organization, adds graceful error handling for missing dependencies, and enhances code structure with clear installation instructions and extracted import validation logic.
<br>
<br>
<br>
<br>
</div>
> add httpx dependency for webhook agent in flytekit dependency

- plugins/flytekit-flyteinteractive/Dockerfile
- plugins/flytekit-openai/Dockerfile.batch
- plugins/flytekit-spark/Dockerfile
- plugins/flytekit-sqlalchemy/Dockerfile
NA
We should standardize and use `uv` as much as we can.
This PR implements two major changes: 1) Standardizes package installation across Docker images using 'uv' package installer with Python 3.12 as default, though reviewers suggest using pip's native features instead. 2) Enhances Flyte plugins by standardizing output handling in AWS SageMaker and OpenAI plugins with LiteralMap format, while improving Ray plugin configuration with better head node handling.
<br>
<br>
<br>
<br>
</div>
> Use uv in all docker images

- flytekit/bin/entrypoint.py
- flytekit/core/context_manager.py
- flytekit/core/python_function_task.py
- flytekit/core/worker_queue.py
- tests/flytekit/unit/core/test_async.py
- tests/flytekit/unit/core/test_context_manager.py
To enable users to see the deck listing launched executions for eager workflows before completion.
* Added and set enable_deck to eager tasks
* Added a repr to ExecutionParameters for debugging
* Updated the html generation to not skip incomplete executions
* Use the context within the FlyteRemote object for publishing the deck, since `publish()` effectively does a check on the context to make sure the task has generates_deck set to true.
Unit tested, with sandbox, and Union servers.
This PR introduces deck publishing for eager workflows with an enable_deck parameter and improved context management for HTML deck rendering. It enhances worker queue processing to publish deck information without skipping incomplete executions and adds …
> Worker queue to publish deck

- flytekit/types/file/file.py
- tests/flytekit/integration/remote/workflows/basic/flytefile.py
- tests/flytekit/unit/types/file/test_file.py
- tests/flytekit/unit/utils/test_pbhash.py
Closes https://github.com/flyteorg/flyte/issues/6257
With this PR, metacata can be attached to a FlyteFile.
This PR adds `metadata` to FlyteFile so that it an adjust the Literal's metadata.
Unit test and integration tests were updated.
The UI automatically shows the new metadata:
This PR has two main components: 1) Adds metadata support to FlyteFile with serialization/deserialization handling and type validation, enabling storage of string key-value pairs and preserving metadata during workflow execution. 2) Implements modular agent-related dependencies by moving them to an optional dependency group, with updates to Dockerfile.agent and dependency management through pyproject.toml.
<br>
<br>
<br>
<br> …
> Adds metadata to FlyteFile

- flytekit/remote/executions.py
- flytekit/remote/remote.py
Currently if we sync an execution which contains a launch plan, the sync would fail if the execution failed. This is because we didn't check the execution phase before access the outputs.
Check if the execution is successful before access the output.
Tested with
```python
from flytekit import workflow, task, LaunchPlan
@task()
def print_head(a: int) -> int:
print(1 / 1)
return a + 1
@workflow()
def easy_execution(b: int) -> int:
return print_head(a=b)
lp = LaunchPlan.create(name="lp-easy-execution", workflow=easy_execution)
@workflow()
def master(a: int) -> int:
return lp(b=a)
```
```python
r = FlyteRemote()
a = r.sync(exec, sync_nodes=True)
```
This PR fixes a critical bug where output access could fail for unsuccessful executions. It adds …
> check execution phase before access outputs

- flytekit/image_spec/__init__.py
- flytekit/image_spec/default_builder.py
- flytekit/image_spec/image_spec.py
- plugins/flytekit-spark/flytekitplugins/spark/task.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
NA
The default builder creates another Python venv in the image. The driver is using the venv (python3.11) that was created from the default builder, and the worker is using the default venv (python3.9) in the base image
Always install the dependencies in the default venv in the spark base image.
```python
from operator import add
from flytekit import ImageSpec, Resources, task, workflow, dynamic
from flytekitplugins.spark import Spark
from utils import f
container_image = ImageSpec(
packages=["flytekitplugins-spark==1.15.1b0", "numpy"],
)
@task(
task_config=Spark(
spark_conf={
"spark.driver.memory": "1000M",
"spark.executor.memory": "2000M",
"spark.executor.cores": "1",
"spark.executor.instances": "5",
"spark.driver.cores": "2",
}, …
```
> Install the dependencies in the default venv in the spark base image

- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/pod_template.py
- plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
- plugins/flytekit-kf-pytorch/tests/test_shared.py
https://github.com/flyteorg/flytekit/pull/2543 introduced a convenience flag `increase_shared_mem` to the task configs provided by the kfpytorch plugins (`PyTorch` and `Elastic`). If specified, a shared memory volume mount is added to the pod template under the hood.
The flytekit 1.15.0 release introduced a similar flag to the `@task` decorator itself. Instead of using the pod template to configure the volume mount on the flytekit side, there is [proper support in flyteidl ](https://github.com/flyteorg/flyte/blob/b779bed928e4fbc914ab64b51940d861ffbc968d/flyteidl/protos/flyteidl/core/tasks.proto#L82) and the volume mount is added in flytepropeller.
The flag on the `@task` level also works for the distributed kfpytorch plugin task types which means there are now two ways to increase shared …
> Deprecate `increase_shared_mem` flag in flytekitplugins-kf-pytorch in favor of new native `@task` argument

- flytekit/remote/remote.py
- flytekit/remote/remote_fs.py
- flytekit/tools/script_mode.py
- flytekit/types/pickle/pickle.py
- tests/flytekit/integration/remote/test_remote.py
- tests/flytekit/integration/remote/workflows/basic/pickle_wf.py
NA
I encountered an error when attempting to run the task for the second time. Here’s the error message I received.
The issue occurs because the pickle path in the node binding changes each time a new workflow is registered
File name was a random string generated from [here](https://github.com/flyteorg/flytekit/blob/55e9f8d7f226302277c5d70abdcfd5d1ff19a789/flytekit/types/pickle/pickle.py#L45), and it causes `get_upload_signed_url` to always return a different S3 path. 
```
Request rejected by the API, due to Invalid input.
RPC Failed, with Status: StatusCode.INVALID_ARGUMENT
Details: cus.test_workflow workflow with different structure already exists. (Please register a new version of the workflow):
/primary/connections:
- <nil>
+ map[downstream:map[n0:map[ids:[end-node]] …
```
> Use digest as file_name to get signed url

- flytekit/core/context_manager.py
- tests/flytekit/unit/core/test_context_manager.py
Overriding `group` and `group_version` is a bug when trying to get the secret from `SecretManager`. We already have a check during registration time:
https://github.com/flyteorg/flytekit/blob/fc5421e1692b04bf72c69fc0f1fba319ea3428d3/flytekit/models/security.py#L54-L56
This means that during registration time, we'll check if groups are required. During runtime,  there are two cases (assuming `secret_requires_group=True`):
1. If the secret manager requires groups, then `Secret(group="...")` is configured correctly.
2. If the secret manager does not require group, then compiling passes and `group` is set to `None` already.
This PR removes the check for groups in `SecretManager`.
A unit test was added to this PR.
On sandbox, I created a kubernetes secret:
```bash
kubectl create secret -n …
```
> Do not set group or group_version when secret_requires_group=False

- flytekit/core/container_task.py
- flytekit/core/node.py
- flytekit/core/python_auto_container.py
- flytekit/core/python_customized_container_task.py
- flytekit/core/resources.py
- flytekit/core/task.py
- flytekit/core/utils.py
- flytekit/types/file/file.py
- tests/flytekit/unit/core/test_local_raw_container.py
- tests/flytekit/unit/core/test_node_creation.py
- tests/flytekit/unit/core/test_resources.py
- tests/flytekit/unit/core/test_task.py
- tests/flytekit/unit/core/test_type_hints.py
Related to https://github.com/flyteorg/flyte/issues/6142
Setting request and limits is directly is very verbose. With this PR we can do this:
```python
@task(resources=Resources(cpu=(1, 2), mem="1Gi"))
def my_task():
...
```
The above will set the cpu request to 1, cpu limit to 2 and the memory request to 1Gi.
Note this has basically the same API as modal: https://modal.com/docs/guide/resources
This PR adds support for tuples and list and `Resources`. Which means `Resources` is extended to define both the request and limits. This PR also adds checks to make sure functions that expected resources to be singular raise an error.
Also, we also raise an error if `limits` or `requests` is used together with `resources` in `@task`.
Unit tests were added to this PR.  …
> Adds @task(resources)

- flytekit/core/array_node.py
- flytekit/core/array_node_map_task.py
- flytekit/core/interface.py
- flytekit/core/legacy_map_task.py
- flytekit/models/interface.py
- flytekit/remote/remote.py
- tests/flytekit/unit/core/test_array_node.py
- tests/flytekit/unit/core/test_interface.py
- tests/flytekit/unit/models/test_interface.py
fixes: https://linear.app/unionai/issue/BB-2860/utilize-fixed-inputs-set-for-a-launch-plan-when-mapping-over-launch
Getting this change in here since this is a bug instead of an add on. Will add to union sdk as well.
When mapping over a launch plan with fixed inputs, don't set the fixed_inputs as part of the array node's interface
- updated unit tests
- tested [launch plans](https://dogfood.cloud-staging.union.ai/console/projects/flytesnacks/domains/development/executions/ap5tstv4mrdqzfr2kn66), [reference launch plans](https://dogfood.cloud-staging.union.ai/console/projects/flytesnacks/domains/development/executions/a46ltcwc7587v5wwtwrt), and [remote launch plans](https://dogfood.cloud-staging.union.ai/console/projects/flytesnacks/domains/development/executions/axtvglqjplggb5rj8mpm) in …
> Fixed inputs map lp

- flytekit/core/array_node_map_task.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_array_node_map_task.py
fixes: https://linear.app/unionai/issue/BB-2941/utilize-bound-inputs-for-partials-for-map-tasks
add support for setting bound_inputs for ArrayNodeMapTask
https://dogfood.cloud-staging.union.ai/console/projects/flytesnacks/domains/development/executions/a29rf95w9fx4hvqjpnt8/nodeId/n0/nodes
```
@workflow
def wf():
strings = ['hello', 'world']
strings1 = ['hello', 'world']
return union.map(my_task, bound_inputs={"s1": "test"})(s=strings, s1=strings1)
```
This PR adds support for bound inputs in ArrayNodeMapTask with input consistency validation. The implementation includes updates to the flytekit core and translator module, implementing checks for key mismatches between 'bound_inputs' and 'bound_inputs_values'. It enhances robustness through …
> Support bound inputs for array node tasks

- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
NA
The image tag is different when specifying the builder 
Exclude the builder from image tag calculation.
unit test
This PR fixes an issue where the 'builder' parameter was incorrectly affecting image tag calculation. The update to image_spec.py ensures builder is excluded from tag computation parameters. The unit test has been updated to validate that tags are computed using dynamic values from image_spec.tag instead of hard-coded strings, improving test accuracy and preventing potential build issues.
<br>
<br>
<br>
<br>
</div>
> Exclude the builder from image tag calculation

- flytekit/core/array_node_map_task.py
- tests/flytekit/unit/core/test_array_node_map_task.py
- tests/flytekit/unit/core/test_partials.py
fixes https://linear.app/unionai/issue/BB-3499/cannot-pass-arguments-of-type-list-to-a-partial-function-that-will-be
closes: https://github.com/flyteorg/flyte/issues/4325
w/ https://github.com/flyteorg/flyte/pull/6322 merged, we can now set lists for partials in map_tasks
remove check for list getting set in partials
Since this is reliant on a BE change, is there something that we set for ~"min flyte version" or do we need to make this backwards compatible w/ older flyte propeller versions?
```
from flytekit import map_task, task, workflow
import functools
import typing
@task
def demo_task(strings: typing.List[str], num: int) -> str:
return f"{num}".join(strings)
@workflow
def demo_wf(nums: typing.List[int] = [1, 2]) -> None:
map_task(functools.partial(demo_task, strings=["a", "b", …
```
> remove check of settings lists in partials

- flytekit/image_spec/default_builder.py
Pushing docker images from a local network with a bad upload speed can take forever, but buildx is capable of building docker images remotely. For a user who has buildx installed we should prefer this method rather than force them to compromise and use a different environment to use `ImageSpec`.
Remove `image` from the string altogether and let docker decide for us. Users who run `docker buildx install` will automatically alias this command for them, and therefore the flyte cli.
I tested this patch on a system with and without buildx to verify the command's functionality persisted.
1. Install Docker
2. (optional) Install the buildx plugin and configure a remote driver
3. Use an existing imagespec workflow to test:
```python
from flytekit import ImageSpec
sklearn_image_spec = ImageSpec( …
```
> Docker Buildx support in CLI

- flytekit/core/python_function_task.py
- tests/flytekit/unit/core/test_eager_cleanup.py
Kind of a follow-up item to https://github.com/flyteorg/flytekit/pull/3148 which added a cleanup task in a failure node.  
This PR just updates that task to use the same image for the failure task as the parent eager task.
Technically we don't need to do this, but it's helpful especially when the eager functionality itself is changing.
Tested end to end on sandbox and Union clusters.
This PR enhances EagerFailureHandlerTask to use the same container image as its parent eager task. Core module changes update task initialization to incorporate the container_image parameter. Tests have been refactored and expanded to verify this behavior, improving image sharing between tasks and test robustness.
<br>
<br>
<br> …
> Eager failure task to share image with parent

- flytekit/sensor/base_sensor.py
- tests/flytekit/unit/sensor/test_file_sensor.py
https://github.com/flyteorg/flyte/issues/5035
Previously, setting both `timeout` and `metadata` parameters simultaneously in a sensor would raise an error, regardless of whether `metadata` already contained a timeout.
This change allows both parameters to be used together as long as there's no conflict (i.e., `metadata.timeout` is None).
- Enhanced the timeout handling logic in `BaseSensor` to allow setting both `timeout` and `metadata` parameters when `metadata.timeout` is None
- Updated error message to be more specific about the conflict condition
- Added comprehensive test cases covering all timeout and metadata combinations
1. unit test
2. single binary
> [flyteagent] FileSensor Timeout (Remote Execution Only) Enhancement

- flytekit/extend/backend/base_connector.py
- flytekit/extend/backend/connector_service.py
- tests/flytekit/unit/extend/test_connector.py
NA
Allow agent to fetch the log and metrics from the external service, such as databricks and bigquery.
Add GetMetric and GetLog interface to the baseAgent
This PR extends the agent backend to fetch task metrics and logs from external services. It updates the base connector with new methods and enhances the connector service for asynchronous log and metrics retrieval. The changes support broader integration with services like Databricks and BigQuery.
<br>
<br>
<br>
<br>
</div>
> Add GetTaskMetrics and GetTaskLogs to connector service

- .github/workflows/pythonbuild.yml
- plugins/flytekit-geopandas/README.md
- plugins/flytekit-geopandas/flytekitplugins/geopandas/__init__.py
- plugins/flytekit-geopandas/flytekitplugins/geopandas/gdf_transformers.py
- plugins/flytekit-geopandas/setup.py
- plugins/flytekit-geopandas/tests/test_geopandas_plugin.py
- plugins/setup.py
Currently, there is no support for geopandas dataframes and one must likely return FlyteFile's instead of gpd.GeoDataFrame objects. 
This plugin adds support for encoding/decoding StructuredDatasets for geopandas dataframes. Specifically, we allow encoding to parquet and decoding from parquet, geojson and geopackage. This PR does **not** add support for shape files. 
Plugin level tests
TODO: register, run remotely, take screenshots.
This PR adds a new geopandas plugin to Flytekit, enabling encoding and decoding of geopandas dataframes. It implements data rendering, parquet encoding, and multi-format decoding with lazy module loading. The implementation includes both plugin-specific and global setup configurations, with comprehensive test …
> feat: add geopandas plugin

- flytekit/core/context_manager.py
- flytekit/core/node_creation.py
- flytekit/core/promise.py
- flytekit/core/python_function_task.py
- tests/flytekit/unit/core/test_dataclass_dynamic.py
https://flyte-org.slack.com/archives/CP2HDHKE1/p1740432192774269
When running the dynamic workflow locally, the subtask should return a promise/voidPromise instead of a Python value.
Add LOCAL_DYNAMIC_TASK_EXECUTION mode. Change the execution mode to `LOCAL_DYNAMIC_TASK_EXECUTION` when running the dynamic task locally.
unit tests
This PR introduces LOCAL_DYNAMIC_TASK_EXECUTION mode, updating flytekit's core components to support local dynamic task execution. Key changes in node_creation.py and promise.py modify execution state checks to utilize the new local mode. It also cleans up obsolete test functions and removes redundant dynamic task validations, streamlining the testing environment while enhancing reliability for local workflows.
<br> …
> Add LOCAL_DYNAMIC_TASK_EXECUTION mode

- plugins/flytekit-geopandas/flytekitplugins/geopandas/gdf_transformers.py
- plugins/flytekit-geopandas/tests/test_geopandas_plugin.py
Geopandas plugin type support for geopandas dataframes was failing remotely. 
```
Message:
ArrowInvalid: Failed to convert outputs of task 'flyte.examples.test_geopandas_task' at position 0.
Failed to convert type <class 'geopandas.geodataframe.GeoDataFrame'> to type <class 'geopandas.geodataframe.GeoDataFrame'>.
Error Message: Missing bucket name in S3 URI.
```
Caused by `Path` transforming protocols e.g. `Path("s3://xyz") -> "s3:/xyz"
Use `get_random_remote_path` directly
I tested these changes with 
```
pip install git+https://github.com/ljstrnadiii/flytekit.git@fix_geopandas_plugin#subdirectory=plugins/flytekit-geopandas
```
within a container used on a remote flyte cluster.
This PR fixes a critical bug in the Geopandas plugin by …
> fix: use `get_random_remote_path` in geopandas plugin

- flytekit/core/node.py
- flytekit/core/promise.py
- flytekit/core/task.py
- tests/flytekit/unit/core/test_node_creation.py
fixes: https://linear.app/unionai/issue/BB-4976/cache-policies-dont-work-w-caching-subworkflows
Follow up changes:
- https://linear.app/unionai/issue/BB-4977/with-overrides-cache-doesnt-support-ignore-input-vars 
(need idl change)
- https://linear.app/unionai/issue/BB-4978/add-support-for-not-setting-cache-version-in-with-overrides
with_overrides doesn't work when setting Cache object
support setting Cache object in with_overrides + maintain backwards compatibility w/ existing params 
- added unit test
https://dogfood.cloud-staging.union.ai/console/projects/flytesnacks/domains/development/executions/acmrgrn887lb2kzn59dk/nodes
https://dogfood.cloud-staging.union.ai/console/projects/flytesnacks/domains/development/executions/avwrqd2cq7796skz6xqc …
> support using cache policies in with_overrides

- plugins/flytekit-spark/Dockerfile
- plugins/flytekit-spark/scripts/flytekit_install_spark3.sh
- plugins/flytekit-spark/setup.py
The upgrade to spark >= 3.4 is needed to support IPv6 and iceberg. This is very useful for k8s deployments and is currently breaking our pipelines. We implemented an ugly fix overwriting arguments with ImageSpecs. 
Without this we are seeing issues where the ip is not wrapped in [] fixed in 
https://github.com/apache/spark/pull/36868
Upgrade from spark 3.2.1 to 3.5.5
Ran test of spark plugin successfully
This PR upgrades Flytekit Spark integration to support Spark 3.4+ with IPv6 and Iceberg support for Kubernetes deployments. Updates include a new Spark base image, revised hadoop-aws dependencies, and modified installation scripts. The PR also fixes file permissions for spark jars directory, locks pyspark version to prevent compatibility …
> Add support for IPv6 and iceberg with spark >= 3.4

- flytekit/clis/sdk_in_container/__init__.py
- pyproject.toml
- tests/flytekit/unit/cli/pyflyte/test_grpc_verbosity.py
Originally noted in https://github.com/flyteorg/flyte/issues/6082
See some additional discussion in the [referenced issue](https://github.com/flyteorg/flyte/issues/6353#issuecomment-2774052213). 
This PR fixes issue #6082 by setting GRPC_VERBOSITY to 'NONE' by default in the SDK container module to silence unwanted grpc logging. It also removes upper bounds on grpcio and grpcio-status dependencies in pyproject.toml. Unit tests were added to validate both scenarios of environment variable presence.
<br>
<br>
<br>
<br>
</div>
> fix: set GRPC_VERBOSITY and remove grpcio upper bound

- .github/workflows/pythonpublish.yml
NA
CI is failing https://github.com/flyteorg/flytekit/actions/runs/14371904608/job/40296421255
`$GITHUB_REF` returns `'refs/tags/v1.2.3'` now instead of `refs/tags/v1.2.3`
```
echo 'refs/tags/1.16.0b4' | sed 's|refs/tags/||'
```
> ci: Update version extraction in workflows

- plugins/flytekit-async-fsspec/flytekitplugins/async_fsspec/s3fs/s3fs.py
- pydoclint-errors-baseline.txt
N/A
AsyncS3FileSystem does not work with latest changes to FlyteFile [here](https://github.com/flyteorg/flytekit/blob/2e2d2c2a561c76fa5a7642dd12544c250cff1a19/flytekit/types/file/file.py#L321)
1. Install both `flytekit` and `flytekitplugins-async-fsspec`
2. Run `FlyteFile(<remote-file>).__fspath__()`
> fix: Fix async s3fs to handle latest changes to FlyteFile

- plugins/flytekit-spark/flytekitplugins/spark/task.py
- plugins/flytekit-spark/tests/test_spark_task.py
Closes flyteorg/flyte#6405
In Spark fast registration workflows, `entrypoint.py` runs into an infinite loop while preparing to run the job
`flytekit` is taking everything in the current working directory and zip it, the archive file (`flyte_wf.zip`) is placed in the same directory that is being archived.
`shutil.make_archive` creates a zip file and archives the whole directory, including the zip file itself. In the case of Databricks clusters, it triggers a recursion and runs into an endless zipping loop.
The easiest way to fix this issue to create the archive outside of the directory to be archived.
Built a docker image with the fixed flytekit version and tested it E2E.
This PR fixes a critical bug in Spark fast registration workflow that …
> Bugfix for issue #6405: Fast registration runs into infinite loop

- plugins/flytekit-bigquery/flytekitplugins/bigquery/connector.py
- plugins/flytekit-bigquery/flytekitplugins/bigquery/task.py
- plugins/flytekit-bigquery/tests/test_bigquery.py
- plugins/flytekit-bigquery/tests/test_connector.py
necessary for the bigquery partnership with google.
added user agent to the bigquery client call per the format described by google.
This PR enhances the BigQuery integration by adding a custom user agent to meet Google partnership requirements. It reorganizes imports, adjusts client initialization with safer domain field handling using .get() method, and updates task configuration to include domain details. These changes improve error handling, ensure compliance, and validate the updated client configuration.
<br>
<br>
<br>
<br>
</div>
> add user agent to bigquery connector

- plugins/flytekit-spark/flytekitplugins/spark/task.py
- plugins/flytekit-spark/tests/test_spark_task.py
Closes flyteorg/flyte#6405
In Spark fast registration workflows, `entrypoint.py` runs into an infinite loop while preparing to run the job
`flytekit` is taking everything in the current working directory and zip it, the archive file (`flyte_wf.zip`) is placed in the same directory that is being archived.
`shutil.make_archive` creates a zip file and archives the whole directory, including the zip file itself. In the case of Databricks clusters, it triggers a recursion and runs into an endless zipping loop.
The easiest way to fix this issue to create the archive outside of the directory to be archived.
Built a docker image with the fixed flytekit version and tested it E2E.
This pull request addresses a critical bug in Spark fast registration …
> (backport) Fast registration runs into infinite loop

- flytekit/clis/sdk_in_container/run.py
- tests/flytekit/unit/cli/pyflyte/test_run.py
This change introduces a feature for users who use `pyflyte run --remote`. Currently, if a user wants to override the default `interruptible` setting defined in the workflow or launch plan, they cannot do so directly via the CLI. This PR adds an `--interruptible` option to `pyflyte run`, providing a command-line mechanism to control this behaviour for remote executions. 
This gives users more direct control over the interruptible setting for their workflow executions launched via `pyflyte run --remote`.
1.  Added a new `--interruptible` option to the `pyflyte run` command.
*   This option accepts boolean values (`true`, `false`, case-insensitive).
*   It allows users to explicitly set the `interruptible` property for the remote execution.
*   If the option is not provided, the default …
> Add an `--interruptible` option to `pyflyte run --remote`

- plugins/flytekit-airflow/setup.py
NA
The unit test in the Airflow plugins is failing since it's not compatible with airflow 3
pin apache-airflow version < 3.0.0
CI
This PR pins the apache-airflow dependency in setup.py to remain below version 3.0.0. The change prevents unit test failures associated with Airflow 3 and ensures environment stability. This is a straightforward dependency update with no functional code changes.
<br>
<br>
<br>
<br>
</div>
> fix(flytekit-airflow): pin apache-airflow version < 3.0.0

- flytekit/core/cache.py
- tests/flytekit/unit/core/test_cache.py
Closes flyteorg/flyte#6420
The `Cache` constructor's policies kwarg is typed `Optional[Union[List[CachePolicy], CachePolicy]]`, so it should accept a list of policies. But it throws an error when passing a `CachePolicy` list while initializing a Cache instance.
Fix flytekit code to correctly accept `CachePolicy` list while initializing a new Cache instance.
The test code:
Before the code fix, an error occured:
After the code fix, the error is gone:
This PR fixes a bug in the cache initialization process by adding proper handling for lists of CachePolicy objects. The change ensures the Cache constructor correctly processes policy lists, preventing type mismatch errors. The update includes test improvements to verify list acceptance …
> [BUG] flytekit: Cache object "policies" kwarg typing accepts a list, but errors if provided a list

- flytekit/core/base_task.py
`disable_deck` is deprecated. This makes my tests go yellow which is obviously an unbearable situation. Should be a straightforward merge. Searching for "self.disable_deck" does not return any matches after this fix.
Happy monday! 
This PR updates the task configuration by replacing the deprecated disable_deck property with enable_deck in flytekit/core/base_task.py. The change improves deck field assignment logic, ensuring deck_fields are only set when explicitly provided and enable_deck is true, which resolves previous testing issues.
<br>
<br>
<br>
<br>
</div>
> Replacing deprecated disable_deck with new enable_deck property

- flytekit/core/pod_template.py
- flytekit/remote/remote.py
- flytekit/tools/repo.py
- tests/flytekit/unit/core/test_pod_template_hash.py
We need to account for changes to the image and pod template based on resolution of env variables rather than a code change. e.g. a user may have an env variable that controls the base image of an imagespec. If the env variable changes, the version we compute should change, but currently it does not.
There are two paths fast registration can take:
1. pyflyte run -> version computed in remote.py
2. pyflyte register -> version computed in repo.py
In remote.py, we account for a change in `container_image` but not `pod_template`. In repo.py, don't account for for either.
1. Add a method to `PodTemplate` that hashes its contents.
2. Add a method that searches an entity for a pod template and adds its hash to a list.
3. Include the list of pod template hashes in the remote.py version …
> Include hash of pod template when computing fast registration version

- flytekit/image_spec/default_builder.py
- flytekit/image_spec/image_spec.py
- tests/flytekit/unit/core/image_spec/test_default_builder.py
N/A
Currently, `image_spec.tag` used by `image_spec.image_name()` calculates hash based on file contents every time. 
1. This may lead to "ImagePullBackOff" when running the registered component, because flyte uses different image_name for registration from what is used in image build and push if the file content was modified while the image is built.
2. Going through files every time isn't efficient
1. Make the `image_spec.tag` a cached_property, to avoid unnecessary recomputes.
2. If the image is actually built, check that the tag is still consistent with what was in the cache. This doesn't prevent if the content was just modified while creating docker context, but it should be rare. Alternative is to make image tag based on the created temporary context, but it will be a much bigger …
> Make image_spec.tag a cached property

- pyproject.toml
Bug in gcsfs: https://github.com/fsspec/gcsfs/issues/687
Causes GCP workflows to non-deterministically fail with 
```
.../site-packages/gcsfs/creden │
│ tials.py:219 in apply                                                        │
│                                                                              │
│ ❱ 219 │   │   self.maybe_refresh()                                           │
│                                                                              │
│ .../site-packages/gcsfs/creden │
│ tials.py:196 in maybe_refresh                                                │
│                                                                              │
│ ❱ 196 │   │   if self._credentials_valid(refresh_buffer):                    │
│ …
```
> gcsfs must be lower than 2025.5.0

- plugins/flytekit-onnx-scikitlearn/setup.py
- plugins/flytekit-spark/setup.py
Fix all plugin errors in CI
Unit tests are failing
Set an upper bound for PySpark, since the plugin isn’t compatible with PySpark 4
unit tests
> [CI] Fix plugin errors

- flytekit/remote/remote.py
We have a `FlyteRemote.activate_launchplan` convenience method, but there's no way to deactivate a launch plan from a remote object.
Adds a `deactivate_launchplan` to the `FlyteRemote` class
Tested on local sandbox
This pull request adds a new method, `deactivate_launchplan`, to the `FlyteRemote` class, enabling users to deactivate launch plans. This enhancement fills a gap in functionality alongside the existing activation method. Local tests were conducted to verify its proper operation.
</div>
> add FlyteRemote.deactivate_launchplan

- flytekit/remote/remote.py
- tests/flytekit/unit/remote/test_remote.py
If I have tasks/workflows that don't take any input, I should be able to run them on `FlyteRemote` without specifying an `inputs` arg:
```python
FlyteRemote.execute(my_task_with_no_inputs)
FlyteRemote.execute(my_task_with_no_inputs, inputs={})
```
Changes the signatures of the `FlyteRemote` execute methods so that `inputs` is an optional argument that defaults to None.
Unit tests were added.
This pull request enhances the FlyteRemote class by making the 'inputs' argument optional in its execute methods, allowing users to run tasks and workflows without passing an empty dictionary. Unit tests have been added to verify the new functionality.
</div>
> support FlyteRemote.execute with no inputs

- plugins/flytekit-ray/flytekitplugins/ray/task.py
During local execution workflows using multiple Ray tasks fail, because every task attempts to create a fresh ray instance. This PR simply sets turns on the flag to ignore ray re-initialization errors.
Ray init [params](https://docs.ray.io/en/latest/ray-core/api/doc/ray.init.html) contain `ignore_reinit_error` set to `True` when executing locally.
Tested this code version both locally and on flyte cluster with workflows using multiple ray tasks.
This pull request enhances the Ray initialization process by adding a parameter to ignore reinitialization errors during local workflow execution. This improvement increases the reliability and stability of workflows that involve multiple Ray tasks.
</div>
> Ignore ray reinit errors in local execution

- plugins/flytekit-spark/flytekitplugins/spark/agent.py
- plugins/flytekit-spark/tests/test_spark_task.py
- tests/flytekit/unit/experimental/test_eager_workflows.py
Closes https://github.com/flyteorg/flyte/issues/6471
Using Databricks connector without setting optional `spark_conf` field will cause `KeyError: 'sparkConf'`
If `sparkConf` is empty, use `{}`
Added unit test for DatabricksV2 with and without `spark_conf`
This pull request resolves a KeyError in Databricks tasks by using an empty dictionary when the optional spark_conf field is absent. It also includes unit tests for the new DatabricksV2 configuration to ensure functionality in both scenarios.
</div>
> [cherry-pick]  KeyError: 'sparkConf' occurs when running a Databricks task without spark_conf

- flytekit/remote/remote.py
Currently, registering tasks, workflows, and launchplans via notebooks doesn't work. This is because uploading the pickle-serialized task functions only happens in the `execute_local_*` methods.
This pull request enhances the registration process for tasks, workflows, and launch plans by introducing serialization of task functions in interactive mode. It prevents duplicate workflows, improving workflow management, and adds a caching mechanism for optimized retrieval of pickled target dictionaries. Additionally, it resolves previous issues with notebook-based task registration.
</div>
> enable notebook task/workflow registration

- flytekit/tools/translator.py
- tests/flytekit/unit/test_translator.py
Fixes https://github.com/flyteorg/flyte/issues/6463
The pod_spec was not included in the pod template when not using fast registration. This would lead to bad task specification errors on the backend since there would be no pod spec but a primary container name was configured.
Although this comes from our custom Armada plugin, the plugin is just using common pod_helpers code. 
> RuntimeExecutionError: max number of system retry attempts [31/30] exhausted. Last known status message: failed at Node[n0-n0]. RuntimeExecutionError: failed during plugin execution, caused by: failed to execute handle for plugin [armada]: generating job request: [BadTaskSpecification] invalid TaskSpecification, primary container [primary] not defined
After debugging I found that this was logged from propeller …
> Fix issue where pod template override pod spec was missing

- plugins/flytekit-inference/flytekitplugins/inference/nim/serve.py
these changes are required for the private registry support we rolled out with image spec. if `ngc_image_secret` is specified, we still go the old route. if the user provides the image pull secret as a secret and adds builder options to the image spec, we don't need to specify the image pull secret in the pod template.
made `ngc_image_secret` optional.
tested the NIM plugin by specifying the image pull secret as a flyte secret and adding it to imagespec.
This pull request enhances the NIM plugin by making the 'ngc_image_secret' parameter optional and introducing new builder options for improved private registry support, while maintaining compatibility with the old method. These changes aim to …
> make ngc image secret optional

- flytekit/remote/remote.py
https://github.com/flyteorg/flytekit/pull/3285
This pull request includes a small change to the register_script method in flytekit/remote/remote.py. The change sets the version attribute of serialization_settings before proceeding with entity registration.This pull request includes a minor update to the register_script method in flytekit/remote/remote.py. The change assigns the version to the serialization_settings object before registering the entity.
> [backport] Fix launch plan CLI registration

- flytekit/image_spec/default_builder.py
- tests/flytekit/unit/core/image_spec/test_image_spec.py
None
`ImageBuildEngine` supports recursively build `ImageSpec` if `base_image` is also an `ImageSpec`.
https://github.com/flyteorg/flytekit/blob/147c405d11abb222f88933d5ef3ed258df92ba99/flytekit/image_spec/image_spec.py#L523
However, it doesn't work with current `DefaultBuilder`. This PR includes a few minor changes so that such recursive build works.
1. `micromamba create` falls back to `micromamba install` in case the micromamba environment already exists.
2. Set workdir to `/` to have consistent behavior in the second build. Otherwise, workdir is set to `/root` in the first build, and `uv run` itself uses `/root/.venv` instead of `UV_PYTHON` (if uv lock or poetry lock was used).  
3.  When there are `/root/.venv` from the first build (if uv lock or poetry lock was used), `chown -R …
> Support recursive `ImageSpec` build by `DefaultBuilder`

- flytekit/remote/remote.py
The version won’t change if you update the requirements.txt file in the imageSpec and run a launch plan with Pyflyte.
```python
from union import workflow, task, LaunchPlan, ImageSpec
name="runlp",
requirements="requirements.txt",
pip_extra_args="--prerelease=allow",
)
@task(container_image=custom_image)
def something(region: str, start_date: str) -> str:
return f"{start_date}-{region}"
@workflow
def wf(region: str = "eu", start_date: str = "2024-01") -> str:
return something(region=region, start_date=start_date)
qa_lp = LaunchPlan.get_or_create(
name="qa_lp",
workflow=wf,
)
```
This pull request updates the `_get_image_names` method in `flytekit/remote/remote.py` to handle `LaunchPlan` entities. The most important change …
> Version hash should include the image from launchPlan.workflow.nodes

- plugins/flytekit-deck-standard/dev-requirements.in
- plugins/flytekit-deck-standard/setup.py
This pull request updates the dependency management in `plugins/flytekit-deck-standard/setup.py` to ensure compatibility with different Python versions.
Dependency management updates:
* Modified the `all` extras group to include a version-specific constraint for `pandas` when using Python 3.9, ensuring compatibility (`pandas<=2.2.3; python_version==3.9`), while keeping the latest version for Python versions above 3.9 (`pandas; python_version>3.9`). 
This pull request updates the dependency management in the `setup.py` file for the `flytekit-deck-standard` plugin by introducing version-specific constraints for the `pandas` library, ensuring compatibility with Python 3.9 and later versions. These …
> Specify pandas version for Python 3.9 for deck plugin

- plugins/flytekit-inference/flytekitplugins/inference/nim/serve.py
- plugins/flytekit-inference/flytekitplugins/inference/sidecar_template.py
This PR adds `ephemeral-storage` to the model server's requests and limits. The goal is to make it configurable at the user level.
Adds `ephemeral_storage` to the sidecar template and sets it to `20Gi` for the NIM model server.
This pull request enhances the model server's configuration by introducing an `ephemeral_storage` parameter, allowing users to specify storage requirements. The change is implemented in both the model server and sidecar template files, with a default value of `20Gi` for improved resource management.
</div>
> add ephemeral storage param to nim

- plugins/flytekit-spark/flytekitplugins/spark/schema.py
- plugins/flytekit-spark/flytekitplugins/spark/sd_transformers.py
- plugins/flytekit-spark/setup.py
[#6478](https://github.com/flyteorg/flyte/issues/6478#event-17898997613)
There is a new type of dataframe when  `pyspark`>=4.0.0. It's not recognized by the current structured dataset. Therefore, the type transformer will fail to serialize and deserialize it.
Add a new type of spark dataframe and register it.
Github CI will fail if we don't add the new type of dataframe and pyspark>=4.0.0.
This pull request adds support for the new `pyspark.sql.classic.dataframe.DataFrame` type for compatibility with `pyspark` version 4.0.0 and above. It includes new classes for reading and writing this DataFrame type, along with serialization and deserialization handlers. Plugin requirements have also been updated …
> Add support pyspark.sql.classic.dataframe.DataFrame transformer

- flytekit/core/schedule.py
- tests/flytekit/unit/core/test_schedule.py
Related to [#6470](https://github.com/flyteorg/flyte/issues/6470)
In the Flytekit SDK, it is proposed that an error be raised if the user enters a cron job with an invalid date (e.g., 0 0 31 2 *), preventing the schedule from being sent to the backend.
Add schedule date validation check in flytekit SDK.
Test workflow:
```
from datetime import datetime
from flytekit import task, workflow, CronSchedule, LaunchPlan
@task
def task_1(message: str) -> str:
return message
@workflow
def date_formatter_wf2() -> str:
return task_1("hello")
cron_lp = LaunchPlan.get_or_create(
name="cron_scheduled_lp",
workflow=date_formatter_wf2,
schedule=CronSchedule(
schedule="0 0 31 2 *",
),
)
```
After registering the launch_plan with invalid schedule date, the SDK throws error as expected.
<div …
> [BUG]Invalid cron date schedule creates infinite loop in flytescheduler

- flytekit/types/file/file.py
Related to the discussion in the [slack channel](https://flyte-org.slack.com/archives/CP2HDHKE1/p1753270501631199), when using `FlyteFile` with `Elastic`, the file cannot be downloaded and we will get warning:
```sh
.venv/lib/python3.12/site-packages/flytekit/types/file/file.py:356: RuntimeWarning: coroutine 'FileAccessProvider.async_get_data' was never awaited
```
It seems like the `FlyteFile` does not play well with underlying multiprocessing spawn
Based on my experiment, when we create the `_downloader` partial function, we use the
context in main process: https://github.com/flyteorg/flytekit/blob/eb5a67f76aaef96a44bde04afb72b87592cc8b7a/flytekit/types/file/file.py#L321-L326
But when we use `Elastic` and run the `FlyteFile` within each process via spawn, the memory
is not shared, but …
> [Fix] Issue when using FlyteFile with Elastic

- dev-requirements.txt
- flytekit/models/core/workflow.py
- tests/flytekit/unit/models/core/test_workflow.py
https://github.com/flyteorg/flytekit/pull/3292#issuecomment-3189158040
failed to compile if bound_inputs is none
Only sort the inputs when it's not none
unit test
This pull request enhances the workflow model by improving the handling of bound inputs, updating the flyteidl dependency for better flexibility, and refining the sorting logic for None values. A new unit test has been added to ensure correct behavior of ArrayNode without bound inputs.
</div>
> Handle None in sorted bound_inputs conditionally

- flytekit/bin/entrypoint.py
No log or stack trace when the task is hanging.
Register a signal handler, so that we can see the stacktrace when the task gets killed
Run a task, and kill the pod.
Locally,
```
$ cat > x.py
import faulthandler
import signal
faulthandler.register(signal.SIGUSR1)
import asyncio
asyncio.run(asyncio.sleep(100))
^C
$ python x.py &
[1] 68306
$ kill -USR1 68306
Current thread 0x00000001f8b74c80 (most recent call first):
File "/Users/ytong/.local/share/uv/python/cpython-3.13.1-macos-aarch64-none/lib/python3.13/selectors.py", line 548 in select
File %                                                                                                                                                                   "/Users/ytong/.local/share/uv/python/cpython-3.13.1-macos-aarch64-none/lib/python3.13/as …
```
> feat: Add faulthandler registration for SIGUSR1

- flytekit/models/admin/workflow.py
- flytekit/models/task.py
- tests/flytekit/unit/models/test_tasks.py
- tests/flytekit/unit/remote/test_remote.py
Currently, `short_description` is defined in the Task and Workflow protos but are not being piped through in the `flytekit` Task and Workflow models.
- `flytekit.models.tasks.Task` now takes a `short_description` as input
- `flytekit.models.admin.workflow.Workflow` now takes a `short_description` as input
Unit tests were updates 
This PR adds a new short_description parameter to Task and Workflow classes in flytekit models, including constructor modifications, property methods, and updated serialization for protocol buffer conversion. Tests have been updated to verify these new capabilities.
<br>
<br>
<br>
<br>
</div>
> add short_description to Task and Workflow model

- flytekit/clients/raw.py
- tests/flytekit/unit/clients/test_raw.py
The `FlyteRemote` class is documented as allowing gRPC options in the 
https://github.com/flyteorg/flytekit/blob/v1.16.3/flytekit/remote/remote.py#L284-L285.
These are still passed through to client construction, though we stopped passing these to the underlying gRPC channel creation in https://github.com/flyteorg/flytekit/pull/1458. (It's not clear to me if this was an oversight or intentional decision?)
This does mean that from v1.10.0 onward, there's no longer any way to provide additional options for the gRPC channel.
We have a custom proxy that requires additional gRPC options to be set at channel creation time (specifically, `grpc.default_authority`, though I can imagine others may be useful too). Unfortunately, it's not possible to configure this at any other point (e.g. with an …
> Restore behavior passing FlyteClient kwargs to gRPC channel creation

- dev-requirements.in
- flytekit/core/type_engine.py
- tests/flytekit/unit/core/test_list.py
- tests/flytekit/unit/core/test_type_engine.py
Closes flyteorg/flyte#6032
We should only serialize the variable and upload it once to reuse the same input.
To make the same Python value reuse the literal.
Add a local cache to store the literal that has been serialized.
Unit test
This pull request enhances the Flyte framework by implementing a local caching mechanism using an LRU cache for serialized literals, replacing the previous cache. This improvement boosts efficiency by reducing redundant serialization and uploads of identical Python values. A new unit test has been added to verify caching behavior when pandas is unavailable, and existing unit tests have been updated to ensure the new caching behavior is validated.
</div>
> [Core feature] Reuse same literals in the dynamic task

- flytekit/core/type_engine.py
- flytekit/models/types.py
- tests/flytekit/unit/types/structured_dataset/test_structured_dataset.py
NA
Handle empty external schema fields
set external schema fields to None if the fields are none in proto
unit test
This pull request fixes a bug related to empty external schema fields in the Flytekit library, updates import statements for clarity, and ensures proper handling of empty fields. These enhancements improve the robustness of the type engine and model types.
</div>
> fix(core): Handle empty external schema fields

- .github/workflows/pythonbuild.yml
- tests/flytekit/integration/remote/test_remote.py
Recently, the integration test often fail at test_attr_access_sd with user runtime error.
Thus, just extending the waiting time to test whether the integration test pass easily.
Extend the waiting time.
This pull request extends the waiting time in the integration test for the `test_attr_access_sd` function to reduce frequent test failures caused by user runtime errors. The adjustment aims to enhance the reliability of the integration tests.
</div>
> Extend waiting time in test_attr_access_sd

- flytekit/__init__.py
- flytekit/core/launch_plan.py
- flytekit/models/concurrency.py
- flytekit/models/launch_plan.py
- flytekit/tools/translator.py
- tests/flytekit/unit/core/test_launch_plan.py
- tests/flytekit/unit/models/test_concurrency.py
- tests/flytekit/unit/tools/test_translator_concurrency.py
This is associated to flyte change https://github.com/flyteorg/flyte/pull/6475, and RFC https://github.com/flyteorg/flyte/pull/5659 
These are the necessary changes needed to implement the ConcurrencyPolicy within flytekit. Namely, it will allow users to manage concurrency control via `LaunchPlan.create()` or `LaunchPlan.get_or_create()`
Unit tests are added, local testing is also done.
This pull request introduces a new concurrency policy feature in the Flytekit library, enhancing concurrency control through LaunchPlan methods. It updates existing models and launch plan parameters to incorporate these settings, improving overall functionality. Comprehensive unit tests have been added to ensure …
> Add concurrency policy
