flyteorg/flytekit

flytekit/common/types/containers.py, setup.cfg, tests/flytekit/unit/common_tests/types/test_containers.py
The exception fails to raise properly because an abstract class is used as the type comparison. This fixes that and adds two tests.
=> [Bug] Error message isn't properly raised because abstract class is accessed during rendering of the error

flytekit/plugins/__init__.py
There is a transient dependency on `k8s-proto` through `flyteidl.plugins`.  Since we only want to install k8s-proto when it is needed, we need to add another module to the lazy load list.
=> [Bug] Add Modules to Lazy Load List

flytekit/__init__.py, flytekit/engines/unit/engine.py, setup.cfg, tests/flytekit/unit/use_scenarios/unit_testing/hive_tasks.py
Hive unit tests are primarily interesting for validating the queries generated. This change surfaces the queries generated as the output of the `@hive_task` unit test.
=> Implement Hive Unit Test Behavior

flytekit/__init__.py, flytekit/clients/friendly.py, flytekit/clients/raw.py, flytekit/clis/flyte_cli/main.py, flytekit/clis/sdk_in_container/launch_plan.py, flytekit/common/launch_plan.py, flytekit/engines/flyte/engine.py, setup.py, tests/flytekit/unit/engines/flyte/test_engine.py
* Implement client endpoints for get and list on active launch plans.
* Implement tool command to activate launch plans regardless of having a schedule or not.
* Implement SDK fetch() method to retrieve the active launch plan when looking for a non-specific version
* Deprecates existing activation command (activate-all-schedules) in favor of the new command.
=> Implement client-side behavior for active launch plans

flytekit/configuration/__init__.py, flytekit/configuration/common.py, tests/flytekit/unit/configuration/conftest.py
Also brings back the ability to find a config file that is at a path configured by default in the environment.
=> Fix a Failing Unit Test for Configurations

flytekit/__init__.py, flytekit/clis/sdk_in_container/launch_plan.py, setup.py
In a previous version, click was upgraded to provide a deprecation message via the `click.command` decorator. However, this proved too limiting on users who had hard requirements on click versions. Therefore, allow older versions of click and just manually secho the deprecation message.
=> Loosen click version requirements

flytekit/clis/flyte_cli/main.py, flytekit/common/tasks/sidecar_task.py, flytekit/common/types/impl/schema.py, flytekit/models/task.py, flytekit/plugins/__init__.py, flytekit/tools/lazy_loader.py, setup.py, tests/flytekit/unit/engines/flyte/test_engine.py, tests/flytekit/unit/test_plugins.py, tests/flytekit/unit/tools/test_lazy_loader.py
Using an external lazy-load library was problematic because it had side-effectual behavior with imports outside the scope of `flytekit`.  Generally, the side-effects were harmless, but in more complicated projects using `numpy`, issues clearly began to arise.  To counteract this, I've implemented similar lazy-load behavior, but only for handles specifically known to `flytekit`.  Thus user-code that imports modules that we additionally lazy-load will be unaffected. Developers inside `flytekit` will be aware of the short-comings of lazy-loaded modules and should handle accordingly.
Also, added a CLI endpoint which got caught up in my commits and I'm too lazy to pull out into a separate PR.
=> Remove Sloth-Import and Test Internal Implementation

flytekit/common/tasks/spark_task.py
We must load pyspark via the plugins package or else random imports will fail when spark is not installed (and not intended for use).
=> Load pyspark via Plugins

flytekit/common/launch_plan.py, flytekit/common/tasks/task.py
Fetch should not be relative to internal version config. If that is the desired behavior, the user must explicitly set it.
=> [Bug] Remove Bad Fallback Behavior in Fetch

flytekit/clis/sdk_in_container/pyflyte.py, flytekit/clis/sdk_in_container/register.py
I moved the `--test` flag into the `register` subcommand scope as it doesn't seem to apply anywhere else.
I also removed the duplicate `--pkgs` arg from the `register` subcommand, as it is already defined at the main command level. Having them in two places makes it confusing as when each one applies will depend on the order of the args, e.g.
```
pyflyte --pkgs common.workflows serialize
```
will work, but
```
pyflyte --pkgs common.workflows register workflows
```
will not because the redefinition of `--pkgs` at the `register` subcommand level will override it and reset it back to the default. (You would have to put `--pkgs` in between register and workflows for it to apply for the register subcommand as it stands before this PR.)
This is unfortunately a breaking change though, as it …
=> Remove redundant args and narrow scope

README.md, tests/flytekit/unit/common_tests/exceptions/test_scopes.py, tests/flytekit/unit/tools/test_lazy_loader.py
I just went through the README to get myself setup for this repo and found a few issues. This PR fixes -
* ~requirements.txt so it contains all the packages needed to run the tests (presumably this file is only used for dev as it previously had pytest in it)~ looks like this was fixed recently
* tests so they assert exception messages properly. _Looks like this was changed between pytest 4 and pytest 5._ The repo now pins to pytest 4, so these tests currently work, although this change is backwards compatible
* README to reference `flytekit` instead of `flytekit2`
---
I should've gotten the latest changes before creating this PR :) The remaining changes are pretty minor, so don't mind if we close this instead.
=> Fix tests and instructions in README

flytekit/clis/sdk_in_container/register.py, tests/flytekit/unit/cli/pyflyte/conftest.py, tests/flytekit/unit/cli/pyflyte/test_register.py
This implements the `--test` functionality for the register subcommand. As it is now, the `--test` flag does nothing and workflows and tasks will be registered regardless of whether it is set.
I know there's some discussion about the usefulness of `--test` at all as full validation only happens server-side. I think there's still value to catch simple errors like missing imports, and also shows what Flyte has detected (to catch bad module paths, sys.path or missing `__init__.py` issues). Might need a better name though for clarity.
I also fixed a bug with a test mock - it mocks out flytekit.tools.module_loader.iterate_modules, which takes a sequence of names, but the mock only took in a single module name. It worked because there was also a mistake when specifying the value in the context.
=> Implement the register --test arg

flytekit/common/constants.py, flytekit/configuration/gcp.py, flytekit/configuration/platform.py, flytekit/interfaces/data/data_proxy.py, flytekit/interfaces/data/gcs/gcs_proxy.py
Continuation of https://github.com/lyft/flytekit/pull/6
reference: https://serverfault.com/questions/682708/copy-directory-structure-intact-to-aws-s3-bucket
=> Add GCS Support (with fixes)

flytekit/clis/sdk_in_container/register.py, setup.py
The `hidden=True` arg on `@click.option` was only introduced in Click 7.0. Bumping flytekit up to this version led to an incompatibility with lyftlearnclient, a package commonly installed with flytekit, which requires v6.x.
Ideally lyftlearnclient would be updated to use Click 7.x, but I don't have the time to learn another package, so replacing the `hidden=True` arg with an angry `DEPRECATED` message is the next best option. It was only there for cosmetic reasons, so this doesn't affect the reason for the original change.
Slack thread - https://lyft.slack.com/archives/C3BLDHN92/p1573498574188800
=> Remove hidden arg from register --pkgs option

flytekit/common/tasks/sdk_runnable.py
Missing the output name in the message, making the message pretty useless :)
```
/usr/local/lib/python3.6/dist-packages/flytekit/common/tasks/sdk_runnable.py:495: in _validate_outputs
???
E   flytekit.common.exceptions.user.FlyteValidationException: The output named '{}' was not specified in the task function.  Therefore, this output cannot be provided to the task.
```
=> Add missing format call on exception message

flytekit/interfaces/data/http/http_data_proxy.py
- the encoding is automatically preserved as http will transfer it as
binary
=> Allow all content types to be downloaded.

flytekit/common/exceptions/scopes.py, tests/flytekit/unit/common_tests/exceptions/test_scopes.py
When we tried to raise our exception inherited from `FlyteUserException`, the error code is not propagated to the task execution as we always get `USER:unknown`. The PR is to address the issue.
=> Propagating error code instead of unknown

flytekit/__init__.py, scripts/flytekit_build_image.sh
This allows an override so that when we try to build images for git repos with multiple container images, we can customize the name.
=> Ability to customize image name

flytekit/common/interface.py, tests/flytekit/unit/common_tests/tasks/test_sdk_runnable.py
If a task is missing an input, the error message is currently -
```
Input was not specified for: type {
simple: INTEGER
}
```
This updates that to include the name of the input that's missing -
```
Input was not specified for: value_in of type simple: INTEGER
```
=> Fix missing input error message

setup.py
This slows down installation and is too late to have an effect on the actual package build
=> Remove `setup_requires` of pip

flytekit/__init__.py, flytekit/clients/raw.py, flytekit/clis/auth/credentials.py, flytekit/configuration/platform.py, tests/flytekit/unit/cli/auth/test_credentials.py
I realized while testing things a bit more locally that just having one endpoint was insufficient - flyte-cli and pyflyte currently leverage the gRPC Python Flyte Admin client.  However, discovery needs the HTTP endpoint.  Even though in production both are served on the same endpoint and traffic is handled through ingress, this is not always the case, and we want to support the use-case where gRPC Admin and HTTP Admin are hosted separately.
We were debating just adding a separate config for discovery alone, but ultimately it makes more sense to split out the existing URL config into two objects, especially if the above pattern is something we want to continue to support.  However, in the interest of not making people migrate, and not writing migration code in this PR, we're just …
=> Changes to Auth configurations

setup.py
`pip install flytekit`
```
...
ERROR: botocore 1.13.41 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
...
```
This usually has no issue but recently we started to get error like:
```
File "/root/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
ws.require(__requires__)
File "/root/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
needed = self.resolve(parse_requirements(requirements))
File "/root/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 …
```
=> botocore requires python-dateutil lower than 2.8.1

flytekit/__init__.py, flytekit/clis/flyte_cli/main.py
This change introduces a lookup against the admin `config/v1/flyte_client` endpoint to discover values necessary to write a config when it doesn't exist.
=> Add option to write default config file

flytekit/__init__.py, flytekit/clis/flyte_cli/main.py
Basically, this makes it so that,
* If you don't have a `~/.flyte/config` file...
* `flyte-cli -h host.com` will use `host.com`
* Not having a `-h` switch will fail
* `flyte-cli --insecure` will use insecure connections
* `flyte-cli` without `--insecure` will use secure.
* If you do have a `~/.flyte/config` file...
* `flyte-cli -h host.com` will use `host.com`
* Not having a `-h` switch will default to the value set in the config file.  If not set in the config file, the command will fail.
* `flyte-cli --insecure` will use insecure connections
* `flyte-cli` without `--insecure` will use the setting in the config file.  If not set in the config file, it will pick up the default, which is `False` and only use secure connections.
=> Fixing host and insecure flag handling

flytekit/common/nodes.py, setup.py
As in version 2.0 the method was changed from `iteritems` to `items`, it seemed easiest to connect the two in `__getattr__` as `_six.items` doesn't exist.
The reason to upgrade sortedcontainers is to support python3.8: in that version, the path that it imports ABCs from will no longer exist: 
```
/srv/venvs/service/trusty/service_venv_python3.7/lib/python3.7/site-packages/sortedcontainers/sortedlist.py:9
/srv/venvs/service/trusty/service_venv_python3.7/lib/python3.7/site-packages/sortedcontainers/sortedlist.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import Sequence, MutableSequence
```
In addition, `super(ParameterMapper, self).__getattr_` doesn't exist.
=> Relax constraints on sortedcontainers for python3.8

.github/workflows/pythonpublish.yml
From looking at the release page and https://pypi.org/project/flytekit/#history, it doesn't seem like there's a perfect fit between releases made on github and published.
This should automate that process. Can you please help me by setting the secrets? https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
=> Add Github action for release

flytekit/__init__.py, flytekit/plugins/__init__.py
Pandas v1.0.1 is out. We would like to start consuming it in `etamodels`.
=> Bump pandas to 1.0.0

.travis.yml
We use this now: https://github.com/lyft/flytekit/blob/master/.github/workflows/pythonpublish.yml
=> Remove the travis version of pypi push now that we have github workflows

flytekit/interfaces/data/gcs/gcs_proxy.py, tests/flytekit/unit/interfaces/data/gcs/test_gcs_proxy.py
Problem: When flyte propeller set the `--output-prefix` to `{gcs_bucket}/propeller/{workflow_name}-development-{execution_id}/{task_name}/data/0`, gsutil write the `output.pb` to `/0` file instead of creating a new folder `0` and upload the file `output.pb` to the `0` folder. When flyte propeller trying to validate the '0' folder, it could not find `output.pb` file and fill the task.
Fix: Append `/` to the output dir fixes the issue
=> Append '/' to remote_path for gcs

flytekit/__init__.py, flytekit/common/tasks/sidecar_task.py, tests/flytekit/unit/sdk/tasks/test_sidecar_tasks.py
Fixes https://github.com/lyft/flyte/issues/180 so that the vanilla flytekit `gpu_request` & `gpu_limit` attributes get respected in the primary sidecar container.
For background, we replace [GPU](https://github.com/lyft/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/container_helper.go#L22) requests/limits with the[ nvidia/gpu resource name](https://github.com/lyft/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/container_helper.go#L24).
Capitalization doesn't affect pod spec unmarshaling (tested in flyteplugins)
=> Don't modify resource names when generating sidecar pod spec

flytekit/__init__.py, flytekit/common/tasks/sidecar_task.py, tests/flytekit/unit/sdk/tasks/test_sidecar_tasks.py
Reverts lyft/flytekit#88
Originally this was a misguided fix for https://github.com/lyft/flyte/issues/180, because flyteplugins updates all "[GPU](https://github.com/lyft/flyteplugins/blob/master/go/tasks/pluginmachinery/flytek8s/container_helper.go#L22)" resources with the appropriate nvdia full resource name.
However, https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L4623 uses the lower case name for referencing cpu.
Furthermore, when we build Flyte container tasks we never even use "GPU", but rather the full nvidia name anyways (https://github.com/lyft/flytepropeller/blob/f487cfe6e4d35b52f6f9cb399cceb5abf4a0595a/pkg/utils/k8s.go#L58)
=> Revert "Don't modify resource names when generating sidecar pod spec"

flytekit/__init__.py, flytekit/clients/raw.py
When using auth, we need to send the gRPC metadata along to all calls on the stub.  It appears some were missed.
_NA_
OR
=> Add metadata to all calls to Admin

flytekit/__init__.py, flytekit/clients/friendly.py, flytekit/clients/raw.py, flytekit/clis/flyte_cli/main.py, flytekit/models/admin/workflow.py, setup.py
This change allows a user to update workflow state using the flyte-cli
Tested on flyte staging and checked on portal that the state was correctly modified.
https://github.com/lyft/flyte/issues/235
_NA_
=> Add cli option to update workflow

flytekit/__init__.py, flytekit/clients/friendly.py, flytekit/clients/raw.py, flytekit/clis/flyte_cli/main.py, flytekit/models/admin/workflow.py, setup.py
=> Revert "Add cli option to update workflow"

flytekit/__init__.py, flytekit/clients/friendly.py, flytekit/clients/raw.py, flytekit/clis/flyte_cli/main.py, flytekit/models/named_entity.py, tests/flytekit/unit/models/test_named_entity.py
This change implements setting/updating the description of a named entity.  For background, a NamedEntity includes a task, workflow or launch plan for a specific {Project, Domain, Name} combination across versions. NamedEntities for all resource types have mutable descriptions. Furthermore, workflows also have a state attribute which enables their visibility in the console.
https://github.com/lyft/flyte/issues/235
_NA_
=> Implement UpdateNamedEntity in flyte-cli

flytekit/__init__.py, flytekit/common/workflow.py, flytekit/models/core/workflow.py, flytekit/sdk/workflow.py, setup.py, tests/flytekit/unit/models/core/test_workflow.py, tests/flytekit/unit/sdk/test_workflow.py
Allow a user to specify `queueing_budget` parameter for their workflow. This parameter corresponds to the amount of time a user is willing to wait for a workflow to be executed.
FlyteIDL PR: https://github.com/lyft/flyteidl/pull/50
https://github.com/lyft/flyte/issues/245
_NA_
=> Enable queuing_budget in Workflow Metadata

flytekit/common/tasks/sdk_runnable.py
The logging message was logging the Types instead of logging the name of the input, which is a more legible and precise error.
I changed this in the Github UI. flytekit was logging a value of a dict instead of the key of the dict. I made the appropriate change.
=> log the input name instead of value input

flytekit/__init__.py, flytekit/common/tasks/generic_spark_task.py, flytekit/common/tasks/spark_task.py, flytekit/models/task.py, flytekit/sdk/spark_types.py, flytekit/sdk/tasks.py, flytekit/sdk/types.py, tests/flytekit/common/workflows/scala_spark.py
Makes it easier to integrate a non-Python Spark Job as a task in Flyte. Issue : https://github.com/lyft/flyte/issues/266 
_NA_
OR
=>  Generic Spark Integration

flytekit/__init__.py
New release v0.7.0
NA
https://github.com/lyft/flyte/issues/301
NA
=> Flytekit v0.7.0 release

.travis.yml, flytekit/__init__.py, flytekit/clis/sdk_in_container/serialize.py, scripts/flytekit_build_image.sh
Minor switch in `flytekit_build_image.sh` and removing python 2.7 tests.  Minor bug fix.
Adding a switch to the image building script to not push even when a `REGISTRY` section is detected.  Currently the behavior is that if a `REGISTRY` is present, it'll automatically be pushed.  By not pushing users can build images locally, but still have the image tagged with the full name `docker.io/corp/myworkflow:<sha>`
Python 2.7 is no longer supported.
When the `-f/--folder` option is specified, only the Identifier file was being written there.  We need to write both files there.
No issue, can create one, but minor cleanup only.
NA
=> Image build script flag and remove 2.7 from travis, bug for serialize

flytekit/__init__.py, flytekit/clients/friendly.py, flytekit/clis/flyte_cli/main.py, scripts/flytekit_build_image.sh, tests/flytekit/unit/cli/test_flyte_cli.py
As detailed in the linked issue, this will take the output of the [previous pr](https://github.com/lyft/flytekit/pull/104) and register them with `flyte-cli`.
This uses the same core logic as in the old registration path.  The only difference is that the data is read from files - files which follow a specific set of rules (detailed in help) - and the `to_flyte_idl()` call has already been made.
https://github.com/lyft/flyte/issues/225
NA
=> File-based registration

flytekit/__init__.py
Minor PR...
The 0.7.0 version of flytekit was deployed as part of Flyte milestone 0.3.0.  The features since then on master I'm going to try to make a full minor version increase, hence 0.8.0x, and reserve the 0.7.x moniker for patches.
=> Amend master version to 0.8.x

flytekit/__init__.py, flytekit/common/tasks/sdk_dynamic.py, tests/flytekit/unit/models/test_dynamic_wfs.py
Please see the issue for a proper description.
If a launch plan/subworkflow node does not have outputs, currently there is no dynamic job spec created.  This was the main issue this PR is meant to address.
Also discovered that if the workflow/launchplan yielded in a dynamic node does not have outputs, but does have inputs, those inputs would not be generated.  This was from improper indentation from the first time this code was created.
This code needs to be cleaned up... a lot.  See the follow-up issue.
https://github.com/lyft/flyte/issues/282
https://github.com/lyft/flyte/issues/226
=> Add condition to generation of dynamic job spec

flytekit/__init__.py, flytekit/common/tasks/sdk_dynamic.py, tests/flytekit/unit/sdk/tasks/test_dynamic_tasks.py
Enable dynamic_tasks to yield dynamically generated workflows.
```
@inputs(task_input_num=Types.Integer)
@inputs(decider=Types.Boolean)
@outputs(out=Types.Integer)
@dynamic_task
def workflow_builder(wf_params, task_input_num, decider, out):
wf_params.logging.info("Running inner task... yielding a code generated sub workflow")
input_a = Input(Types.Integer, help="Tell me something")
if decider:
node1 = inverse_inner_task(num=input_a)
else:
node1 = inner_task(num=input_a)
MyUnregisteredWorkflow = workflow(
inputs={
'a': input_a,
},
outputs={
'ooo': Output(node1.outputs.out, sdk_type=Types.Integer, help='This is an integer output')
},
nodes={
'node_one': node1,
}
)
setattr(MyUnregisteredWorkflow, 'auto_assign_name', manual_assign_name)
MyUnregisteredWorkflow._platform_valid_name = …
```
=> Write Tasks and SubWorkflows in Dynamic Job Spec

flytekit/__init__.py, flytekit/common/mixins/artifact.py, flytekit/common/nodes.py, flytekit/common/tasks/executions.py, flytekit/common/workflow_execution.py, flytekit/plugins/__init__.py
The `wait_for_completion` method calls a full sync every poll period even though a full sync is really only needed after the underlying closure indicates the artifact has transitioned to complete.
https://github.com/lyft/flyte/issues/312
_NA_
=> Add _sync_closure call to reduce load from wait_for_completion calls.

flytekit/__init__.py, flytekit/clis/sdk_in_container/launch_plan.py, flytekit/clis/sdk_in_container/pyflyte.py
I want just a bit more information to be logged in this command.
* Adding code to the main pyflyte command to respect the internal logging configuration option. If set, it will be used.
* Added a couple log lines.
NA
NA
=> Adding logging to pyflyte launch plan activation command

flytekit/__init__.py, flytekit/clients/friendly.py, flytekit/clients/raw.py, flytekit/clis/flyte_cli/main.py, flytekit/models/matchable_resource.py, tests/flytekit/unit/models/test_matchable_resource.py
Currently setting overridable matchable resources requires configuring the json for a post request which can be cumbersome - especially when auth is enabled.
For more background on matchable resource types, how they're used and how they're applied - see [managing customizable resources 
](https://lyft.github.io/flyte/administrator/install/managing_customizable_resources.html)
https://github.com/lyft/flyte/issues/335
_NA_
=> Make MatchableResources configurable through flyte-cli

flytekit/__init__.py
Bump version to 0.9.1 to make the OnFailurePolicy available when FlyteKit's upgraded.
lyft/flyte#191
=> Bump version to 0.9.1

flytekit/__init__.py, setup.py
Following the discussion from https://github.com/lyft/lyftlearnclient/pull/595 bumping up the version for `python-dateutil`.
STEP 2: [FAILED] `control run piptools.compile lyftlearnclient` There is a clash on `python-dateutil`. `GE` expects `python-dateutil>=2.8.1` but `flytekit` expects `python-dateutil<2.8.1` as from here https://github.com/lyft/flytekit/blob/8eb27ec61771f44bb25614401377b2f70b2c565c/setup.py#L38 There is no later version of `flytekit`.
=> bump up version for python-dateutil to support lyftlearnclient upgrade and enable great expectations latest version

flytekit/__init__.py, flytekit/common/mixins/launchable.py, flytekit/common/mixins/registerable.py, flytekit/common/tasks/presto_task.py, flytekit/common/tasks/task.py, flytekit/models/common.py, tests/flytekit/unit/common_tests/tasks/test_task.py
This change implements register_and_launch for single task executions featuring containerless tasks.
The use case for this feature is in-notebook task execution. Because only containerless tasks do not need to update an image during task iteration, only those are supported for register_and_launch.
https://github.com/lyft/flyte/issues/256
https://github.com/lyft/flyte/issues/221
=> Register and launch single task execution

flytekit/__init__.py, flytekit/common/types/impl/schema.py, tests/flytekit/unit/common_tests/types/test_schema.py
A user internally wanted to subclass one of our primitive types, and then created a separate type engine, and used said engine to resolve types.  However, since the Datetime primitive type was subclassed, the comparison failed.
This relegates the comparison to a common denominator, namely the Flyte literal type object.
Internal issue only
NA
=> Use to_flyte_literal_type() when comparing schema columns

flytekit/__init__.py, flytekit/common/workflow.py, flytekit/models/core/workflow.py, flytekit/sdk/workflow.py, tests/flytekit/unit/models/core/test_workflow.py, tests/flytekit/unit/sdk/test_workflow.py
This fix removes access of queuing_budget in flytekit as this is not used and there has been refactoring that renders the current Interface incorrect. Problems,
queuing_budget renamed to queueing_budget
field 1 in WorkflowMetadata is now QualityOfService instead
queueing budget is part of the QOSSpec and is one of.
Usage for the users was still access to queueing budget
Flytekit was still accessing workflowmetadata.queuing_budget and this breaks in production for anyone who upgrades to latest flytekit.
Bug Fix
Feature
Plugin
Code completed
Smoke tested
Unit tests added
Code documentation added
Any pending items have an associated Issue
Complete description
Currently eliminated queuing_budget as it is not used. It should be re-introduced carefully thinking about the interface …
=> bug; Queuing budget no longer exists. Quality of service is not yet integrated

flytekit/__init__.py, flytekit/clis/flyte_cli/main.py
It appears my previous [attempt](https://github.com/lyft/flytekit/pull/73/files) at fixing this failed.  I think now everything is actually fixed.
it appears that flags operate like toggles. If both the default is true and the flag is passed in the command, they negate each other and it's as if it's not passed.
Tested with:
* `-i` right after flyte-cli
* `-i` after the subcommand
* without the `-i` flag at all,
while the config file had
* "insecure=True"
* "insecure=False"
* insecure not specified.
Also for flags, there is no difference between a required one and a not-required one it seems.
NA
NA
=> Fix insecure flag

flytekit/__init__.py, flytekit/clients/raw.py, flytekit/clis/auth/credentials.py, flytekit/clis/flyte_cli/main.py, tests/flytekit/unit/clients/test_raw.py
When the `RawSynchronousFlyteClient` is created, it's given a host.  We should prefer to use this instead of retrieving from configuration again.
Save the url passed into the client instead and when it comes time to get the Admin endpoints, use it first.  Configuration fallback has been left in there in case we make the client url optional down the road.
https://github.com/lyft/flyte/issues/368
NA
=> Prefer the URL used to create the client object instead of configuration

flytekit/__init__.py, flytekit/clis/flyte_cli/main.py
Adding a command `execute-launch-plan-and-wait`, by using which users kick off an execution and enforce a wait for the completion of the execution. This can be useful for kicking off workflows as tests in CI.
_NA_
=> Add a --watch argument to execute-launch-plan command and add a watch-execution command

flytekit/__init__.py, flytekit/configuration/gcp.py, flytekit/interfaces/data/gcs/gcs_proxy.py, tests/flytekit/unit/interfaces/data/gcs/test_gcs_proxy.py
Adds multiprocessing support to the GCS data proxy via the `-m` flag to `gsutil`. This can be turned on via the `gcp.gsutil_parallelism` configuration variable.
We can achieve much better performance with `gsutil` with the `-m` flag that enables parallelism via multiple processes/threads. This will come in extremely handy when up/downloading a large number of files or just a few large files. See: https://medium.com/@duhroach/gcs-read-performance-of-large-files-bd53cfca4410.
I figured that the best way to enable this will be via the `[gcp]` configuration block: `gsutil_parallelism`. Further tweaking of the parallelism behavior can be achieved via the `.boto` config file: https://cloud.google.com/storage/docs/boto-gsutil
https://github.com/lyft/flyte/issues/429
_NA_
=> Add support for parallelism with gsutil command in GCSProxy

flytekit/__init__.py, flytekit/common/types/impl/schema.py, tests/flytekit/unit/common_tests/types/impl/test_schema.py
Basically if you `pip install numpy==1.18` this works.
```
python -m pytest -svv tests/flytekit/unit/common_tests/types/impl/test_schema.py::test_type_promoted_schema_read_with_fastparquet                                                                                  
```
If you `pip install numpy==1.19`
it fails.  Basically in 1.18 and earlier, if you declared a bool column and had Nones in the data, it would automatically promote the column to an object.  Starting with 1.19, they're no longer do this.  The 1.19 behavior makes more sense IMO, since this is how most typed languages work.
Removed the offending test.
https://github.com/lyft/flyte/issues/430
In working on this, also discovered that the fastparquet test wasn't actually setting the fastparquet engine.  Doing so ended up …
=> Remove test breaking numpy 1.19

README.md, flytekit/__init__.py, flytekit/models/literals.py, tests/flytekit/unit/models/test_literals.py
There's a bug in the `value` function where if a `0`, `""`, `0.0`, or `False` is set as the Primitive, then the function would always return `None`.
=> Fix Primitive.value returning None issue

flytekit/__init__.py, setup.py
If you upgrade flytekit, flyteidl will not be upgraded and this is required for Sagemaker
NA
=> Sagemaker is only available in v0.18.0 onwards.

flytekit/__init__.py, flytekit/common/tasks/sdk_dynamic.py, flytekit/common/tasks/sidecar_task.py, flytekit/sdk/tasks.py, tests/flytekit/unit/sdk/tasks/test_dynamic_sidecar_tasks.py, tests/flytekit/unit/sdk/tasks/test_dynamic_tasks.py
The new class `SdkDynamicSidecarTask` is a hybrid of the dynamic and sidecar tasks. The core logic in `SdkDynamicTask` was moved into a mixin (`SdkDynamicTaskMixin`) that was then used as a base in `SdkDynamicTask` and `SdkDynamicSidecarTask` respectively. `SdkDynamicSidecarTask` allows us to use the same mechanisms for specifying custom pod specs in `sidecar_task`s for `dynamic_task`s as well!
NA
=> Add dynamic sidecar tasks

flytekit/__init__.py, setup.py
We are seeing runtime errors like:
```
[v0wh9mudkz-sub-wf-task-0] terminated with exit code (1). Reason [Error]. Message: 
File "/opt/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
ws.require(__requires__)
File "/opt/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
needed = self.resolve(parse_requirements(requirements))
File "/opt/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.24.3 (/opt/venv/lib/python3.6/site-packages), Requirement.parse('urllib3>=1.25.10'), {'responses'})
```
We are raising the requirement to 2.x as proper semantic …
=> Bump urllib3 requirement

flytekit/engines/flyte/engine.py, flytekit/models/execution.py, setup.py, tests/flytekit/unit/engines/flyte/test_engine.py, tests/flytekit/unit/models/test_execution.py
Building off of https://github.com/lyft/flyte/issues/419, this change reads full execution input and output data when it is returned inline.
https://github.com/lyft/flyte/issues/478
_NA_
=> Use full execution inputs and outputs data

README.md, flytekit/__init__.py, flytekit/tools/lazy_loader.py
Add support for `all` with Spark 3.x. 
Ref: https://github.com/lyft/flyte/issues/482  and https://github.com/lyft/flyte/issues/483 to move default to Spark 3.x at some point. 
https://github.com/lyft/flyte/issues/482
https://github.com/lyft/flyte/issues/483
=> Add support for flytekit[all3] with Spark 3.x

flytekit/__init__.py, flytekit/bin/entrypoint.py, flytekit/common/tasks/sdk_runnable.py, flytekit/contrib/notebook/tasks.py, flytekit/engines/common.py, flytekit/engines/flyte/engine.py, flytekit/interfaces/data/data_proxy.py, flytekit/interfaces/data/gcs/gcs_proxy.py, flytekit/interfaces/data/s3/s3proxy.py, tests/flytekit/unit/bin/test_python_entrypoint.py, tests/flytekit/unit/interfaces/data/gcs/test_gcs_proxy.py, tests/flytekit/unit/interfaces/data/s3/test_s3_proxy.py, tests/flytekit/unit/sdk/tasks/test_dynamic_sidecar_tasks.py, tests/flytekit/unit/sdk/tasks/test_sidecar_tasks.py
Please see the linked issue for more information.  This adds a `--raw-output-data-prefix` switch to the pyflyte-execute command and container args will be changed so that they're registered with `--raw-data-output-prefix {{.rawOutputDataPrefix}}`.  Propeller will then fill them in.
*Release this change last, after testing propeller/plugins*
* The AWS and GCP data proxy classes now take in its constructor a prefix which will be used when `get_random_path` is called.  If it is missing it will fall back to the current behavior of looking up either the S3 shard formatter config or the GCS prefix config.
* Added switch to click command
* Added switch and template placeholder to sdk runnable task and notebook task container args.
https://github.com/lyft/flyte/issues/211
NA
=> Add --raw-output-data-prefix to the pyflyte-execute command

flytekit/__init__.py, flytekit/common/workflow.py, flytekit/sdk/workflow.py, flytekit/tools/module_loader.py, tests/flytekit/unit/common_tests/test_workflow.py
Adds a flag to control whether a default launchplan should be generated for the workflow at registration time. The default behavior is to do so.
E.g.
```
@workflow_class(disable_default_launch_plan=True)
def MyWorkflow():
...
my_lp = MyWorkflow.create_launch_plan(...)
#my_lp will be the only launchplan created for this workflow
```
https://github.com/lyft/flyte/issues/462
=> Add a flag to disable default launch plan generation

README.md, flytekit/common/constants.py, flytekit/common/tasks/tensorflow_task.py, flytekit/models/task.py, flytekit/plugins/__init__.py, flytekit/sdk/tasks.py, tests/flytekit/unit/sdk/tasks/test_tensorflow_task.py
Tensorflow plugin for Flyte that leverages https://github.com/kubeflow/tf-operator to run distributed tensorflow jobs on k8s.
Tensorflow plugin for Flyte that leverages https://github.com/kubeflow/tf-operator to run distributed TensorFlow jobs on k8s.
https://pypi.org/project/flyteidl/0.17.36/
Related PRs:
TFOperator support in FlytePlugins
https://github.com/lyft/flyte/issues/115
Subtask:
https://github.com/lyft/flyteidl/pull/71
https://github.com/lyft/flyteplugins/pull/103
https://github.com/lyft/flyte/pull/424
_NA_
_NA_
=> tensorflow plugin implementation

flytekit/__init__.py, flytekit/clis/sdk_in_container/register.py
This code doesn't fix any issue here, but addresses an issue with an internal Lyft library that allows this open-source code to interact with Lyft internal systems.
Iterating through the list of objects that need to be registered twice triggers the incorrect register call.  Since the double-iteration was just used for logging, we can just remove it.
NA
NA
=> Remove double-iteration (legacy code fix)

flytekit/interfaces/data/s3/s3proxy.py
This patch fixes incorrect error message formatting while retrying failed AWS CLI command (it uses unsupported ```{}``` syntax). Switched to ```format``` method.
=> Incorrect error formatting

flytekit/__init__.py, flytekit/common/mixins/registerable.py, flytekit/common/tasks/sdk_runnable.py, flytekit/common/tasks/spark_task.py, flytekit/engines/unit/engine.py, flytekit/models/task.py, tests/flytekit/unit/models/test_dynamic_spark.py, tests/flytekit/unit/sdk/tasks/test_spark_task.py
A user can now easily override spark and hadoop conf using dynamic tasks or when registering a workflow. This does not solve overrides completely, but is step 1 towards it
```python
@spark_task(spark_conf={...}, hadoop_conf={...})
def foo(...):
pass
@dynamic_task
def dynamic():
t = foo.with_overrides(spark_conf={})()
yield t
```
SdkSparkTask has a special method called with_conf(...) that creates a new flyte task with the override configuration.
https://github.com/lyft/flyte/issues/528
_NA_
=> Spark Configuration can be dynamically updated or overriden

flytekit/__init__.py, flytekit/common/tasks/spark_task.py, tests/flytekit/unit/sdk/tasks/test_spark_task.py
SparkConfig and HadoopConfig are available from the declared Flyte task
```python
@spark_task(spark_conf={"spark.driver.memory": "1g"}, hadoop_conf={"hadoop.s3committer":"x"})
def my_spark_task():
pass
print(my_spark_task.spark_conf)
```
Result
```bash
{
"spark.driver.memory": "1g",
}
```
=> SparkConf & HadoopConf are exposed

flytekit/__init__.py, flytekit/clis/flyte_cli/main.py
Port changes from https://github.com/lyft/flytekit/pull/191.
`-h/--host` flag does not get picked up for `watch-execution`:
```
> flyte-cli watch-execution -i -h localhost:51234 -u ex:sunflower-sandbox:default:f97312912bdfc476eab1
...
flytekit.common.exceptions.user.FlyteAssertion: No configuration set for [platform] url.  This is a required configuration.
```
`-i/--insecure` flag does not get picked up for `watch-execution`:
```
> FLYTE_PLATFORM_URL=localhost:51234 flyte-cli watch-execution -i -u ex:sunflower-sandbox:default:f37243487d6794178b76
...
E1003 02:24:42.122552000 4817231296 ssl_transport_security.cc:1439]    Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
...
```
However, this works:
```
> …
```
=> Make --insecure and --host flags work when watching an execution.

flytekit/__init__.py, flytekit/plugins/__init__.py
In generating docs, we noticed that tensorflow was missing.
Added to lazy load configuration and tested by running
```
pip install https://github.com/lyft/flytekit/archive/0f57f6a9af1459009c5ba61d669499ab440badce.zip#egg=flytekit[tensorflow]
```
NA
NA
=> Missing tensorflow setting

flytekit/annotated/interface.py, flytekit/annotated/task.py, flytekit/annotated/workflow.py, flytekit/bin/entrypoint.py, flytekit/common/tasks/spark_task.py, flytekit/engine.py, tests/flytekit/unit/use_scenarios/unit_testing/test_type_hints.py
Implement 2 extensions
Generic SQL task base and extended Spark Task
=> Cleanup extensibility

flytekit/annotated/context_manager.py, flytekit/annotated/interface.py, flytekit/annotated/promise.py, flytekit/annotated/task.py, flytekit/annotated/workflow.py, flytekit/engine.py, flytekit/models/interface.py, tests/flytekit/unit/use_scenarios/unit_testing/test_type_hints.py
Ignore unless you're ketan/haytham.
* Delete all the freeform param stuff
* Remove the fancier (original, on master) Interface object in favor of the straight model
* Factor out the loop that makes things into Promise objects
* Remove nested subwf execution arg
* Move transformation of wf outputs in local exec to the call function (search for "unpack result")
* Add SdkNode creation on subworkflow call
* Add list binding creation
* Change workflow binding to use the binding creator in the flytekit_engine file
* Allow workflow compile to be given native inputs
=> [ignore] Annotations changes

Makefile, dev-requirements.txt, flytekit/__init__.py, flytekit/plugins/__init__.py, requirements-spark3.txt, requirements.txt
- Flytekit has plugins for tensorflow and pytorch, but it does not
really depend on pytorch or tensorflow
-  Users should install their own versions of tensorflow and pytorch
https://github.com/lyft/flyte/issues/564
_NA_
=> Cleanup flytekit dependencies that bloat the package and are not used

flytekit/annotated/interface.py, flytekit/annotated/promise.py, flytekit/annotated/type_engine.py, flytekit/annotated/workflow.py, tests/flytekit/unit/use_scenarios/unit_testing/test_type_hints.py
Adds a new pandas dataframe transformer. This results in a generic schema
=> Simple Schema type support -> pandas dataframe

flytekit/annotated/interface.py, flytekit/annotated/type_engine.py, flytekit/annotated/workflow.py, flytekit/typing.py, tests/flytekit/unit/annotated/test_flyte_typing.py, tests/flytekit/unit/annotated/test_interface.py, tests/flytekit/unit/annotated/test_type_engine.py, tests/flytekit/unit/annotated/test_type_hints.py
for ketan/haytham
* Moved the `test_type_hints` file over into the annotated test dir.
=> [ignore] Annotations - file typing

flytekit/annotated/context_manager.py, flytekit/annotated/interface.py, flytekit/annotated/launch_plan.py, flytekit/annotated/node.py, flytekit/annotated/task.py, flytekit/annotated/workflow.py, flytekit/clis/sdk_in_container/serialize.py, flytekit/models/interface.py, tests/flytekit/unit/annotated/test_interface.py, tests/flytekit/unit/annotated/test_type_hints.py
ignore unless ketan/haytham.
* Adds a new Launch Plan class in the same pattern as the new Task and Workflow classes
* Remove the identifier_model.Identifier instantiations in Task and Workflow now that we handle it at serialization time.
* Call the type engine to create literals when making the ParameterMap in interface.
* Stupid oneof in Parameter tripped me up for hours. Thanks Haytham.
=> [ignore] Annotations launch plans

flytekit/annotated/type_engine.py, tests/flytekit/unit/annotated/test_type_hints.py
- We could stat and ensure that the passed string is a file, but
uploader will fail?
=> FlyteFilePath works with os.pathlike / str objects

dev-requirements.txt, flytekit/__init__.py, requirements-spark3.txt, requirements.txt, scripts/flytekit_sagemaker_runner.py, setup.py
My test SageMaker jobs were failing, but Chang-Hong's jobs worked. After investigating, we discovered that the issue is a text sort that should be a "natural" order sort.
Details for the issue in https://lyft.slack.com/archives/CUMH80X6W/p1604517799068200 and an explanation of this fix in https://lyft.slack.com/archives/CUMH80X6W/p1604526254078800.
JIRA link: https://jira.lyft.net/browse/AVSW-64440
Without this fix the error can be reproduced in a container with `flytekit` 0.14.x with the following:
```
root@4a9ab1c1ada7:/usr/local/bin# /usr/local/bin/python /usr/local/bin/flytekit_sagemaker_runner.py --__FLYTE_CMD_0_pyflyte-execute__ __FLYTE_CMD_DUMMY_VALUE__ --__FLYTE_CMD_10_s3://lyft-modelbuilder/88/q8i35ntlmg-jadoo-task-0__ __FLYTE_CMD_DUMMY_VALUE__ --__FLYTE_CMD_1_--task-module__ …
```
=> Fix to use natural sort for flytekit Sagemaker script

flytekit/annotated/node.py, flytekit/annotated/promise.py, flytekit/annotated/workflow.py, flytekit/common/utils.py
don't like this PR.  we'll merge and clean up later.
=> Annotations wf inputs

dev-requirements.txt, flytekit/__init__.py, requirements-spark3.txt, requirements.txt, setup.py, tests/flytekit/unit/models/test_dynamic_job.py, tests/flytekit/unit/models/test_tasks.py
* Changed setup.py to limit urllib3 to <1.26.0. That version has been giving users issues since it was released yesterday.
* Ran make requirements.
* Nit changes to tests
=> Annotations limit urllib3

flytekit/__init__.py, flytekit/bin/entrypoint.py, flytekit/clis/sdk_in_container/fast_register.py, flytekit/common/tasks/sdk_runnable.py
To support using pyflyte outside of the container, this change adds a `dest-dir` param to fast-registration so code distributions can be installed wherever a user decides.
https://docs.google.com/document/d/1n7DmKXaOv8dAb9eHD4TKqka6FsdJNs3Tugpf1I6nvMg/edit?usp=sharing
https://github.com/lyft/flyte/issues/554
_NA_
=> Fast registration: Make download destination dir configurable

flytekit/__init__.py, flytekit/tools/module_loader.py, tests/flytekit/unit/tools/test_module_loader.py
Adds support for single python files in the `sdk.workflow_packages` field of flyte configuration file.
Skip walking packages if they don't have a `__path__` variable.
https://github.com/lyft/flyte/issues/623
_NA_
OR
=> Properly handle packages that are single python files

flytekit/annotated/condition.py, setup.py, tests/flytekit/unit/annotated/test_serialization.py
Ensure that inputs variables to a branch node have unique names instead of copying the name from the promise as is.
https://github.com/lyft/flyte/issues/602
=> Annotations branch fix

flytekit/annotated/python_function_task.py, flytekit/annotated/resources.py, flytekit/annotated/task.py, flytekit/taskplugins/sidecar/__init__.py, flytekit/taskplugins/sidecar/task.py, tests/flytekit/unit/annotated/test_resources.py, tests/flytekit/unit/annotated/test_sidecar.py
Moved the resources to a separate location to avoid a circular dependency with task and python_function_task, let me know if it belongs elsewhere.
Also the foo().with_overrides(cpu="1") syntax is not implemented by these changes
=> Implement sidecar tasks and task resource specification

.travis.yml, flytekit/annotated/base_task.py, flytekit/common/tasks/sdk_runnable.py, flytekit/interfaces/data/data_proxy.py, flytekit/taskplugins/spark/__init__.py, flytekit/taskplugins/spark/schema.py, flytekit/taskplugins/spark/task.py, flytekit/types/__init__.py, flytekit/types/pandas_schema.py, flytekit/types/schema.py, tests/flytekit/unit/annotated/test_flyte_file.py, tests/flytekit/unit/annotated/test_type_hints.py
- This is also an overhaul of the schema system to support remote IO
based dataframes and regular pandas style dataframes. All of them can
be added at the user layer by implementing 2 classes SchemaReader
/ SchemaWriter.
- If the new dataframe is to be added as a supported type then, it
contributor needs to implement the TypeTransformer interface as well
=> Spark DataFrames handled as a type if using spark

setup.py
Require at least Python 3.7.
The new API requires at least Python 3.7 to function.
_NA_
_NA_
=> Require at least py37

flytekit/annotated/promise.py, tests/flytekit/unit/annotated/test_conditions.py
condition handling of tuples in tasks was broken because it assumed always a single Promise will be returned.
=> Fix tuple handling in condition branches

flytekit/configuration/__init__.py
More mild and less seemingly harmful warning message is logged when `flytekit.conf` cannot be found.
When an `flytekit.conf` file with absolute path cannot be found, we log the original configuration as well as point out a different possibility.
https://github.com/lyft/flyte/issues/646
_NA_
=> More mild warning message if no flytekit.conf

flytekit/annotated/base_task.py
=> Move around void promise?

flytekit/__init__.py, flytekit/common/tasks/sagemaker/custom_training_job_task.py, tests/flytekit/unit/sdk/tasks/test_sagemaker_tasks.py
Fix the output-persisting logic for CustomTrainingJob that falsely blocked the output of a non-distributed training job
Was missing the non-distributed training case. This PR adds that and make non-distributed training jobs always persist the output
=> Fix the output-persisting logic for CustomTrainingJobTask

flytekit/__init__.py, flytekit/annotated/base_sql_task.py, flytekit/annotated/base_task.py, flytekit/annotated/container_task.py, flytekit/annotated/dynamic_workflow_task.py, flytekit/annotated/interface.py, flytekit/annotated/map_task.py, flytekit/annotated/node.py, flytekit/annotated/python_function_task.py, flytekit/annotated/reference_task.py, flytekit/annotated/task.py, flytekit/taskplugins/hive/task.py, flytekit/taskplugins/pytorch/task.py, flytekit/taskplugins/sagemaker/hpo.py, flytekit/taskplugins/sagemaker/training.py, flytekit/taskplugins/sidecar/task.py, flytekit/taskplugins/spark/task.py, flytekit/taskplugins/sqlite/task.py, flytekit/taskplugins/tensorflow/task.py, tests/flytekit/unit/annotated/test_serialization.py, tests/flytekit/unit/annotated/test_type_hints.py, tests/flytekit/unit/taskplugins/pytorch/test_pytorch_task.py, tests/flytekit/unit/taskplugins/sagemaker/test_hpo.py, tests/flytekit/unit/taskplugins/sagemaker/test_training.py, tests/flytekit/unit/taskplugins/sqlite/test_task.py, tests/flytekit/unit/taskplugins/tensorflow/test_tensorflow_task.py
TaskMetadata will be maintained as a shadow and allows decoupling of
protocol buffer types from contributor code and user code. This allows
more flexiblity
another prime motivation behind this change is that - it allows making the interface less verbose. This makes it trivial to support default values for metadata.
=> Switching from using model Metadata -> TaskMetadata

flytekit/annotated/condition.py, flytekit/annotated/context_manager.py, flytekit/annotated/interface.py, flytekit/annotated/node.py, flytekit/annotated/node_creation.py, tests/flytekit/unit/annotated/test_interface.py, tests/flytekit/unit/annotated/test_node_creation.py, tests/flytekit/unit/annotated/test_references.py, tests/flytekit/unit/annotated/test_serialization.py, tests/flytekit/unit/annotated/test_type_hints.py, tests/flytekit/unit/taskplugins/hive/test_hive_task.py, tests/flytekit/unit/taskplugins/sagemaker/test_training.py
Make automatically generated output names `o0, o1, o2, ...` rather than `out_0, out_1, out_2, ...`.
Make automatically generated node names `n0, n1, n2, ...` rather than `node-0, node-1, node-2, ...`.
=> Annotations o0 n0

flytekit/__init__.py, flytekit/annotated/dynamic_workflow_task.py, flytekit/annotated/workflow.py, flytekit/models/core/workflow.py, tests/flytekit/unit/annotated/test_workflows.py
* Add a WorkflowMetadata dataclass
* Add a WorkflowMetadataDefaults dataclass
* Hook up data classes to constuctors and expose those settings in the workflow decorator
* Remove unnecessary Workflow input to construct_input_promises
* Add a docstring to the workflow decorator.
=> Annotations - workflow metadata

flytekit/clis/flyte_cli/main.py
`parse-proto` should output json.
=> Annotations - Change parse-proto output to json

flytekit/taskplugins/sqlite3/task.py, tests/flytekit/unit/taskplugins/sqlite3/test_task.py
It is possible to declare sqlite3 statements that can read from a dynamically downloaded sqlite3 database or one that is stored in the container.
TODO:
1. Prevent tasks being written inside the workflow function `<local>`
2. Make it possible that Sqlite3 tasks can be executed on a predefined container - dynamically! No need to build a container. This is not possible today
=> In Container - Sqlite3 Plugin

README.md, flytekit/tools/lazy_loader.py, scripts/flytekit_install_spark.sh, scripts/flytekit_install_spark3.sh
- Updates Hadoop/AWS version to support IAM role fetch via https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html
- Default flytekit[all] to Spark 3.x (https://github.com/lyft/flyte/issues/483) 
https://github.com/lyft/flyte/issues/483
_NA_
OR
=> Spark: Update Hadoop/AWS Sdk version + set all to Spark3

flytekit/__init__.py, flytekit/annotated/testing.py, setup.py
These were missed!  We need to put these imports at the top layer.
I just went through the cookbook as it stands on master and looked for imports that still referred to the `annotated` folder (which we're shortly going to rename).
Some of these are only used by extensions but it's still nice to move them.
=> Hide remaining implementations

flytekit/__init__.py, flytekit/clients/raw.py, setup.py
Add call _handle_rpc_error() for missed create task & create execution in raw client otherwise creating tasks or executions fails.
User-reported bug
_NA_
=> Add call _handle_rpc_error() for missed create task & create execution

flytekit/__init__.py, flytekit/configuration/platform.py, flytekit/configuration/sdk.py, setup.py
Remove flyte platform url and flyte sdk role as required config options
It's no longer necessary to specify the platform url in the config because `pyflyte serialize` should not make any network calls.
The flyte sdk role has been deprecated in favor of kubernetes-service-account or assumable-iam-role
_NA_
=> Remove required string configuration options

flytekit/__init__.py, flytekit/configuration/images.py, setup.py
One last change to make --config an optional arg to pyflyte for out of container serialize. Tested locally
_NA_
=> One last change to make --config an optional arg to pyflyte

flytekit/clis/flyte_cli/main.py, flytekit/clis/sdk_in_container/serialize.py
- Make it more clear that serialize terminated successfully
- Default to user's currently working dir when local source root is omitted in out of container serialize
- Raise an error when the expected tar file is missing during fast register
Tested locally.
**Note** I still can't recreate the
```
flytekit.common.exceptions.user.FlyteAssertion: No configuration set for [internal] image.  This is a required configuration.
```
issue or the case where a custom version is specified during fast register and tar file is not uploaded with the specified version as the filename.
Discovered while onboarding a new user.
_NA_
=> A few small fixes for serialize & register

plugins/awssagemaker/setup.py, plugins/hive/setup.py, plugins/kfpytorch/setup.py, plugins/kftensorflow/setup.py, plugins/papermill/setup.py, plugins/pod/setup.py, plugins/spark/setup.py
This should've been part of https://github.com/flyteorg/flytekit/pull/356
Without this, users won't have a new version of plugins to bump to, and without that, the plugins will continue to look for things in the `annotated` folder, which as of the new release, no longer exists.
=> Bump all (new) plugins to 0.1.1s

.github/workflows/pythonpublish.yml, Makefile, flytekit/__init__.py, plugins/Makefile, plugins/awssagemaker/setup.py, plugins/hive/setup.py, plugins/kfpytorch/setup.py, plugins/kftensorflow/setup.py, plugins/papermill/setup.py, plugins/pod/setup.py, plugins/spark/setup.py, setup.py
Automatically publishes to pypi when a release is created. Removes the need to update any versions embedded in the files (__init__ and setup.py) for the core library as well as plugins.
- [] Unit tests added
https://github.com/flyteorg/flyte/issues/688
=> Dynamically update lib version and publish all plugins

CODEOWNERS
The new-codebase has new contributors and currently Matt is not an active collaborator on the codebase. This change makes it faster to get PR's and directs it to more relevant users
=> Removing Matt from the required reviewers

flytekit/clis/flyte_cli/main.py
List active lps without erroring when they have no schedule data
_NA_
=> List lps without erroring when they have no schedule data

flytekit/clis/sdk_in_container/serialize.py
Set in container serialize spark path to sys.executable. Reverts https://github.com/flyteorg/flytekit/pull/344/files#diff-632d372ce8489b928502cba2517307448a28d0a46dd3c06017c6b90c7c765be3L89
User-reported bug
_NA_
OR
=> Set in container serialize spark path to sys.executable

docs/source/conf.py, flytekit/__init__.py
In an earlier [PR](https://github.com/flyteorg/flytekit/pull/356/files) we inadvertently removed the `PythonInstanceTask` object from the core flytekit import.
Adding it back.
=> Add PythonInstanceTask to core flytekit import

flytekit/clis/sdk_in_container/serialize.py, flytekit/core/context_manager.py, plugins/spark/flytekitplugins/spark/task.py
Add a new variable `CTX_PYTHON_INTERPRETER` to ctx. This points to the python interpreter that should be used as part of the executor path. 
Revert back to how `CTX_FLYTE_VIRTUALENV_ROOT` was previously calculated and only use the directory. This corrects teh application file from `local:///<some_path>/flytekit/__init__.py/bin/entrypoint.py` to `local:///<some_path>/flytekit/bin/entrypoint.py`
- [x ] Bug Fix
_NA_
OR
=> Fix executor path and application file parameters for Spark Tasks

flytekit/core/context_manager.py, flytekit/core/python_function_task.py, tests/flytekit/unit/core/test_python_function_task.py
Allow users to specify {{image.sagemaker}} (or others) into their `container_image` attribute of a task to substitute for the entire image path... instead of forcing them to write `{{image.sagemaker.fqn}}:{{image.sagemaker.version}}`.
https://github.com/flyteorg/flyte/issues/734
=> Allow {{image.sagemaker}} to substitute for the entire image

flytekit/bin/entrypoint.py, tests/flytekit/unit/bin/test_python_entrypoint.py
Currently, new style Python-native typed tasks that raise an exception do not properly write an errors.pb file.  This replicates the existing logic in the flyte engine task code.
Copied code from https://github.com/flyteorg/flytekit/blob/master/flytekit/engines/flyte/engine.py#L320-L376
https://github.com/flyteorg/flyte/issues/739
=> Upload errors.pb in new API

flytekit/clis/sdk_in_container/serialize.py, flytekit/tools/module_loader.py
- AFter the refactor in which registrable entities were removed, we
inadvertently broke instance variable lookup
- This PR resurrects it, creating a separate Path.
One problem with this PR is potentially slower serialization performance
(unnoticeable to humans), because the modules are imported twice to scan
for relevant objects
The second pass scans only for Instance Vars, and topo sort is not
needed, as automatically create a inmemory map of all the tasks loaded.
_NA_
OR
=> Instance variable load issue.

flytekit/core/base_task.py, flytekit/core/launch_plan.py, flytekit/core/promise.py, flytekit/core/reference_entity.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_workflows.py
This previously didn't work
```
@task
a = a + 5
return a
@workflow
def list_output_wf() -> typing.List[int]:
v = []
for i in range(2):
v.append(t1(a=i))
return v
```
What was happening was that `Promise` objects were getting wrapped twice.  Coming out of the workflow function call, it was already a list of Promises.  What the workflow function should return is a `LiteralCollection` rather than attempting to rewrap. The end result was that `type(result.val.collection.literals[0].scalar.primitive.integer)` was again a `Promise` rather than a proper Python integer. (`result` here is the output of [`_local_execute`](https://github.com/flyteorg/flytekit/pull/388/files#diff-b1a8538044c80e14d7998344a528dccb59cf54c9735de724f39d345e5f8dfcf5R306))
* Removed the …
=> List workflow outputs

flytekit/clis/flyte_cli/main.py
Adding a pointer to the documentation for [FlyteAdmin Service](https://docs.flyte.org/en/latest/dive_deep/admin_service.html#adding-request-filters) to help users understand the '--filter' option
Adding a link and an example.
=> Adding a pointer to the docs for filter option

flytekit/core/dynamic_workflow_task.py, flytekit/core/resources.py, flytekit/core/task.py, tests/flytekit/unit/core/test_realworld_examples.py
Instead of kwargs, at the task decorator level, specify explicitly everything that can be passed.  Indeterminate kwargs led to user confusion.
* Also fix a test that wasn't specifying things resources correctly.
=> Remove kwargs

.github/workflows/pythonbuild.yml
Coverage report is on the fritz, try collapsing pytest run in one `coverage run` invocation
_NA_
OR
=> collapse coverage run into single command

flytekit/core/workflow.py, tests/flytekit/unit/core/test_conditions.py
Please see https://github.com/flyteorg/flyte/issues/807
Basically when a `then()` block ran a task, but wasn't in the true condition case, we'd skip execution but we never did that for subworkflows.
Basically we're copying this section https://github.com/flyteorg/flytekit/blob/master/flytekit/core/base_task.py#L238-L246 which will skip the branches not taken when running locally.
https://github.com/flyteorg/flyte/issues/807
=> Fix subworkflow branch skip return

README.md
Updates the readme with a minor change to argument passing
Updates the readme with a minor fix to change `square(y=y)` while square accepts `x`.
_NA_
=> Update readme to fix square function argument passing

plugins/kfpytorch/flytekitplugins/kfpytorch/task.py
As done in kftensorflow in https://github.com/flyteorg/flytekit/pull/408
=> Override requests and limits in kwargs with values from task_config

flytekit/bin/entrypoint.py
Remove unused arguments breaking map task execution.
https://github.com/flyteorg/flyte/issues/861
_NA_
=> Fix map tasks

flytekit/contrib/notebook/tasks.py, flytekit/plugins/__init__.py
Currently if you create a new virtualenv and just `pip install -e .` in the flytekit directory (installing flytekit but none of the legacy plugin dependencies),
`sdk/tasks.py` calls `from flytekit.contrib.notebook import tasks as _nb_tasks` which in turn tries to import papermill.
This PR hides the papermill behind the lazy loading mechanism.
copy/paste.
=> Lazy load papermill in legacy plugins

dev-requirements.txt, doc-requirements.txt, flytekit/bin/entrypoint.py, flytekit/clis/flyte_cli/main.py, flytekit/common/launch_plan.py, flytekit/common/mixins/launchable.py, flytekit/common/tasks/task.py, requirements-spark3.txt, requirements.txt, setup.py
Accept auth role arg in single task execution. This is a required param for single task executions but currently can only be set from the user flytekit config.
Also bump flyteidl version to pick up the fix for a non-backwards compatible field number change for auth roles.
https://github.com/flyteorg/flyte/issues/860
_NA_
=> Accept auth role arg in single task execution

plugins/pod/flytekitplugins/pod/task.py, plugins/tests/pod/test_pod.py
Signed-off-by: Jeev B <jeev.balakrishnan@freenome.com>
Pod specs in the `custom` struct of `TaskTemplate` were being improperly serialized, resulting in a subsequent parsing failure by Flytepropeller.
_NA_
OR
=> Fix serialization of pod specs in pod plugin

flytekit/types/directory/types.py, flytekit/types/file/file.py, tests/flytekit/unit/core/test_flyte_directory.py, tests/flytekit/unit/core/test_flyte_file.py
In converting a workflow from the old api to the new one, @samhita-alla found a bug in the flytefile/directory objects.  Basically, there was a [dynamic task](https://github.com/flyteorg/flytesnacks/blob/master/legacy/demos/gaic-2020/demo/multiregion_house_price_predictor.py#L32) that would unpack a list of blobs and then call another task on each element.
However in doing so, the s3 location that was bound to the tasks in the dynamicjobspec was different than the s3 locations that came in.  Basically there was an unnecessary conversion happening.
This PR adds an early return to File/Directory so that if the object to be converted into a literal was tagged as having been created from a remote source, then we just use …
=> Pass through FlyteFile and FlyteDirectory if created from a remote source

flytekit/core/container_task.py, tests/flytekit/unit/common_tests/test_translator.py
This allows a user to be able to set Resources limits and requests for containerTasks. 
https://github.com/lyft/flyte/issues/877
_NA_
=> add requests and limits parameter to ContainerTask

dev-requirements.txt, doc-requirements.in, doc-requirements.txt, docs/source/_static/custom.css, docs/source/_templates/sidebar/brand.html, docs/source/conf.py, docs/source/design/authoring.rst, docs/source/design/index.rst, docs/source/design/models.rst, docs/source/flytekit.rst, docs/source/generator.rst, docs/source/index.rst, docs/source/reference/index.rst, flytekit/__init__.py, requirements.txt
=> update flytekit docs theme, fix index links

tests/flytekit/unit/core/test_type_hints.py
Adds additional unit test, that checks for != condition
=> Added a missing test for != `ne` condition

flytekit/core/type_engine.py, plugins/spark/flytekitplugins/spark/task.py, plugins/tests/spark/test_spark_task.py, plugins/tests/spark/test_wf.py
This PR has two goals: 1) introduce a feature to propagate python configurations to Spark executors, and 2) fix a bug in how Spark configs are set in `SparkContext`/`SparkSession`. In addition, fixed other minor bugs as part of this PR.
1. [Feature] Propagate `PYTHONPATH` to executors. If the variable is found in the system, means we already have a setup already prepared, so convey that env to the `SparkSession` to propagate the configuration in executors.
2. [Bug] Fix how configs are set to the `SparkSession`. Changed the way it's set with a `SparkConfig` and introduced it to the 'SparkSession' before creating.
NA
_NA_
OR
=> Propagate required envs to executors and fix bug to set configs in Spark task

codecov.yml, flytekit/core/launch_plan.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_launch_plan.py
It was decided that the existing functions for creating launch plans were not user-friendly.  The `get_default_launch_plan` function required a context, but it's supposed to be the `FlyteContext` not the user-facing context (`ExecutionParameters`). The regular `create` function requires a name all the time. This PR introduces a new function that is
* cached by default
* Doesn't need the name. If no name is provided, it's assumed the default launch plan is what you're after.
See code.
https://github.com/flyteorg/flyte/issues/892
=> Add a lot more user friendly launch plan creating function

flytekit/bin/entrypoint.py, flytekit/common/translator.py, flytekit/core/context_manager.py, flytekit/core/python_function_task.py, plugins/tests/pod/test_pod.py, tests/flytekit/unit/core/test_context_manager.py, tests/flytekit/unit/core/test_dynamic_conditional.py, tests/flytekit/unit/core/test_type_hints.py
Passes in fast register arguments and substitutes them at dynamic task compilation time.
https://github.com/flyteorg/flyte/issues/824
_NA_
=> Fast register for dynamic tasks

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Converting a float of 0 fails currently.
Using None check.
https://flyte-org.slack.com/archives/CREL4QVAQ/p1619449414338000
=> Fix 0.0 value floats

flytekit/bin/entrypoint.py, flytekit/core/python_auto_container.py, flytekit/core/python_third_party_task.py, flytekit/core/type_engine.py, flytekit/extras/sqlite3/Dockerfile, flytekit/extras/sqlite3/task.py, tests/flytekit/unit/extras/sqlite3/test_task.py
These comments are based against the `third-party-container` branch.
* The new entrypoint has been removed from `entrypoint.py` and we've reverted to using the same `pyflyte-execute`.
* `entrypoint.py` setup was put into its own function so that the task template task resolver can access aws/gcs and download the template from the cloud.
* `TaskResolverMixin` made to operate at a level higher (`Task` instead of `PythonAutoContainerTask`).
* Created a new `ExecutorTask` that has only a `TaskTemplate` and a `TaskTemplateExecutor`.  In the future, this will be the 
* Added a `TaskTemplateResolver` that will create only two strings for the loader args, the regex string for propeller to fill in the task template location, and the module and name of the executor.  At run time, the entrypoint …
=> [ignore] pr into #449

flytekit/core/workflow.py, tests/flytekit/unit/core/test_workflows.py
Previously `_local_execute` would be called without checking for default arguments. See https://github.com/flyteorg/flyte/issues/951 for more details.
- [ X] Bug Fix
https://github.com/flyteorg/flyte/issues/951
=> Use default arguments in addition to kwargs in local wf execution

flytekit/core/launch_plan.py, tests/flytekit/unit/core/test_launch_plan.py
Verify if the cached outputs are the same as the arguments passed in the further repeat calls.
https://github.com/lyft/flyte/issues/892
In flytekit's `core/launch_plan.py::LaunchPlan` object, the `get_or_create` function creates a launch plan. The user can supply things like a schedule or fixed or default inputs to it. The resultant launch plan is cached. On repeat calls, the cached version (based on the name) is returned. We should add a check to make sure that these repeat calls raise an error if any of the other arguments have changed.
_NA_
=> Validate All Arguments While Using the Cached LaunchPlan

flytekit/core/interface.py
Make `extract_return_annotation` compatible with Python 3.9 `NamedTuple`.
`_field_type` attribute was removed in Python 3.9 (see [typing.NamedTuple](https://docs.python.org/3/library/typing.html#typing.NamedTuple)). Instead, check that the type has `tuple` as a base class, and that it has the `_field` attribute (part of [namedtuple API](https://docs.python.org/3/library/collections.html#collections.somenamedtuple._fields)). Then return `__annotations__` which contains the same information as `_field_types`. 
https://github.com/flyteorg/flyte/issues/914
_NA_
=> Make extract_return_annotation compatible with 3.9 NamedTuple

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Allow passing an empty dictionary as input. 
Tried to execute the following task:
```
@task
def test_empty(d: Dict[str, str]) -> int:
return len(d)
@workflow
def my_wf() -> int:
res = test_empty(d={})
return res
```
which would fail with:
```
File "/root/flytekit/core/type_engine.py", line 447, in to_python_value
raise TypeError(f"Cannot convert from {lv} to {expected_python_type}")
TypeError: Cannot convert from map {
}
to typing.Dict[str, str]
```
https://github.com/flyteorg/flyte/issues/918
_NA_
=> DictTrasformer works when LiteralMap is empty

flytekit/core/base_task.py, flytekit/core/condition.py, flytekit/core/context_manager.py, flytekit/core/reference_entity.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_type_hints.py
- this solution breaks the flow when the conditional section is
instantiated. So we can only have one of 3 behaviors
1. new conditional section in compilation state
2. new conditional section in execution state
3. a nested conditional section in skipped state
=> alternate to using Branch ignored flag.

flytekit/clis/flyte_cli/main.py, flytekit/clis/sdk_in_container/serialize.py, flytekit/common/translator.py, flytekit/core/condition.py, flytekit/core/node.py, flytekit/core/python_function_task.py, plugins/tests/hive/test_hive_task.py, plugins/tests/pod/test_pod.py, plugins/tests/sqlalchemy/test_sql_tracker.py, tests/flytekit/unit/common_tests/test_translator.py, tests/flytekit/unit/core/test_conditions.py, tests/flytekit/unit/core/test_dynamic_conditional.py, tests/flytekit/unit/core/test_imperative.py, tests/flytekit/unit/core/test_launch_plan.py, tests/flytekit/unit/core/test_map_task.py, tests/flytekit/unit/core/test_node_creation.py, tests/flytekit/unit/core/test_references.py, tests/flytekit/unit/core/test_resolver.py, tests/flytekit/unit/core/test_serialization.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/core/test_workflows.py, tests/flytekit/unit/extras/sqlite3/test_sql_tracker.py, tests/flytekit/unit/models/test_common.py
Gets rid of the Sdk... classes in the `translator.py` module. This should be the last place flytekit is explicitly using the old classes.
Previously the `translator` module converted from the new Python classes (PythonFunctionTask, PythonFunctionWorkflow, LaunchPlan) into the `SdkXyz` classes, and then relied on the `serialize()` call within each of those Sdk classes, invoked by `serialize.py` to convert them into model objects.  Now `translator` will go directly to the model, and the serialization step will just call `to_flyte_idl()`
* Remove most of the `common` dependencies in `translator.py` and replace with the model classes.
* Python objects get converted to the same model classes as the output of their respective serialize calls earlier, namely
* Tasks -> …
=> Serialize directly to model classes

flytekit/control_plane/nodes.py, flytekit/control_plane/workflow.py, flytekit/control_plane/workflow_execution.py, flytekit/models/interface.py, tests/flytekit/integration/control_plane/test_workflow.py
Fixes https://github.com/flyteorg/flyte/issues/974. The `inputs` and `outputs` properties of the `FlyteWorkflowExecution` and `FlyteNodeExecution` should now return python values instead of flyte literals
_NA_
OR
=> execution classes in control plane convert flyte literals to python

dev-requirements.txt, flytekit/common/tasks/sidecar_task.py, flytekit/models/task.py, flytekit/sdk/tasks.py, requirements-spark2.txt, requirements.txt, setup.py, tests/flytekit/unit/models/test_tasks.py, tests/flytekit/unit/sdk/tasks/test_sidecar_tasks.py
Make `sidecar_task` and `dynamic_sidecar_task` support k8s annotations & labels.
_NA_
OR
=> SidecarTask support annotations/labels

flytekit/core/launch_plan.py, tests/flytekit/unit/core/test_launch_plan.py
Consistent launch plan initialization interfaces. Get and get_or_create now accept labels, annotations, and raw_output_data_config parameters just like `__init__`
User reported bug.
https://github.com/flyteorg/flyte/issues/1086
_NA_
=> Consistent launch plan initialization interfaces.

flytekit/core/launch_plan.py, tests/flytekit/unit/core/test_references.py
Adds the `@reference_launch_plan` decorator that simplifies creating a reference launch plan from a function signature.
Currently the way to create/use reference launch plans is as follows:
```
import os
from flytekit import workflow
from flytekit.core.base_task import kwtypes
from flytekit.core.launch_plan import ReferenceLaunchPlan
rlp = ReferenceLaunchPlan(
project=os.environ["FLYTE_INTERNAL_PROJECT"],
domain=os.environ["FLYTE_INTERNAL_DOMAIN"],
name="workflows.single_step.compute_square_wf",
version="ff414a48bba9",
inputs=kwtypes(input_integer=int),
outputs=kwtypes(o0=int),
)
@workflow
def reference_compute_square_wf_wrapper(input_integer: int) -> int:
return rlp(input_integer=input_integer)
```
This PR would allow us to create the reference launch plan as follows:
```
from …
```
=> Add decorator to simplify creating a reference launch plan from a function signature

flytekit/clis/sdk_in_container/serialize.py, flytekit/configuration/internal.py, flytekit/core/context_manager.py, flytekit/core/python_auto_container.py, tests/flytekit/unit/core/test_python_function_task.py
In light of containerless tasks it no longer makes sense to have image be a required configuration parameter. Rather, PythonAutoContainer tasks should validate that the image config is provided at serialization
https://github.com/flyteorg/flyte/issues/1031
_NA_
=> Make image config param optional

flytekit/clients/friendly.py, flytekit/clients/helpers.py, flytekit/control_plane/component_nodes.py, flytekit/control_plane/nodes.py, flytekit/control_plane/tasks/task.py, flytekit/control_plane/workflow.py, flytekit/models/node_execution.py, tests/flytekit/integration/control_plane/mock_flyte_repo/workflows/basic/subworkflows.py, tests/flytekit/integration/control_plane/test_workflow.py
Add support for inspecting inputs and outputs of subworkflows in the control plane objects.
As a user, I can get a `FlyteWorkflowExecution` and access the inputs and outputs of its child node executions, including subworkflows. This is enabled by adding support in `FlyteNodeExecution` for determining whether it is associated with a task or a subworkflow via the `metadata.is_parent_node` attribute.
```python
wf_exec = FlyteWorkflowExecution.fetch(...)
wf_exec.wait_for_completion()
for node_exec in wf_exec.node_executions:
if node_exec.metadata.is_parent_node:
node_exec.subworkflow_node_executions  # Dict[str, FlyteNodeExecution]
node_exec.inputs  # subworkflow inputs
node_exec.outputs  # subworkflow outputs
else: …
```
=> expose subworkflow inputs, outputs in node execution

flytekit/common/types/primitives.py, flytekit/core/type_engine.py, flytekit/models/types.py, setup.py, tests/flytekit/unit/core/test_type_engine.py
This PR introduces automatic schema extraction from Dataclass declarations. This is not used at runtime to validate the data currently, but just used to improve the visualization in the UI / CLI
uses a new library called marshmallow-jsonschema
https://github.com/flyteorg/flyte/issues/654
=> Support for Schema of Dataclasses for better rendering in the UI

doc-requirements.txt, flytekit/core/map_task.py, flytekit/core/python_auto_container.py, plugins/tests/pod/test_pod.py, tests/flytekit/unit/core/test_serialization.py
Updates map task serialization to support non-container target type tasks (e.g. pod tasks).
https://github.com/flyteorg/flyte/issues/1051
_NA_
=> Support mapping over pod tasks

flytekit/common/translator.py, flytekit/core/python_auto_container.py, plugins/tests/pod/test_pod.py
Pod tasks now write the pod spec to the task target directly. In order to fast-execute them, we must modify the primary container command to first run `pyflyte-fast-execute...`
User reported bug (thank you @jeevb)
https://github.com/flyteorg/flyte/issues/1050
_NA_
=> Implement fast register for pod tasks v2

dev-requirements.txt, doc-requirements.txt, flytekit/loggers.py, requirements-spark2.txt, requirements.txt, setup.py
Use JSON logging formatter.  Logs will now look like:
```
{"asctime": "2021-06-15 19:30:58,474", "name": "flytekit", "levelname": "INFO", "message": "This is the base logger - UTC: 19:30:58"}
{"asctime": "2021-06-15 19:30:58,474", "name": "flytekit.auth", "levelname": "DEBUG", "message": "This is a debug auth logger 19:30:58"}
```
Added a JSON formatter for logging and set the formatter in the main handler to use it.
The reason for this is because json logs are easier to parse, esp by third party log search providers.
=> Use JSON logging formatter

flytekit/core/promise.py, flytekit/core/workflow.py, tests/flytekit/unit/common_tests/test_promise.py, tests/flytekit/unit/core/test_serialization.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/core/test_workflows.py
The following example is incorrect
```
nm = typing.NamedTuple("OP", greet=str)
@task
def say_hello() -> nm:
return nm("hello world")
wf_outputs = typing.NamedTuple("OP2", greet1=str, greet2=str)
@workflow
def my_wf() -> wf_outputs:
return wf_outputs(say_hello(), say_hello())
```
This fails at registration time, because Flyte does not support tuples for individual values.
It can be fixed by simply adding `.greet` to the returned value from a task - that returns a namedtuple
```
@workflow
def my_wf() -> wf_outputs:
return wf_outputs(say_hello().greet, say_hello().greet)
```
This usually is ok for cases in which you have multiple values returned as the assumption is that you need to de-reference, but for single values, this is not directly …
=> Early error for cases in which namedtuple usage causes compile time errors

flytekit/clis/sdk_in_container/serialize.py, flytekit/common/translator.py, flytekit/core/context_manager.py, flytekit/core/python_function_task.py, plugins/tests/pod/test_pod.py, tests/flytekit/unit/common_tests/test_translator.py, tests/flytekit/unit/core/test_dynamic_conditional.py, tests/flytekit/unit/core/test_type_hints.py
For fast registered entities, the destination dir specifies where to untar the fast-registered code archive. Currently the destination dir is a registration time attribute, however considering that the code location is specified in the Dockerfile, this actually ought to be a serialization attribute. This change enables that for future `pyflyte package` work.
_NA_
=> Fast register: move destination dir as part of serialization settings

flytekit/core/interface.py, flytekit/core/type_engine.py
Make `transform_signature_to_interface` compatible with 3.9 `NamedTuple`
Similar to https://github.com/flyteorg/flytekit/pull/471/files
https://github.com/lyft/flyte/issues/1166
=> Make transform_signature_to_interface compatible with 3.9 NamedTuple

flytekit/configuration/statsd.py, flytekit/interfaces/stats/taggable.py
Signed-off-by: Haytham Abuelfutuh <haytham@afutuh.com>
Statsd Library used by flytekit [doesn't support tagging](https://statsd.readthedocs.io/en/v3.3/tags.html). This PR adds a flag to allow disabling of the tagging functionality in the flytekit's statsd wrapper.
The main concern with the way tagging is implementing is the huge cardinality it can potentially produce which can overwhelm the metrics system or incur high costs.
fixes https://github.com/flyteorg/flyte/issues/1204
=> Allow statsd tags to be disabled through config

.readthedocs.yml
Build is currently failing because of a dependency issue. Observed that flytekit docs requirements are getting installed through Python3.7, bumped the version through `readthedocs` yml file. 
_NA_
OR
=> Fix flytekit docs build

tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
Previous PR didn't work because flytekit itself wasn't released.
=> Bump urllib3 dependency in inner repo

flytekit/configuration/sdk.py
fixes https://github.com/flyteorg/flyte/issues/782
The default filepath defined in by `LOCAL_SANDBOX` resulted in an usable tmp-dir path when invoking `flytekit.current_context().working_directory`
fixes https://github.com/flyteorg/flyte/issues/782
_NA_
OR
=> local sandbox tmp dir supports windows

flytekit/core/base_task.py, flytekit/core/condition.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_type_hints.py
Flyte conditionals support asymmetric return values for the tasks in each of the case statements. The behavior is to truncate the outputs to only the minimal set that match across all outputs. this mostly affected local execution
```python
@task
def square(n: int) -> int:
return n * n
@task
def double(n: int) -> int:
return 2 * n
@task
def coin_toss(seed: int) -> bool:
"""
Mimic some condition checking to see if something ran correctly
"""
r = random.Random(seed)
if r.random() < 0.5:
return True
return False
@task
def sum_diff(a: int, b: int) -> (int, int):
return a + b, a - b
@workflow
def consume_outputs(my_input: int, seed: int = 5) -> int:
is_heads = coin_toss(seed=seed)
res = (
conditional("double_or_square")
.if_(is_heads.is_true()) …
```
=> handle Asymmetric return values from tasks within a conditional block

docs/source/design/authoring.rst, flytekit/bin/entrypoint.py, flytekit/common/exceptions/scopes.py, flytekit/core/map_task.py, flytekit/core/python_function_task.py, flytekit/core/resources.py, flytekit/core/schedule.py, flytekit/core/workflow.py, flytekit/engines/flyte/engine.py, flytekit/models/core/errors.py, flytekit/models/core/execution.py, flytekit/models/literals.py, tests/flytekit/unit/bin/test_python_entrypoint.py, tests/flytekit/unit/core/test_imperative.py, tests/flytekit/unit/models/core/test_errors.py, tests/flytekit/unit/models/core/test_execution.py
This cleans up the exception handling of new tasks and workflows.  Currently there is no differentiation of recoverable or non-recoverable errors and all errors were system errors.
* Remove six from the scopes handling, no Python 2 anymore.  This makes the scopes code slightly easier to read.
* Add in [`kind`](https://github.com/flyteorg/flyteidl/blob/f4809c1a52073ec80de41be109bccc6331cdbac3/protos/flyteidl/core/execution.proto#L68) into the `ExecutionError` model.
* Add in [`origin`](https://github.com/flyteorg/flyteidl/blob/f4809c1a52073ec80de41be109bccc6331cdbac3/protos/flyteidl/core/errors.proto#L27) into the `ContainerError`.
* Use the user scope decorator where user-code is invoked (see https://github.com/flyteorg/flytekit/pull/540/files which this PR originally came from).
* Add …
=> Clean up scopes and exception handling for new tasks

dev-requirements.txt, doc-requirements.txt, flytekit/clients/friendly.py, flytekit/clients/raw.py, flytekit/clis/flyte_cli/main.py, requirements-spark2.txt, requirements.txt, setup.py
Allows users to recreate a previously-run workflow execution that will only start executing from the last known failure point.
In keeping with existing execution commands `relaunch-execution` and `terminate-execution` as separate commands I made this one an additional command for consistency.
https://github.com/flyteorg/flyte/issues/1151
_NA_
=> Add recover-execution flyte-cli command

flytekit/clients/friendly.py, flytekit/core/base_task.py, flytekit/core/docstring.py, flytekit/core/interface.py, flytekit/core/python_auto_container.py, flytekit/core/python_function_task.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_docstring.py, tests/flytekit/unit/core/test_interface.py, tests/flytekit/unit/core/test_workflows.py
Signed-off-by: Sean Lin <sean@union.ai>
- Add support for @workflow decorated Python function's docstring input/output variable description.
- Add support for docstring's short/long description for future use
- Add a new class `Docstring` for passing structured docstring around
- See https://github.com/flyteorg/flytekit/pull/557 for more context
https://github.com/flyteorg/flyte/issues/1235
_NA_
=> Add support for @workflow docstring input/output variable description

.gitignore, doc-requirements.txt, docs/source/_templates/custom.rst, docs/source/conf.py, docs/source/design/control_plane.rst, docs/source/design/index.rst, docs/source/index.rst, flytekit/remote/__init__.py, flytekit/remote/component_nodes.py, flytekit/remote/launch_plan.py, flytekit/remote/nodes.py, flytekit/remote/remote.py, flytekit/remote/tasks/executions.py, flytekit/remote/tasks/task.py, flytekit/remote/workflow.py, flytekit/remote/workflow_execution.py, tests/flytekit/integration/remote/test_remote.py, tests/flytekit/unit/remote/test_remote.py
- Add documentation for `remote` module
- change `FlyteRemote.from_environment` to `from_config`
- add `@property` vars for FlyteRemote properties
- improve doc strings
- add a little more content to flytekit home page
NA
_NA_
OR
=> document flytekit remote module

flytekit/core/python_function_task.py, tests/flytekit/unit/core/test_dynamic.py
Found out local execution of dynamic tasks was missing when investigating something
Add a case for execution mode `LOCAL_TASK_EXECUTION`
Found when debugging https://flyte-org.slack.com/archives/CREL4QVAQ/p1627384320463800
=> Local dynamic execution was missing

flytekit/bin/entrypoint.py
When running in GCP without a config file present, flytekit uses the wrong setting to try to determine what environment it's running in.  We should base the decision on the offloaded data location, not the cloud provider setting, which defaults to AWS.
Add an extra conditional to first check the `raw_output_data_prefix`.  Not too worried about the increased complexity becase this section of the code will soon be removed by #559, which should be going in within a week and change.
=> Raw output prefix takes precedence for remote proxy creation in entrypoint

dev-requirements.txt, doc-requirements.txt, requirements-spark2.txt, requirements.txt, setup.py
Pin ipykernel since commits on master now fail to install dependencies with
```
The conflict is caused by:
The user requested importlib-metadata==4.6.1
flake8 3.9.2 depends on importlib-metadata; python_version < "3.8"
ipykernel 6.0.3 depends on importlib-metadata<4; python_version < "3.8.0"
```
_NA_
=> Pin ipykernel

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
- Zero value protobufs, become empty json (or empty dictionaries).
- empty dictionaries currently result in an exception, when it should
result in empty proto
- This needs a simple change in the condition
fixes https://github.com/flyteorg/flyte/issues/1325
=> Protobuf transformer did not consider empty generic

flytekit/core/node.py, tests/flytekit/unit/core/test_node_creation.py
Specifying resource overrides for nodes fails if only one of `requests` or `limits` are specified. This PR fixes this, and allows either `requests` or `limits` overrides to be applied on their own.
Use `kwargs.get(key)` which better handles missing values, instead of `kwargs[key]`.
_NA_
OR
=> Fix resource overrides

flytekit/core/node.py, tests/flytekit/unit/core/test_node_creation.py
Allows node-level overriding of timeout, retries, interruptibility.
Added ability to modify the respective fields in the `NodeMetadata` object with `Node.with_overrides(...)`.
_NA_
OR
=> Allow overrides of timeout, retries and interruptible in nodes

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Signed-off-by: Oliver Mannion <125105+tekumara@users.noreply.github.com>
Better error messages when Any is used as a type, eg: in a task signature.
The following:
```
from typing import Any
@task
def could_be_anything() -> Any:
return "surprise!"
```
Will now error with 
```
ValueError: Type typing.Any not supported currently in Flytekit. Please register a new transformer
```
rather than the less informative message
```
TypeError: issubclass() arg 1 must be a class
```
None
NA
=> feat: better error message when the Any type is used 

flytekit/core/base_task.py, plugins/flytekit-pandera/flytekitplugins/pandera/schema.py, plugins/tests/pandera/test_plugin.py
This PR fixes an issue where the pandera schema was not validating out-going dataframes in the `PanderaTransformer.to_literal` method. This resulted in a no-op when executing a task on a flyte backend
The flytekit pandera plugin was not working correctly on a flyte backend because the pandera schema was not being invoked in the `PanderaTransformer.to_literal` method. This PR fixes this by validating a dataframe output before it's written out to disk.
NA
_NA_
OR
=> bugfix flytekit-pandera

flytekit/__init__.py, flytekit/types/directory/types.py, flytekit/types/file/file.py, tests/flytekit/unit/core/test_flyte_directory.py, tests/flytekit/unit/core/test_flyte_file.py
Adding guess for FlyteFile and FlyteDirectory.
Importing in base `__init__` file to trigger transformer loading.
https://github.com/flyteorg/flyte/issues/1335
=> Add guess python type to FlyteFile and FlyteDirectory

flytekit/core/base_task.py
Signed-off-by: Eduardo Apolinario <curupa@gmail.com>
Add link to [Caching docs](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/flyte_basics/task_cache.html#caching) in `TaskMetadata` docstring.
I used [sphobjinv](https://github.com/bskinn/sphobjinv) to get the right label set in the caching docs like:
```
❯ sphobjinv suggest https://flytecookbook.readthedocs.io/en/latest -u caching
No inventory at provided URL.
Attempting "https://flytecookbook.readthedocs.io/en/latest/objects.inv" ...
Remote inventory found.
:std:label:`caching`
:std:label:`how caching works`
:std:label:`how local caching works`
:std:label:`how remote caching works`
```
And used the first result to set a `:std:ref:` pointing to that location.
_NA_
=> Add link to Caching docs

flytekit/models/launch_plan.py, flytekit/remote/remote.py, tests/flytekit/unit/remote/test_remote.py
When `FlyteRemote` executes a `FlyteLaunchPlan`, it's currently using labels, annotations, and auth information from the remote itself rather than the launch plan.  This defaults to that first.
https://github.com/flyteorg/flyte/issues/1365
=> Pass launch plan settings to remote execute

flytekit/clis/sdk_in_container/serialize.py, tests/flytekit/unit/cli/pyflyte/test_package.py
Detect if tasks are duplicated at serialization time.
Before we serialize entities in `pyflyte` (both for the `serialize` and `package` commands), we detect if any of the defined tasks is duplicated, and in case they are duplicated, we raise an exception and fail the corresponding `pyflyte` command. We defined two tasks as being duplicated if their metadata identifiers are the same, i.e. if project, domain, name, and version match. 
https://github.com/flyteorg/flyte/issues/1368
_NA_
=> Detect duplicate tasks at serialization time

flytekit/core/local_cache.py
Do not use hashing as part of the cache key calculation in local executions 
Hashing, by default, is not deterministic ([for good reasons!](https://mail.python.org/pipermail/python-announce-list/2012-March/009394.html)). We should not use the hash of the inputs as part of the cache key, instead, let's take the string representation of the input literal map (which is deterministic).
_NA_
OR
=> Remove hashing from local cache keys

flytekit/core/condition.py, flytekit/core/type_engine.py, plugins/tests/greatexpectations/test_schema.py, plugins/tests/greatexpectations/test_task.py, tests/flytekit/unit/core/test_conditions.py, tests/flytekit/unit/core/test_launch_plan.py, tests/flytekit/unit/core/test_local_cache.py, tests/flytekit/unit/core/test_references.py, tests/flytekit/unit/core/test_resolver.py, tests/flytekit/unit/core/test_serialization.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/core/test_workflows.py
**Describe the bug**
Currently, if a task returns two or more outputs, users are expected to declare those return signatures as
```
def t1() -> (int, int):
...
```
This is fine but is not idiomatic and doesn't pass mypy.  The correct thing to support is:
```
def t1() -> typing.Tuple[int, int]:
...
```
We could check it by running `make lint | grep "Use Tuple"`.
If there are somewhere don't use Tuple, will get the below error.
```
tests/flytekit/unit/core/test_resolver.py:28: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
tests/flytekit/unit/core/test_references.py:99: note: Suggestion: Use Tuple[T1, ..., Tn] instead of (T1, ..., Tn)
``` 
https://github.com/flyteorg/flyte/issues/1029
_NA_
=> Support typing.Tuple for multiple returns

.github/workflows/pythonbuild.yml, cc, plugins/Makefile, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
The mock repo wasn't getting updated.
`make requirements` in the mock workflows repo.
This should really point to the code in the flytekit PR itself, rather than any released version of flytekit.  Overhauling this will tie into
https://github.com/flyteorg/flyte/issues/1364 possibly.
=> Fix integration tests - pull in latest flytekit

flytekit/clis/flyte_cli/main.py, tests/flytekit/unit/cli/test_flyte_cli.py
**flyte-cli** looks to `~/.flyte/config` as the default place to find a configuration file. This is good, but we should also support a flag to allow the user to specify a different one. This is helpful for developers of Flyte, who might have several configuration files pointing to different Admins, and advanced users who might be running a local Flyte cluster as well as a live production (and staging) cluster.
If users don't specific conf, flyte will use default config.
```
(flyte) ➜  flytekit git:(sub-flag) ✗ flyte-cli --config ~/.flyte/config get-task
Using config file at /home/kevin/.flyte/config
Usage: flyte-cli get-task [OPTIONS]
Try 'flyte-cli get-task --help' for help.
Error: Missing option '-u' / '--urn'.
(flyte) ➜  flytekit …
```
=> Support a flag to find config file

Makefile, flytekit/core/base_task.py, flytekit/core/condition.py, flytekit/core/context_manager.py, flytekit/core/data_persistence.py, flytekit/core/interface.py, flytekit/core/promise.py, flytekit/core/python_customized_container_task.py, flytekit/core/reference_entity.py, flytekit/core/type_engine.py, flytekit/types/file/file.py, flytekit/types/schema/types.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py, plugins/flytekit-dolt/flytekitplugins/dolt/schema.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/task.py, plugins/flytekit-pandera/flytekitplugins/pandera/schema.py, plugins/flytekit-papermill/flytekitplugins/papermill/task.py, plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py, tests/flytekit/unit/core/test_workflows.py
Add `type: ignore` to Ignore the below errors:
- Item "None" of "Optional[CompilationState]" has no attribute "prefix"
- "Type[T]" has no attribute "from_json"
- Module has no attribute (It seems like a bug in mypy) https://stackoverflow.com/questions/60734086/mypy-gives-an-error-while-importing-submodule-module-has-no-attribute. sqlalchemy has a attribute `create_engine`, but mypy will raise an error `Module "sqlalchemy" has no attribute "create_engine"`
Fix mypy errors like `Item "None" of "Optional[Interface]" has no attribute "inputs"`
```
flytekit/core/reference_entity.py:114: error: Item "None" of "Optional[Interface]" has no attribute "inputs"
flytekit/core/reference_entity.py:124: error: Item "None" of "Optional[Interface]" has no …
```
=> Fix item has no attribute error

.github/workflows/sqlachemy_publish.yml
nit: It's unnecessary to push an image to the GitHub registry when we create a pull request.
Trigger sqlachemy publish workflow only on push
_NA_
_NA_
=> Trigger sqlachemy publish workflow only on push

.github/workflows/sqlachemy_publish.yml
I think I missed this when checking https://github.com/flyteorg/flytekit/pull/634/
=> Restrict SQLAlchemy GH workflow to master branch

flytekit/core/base_task.py, flytekit/core/condition.py, flytekit/core/context_manager.py, flytekit/core/interface.py, flytekit/core/promise.py, flytekit/core/reference_entity.py, flytekit/core/resources.py, flytekit/core/type_engine.py, flytekit/types/directory/types.py, flytekit/types/file/file.py, flytekit/types/schema/types.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py, plugins/flytekit-hive/flytekitplugins/hive/task.py, plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py, plugins/flytekit-spark/flytekitplugins/spark/task.py, tests/flytekit/unit/core/test_composition.py, tests/flytekit/unit/core/test_conditions.py, tests/flytekit/unit/core/test_imperative.py, tests/flytekit/unit/core/test_launch_plan.py, tests/flytekit/unit/core/test_node_creation.py, tests/flytekit/unit/core/test_references.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/core/test_workflows.py
Fix mypy errors like "Incompatible types  ..."
```
plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py:54: error: Incompatible types in assignment (expression has type "None", variable has type "BatchRequestConfig")
plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py:70: error: Incompatible return value type (got "Tuple[Type[str], GreatExpectationsFlyteConfig]", expected "Tuple[Type[Any], Type[GreatExpectationsFlyteConfig]]")
plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py:84: error: Incompatible return value type (got "Tuple[Type[Any], GreatExpectationsFlyteConfig]", expected "Tuple[Type[Any], Type[GreatExpectationsFlyteConfig]]") …
```
=> [mypy] Fix Incompatible types

.github/workflows/sqlachemy_publish.yml
Fix invalid reference format when pushing SQLAlchemy image to GitHub Registry
https://github.com/flyteorg/flytekit/runs/3589591512
_NA_
OR
=> Fix invalid reference format when pushing SQLAlchemy image

flytekit/clis/flyte_cli/main.py, tests/flytekit/unit/cli/test_flyte_cli.py
flyte-cli setup-config throws JSONDecodeError because we tried to get admin credential in insecure mode. 
Get credentials only in a secure mode.
https://github.com/flyteorg/flyte/issues/163
_NA_
=> flyte-cli setup-config throws JSONDecodeError

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_hints.py
Please see the issue.  Basically allow the dict transformer to back out non-typed dictionaries.
I'm slightly concerned that someone else might want to write a different transformer that handles this case in the future, but that concern may be obviated by the addition of user-supplied type hints to `FlyteRemote`, in those cases where it's necessary to guess.
https://github.com/flyteorg/flyte/issues/1479
=> Add guess to DictTransformer

.github/workflows/pythonbuild.yml
This is just some cleanup work. A followup to https://github.com/flyteorg/flytekit/pull/641/
_NA_
OR
=> Stop pinning pip, setuptools, and wheel in github workflow

flytekit/core/workflow.py
Nit: remove duplicate error messages
Update error message in `flytekit/core/workflow.py`
_NA_
```bash=
File "test/workflows/example.py", line 17, in <module>
print(welcome(name="Kevin"))
File "/Users/kevin/opt/anaconda3/envs/flyte/lib/python3.8/site-packages/flytekit/core/workflow.py", line 236, in __call__
return flyte_entity_call_handler(self, *args, **input_kwargs)
File "/Users/kevin/opt/anaconda3/envs/flyte/lib/python3.8/site-packages/flytekit/core/promise.py", line 857, in flyte_entity_call_handler
result = cast(LocallyExecutable, entity).local_execute(child_ctx, **kwargs)
File "/Users/kevin/opt/anaconda3/envs/flyte/lib/python3.8/site-packages/flytekit/core/wo …
```
=> Duplicate error messages when running the workflow

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Cases in which a Dataclass consists of Generic types of nested types that contain an int, the integer ends up being a Float value. This is because protobuf struct does not have ints only a number.
fixes https://github.com/lyft/flyte/issues/1510
=> Dataclass should patch int values for nested cases

flytekit/remote/remote.py, tests/flytekit/unit/remote/test_remote.py
Let users specify a different config file if they have multiple flyte clusters.
_NA_
_NA_
=> Support flyte remote to use different config

flytekit/core/base_task.py, flytekit/core/condition.py, flytekit/core/promise.py, flytekit/core/type_engine.py, flytekit/types/directory/types.py, flytekit/types/file/file.py, flytekit/types/schema/types.py, tests/flytekit/unit/common_tests/test_promise.py, tests/flytekit/unit/core/test_conditions.py, tests/flytekit/unit/core/test_flyte_directory.py, tests/flytekit/unit/core/test_flyte_file.py, tests/flytekit/unit/core/test_imperative_with_patching.py, tests/flytekit/unit/core/test_schema_types.py, tests/flytekit/unit/core/test_type_hints.py
This PR intends to improve the error messages in case of type errors and also introduces stricter type checking for primitive types.
fixes https://github.com/lyft/flyte/issues/1439
fixes https://github.com/lyft/flyte/issues/1423
_NA_
=> Better error messages for Type Errors

.github/workflows/pythonbuild.yml
We run lint check three times per run, but we should only run once per run.
I've Ran the workflow in my fork's Github actions 
https://github.com/pingsutw/flytekit/actions/runs/1285916415
_NA_
=> Move lint check out of unit test

flytekit/remote/remote.py, flytekit/remote/workflow_execution.py
- remote.sync updates the execution object in place
`FlyteRemote.sync` no longer makes a copy of the input workflow execution, remove `FlyteWorkflowExecution.sync`
To make the UX around `FlyteRemote` more intuitive, we remove the `sync` method from the workflow execution object and make is so the `remote.sync` syncs the inputs and outputs of the underlying execution instead of making a copy
See more details in https://docs.google.com/document/d/1v1EFdqnHrsB7XSNzQLrpSSZtXtoBGQGoRFcztFGxRfM/edit
NA
NA
=> update remote.sync behavior, remove FlyteWorkflowExecution.sync

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Fix errors in feast notebook.
Before
```
>>> print(feature_store)
>>> print(feature_store.config)
During handling of the above exception, another exception occurred:
AttributeError                            Traceback (most recent call last)
/var/folders/by/42kc70lj1bb77klbhf2fmxx00000gn/T/ipykernel_46553/3923996928.py in <module>
1 print(feature_store)
----> 2 print(feature_store.config)
3 
~/opt/anaconda3/envs/flyte/lib/python3.8/site-packages/flytekit/core/type_engine.py in __getattr__(self, key)
766                 return self.__getitem__(key)
767             except KeyError:
--> 768                 raise AttributeError(key)
769 
770     return dataclass_json(dataclasses.dataclass(Model))
AttributeError: config
```
After …
=> Failed to load json_data to dataclass

flytekit/__init__.py, flytekit/models/admin/common.py, flytekit/models/core/execution.py, flytekit/models/core/literals.py, flytekit/models/core/types.py
Add common models to flytekit __init__
=> Add common models to flytekit __init__

flytekit/clis/flyte_cli/main.py
Add deprecation notice to `flyte-cli`
This is how executions of `flyte-cli` look like now:
```
❯ flyte-cli setup-config --host="localhost:30081" --insecure
...
DeprecationWarning: The command flyte-cli is deprecated.
################################################################################################################################
################################################################################################################################
Welcome to Flyte CLI! Version: 0.0.0+develop
```
_NA_
OR
=> Add deprecation warning and notice to flyte-cli

flytekit/remote/remote.py, flytekit/remote/workflow_execution.py
Fix FlyteRemote bugs:
- don't override `_closure` property with `self._closure = None` in `FlyteWorkflowExecution.__init__`
- Remove unnecessary check in `sync_workflow_execution` for `ResourceType.WORKFLOW`
_NA_
OR
=> fix flyte remote bugs

dev-requirements.txt, doc-requirements.txt, requirements-spark2.txt, requirements.txt, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt, tests/flytekit/unit/core/test_type_engine.py
test_dataclass_transformer is broken after bumping `marshmallow-jsonchema` to 0.13.0
https://github.com/fuhrysteve/marshmallow-jsonschema/pull/152 changed the type of the python int to integer, as opposed to number.
_NA_
OR
=> Fix dataclass transformer test

dev-requirements.txt, doc-requirements.txt, plugins/flytekit-aws-athena/requirements.txt, plugins/flytekit-aws-sagemaker/requirements.txt, plugins/flytekit-data-fsspec/requirements.txt, plugins/flytekit-dolt/requirements.txt, plugins/flytekit-greatexpectations/requirements.txt, plugins/flytekit-hive/requirements.txt, plugins/flytekit-k8s-pod/requirements.txt, plugins/flytekit-kf-pytorch/requirements.txt, plugins/flytekit-kf-tensorflow/requirements.txt, plugins/flytekit-modin/requirements.txt, plugins/flytekit-pandera/requirements.txt, plugins/flytekit-papermill/requirements.txt, plugins/flytekit-snowflake/requirements.txt, plugins/flytekit-spark/requirements.txt, plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/requirements.txt, plugins/flytekit-sqlalchemy/requirements.txt, requirements-spark2.txt, requirements.txt, setup.py, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
- (hopefully) Working duplicate of #740 (thanks to #741)
Updates the `pyarrow` dependency to 6.0.0 for easier `flytekit` installation on M1 macs. 
Previously, installation on M1 macs required `pyarrow` to be built from source since no prebuilt arm64 wheels were available for the 3.0.0 version. This build, in turn, depended on the 3.0.0 version of the [Apache Arrow](https://github.com/apache/arrow) library (`pyarrow`'s build system had breaking changes between 3.0.0 and 4.0.0). Apache Arrow can be installed via `brew`, but only the 6.0.0 version is currently available. This meant that users had to _also_ build the Apache Arrow library from source (and remember to set the correct `LDFLAGS` and `CFLAGS`, etc.) prior to building `pyarrow`. 
Since `pyarrow` version 6.0.0 includes prebuilt …
=> Bump pyarrow from 3.0.0 to 6.0.0 (for M1 mac installations; duplicates #740)

flytekit/types/directory/types.py, flytekit/types/file/file.py, tests/flytekit/unit/core/test_type_engine.py
Ensure that behavior of working with remote vs local files is identical when using Flytefile and Flytedirectory
Refer to the issue
fixes https://github.com/flyteorg/flyte/issues/1818
_NA_
=> Fix problem with FlyteFile / FlyteDirectory download

flytekit/remote/remote.py, plugins/flytekit-spark/tests/test_remote_register.py
Added default EntrypointSettings to flyte remote to eliminate the RuntimeError with spark tasks. 
Adapted the settings from `pyflyte package` to remote as in: https://github.com/flyteorg/flytekit/blob/751425d573d7ef7d2faa20de772b82b147083c5b/flytekit/clis/sdk_in_container/package.py#L137-L139
https://github.com/lyft/flyte/issues/1755
_NA_
=> Remote entrypoint serialize

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py
change the `load_by` value in the enum field so that we can dump JSON Schema from dataclass which has enum inside it.
otherwise, we will get the following errors from `marshmallow_jsonschema`
```
value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
File "/Users/kevin/opt/anaconda3/envs/flytekit-3.8/lib/python3.8/site-packages/marshmallow/fields.py", line 338, in serialize
return self._serialize(value, attr, obj, **kwargs)
File "/Users/kevin/opt/anaconda3/envs/flytekit-3.8/lib/python3.8/site-packages/marshmallow/fields.py", line 1864, in _serialize
return self._serialize_method(obj)
File "/Users/kevin/opt/anaconda3/envs/flytekit-3.8/lib/python3.8/site-packages/marshmallow_jsonschema/base.py", line 163, in get_properties …
```
=> Support enum in dataclass

flytekit/core/base_task.py, flytekit/models/admin/execution.py, flytekit/models/admin/node_execution.py, flytekit/models/core/catalog.py, tests/flytekit/unit/models/admin/test_node_executions.py, tests/flytekit/unit/models/core/test_catalog.py
See https://github.com/flyteorg/flytekit/pull/751/files.  This is just keeping the model files in line.
=> Mirror model changes from #751

flytekit/core/type_engine.py, flytekit/types/schema/types.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py
- Support FlyteSchema in dataclass
- Update cookbook https://github.com/flyteorg/flytesnacks/pull/491
Make FlyteSchema as dataclass
My sample code
```python
@dataclass_json
@dataclass
class SomeResult:
some_int: int
some_schema: SomeSchema
@task
def some_task() -> SomeResult:
some_schema = SomeSchema()
print("some_schema", some_schema.local_path)
some_df = pd.DataFrame(data={"some_str": ["a", "b", "c"]})
some_schema.open().write(some_df)
return SomeResult(some_int=1, some_schema=some_schema)
@workflow
def some_workflow() -> SomeResult:
return some_task()
```
https://github.com/flyteorg/flyte/issues/1521
_NA_
=> Add support FlyteSchema in dataclass

flytekit/core/type_engine.py, flytekit/remote/executions.py, flytekit/remote/remote.py, tests/flytekit/integration/remote/test_remote.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/remote/test_remote.py
Get raw input/output (Literal) from remote execution.
_NA_
OR
=> Get raw input/output from remote execution

flytekit/core/type_engine.py, flytekit/types/directory/types.py, flytekit/types/file/file.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py
Another way to support FlyteFile in dataclass
https://github.com/flyteorg/flytesnacks/pull/491
Add additional metadata to serialize/deserialize FlyteFile.
_NA_
=> Add support FlyteFile in dataclass

flytekit/core/task.py
Add `task_resolver` argument to the `@task` decorator
As part of the `flytekit-learn` project, we need to implement custom task resolvers for the `Dataset` and `Model` classes, which compose multiple functions together into a single task. The problem is that the task definition occurs within the class definition of `Dataset` and `Model`, so a custom task resolver needs to be implemented so that Flyte knows where to get the task definition.
NA
_NA_
OR
=> add task_resolver arg to @task decorator

flytekit/core/map_task.py, tests/flytekit/unit/core/test_map_task.py
For map tasks, if metadata is not specified, copy it from the underlying task.
https://github.com/flyteorg/flyte/issues/1912
=> Copy metadata into map task from underlying

tests/flytekit/unit/core/test_complex_nesting.py
Tests that came up during debugging.
=> Complex dataclass unit tests

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_flyte_file.py, tests/flytekit/unit/core/test_type_hints.py
Failed to run dynamic task which input is dataclass that has FlyteFile inside it.
The crux of the problem is that there was a mistake in the `FlyteFile` design.  The object does not invert cleanly.  That is,
if `X = FlyteFile(path="s3://abc")`, `X != TypeEngine.to_python_value(TypeEngine.to_literal(X))`. What happens rather is:
``` 
X -> to_literal -> Blob(uri="s3://abc") -> to_python_value -> FlyteFile(path="/tmp/xyz", remote_source="s3://abc")
```
where `/tmp/xyz` is the autogenerated folder on disk where the contents of the s3 would be downloaded to, if it were opened.
This means that the `path` in the `FlyteFile` object might not always be the path you want.  The `FlyteFile` transformer has special logic built in to detect this but the …
=> remote_source lost on serialization of @dataclass_json with FlyteFile

flytekit/remote/remote.py, tests/flytekit/integration/remote/test_remote.py
The semantics for how single-task execution compiled workflows seem to have changed at some point. Previously we relied on the node execution's `metadata.spec_node_id` to be empty, which now appears to not be the case.  Not sure what changed.
Add case for it
=> Single-task execution FlyteRemote sync

flytekit/clients/raw.py, flytekit/clis/flyte_cli/main.py, tests/flytekit/unit/remote/test_remote.py
Adding a switch (`-e` or `--cacert`) that takes a path to a PEM encoded file.  If specified, will be read and used as the root certificate to use in SSL connection with Admin.
* Adding click option to main flyte-cli command.
* Setting the path in the click context object if specified, None otherwise
* Value is always passed to client constructor. If present, file will be read and used as `root_certificates` value in `grpc.ssl_channel_credentials`
https://github.com/flyteorg/flyte/issues/1888
=> Add option to flyte-cli for specifying root certificate

dev-requirements.txt, doc-requirements.txt, requirements-spark2.txt, requirements.txt, setup.py, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
Relax the pyarrow requirements to allow for a wider installation base
The pyarrow minimal version is now set to 4.0.0. This will allow for clients that pin `pyarrow` to versions other than latest, while we still pull in latest from pypi in the simple case. 
https://github.com/flyteorg/flyte/issues/1979
_NA_
OR
=> Pyarrow greater than 4.0.0

flytekit/core/map_task.py, tests/flytekit/unit/core/test_map_task.py
`with_overrides` is not covered in the map task API. 
https://github.com/flyteorg/flyte/issues/1574
_NA_
OR
=> add `with_overrides` to map task

flytekit/__init__.py, flytekit/types/structured/__init__.py, flytekit/types/structured/basic_dfs.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py, plugins/flytekit-spark/flytekitplugins/spark/__init__.py, plugins/flytekit-spark/flytekitplugins/spark/schema.py, plugins/flytekit-spark/tests/test_wf.py, tests/flytekit/unit/core/test_local_cache.py
* Add new types to top level import to trigger transformer loading and overriding of base dataframe types in all instances.
* Moved Spark encoder and decoder into the spark plugin.
* Changed encoder to use a randomly generated remote directory instead of a file.
* `flytekit-sqlalchemy`, `flytekit-snowflake`, `flytekit-hive`, `flytekit-aws-athena` need backend changes to handle the new StructuredDataset type in addition to FlyteSchema.  Probably lower priority unless someone asks for it. After backend changes are done, we can update the Python type hints.
* `flytekit-modin` seems to operate on its own type, no interoperability present with the normal `pandas.DataFrame` type, so we don't have to worry about `pandas` -> `modin` compatibility.
* `flytekit-dolt` seems to be the same as …
=> [pr into #785] wip - Compatibility testing

.github/workflows/pythonbuild.yml, dataset_example.py, dev-requirements.txt, doc-requirements.txt, flytekit/core/data_persistence.py, flytekit/models/literals.py, flytekit/models/types.py, flytekit/types/structured/basic_dfs.py, flytekit/types/structured/bigquery.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-spark/flytekitplugins/spark/schema.py, requirements-spark2.txt, requirements.txt, setup.py, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt, tests/flytekit/unit/core/test_structured_dataset.py, tests/flytekit/unit/core/test_structured_dataset_handlers.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/models/test_literals.py
* Remove the format field from the literal model object since it's no longer in the IDL literal.  It's now only in the type.
* Remove `file_format` field from the python `StructuredDataset` object.  It will default to "parquet", and will only be settable by the user through `Annotate`. This should be okay because we don't see format to be used too often.
* Add helper functions to decoder/encoder lookup. Default to use `""` in case a matching format cannot be found.
* Update remaining handlers to have static values for at least type and format, in some cases also protocol.
* Change the `Encoder` interface to add `structured_literal_type: StructuredDatasetType` as an input argument. The reason is because we want contributors to be able to fill in/potentially modify the type information …
=> [pr into #785] Format cleanup

docs/source/conf.py, docs/source/index.rst
This PR should be merged with the following other PRs in order to update the theme to use the navbar header:
- https://github.com/flyteorg/furo/pull/10 << MERGE THIS FIRST
- https://github.com/flyteorg/flyte/pull/2037
- https://github.com/flyteorg/flytesnacks/pull/578
- https://github.com/flyteorg/flytekit/pull/806
- https://github.com/flyteorg/flyteidl/pull/247
- https://github.com/flyteorg/flytectl/pull/259
_NA_
OR
=> update docs for new navbar theme

dev-requirements.in, dev-requirements.txt, doc-requirements.in, doc-requirements.txt
Issue started because of github changes https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
pip install stop working because of deprecated protocol, Change it from `git://` to `https://`
_NA_
OR
=> fix github security issue in requirments

doc-requirements.in, doc-requirements.txt, docs/source/conf.py
Add sphinx panels to flytekit, in prep to spruce up flytekit API reference docs
_NA_
OR
=> Add sphinx panels

plugins/flytekit-aws-sagemaker/setup.py
Sagemaker plugin python package didn't contain the `models` submodule starting on the [0.24.0 release](https://github.com/flyteorg/flytekit/releases/tag/v0.24.0).
The sagemaker plugin does not contain all the expected files:
```
❯ ls -la flytekitplugins-awssagemaker-0.26.0/flytekitplugins/awssagemaker
.rw-r--r--  903 eduardo  5 Jan 14:04 __init__.py
.rw-r--r-- 3.0k eduardo  5 Jan 14:04 distributed_training.py
.rw-r--r-- 7.1k eduardo  5 Jan 14:04 hpo.py
.rw-r--r-- 8.3k eduardo  5 Jan 14:04 training.py
``` 
Note how the [`models`](https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/models) subdirectory is not present. 
We create source distributions (for both …
=> Fix sagemaker plugin

flytekit/testing/__init__.py
Add `SecretsManager` back to the old location - it doesn't belong but easier to leave it here than break people.
=> Add secretsmanager back

plugins/flytekit-spark/flytekitplugins/spark/task.py
Error: https://github.com/flyteorg/flytekit/runs/4859818955?check_suite_focus=true
It might be related to https://stackoverflow.com/questions/52133731/how-to-solve-cant-assign-requested-address-service-sparkdriver-failed-after
Updating spark conf can fix it.
```python
conf_spark = SparkConf().set("spark.driver.host", "127.0.0.1")
```
I ran the tests 100 times, The tests were all passed. 
https://github.com/pingsutw/flytekit/commits/spark-driver?before=8b7cb7d6449db4fea5add36de8014060b7522f9b+35&branch=spark-driver
The test which didn't update the spark config failed 3 times. 
https://github.com/pingsutw/flytekit/commits/bad-spark-driver?before=4cf2a1a41ab470946dcc7485adc573214fb74de7+35&branch=bad-spark-driver
_How did you fix the bug, make …
=> Fix flaky test: test_spark_task

flytekit/core/base_task.py, flytekit/types/structured/structured_dataset.py, setup.py, tests/flytekit/unit/core/test_structured_dataset.py, tests/flytekit/unit/core/test_type_engine.py
* Move logic for scanning Annotated into a separate function
* Make it so that the metadata.type.columns passed to the decoder are different than the columns in the incoming liter.
* Add column information to the type that the decoder gets even if the currently running task's signature does not specify columns.
* document subsetting behavior
* Introduce `StructuredDatasetFormat` as a type alias for str
* Add typing_extensions to setup.py
* Change a couple type hints to int
=> [pr into #822] 

flytekit/__init__.py, flytekit/types/structured/structured_dataset.py, tests/flytekit/unit/core/test_structured_dataset.py
* Unit tests
* Moved the creation of the new metadata and type objects in the `to_python_value` function outside of the conditional that checks for whether the python type is a `StructuredDataset` or an explicit dataframe type - that shouldn't matter.
* Overwriting the passed in literal's metadata with the newly computed metadata.  Now I'm seeing why we need this, and this undoes that change in #827.
* Added todos to address this in the future.
* Add an `updated_metadata` field to `open_as` and `iter_as`
* Export `StructuredDatasetFormat` at the top level of flytekit
=> [pr into #822] Final update to structured dataset column subsetting

plugins/flytekit-spark/flytekitplugins/spark/task.py
https://development.uniondemo.run/console/projects/flytesnacks/domains/development/executions/y3p1jyeegd?duration=all
If statement at line 109 will always be false and we will set the spark driver address to `127.0.0.1`. Therefore, the spark job will run forever.
_NA_
=> Fix spark regression

flytekit/core/context_manager.py, flytekit/core/python_function_task.py, flytekit/tools/translator.py, plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py, plugins/flytekit-k8s-pod/tests/test_pod.py, tests/flytekit/unit/core/test_type_hints.py
Also updates non-pod (regular container) tasks.
Add the second fast register setting (`distribution_location`) to the `FastSerializationSettings` object.
This also changes the behavior for non-pod tasks.  Basically to get the arguments to be filled in, you have to call `dispatch_execute` instead of just `compile_to_workflow` since the former is where the fast serialization settings are set. This should be okay though since that function isn't really exposed to the public but that is why there's a unit test that had to change.
Example of how the Pod spec of the child task looks now in local sandbox:
```
containers:
- args:
- pyflyte-fast-execute
- --additional-distribution
- …
```
=> Update argument setting for in fast registered, dynamically generated, pod tasks

flytekit/core/context_manager.py, flytekit/extras/tasks/shell.py, tests/flytekit/unit/core/test_context_manager.py, tests/flytekit/unit/extras/tasks/test_shell.py, tests/flytekit/unit/extras/tasks/testdata/script.sh
- Allows users to use `ctx.*` in shell tasks
- For secrets, it is necessary to use the attribute accessor api - `ctx.secrets.group.key`. The group and key are the actual group and key values to look for
- Also all inputs and outputs are now namesapced. So to access inputs it is necessary to use `inputs.x`
Example:
```python
t = ShellTask(
name="test",
script="""
export EXEC_ID={ctx.execution_id}
export SEC={ctx.secrets.group.key}
cat {inputs.f}
echo "Hello World {inputs.y} on  {inputs.j}"
""",
inputs=kwtypes(f=CSVFile, y=FlyteDirectory, j=datetime.datetime),
)
```
all variables supported by flytekit.current_context are replaceable.
https://github.com/flyteorg/flyte/issues/2110
_NA_
=> `ctx` Context can be used within shell tasks - to access context vars and secrets

flytekit/models/execution.py, tests/flytekit/integration/remote/test_remote.py, tests/flytekit/unit/models/test_execution.py
This passes on the duration field of the `ExecutionClosure` `fltyteidl` object so that it is available from Python. It converts it to 
a `datetime.timedelta` upon deserializing.
This is a first draft, please let us know what you think and whether this is useful in general. We would add a few tests after this.
This passes on the duration field of the `ExecutionClosure` `fltyteidl` object so that it is available from Python. It converts it to 
a `datetime.timedelta` upon deserializing.
-
-
=> Parse duration field from flyteidl to `flytekit.models.execution.ExecutionClosure`

flytekit/core/map_task.py, flytekit/models/array_job.py, tests/flytekit/unit/core/test_map_task.py
Set sane defaults in the map task template, matching the defaults in the [backend](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/plugins/array/core/state.go#L154-L160).
Map tasks containing custom fields would always succeed. That happened because in such cases we were not serializing `min_success_ratio`. In this PR we set defaults to the custom field.
I'm leaving support for `min_successes` intact just in case we have some client out there that's building these array jobs manually using flytekit.
_NA_
OR
=> Set default values to map task template

.github/workflows/pythonbuild.yml, flytekit/__init__.py, flytekit/extend/__init__.py, flytekit/types/structured/basic_dfs.py, flytekit/types/structured/bigquery.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-papermill/dev-requirements.in, plugins/flytekit-papermill/dev-requirements.txt, plugins/flytekit-spark/flytekitplugins/spark/sd_transformers.py, tests/flytekit/unit/core/test_structured_dataset.py, tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
Make the `register_handler` a class method so that we can get rid of the singleton.
Get rid of the singleton by making a few functions class methods.  This relies on our being able to isolate out the logic for stateful stuff (keeping track of registered handlers/default formats and protocols) with the non-stateful stuff (to literal and to python value and get literal type).
=> Remove singleton from structured dataset transformer engine

flytekit/remote/remote.py, tests/flytekit/integration/remote/test_remote.py
Assign input and output to FlyteWorkflowExecution after fetching execution.
https://github.com/flyteorg/flyte/issues/2108
_NA_
=> Assign input and output to FlyteWorkflowExecution

flytekit/remote/launch_plan.py, flytekit/remote/task.py, flytekit/remote/workflow.py, plugins/flytekit-greatexpectations/setup.py, tests/flytekit/unit/remote/test_calling.py
Attempting to partially address the fact that remote entities can't be used inside workflows.  See [slack](https://flyte-org.slack.com/archives/CREL4QVAQ/p1640009288109500) for more information.
Also upper bounding the great expectations library in the plugin as the latest version is causing some test errors.
Ignoring workflows for now because workflows are harder.  Since Admin doesn't do the fetching internally, we have to maintain the full set of subworkflows for each workflow.
Also still uses guessing.  Will remove in future iterations.  See issue for details.
Tested with the following script in local ipython with a sandbox running:
```python
import typing
from flytekit.remote.remote import FlyteRemote
from flytekit …
```
=> Add reference entities to FlyteTask and FlyteLaunchPlan

flytekit/tools/fast_registration.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/task.py, plugins/flytekit-greatexpectations/requirements.txt
Make the check for file types easier.
Just string match.  The subprocess command `"-xvf"` is actually for .tar files not .tar.gz files.  I guess tar is smart enough to just add the z when doing .tar.gz files.
https://github.com/flyteorg/flyte/issues/2152
=> Fix fast registration error

plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py
Add support for running pod task locally. 
This uses the local execute method inherited from the base Task class to run local execute. A warning was added to warn users that local testing environment may not match the pod environment that the task will use on Flyte.
=> Add support for local execute in pod task

plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py
Signed-off-by: ggydush-fn <greg.gydush@freenome.com>
Cherry-pick into v0.30
=> Add support for local execute in pod task (#852)

flytekit/types/file/__init__.py
Correct docs for HTMLPage type in flytekit.types.
Fixed by changing docs in `flytekit/types/file/__init__.py` for `HTMLPage` type. Documentation change only.
_NA_
=> Change docs for HTMLPage type to say HTMLPage instead of PNGImage

flytekit/models/literals.py, flytekit/types/structured/basic_dfs.py, flytekit/types/structured/bigquery.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/arrow.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/pandas.py, plugins/flytekit-spark/flytekitplugins/spark/sd_transformers.py, plugins/flytekit-spark/tests/test_wf.py, tests/flytekit/unit/core/test_structured_dataset.py, tests/flytekit/unit/core/test_structured_dataset_handlers.py, tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
- Add `current_task_metadata` in decoder interface
- Support spark decoder to read subset column
- Remove duplicate test
https://github.com/flyteorg/flyte/issues/2099
_NA_
=> Revisit StructuredDatasetDecoder interface

docs/source/contributing.rst
Legacy API has been removed, no need to mention it.
=> Quick cleanup of contributing.rst

flytekit/types/structured/basic_dfs.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/__init__.py, plugins/flytekit-data-fsspec/setup.py
Add GCS protocol in the structured dataset. 
Note: we can access google public bucket without adding `{anon: True}` in storage_options
https://gcsfs.readthedocs.io/en/latest/#credentials
sample code: https://gist.github.com/pingsutw/cd3e53905aba6b2073b11ad72c900b14
_NA_
=> Add GCS protocol in the structured dataset

flytekit/clis/sdk_in_container/pyflyte.py, flytekit/clis/sdk_in_container/serialize.py
Missed this in a prior PR.  Calls to setLevel are not correct, but let's just remove them entirely.
_NA_
OR
=> Remove extraneous calls to set logging level

flytekit/core/tracker.py
Add fix to allow usage of [sphinx doctest](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) with Flyte `@task` decorators
I would like to use Sphinx doctest to document some Flyte concepts for our users and include associated tests with Sphinx doctest. Here is a simple example of something that could be written in a doctest:
```python
```{testcode}
@task
def simple_squared_task(x: int) -> int:
return x ** 2
@workflow
def simple_squared_workflow(x: int) -> int:
return simple_squared_task(x=x)
print(simple_squared_workflow(x=2))```
```
```
```{testoutput}
4```
```
At present, this raises an exception, because the doctest module does not have `__name__` in globals when running `make doctest`.
```
Exception raised:
Traceback (most recent …
```
=> Fix to support sphinx doctest with task decorator

.github/workflows/pythonbuild.yml
Stop running integration tests for now. The pytest-flyte framework needs to be updated to reflect the new config system. Should be a minor change but we've been hoping to swap out the docker-compose backend with just flytectl sandbox for a while.
=> Delete CI for integration tests for now

flytekit/bin/entrypoint.py
This was inadvertently removed when we cleaned up configuration.  This code is necessary to ensure that if a dynamic task is fast registered, that calls a task that is also not in the base image, that those child tasks will also pull the same code layer before running. 
Copy back.
=> Add back propagating of fast register state

flytekit/clis/flyte_cli/main.py, flytekit/configuration/__init__.py
If not set on the command line, flyte-cli was not reading the host/insecure flags from the config file.  Behavior on master is:
```bash
(flytekit) ytong@argus:~/go/src/github.com/flyteorg/flytekit [flyte-sandbox] (master) $ cat ~/.flyte/local_sandbox
[platform]
url=localhost:30081
insecure=True
(flytekit) ytong@argus:~/go/src/github.com/flyteorg/flytekit [flyte-sandbox] (master) $ flyte-cli -c ~/.flyte/local_sandbox get-workflow -u wf:flytesnacks:development:core.control_flow.subworkflows.parent_wf:v0.3.56
DeprecationWarning: The command 'flyte-cli' is deprecated.
Config loading
################################################################################################################################
##################################################################################### …
```
=> Add back support for reading from parent command, config file, or subcommand in flyte-cli

dev-requirements.txt, doc-requirements.txt, flytekit/models/execution.py, flytekit/remote/remote.py, requirements-spark2.txt, requirements.txt, setup.py, tests/flytekit/unit/models/test_execution.py, tests/flytekit/unit/remote/test_remote.py
Added RawOutputDataConfig in ExecutionSpec
- Add RawOutputDataConfig in `models.execution.py`
- Unit tests for RawOutputDataConfig `from_flyte_idl` and `to_flyte_idl`
https://github.com/flyteorg/flyte/issues/2230
_NA_
=> Added RawOutputDataConfig in ExecutionSpec

flytekit/clients/raw.py, flytekit/configuration/__init__.py, flytekit/remote/remote.py, tests/flytekit/unit/clients/test_raw.py
Users might not do
```python
from flytekit.configuration import AuthType
PlatformConfig(auth_type=AuthType.BASIC)
```
they might just write `PlatformConfig(auth_mode="basic")` in which case the comparison breaks.
=> Fix auth comparison

.pre-commit-config.yaml, dev-requirements.txt, doc-requirements.txt, flytekit/clients/raw.py, plugins/flytekit-aws-athena/requirements.txt, plugins/flytekit-aws-batch/requirements.txt, plugins/flytekit-aws-sagemaker/requirements.txt, plugins/flytekit-bigquery/requirements.txt, plugins/flytekit-data-fsspec/requirements.txt, plugins/flytekit-dolt/requirements.txt, plugins/flytekit-greatexpectations/requirements.txt, plugins/flytekit-hive/requirements.txt, plugins/flytekit-k8s-pod/requirements.txt, plugins/flytekit-kf-mpi/requirements.txt, plugins/flytekit-kf-pytorch/requirements.txt, plugins/flytekit-kf-tensorflow/requirements.txt, plugins/flytekit-modin/requirements.txt, plugins/flytekit-pandera/requirements.txt, plugins/flytekit-papermill/requirements.txt, plugins/flytekit-snowflake/requirements.txt, plugins/flytekit-spark/requirements.txt, plugins/flytekit-sqlalchemy/requirements.txt, requirements-spark2.txt, requirements.txt, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt, tests/flytekit/unit/cli/test_cli_helpers.py, tests/flytekit/unit/core/test_serialization.py, tests/flytekit/unit/core/test_type_hints.py
Error:
```
File "/home/runner/.cache/pre-commit/repozuci9iid/py_env-python3/bin/black", line 8, in <module>
sys.exit(patched_main())
File "/home/runner/.cache/pre-commit/repozuci9iid/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1129, in patched_main
patch_click()
File "/home/runner/.cache/pre-commit/repozuci9iid/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1115, in patch_click
from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repozuci9iid/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```
It's related to this issue …
=> Fix lint error

flytekit/configuration/__init__.py, flytekit/configuration/feature_flags.py, flytekit/core/workflow.py, flytekit/remote/remote.py, flytekit/tools/translator.py
This PR makes remote.register_* methods work correctly. They use the get_serializable_entity functions and in the case of workflow register all downstream.
Also fixes the `__main__` name in the workflow.
Register will now register the workflow and all its downstream. Does not support fast-register yet
https://github.com/flyteorg/flyte/issues/2241
_NA_
=> FlyteRemote.register works 

flytekit/clis/sdk_in_container/package.py, flytekit/clis/sdk_in_container/serialize.py, flytekit/configuration/__init__.py, flytekit/remote/remote.py, flytekit/tools/repo.py, flytekit/tools/serialize_helpers.py, flytekit/tools/translator.py, tests/flytekit/unit/core/test_context_manager.py, tests/flytekit/unit/remote/test_remote.py
- creates a central tool for all repo level operations to register all workflows, tasks etc programmatically
- Also fixes a bug in registration of a workflow in remote, where the underlying launchplan will not use the options.
Goal:
```
repo.serialize_and_package(...)
repo.register()
repo.serialize_and_register()
```
Tests need to be done
NA
_NA_
=> Supporting repo-level operations

flytekit/deck/deck.py
=> Remove print statement from flytedecks code

.github/workflows/pythonpublish.yml
The `build-and-push-docker-images` job runs in a separate container, which requires to checkout the code before building the image.
https://github.com/flyteorg/flytekit/pull/915 was not enough to build the docker images. Upon publishing v0.32.0b1 we were still [seeing](https://github.com/flyteorg/flytekit/runs/5858541047?check_suite_focus=true) this error:
```
...
+ docker build --cache-from=ghcr.io/flyteorg/flytekit-stages:1 --tag my_awesome_image --file ./Dockerfile.py3.10 --compress=true --build-arg=VERSION= --build-arg=DOCKER_IMAGE=ghcr.io/flyteorg/flytekit:py3.10- .
+ tee build-output.log
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile.py3.10: no such …
```
=> Checkout code before invoking `whoan/docker-build-with-cache-action@v5` action

.github/workflows/pythonpublish.yml
Inter-job access of outputs requires explicit outputs to be set between jobs
We have 2 jobs defined in `pythonpublish.yml`:
1. `deploy` that takes care of pushing to pypi
2. `build-and-push-docker-images` which should be self-evident. 
Job 1 is upstream of job 2 and according to [github docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs), we can use outputs of upstream jobs, but only if we set the output in the upstream jobs directly. 
This PR sets an output in the upstream job `deploy` and consumes it in the downstream job using the required syntax. 
_NA_
OR
=> Fix use of dependency in pythonbuild workflow

flytekit/clients/raw.py, flytekit/clis/auth/auth.py, tests/flytekit/unit/cli/auth/test_auth.py
In the case when client credentials have expired or corrupted, the
default `_refresh_credentials_standard` flow will automatically force
the client to `refresh_access_token`.
But, in a happy case, the clear, unnecessarily removes the client creds,
thus forcing an auth to be retriggered
=> Client credentials should never be cleared

flytekit/remote/remote.py
Flyte Console might be hosted at a different endpoint than the grpc endpoint that backs FlyteAdmin.  To remedy this, we recently added the [service endpoint](https://github.com/flyteorg/flyteidl/pull/277) flag in the PublicClientAuthConfigResponse.
=> use public client response from domain if available

flytekit/clis/sdk_in_container/run.py, flytekit/remote/remote.py, flytekit/tools/script_mode.py
Signed-off-by: Haytham Abuelfutuh <haytham@afutuh.com>
In script mode, we rely on the hash of the generated tar file to idempotent-ly register tasks/workflows. Because tar file metadata changes every time, we end up with a different version S3 path for the task. Because we use the script md5 hash as the task version, admin rejects the registration because the content of the task proto changed.
This PR unifies versioning logic to rely on the tar file content md5 for the task version
=> Use MD5Sum of the tarfile as the task version

flytekit/clis/sdk_in_container/run.py, flytekit/tools/script_mode.py
- currently `pyflyte run` does not handle any flyte derivative classes - like flytefile etc
- Also fixes usage of `tar` to add `arcname=""`
- better error messaging
-
=> Handle: arcname="", unhandled dataclass derivative types and improved error messaging

flytekit/clis/sdk_in_container/run.py
Security context should be used, auth-role is deprecated
_NA_
=> use security context instead of AuthRole

Dockerfile.py3.10, Dockerfile.py3.7, Dockerfile.py3.8, Dockerfile.py3.9
Pod tasks should be usable in the default image
Install the pod plugin in all default images.
_NA_
OR
=> Install flytekitplugins-pod in the default images

flytekit/core/shim_task.py
When `pyflyte run` executes a customized container task, the task resolver returns a `ExecutableTemplateShimTask` directly with the task template model as one of its attributes. This PR fixes the `name` property by first trying to get the name based on the task template id, otherwise it assumes a `Task` subclass, which should have a `_name` attribute defined.
_NA_
OR
=> Fix executable shim task

flytekit/core/tracker.py
attribute `__file__` doesn't exist when running in jupyter notebook
_NA_
OR
=> Use inspect.getfile instead of __file__

flytekit/clis/sdk_in_container/run.py
Change default value for destination dir in `run` sub-command
As of this PR we assume that the working directory is correctly set in the images used in invocations of `pyflyte run`. By leaning on that fact we can approximate `pyflyte run` to `flyteremote` (by requiring less a priori knowledge about other uses of `pyflyte run` for a given workflow+tasks and vice-versa).
https://github.com/flyteorg/flyte/issues/2380
_NA_
=> Change default value for destination dir in run sub-command

flytekit/clis/sdk_in_container/run.py, flytekit/types/structured/structured_dataset.py
* Add support for workflows with `StructuredDataset` types in addition to pd.DataFrame.
* These types will need to be specified on the command line as a string of a path to a directory of one file instead of to the file directly. The better aligns to the rest of the SD encoding behavior.
* Don't use `lstrip`... that removes all the characters in the string passed in, it doesn't just remove the prefix. `"aaaaab".lstrip("a") == "b"` not `"aaaab"`
* Moved the options like `remote` and `service-account` up to the `run` command level to avoid conflicts with user wf input names.
* Move construction of the `FlyteRemote` context to the workflow command and store in context since we know at that point if this is a remote run or not.
* Make the `PandasToParquetDataProxyEncodingHandler` capable of …
=> pr into #960

plugins/flytekit-spark/scripts/flytekit_install_spark3.sh
This PR bumps the hadoop-aws and aws-java-sdk versions from 3.2.0 and 1.11.740 to 3.3.1 and 1.11.901 in accordance with spark 3.2.1 and pyspark 3.2.1. The version compatibility is derived from the [maven repository](https://mvnrepository.com/artifact/org.apache.spark/spark-core_2.13/3.2.1).
_NA_
OR
=> bump hadoop-aws version

flytekit/core/data_persistence.py, tests/flytekit/unit/core/test_flyte_file.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py
Use a randomly generated and unique path on every execution 
Instead of hardcoding the path `/tmp/flyte` as the place where the intermediate files are put, let's use a randomly generated path on every execution. The directory returned by `tempfile.mkdtemp` is guaranteed to be writable the user running the code.
Specifically, instead of using the directory `/tmp/flyte` as the dumping ground we're going to get a temporary directory that contains the prefix `flyte-` for easy identification, e.g. `/tmp/flyte-ml14tvg6`. 
_NA_
OR
=> Do not hardcode /tmp/flyte

flytekit/remote/remote.py
If you have a local `@workflow` that is comprised only of fetched or reference entities, then should not need a serialization settings object.
_NA_
OR
=> Make wfs completely comprised of remote entities not take settings

flytekit/clis/sdk_in_container/run.py
=> Remove suffix _old from pyflyte run help

flytekit/bin/entrypoint.py, flytekit/core/context_manager.py, tests/flytekit/unit/core/test_type_hints.py
Use the same type whether running locally or in production.
Also the execution name was incorrect.  See [flyteplugins](https://github.com/flyteorg/flyteplugins/blob/82be16b9e39907e0842f06bc9f2918f5e1f8eedb/go/tasks/pluginmachinery/flytek8s/k8s_resource_adds.go#L48) code for the env var added.
https://github.com/flyteorg/flyte/issues/2449
=> Use object type for execution identifier in ExecutionParameters

flytekit/clis/sdk_in_container/run.py, flytekit/configuration/file.py
pyflyte run should use config path from arg value
https://github.com/flyteorg/flyte/issues/2474
_NA_
=> pyflyte run use config path from arg value

Makefile
pip==22.1 broke pip-tools
_NA_
OR
=> Skip pip==22.1

flytekit/configuration/file.py, tests/flytekit/unit/configuration/test_internal.py
User reported some issues around external command auth.  Don't think this was the issue, but found it during investigation.
Basically the config object was correctly splitting a comma separated string when it was being passed in by a config file, but not when it was being read from env.
That is, when `ConfigEntry` calls `LegacyConfigEntry`, that class's `read_from_file` will apply a list transform, whereas its `read_from_env` does not.  This adds a default transform for the list type for legacy config if the returned value is a string and not a list but the legacy subtype is a list.
=> Add default list transformer for legacy config

flytekit/clis/sdk_in_container/run.py, flytekit/remote/remote.py, tests/flytekit/unit/cli/pyflyte/test_run.py
It is now possible to execute a single task from the command line
Example
```python
from flytekit import workflow, task
from typing import List, Dict
@task
def t1(l: str) -> List[str]:
return [l]
@workflow
def wf(l: str = "") -> List[str]:
return t1(l=l)
@task
def t2(i: Dict[str, int]) -> Dict[str, int]:
return i
@workflow
def wf2m(i: Dict[str, int]) -> Dict[str, int]:
return t2(i=i)
```
*To Execute*
```
pyflyte run --remote test2.py t1 --l hello
```
and help should show
```bash
➜ pyflyte run test2.py --help
Usage: pyflyte run test2.py [OPTIONS] COMMAND [ARGS]...
Run a [workflow|task] in a file using script mode
Options:
--help  Show this message and exit.
Commands:
wf    Run test2.wf in script mode
wf2m  Run test2.wf2m in script mode
t1 …
```
=> pyflyte run can now execute a task either locally or remote

flytekit/clis/sdk_in_container/pyflyte.py, tests/flytekit/unit/cli/pyflyte/test_package.py
User reported frustration with the `--pkgs` switch.  Users should be able to use comma-separated values in addition to specifying the click switch multiple times.
https://github.com/flyteorg/flyte/issues/2476
=> Allow comma separate packages in pyflyte --pkgs

flytekit/clis/sdk_in_container/pyflyte.py
Read packages from the `FLYTE_SDK_WORKFLOW_PACKAGES` environment variable for backwards compatibility.
[Slack reported](https://flyte-org.slack.com/archives/CREL4QVAQ/p1652275530635879) issue.
=> read packages from environment variables

flytekit/core/data_persistence.py
Prior to this change, the data persistence plugin used in the `FileAccessProvider.put_data` method would not use the correct data config (effectively it was empty). This PR passes the FileAccessProvider object's data_config into the appropriate plugin.
_NA_
OR
=> pass fileaccess data config to data persistence plugin

flytekit/core/interface.py, tests/flytekit/unit/core/test_type_hints.py
Fix typing edge case where `typing.ForwardRef`s get transformed into `FlytePickle` types and fail rather than resolving.
When using `from __future__ import annotations` all type annotations are `typing.ForwardRef`s and need to always be resolved with `typing.get_type_hints()`. Additionally, the returned dict may be mutated, so should be copied rather than still referring to static information (eg. global type annotations dict).
Fixed by `x.__annotations__` -> `dict(typing.get_type_hints(x))`, + unit test.
_NA_
_NA_
=> Correctly resolve forwardrefs in namedtuple typing

flytekit/tools/translator.py
We observed a bug when registering a workflow that directly calls one or more workflows. The first time I register it, it completes successfully. In subsequent times, we would expect it to skip the workflow / tasks, because there are no changes and the registration already happened. However, sometimes when you go to register again, instead of skipping, it produces an error that "workflow with different structure already exists with id resource_type". This is because the serialized versions of the parent workflow are different across calls to registration.
This PR this issue by ensuring that `get_serializable_workflow` returns the `subworkflow` dictionaries in the same order every time it is called.
The main open question I have is is this the correct place for this change to be made? Or …
=> Update get_serializable_workflow to consistently generate the same subworkflow order

flytekit/configuration/internal.py
User reported issue when running a command like
```bash
pyflyte -c ~/.flyte/config.yaml --pkgs core serialize --in-container-config-path /root/config.yaml --image my_image:123 workflows -f /tmp
```
=> Skip config checking if no ini config file present

flytekit/clis/sdk_in_container/run.py, flytekit/remote/remote.py, flytekit/tools/script_mode.py, tests/flytekit/unit/cli/pyflyte/test_nested_wf/a/b/c/d/wf.py, tests/flytekit/unit/cli/pyflyte/test_run.py
Fix importing code in script code by leveraging the script-mode assumption as opposed to the current working directory
The main change is in `load_naive_entity` where we no longer add the working directory to `sys.path` prior to loading the python file, instead, we add the project root.
I also added a few opportunistic fixes, like removing commented code and ensuring that we check the existence of `__init__.py` files before we copy them.
https://github.com/flyteorg/flyte/issues/2467
_NA_
OR
=> Fix importing code in script mode

dev-requirements.txt, doc-requirements.txt, flytekit/clients/raw.py, flytekit/configuration/__init__.py, flytekit/configuration/internal.py, requirements-spark2.txt, requirements.txt, setup.py, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
Enables the insecureSkipVerify config flag on pyflyte. Allows bypassing SSL certificate verification, allowing connections with self-signed certificates.
When insecureSkipVerify is set to true, fetches the SSL cert from the endpoint and creates a grpc secure channel with the 'ssl_target_name_override' option set.
Similar to https://stackoverflow.com/a/52855472
https://github.com/flyteorg/flyte/issues/2531
_NA_
=> Added support for insecureSkipVerify on pyflyte

flytekit/__init__.py, flytekit/types/numpy/__init__.py, flytekit/types/numpy/ndarray.py, plugins/flytekit-greatexpectations/tests/test_schema.py, plugins/flytekit-greatexpectations/tests/test_task.py, tests/flytekit/unit/core/test_numpy.py, tests/flytekit/unit/types/numpy/test_ndarray.py, tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
This PR adds support for `numpy.ndarray` as a native Flyte type.
**One caveat: object Numpy arrays cannot be serialized and unserialized.** 
https://github.com/flyteorg/flyte/issues/2544
_NA_
OR
=> TypeTransformer for Numpy

.github/workflows/pythonbuild.yml
Bump githb codecov action to 1.5.2 to get rid of "token not found" error 
_NA_
OR
=> Bump githb codecov action to 1.5.2

flytekit/core/python_auto_container.py, tests/flytekit/unit/core/configs/images.config, tests/flytekit/unit/core/test_serialization.py
Failed to run this example https://github.com/flyteorg/flytesnacks/pull/750 because we can't use underscores inside image_name `{{ .image.trainer_image.fqn }}.` 
Error message in the sandbox:
```bash=
containers with unready status: [ag2544qfr4zg4tprq6tq-n0-0]|Failed to apply default image tag "
{{.image.trainer_image.fqn}}:{{.image.trainer_image.version}}": couldn't parse image reference "
{{.image.trainer_image.fqn}}:{{.image.trainer_image.version}}": invalid reference format
```
updated regex
_NA_
=> Allow using underscores and numeric in the image name

flytekit/clis/sdk_in_container/register.py
The `click.option("-v", "--version", ..)` currently has the help string from `@click.option("--service-account", ...)`.
_NA_
OR
=> Fix wrong version help string in `pyflyte register`

flytekit/clients/friendly.py, flytekit/clients/raw.py, flytekit/deck/deck.py, flytekit/deck/html/template.html, flytekit/models/node_execution.py
- Added deck_uri to NodeExecution
- Added `get_download_signed_url` to get a signed url from data proxy
- Updated HTML template 
- Upload deck file to s3 if running remotely
New HTML template
_NA_
=> Add deck_uri to NodeExecution

flytekit/clis/flyte_cli/main.py, flytekit/configuration/__init__.py, tests/flytekit/unit/cli/pyflyte/test_main.py
Fix copy of dataclass in get_client in flyte-cli commands
Used `dataclasses.replace` to generate a copy of the PlatformConfig instead of the `with_parameters`.
https://github.com/flyteorg/flyte/issues/2614
_NA_
OR
=> Fix get client in flyte-cli commands

flytekit/configuration/__init__.py, tests/flytekit/unit/remote/test_remote.py
Fix port rewrite in the case of sandbox/demo cluster
We rewrite the flyteconsole port in case we detect that we're running on a sandbox/demo cluster. However, https://github.com/flyteorg/flytekit/pull/992/ made it so that `auth_type` is now read from the config file (as opposed to getting the default value). 
The fix is to ensure that the platform config for sandbox matches the one emitted by `flytectl`. 
https://github.com/flyteorg/flyte/issues/2615
_NA_
OR
=> Fix port rewrite in the case of sandbox/demo cluster

flytekit/core/python_auto_container.py, tests/flytekit/unit/core/test_python_auto_container.py
Fixes serialization of tasks with environment variables set.
Fixes `PythonAutoContainer.get_container` to handle the case where `SerializationSettings.env` is `None` (See: https://github.com/flyteorg/flytekit/blob/87d13903993d5339723ecd859bd362a64e780aec/flytekit/configuration/__init__.py#L638). Currently fails with:
```
File "/fn/bin/pyflyte", line 8, in <module>
sys.exit(main())
File "/fn/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/fn/lib/python3.9/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/fn/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```
=> Fix serialization of tasks with environment variables set

flytekit/core/promise.py, tests/flytekit/unit/core/test_promise.py
Added Unit tests for `create_and_link_node` and `translate_inputs_to_literals`
_NA_
=> Unit tests for promise.py

flytekit/core/schedule.py
Signed-off-by: Prafulla Mahindrakar <prafulla.mahindrakar@gmail.com>
_NA_
OR
=> Fixed doc for cron schedule

flytekit/core/context_manager.py, flytekit/deck/deck.py, tests/flytekit/unit/deck/test_deck.py
nit: We forgot return HTML string in get_deck()
_NA_
OR
=> Return deck html string when calling get_deck()

flytekit/clis/helpers.py, flytekit/clis/sdk_in_container/package.py, flytekit/clis/sdk_in_container/register.py, flytekit/tools/fast_registration.py, flytekit/tools/repo.py, tests/flytekit/unit/cli/pyflyte/conftest.py, tests/flytekit/unit/cli/pyflyte/test_package.py, tests/flytekit/unit/cli/pyflyte/test_register.py
This PR shows a help message along with showing a nice error at the bottom, while also exiting with a non-zero exit code for commands such as `pyflyte package` and `pyflyte register` when they fail. It also fixes the issue of rebundling an existing `.tgz` file while using fast registration.
1. A simple fix for `pyflyte register` when its argument `package_or_module` is not supplied, would have been to add `required=True` in its definition. This would have resulted in the following output after running `pyflyte register`:
```
Usage: pyflyte register [OPTIONS] PACKAGE_OR_MODULE...
Try 'pyflyte register --help' for help.
Error: Missing argument 'PACKAGE_OR_MODULE...'.
```
But, the documentation of `click` here: https://click.palletsprojects.com/en/8.1.x/arguments/#variadic-arguments in the …
=> Housekeeping for pyflyte package and register commands

flytekit/core/interface.py, tests/flytekit/unit/core/test_type_hints.py
Annotated metadata isn't included in namedtuple typing. `include_extras` should fix the issue.
Modified the import of `get_type_hints` from  `typing` to `typing_extensions` since `include_extras` is available starting Python 3.9.
_NA_
OR
=> Correctly fetch `typing.Annotated` metadata in `typing.NamedTuple`

flytekit/clients/raw.py
We were getting
```
Error getpublicclient config <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNKNOWN
details = "Stream removed"
debug_error_string = "{"created":"@1657750494.962014000","description":"Error received from peer ipv4:54.80.18.147:443","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Stream removed","grpc_status":2}"
>
```
when using the admin client with a self-signed cert.
The reason is because the `cn` from the x509 subject had a * in it.  `*.elb.us-east-1.amazonaws.com` which was causing the ssl check to fail in nginx ingress.
https://github.com/flyteorg/flyte/issues/2420
=> Don't override target name when using self-signed certs

MANIFEST.in, flytekit/deck/deck.py, flytekit/deck/html/template.html, setup.py
https://github.com/flyteorg/flytekit/blob/a968a5aa8338adbec10a38f79c5fdddb72c7c161/flytekit/deck/deck.py#L112-L115
- See: https://github.com/conda-forge/flytekit-feedstock/pull/14#issuecomment-1172955010
```sh
```
- The `setup.py` file tries to package `template.html` from the root of the repository. But, it has been moved to `flytekit/deck/html/template.html`.
https://github.com/flyteorg/flytekit/blob/a968a5aa8338adbec10a38f79c5fdddb72c7c161/setup.py#L25
- There is no `template.html` at the root of the package.
- The PyPI package (`v1.1.0`) does not have any `template.html`.
- The PyPI package (`v1.1.0`) also does not include any `template.html` inside `flytekit/deck/html` directory. …
=> Fix PyPI package source for `v1.1.0`

flytekit/types/structured/basic_dfs.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/__init__.py, plugins/flytekit-data-fsspec/setup.py, plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py, plugins/flytekit-spark/flytekitplugins/spark/sd_transformers.py
This PR adds support for storing `StructuredDatasets` using AzureBlobFileSystem (`abfs`).
As discussed before, we've added support for `abfs` (using `adlfs`/`stow` under the hood) for `StructuredDatasets` by adding it to the registered protocols for transformers.
I've also noticed one file (`plugins/flytekit-spark/flytekitplugins/spark/sd_transformers.py`) which still used string constants and didn't support GCS either. As we're currently not using Spark anywhere, I wasn't able to verify this change though, so I can revert those lines if you'd prefer.
https://github.com/flyteorg/flyte/issues/2709
_NA_
=> Added AzureBlobFileSystem support for StructuredDatasets

.github/workflows/pythonbuild.yml, dev-requirements.in, dev-requirements.txt, requirements-spark2.txt, requirements.txt
Use v3 of codecov github action
The number #1 failure in flytekit PRs (e.g. [1](https://github.com/flyteorg/flytekit/runs/7285489312?check_suite_focus=true)) is transient failures in the codecov action, this is supposed to be fixed in later versions. 
Also, v1 was officially [deprecated in February-2022](https://github.com/codecov/codecov-action/#%EF%B8%8F--deprecation-of-v1). The one property we set was migrated to v3, so no change is needed.
_NA_
OR
=> Use latest (as of 2022-07-11) version of codecov action

tests/flytekit/unit/cli/pyflyte/test_run.py
just add a unit test for recent merge
=> [nit] Add unit test

plugins/flytekit-polars/setup.py, plugins/flytekit-polars/tests/test_polars_plugin_sd.py, plugins/flytekit-whylogs/setup.py
=> Add entrypoint to setup.py in flytekit plugins

MANIFEST.in
It seems there is was a py.typed file that was inadvertently added as part of https://github.com/flyteorg/flytekit/pull/1088.  This is causing issues.
There are lots of places where we need to clean up mypy before adding this file.
Remove file.
=> Remove py.typed

plugins/flytekit-papermill/flytekitplugins/papermill/task.py, plugins/flytekit-papermill/tests/test_task.py
This PR modifies the papermill plugin so that, if render_deck=True is passed to __init__, the rendered output html is inserted as a flyte deck.
This PR modifies the papermill plugin so that, if a kwarg render_deck is passed, the flyte deck is added automatically, without need for a follow up task. The render_deck kwarg was used to ensure backwards compatibility, by default, the behaviour of the papermill plugin won't be changed (i.e., this deck support is opt-in).
Note that this won't happen for cached execution, there is an open issue out for fixing flyte decks for cached execution.
I tested this change by installing this branch of flytekit into a container and registering one of our company's test notebook tasks, and running it. It gets a deck as intended:
Not 100% happy with how I …
=> Add deck to papermill plugin task

plugins/flytekit-aws-sagemaker/scripts/flytekit_sagemaker_runner.py, plugins/flytekit-aws-sagemaker/setup.py, plugins/flytekit-aws-sagemaker/tests/test_flytekit_sagemaker_running.py
Sagemaker script was erroneously removed by a previous commit, when scripts were migrated to individual plugins.
=> Add sagemaker script back in

flytekit/clis/sdk_in_container/run.py, tests/flytekit/unit/cli/pyflyte/test_run.py
Should be local false when dealing with remote files, otherwise flytekit run will try to hash it.
This happens when you have a wf locally with a signature like
```
@workflow
from flytekit.types.file import PNGImageFile
def demo_wf(b: PNGImageFile) -> str:
```
and you pass `--b "https:..."` to `pyflyte run`.
=> Set to remote when dealing with remote files

flytekit/core/promise.py, tests/flytekit/unit/core/test_node_creation.py
https://flyte-org.slack.com/archives/CP2HDHKE1/p1659712233906449?thread_ts=1659445048.597709&cid=CP2HDHKE1
We should support overriding the resource of voidPromise
_NA_
=> Override voidPromise resource

flytekit/extras/tasks/shell.py
This PR fixes the type check executed at package time of shell tasks with specified task configurations.
The `task_config` parameter passed to a shell task must be of type `None` or `flytekitplugins.pod.task.Pod`. Right now, this check is being made with the following logic:
```python
if task_config is not None:
if str(type(task_config)) != "flytekitplugins.pod.task.Pod":
raise ValueError("TaskConfig can either be empty - indicating simple container task or a PodConfig.")
```
The nested if condition always returns true, because `str(type(task_config))` returns the string `"<class 'flytekitplugins.pod.task.Pod'>"`.
The proposed solution uses the `__module__` and `__class__.__name__` dunder methods to build the fully qualified class name for the parameter since it appears it shouldn't …
=> Fix how ShellTask retrieves the Pod class name

plugins/flytekit-data-fsspec/setup.py
The fsspec plugin uses the `storage_options` argument in the `to_parquet` call.  This option was not in until 1.2. 
See https://pandas.pydata.org/pandas-docs/version/1.3.5/reference/api/pandas.DataFrame.to_parquet.html
Just bump the plugin requirements.
User reported issue.
=> Add restriction for pandas to be >=1.2 for fsspec plugin

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
https://flyte-org.slack.com/archives/C037MMU74FN/p1660670745909239
```
@dataclass
class MyDataclass(DataClassJsonMixin):
value: Optional[int] = None
my_dataclass = MyDataclass(value=1)
```
`my_dataclass.value` appears to be converted to float and becomes 1.0 instead of remaining int and 1 as I expected.
Explicitly convert the `value` to int as well.
https://github.com/flyteorg/flyte/issues/2775
_NA_
=> Fix the type of optional[int] in dataclass

flytekit/core/data_persistence.py, flytekit/types/structured/basic_dfs.py, flytekit/types/structured/bigquery.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/__init__.py, plugins/flytekit-data-fsspec/flytekitplugins/fsspec/pandas.py, plugins/flytekit-papermill/dev-requirements.in, plugins/flytekit-papermill/dev-requirements.txt, plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py, plugins/flytekit-spark/flytekitplugins/spark/sd_transformers.py, tests/flytekit/unit/core/test_data_persistence.py, tests/flytekit/unit/core/test_structured_dataset.py, tests/flytekit/unit/core/test_structured_dataset_handlers.py, tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
Contributors of dataframe handling plugins use the `StructuredDatasetTransformerEngine.register` method to make the system aware of specific encoders and decoders.  Up until now, the user was asked to specify the "protocol" associated with each handler.
This is awkward for two reasons:
* If your encoder/decoder just relies on the base data persistence layer flytekit provides, there is no reason to ask the contributor to register once per protocol.  If we add a new protocol to the persistence layer, then someone would have to go through and update all these.
* Registering multiple protocols while having the default_for_type option in the signature makes it awkward.  The impression is that you have to somehow decide a priori which protocol should be the default.  This doesn't make sense - …
=> Allow None protocol to mean all data persistence supported storage options in Structured Dataset

docs/source/design/control_plane.rst, docs/source/design/index.rst, plugins/flytekit-onnx-scikitlearn/flytekitplugins/onnxscikitlearn/schema.py, plugins/flytekit-onnx-tensorflow/flytekitplugins/onnxtensorflow/schema.py
* Minor ONNX plugin transformer updates
* Minor flyteremote doc updates
_NA_
OR
=> minor doc and code updates

flytekit/extras/pytorch/__init__.py
The introduction of "soft" dependencies in `flytekit.extras` to support pytorch types leads to an OSError when trying to `import torch`: https://github.com/flyteorg/flytekit/pull/1032. This PR adds `OSError` as a potential exception raised when installing pytorch.
For context, see this slack thread: https://unionai.slack.com/archives/C01H0FN1NJX/p1661365911337069
Flytekit has a plugin system, hosted as separate packages in [this directory](https://github.com/flyteorg/flytekit/tree/master/plugins) of the flytekit repo. However, since Flyte is a ML- and Data-aware orchestration tool, it would make sense for the core ML frameworks to have first class support without having to install any plugins.
Therefore, we're establishing a new …
=> handle ImportError and OSError in extras.pytorch

flytekit/deck/renderer.py, flytekit/types/structured/basic_dfs.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py, plugins/flytekit-polars/tests/test_polars_plugin_sd.py, plugins/flytekit-spark/flytekitplugins/spark/sd_transformers.py, tests/flytekit/unit/core/test_structured_dataset.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/deck/test_renderer.py, tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
Register spark/polars dataframe renderers if the plugin is installed.
_NA_
=> Register dataframe renderers in structured dataset

flytekit/types/numpy/ndarray.py
Signed-off-by: Rahul Mehta <rahul@theoremlp.com>
The `NumpyArrayTransformer` incorrectly omits `raise` before `TypeTransformerFailedError`. Fix this.
See TLDR
None
_NA_
=> Properly raise `TypeTransformerFailedError` in `NumpyArrayTransformer`

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
[slack thread](https://flyte-org.slack.com/archives/CREL4QVAQ/p1661266231263149)
Add `assert_type()`in dataclass transformer, so we don't need to specify `type_hints` when using flyte remote.
We got an error when using dataclass as input in the flyte remote without passing `type_hints`, because `guess_python_type` is not equal to the user-defined dataclass type
```
@dataclass_json
@dataclass
class Foo(object):
a: int = 0
@task
def t1(a: Foo):
...
```
In this example, we use guess_python_type (FooSchema) as our `expected_type` by default if using flyte remote to execute the above task.
However, FooSchema is created by flytekit and it's not equal to the user-defined dataclass (Foo), so [assert_type](https://github.com/flyteorg/flytekit/blob/aff19 …
=> Add assert_type in dataclass transformer

flytekit/core/interface.py, flytekit/core/type_engine.py, flytekit/types/numpy/ndarray.py, tests/flytekit/unit/core/test_flyte_pickle.py, tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
Problems:
- Sequence wasn't converted to pickle
- Unknown type in Union wasn't converted to pickle
Both `Sequence` and `Union` have `__origin__` attribute, but we didn't handle these cases in [_change_unrecognized_type_to_pickle](https://github.com/flyteorg/flytekit/blob/22580d8ba63fe1842a9eb0de6281b2d5eb4bd588/flytekit/core/interface.py#L261-L265) 
https://github.com/flyteorg/flyte/issues/2823
_NA_
=> Pickle in Union Type

plugins/flytekit-aws-athena/setup.py, plugins/flytekit-aws-batch/setup.py, plugins/flytekit-aws-sagemaker/setup.py, plugins/flytekit-bigquery/setup.py, plugins/flytekit-data-fsspec/setup.py, plugins/flytekit-deck-standard/setup.py, plugins/flytekit-dolt/setup.py, plugins/flytekit-greatexpectations/setup.py, plugins/flytekit-hive/setup.py, plugins/flytekit-k8s-pod/setup.py, plugins/flytekit-kf-mpi/setup.py, plugins/flytekit-kf-pytorch/setup.py, plugins/flytekit-kf-tensorflow/setup.py, plugins/flytekit-modin/setup.py, plugins/flytekit-onnx-pytorch/setup.py, plugins/flytekit-onnx-scikitlearn/setup.py, plugins/flytekit-onnx-tensorflow/setup.py, plugins/flytekit-pandera/setup.py, plugins/flytekit-papermill/setup.py, plugins/flytekit-polars/setup.py, plugins/flytekit-ray/setup.py, plugins/flytekit-snowflake/setup.py, plugins/flytekit-spark/setup.py, plugins/flytekit-sqlalchemy/setup.py
Change the upper bound flytekit version in plugins to '<2.0.0' 
The official flytekit docker images failed to build when we released the beta version flytekit 1.2.0b0 [last week](https://github.com/flyteorg/flytekit/runs/7887779364?check_suite_focus=true) because of this error:
```
ERROR: Cannot install flytekit==1.2.0b0 and flytekitplugins-pod==1.2.0b0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested flytekit==1.2.0b0
flytekitplugins-pod 1.2.0b0 depends on flytekit<1.2.0 and >=1.1.0b0
```
https://github.com/flyteorg/flyte/issues/2855
_NA_
=> Set flytekit<2.0 in plugins

flytekit/clis/sdk_in_container/run.py, tests/flytekit/unit/cli/pyflyte/test_run.py
https://github.com/flyteorg/flyte/issues/2817
```python=
class Color(Enum):
RED = "red"
GREEN = "green"
BLUE = "blue"
@task
def coalesce(a:  Union[List[str], str, Color]) -> str:
if type(a) == Color:
print(a.name)
return a.name
print(a)
return a
@workflow
def wf(a:  Union[List[str], str, Color]) -> str:
coalesced = coalesce(a=a)
return coalesced
wf(a=Color("red"))
```
Take the above code as an example. If we run `pyflyte run --remote example_union.py wf --a "flyte"`, we'll get the below error.
```bash
Request failed with status code 400 invalid a input wrong type, expected union_type:<variants:<collection_type:
<simple:STRING > structure:<tag:"Typed List" > > variants:<simple:STRING structure:<tag:"str" > > …
```
=> Add literal type to union literal

flytekit/clis/sdk_in_container/package.py, flytekit/clis/sdk_in_container/register.py, flytekit/clis/sdk_in_container/serialize.py, flytekit/tools/fast_registration.py, flytekit/tools/repo.py, tests/flytekit/unit/tools/test_fast_registration.py
Adds a switch to enable dereferencing symlinks during fast packaging in `pyflyte serialize fast workflows`.
cc @wild-endeavor 
Added a click switch to `pyflyte serialize fast workflows` that enables/disables dereferencing any symlinks encountered during packaging. This only applies to `fast_package`. 
_NA_
No issue associated with this -- this is part of a request from Stripe. Our use case for this is as follows:
Our workflows often import code from utils files that are in sibling directories -- this makes the current `pyflyte package` not quite work for us. Our workaround is to use our bazel build target, which generates a `runfiles` directory that contains all the source code and dependencies, and then serialize from that folder. Some symlinks are generated during the build, so we …
=> Added symlink dereferencing in fast packaging and tests

flytekit/configuration/__init__.py, tests/flytekit/unit/configuration/configs/creds_secret_location.yaml, tests/flytekit/unit/configuration/test_internal.py
Trailing newlines in secrets cause more hard than they are worth, so we strip them and tell the user that they worth  
Remove newlines from the client secret files and log if that happens. 
https://github.com/flyteorg/flyte/issues/2849
_NA_
=> Strip newline from client secret

plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py
Fixes: https://github.com/flyteorg/flyte/issues/2813
Adds docstrings for pod task
[Conversation](https://flyte-org.slack.com/archives/C01RXBFV1M5/p1660732189538789)
Generated doc: https://flyte--1153.org.readthedocs.build/projects/flytekit/en/1153/plugins/generated/flytekitplugins.pod.Pod.html
Signed-off-by: SmritiSatyanV smriti@union.ai
=> Adds docstrings for pod task

flytekit/models/execution.py, tests/flytekit/unit/models/test_execution.py
Updates ExecutionClosure with optional AbortMetadata and ExecutionMetadata with the complete set of fields
User requested feature
https://github.com/flyteorg/flyte/issues/2881
_NA_
=> Execution model fields

flytekit/extras/sqlite3/task.py, tests/flytekit/unit/extras/sqlite3/test_task.py
Users should be able to overwrite the SQL task's image.
If they don't specify the image in the SQL task, then use the default image instead.
_NA_
OR
=> Overwrite SQLite3 Task image

plugins/flytekit-whylogs/README.md, plugins/flytekit-whylogs/flytekitplugins/whylogs/schema.py, plugins/flytekit-whylogs/requirements.txt, plugins/flytekit-whylogs/setup.py, plugins/flytekit-whylogs/tests/test_schema.py
- examples on our README were not using the latest whylogs.core.constraints.factories the same way as on flytesnacks.
- WhylogsDatasetProfileTransformer.to_html() now returns a ProfileSummary HTML string
Make our README.md in line with whylogs' examples page and also [flytenacks'](https://github.com/flyteorg/flytesnacks/tree/master/cookbook/integrations/flytekit_plugins/whylogs_examples)
_NA_
_NA_
=> refreshing examples and to_html() method

flytekit/core/type_engine.py, flytekit/types/schema/types_pandas.py, flytekit/types/structured/structured_dataset.py, tests/flytekit/unit/core/test_local_cache.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py
Ensure all types can have their hash values overriden
Initially we made it so that only pandas dataframes and StructuredDatasets could leverage the ability to override their hash values for the purpose of producing cache keys. This PR lifts that restriction and opens up that feature to all types. 
https://github.com/flyteorg/flyte/issues/2912
_NA_
OR
=> Open HashMethod to all types

flytekit/core/checkpointer.py, tests/flytekit/unit/core/test_checkpoint.py
Signed-off-by: Andrew Dye <andrewwdye@gmail.com>
`SyncCheckpoint.read()` should return `None` when src path is empty rather than raising an exception
Intra task checkpointing in Flyte passes a src path to the task in all attempts > 0. There is no guarantee that the prior attempt will have written checkpoint content. `SyncCheckpoint.read()` should return `None` when src path is empty rather than raising an exception. Tasks must already handle this case, as `None` is returned on attempt 0.
NA
NA
=> Return None for SyncCheckpoint.read() when src is empty

flytekit/core/container_task.py, tests/flytekit/unit/core/test_serialization.py
Bug in container task that wasn't being hit unless user specifies an additional env var map in the task.
Fix npe.
User reported issue:
https://discuss.flyte.org/t/2749411/what-s-your-gh-handle-U03KEF8H6FR
=> ContainerTask fix to read base env vars properly from compilation settings

flytekit/core/node.py, flytekit/core/promise.py, tests/flytekit/unit/core/test_node_creation.py
Add support chain multiple tasks by returning `other` when calling __rshift__
https://github.com/flyteorg/flyte/issues/2955
_NA_
=> Add support chain multiple tasks

flytekit/core/type_engine.py, plugins/flytekit-dbt/tests/test_task.py, tests/flytekit/unit/core/test_type_engine.py
Generalize the handling of Optional in DataclassTransformer
We catch the case of an `Optional[X]` member in a dataclass in the transformer before handing it to the List and Dictionary transformers.
I also added a test in the dbt plugins to confirm that the members in the plugin's [dbt dataclasses](https://cs.github.com/flyteorg/flytekit/blob/0bd3261c7567b0e25fa4cac88c883279b8752447/plugins/flytekit-dbt/flytekitplugins/dbt/schema.py?q=repo%3Aflyteorg%2Fflytekit+dbt#L111-L112) are handled correctly.
https://github.com/flyteorg/flyte/issues/2953
_NA_
=> Fix handling of Optional in the DataclassTransformer

flytekit/clis/sdk_in_container/helpers.py, flytekit/clis/sdk_in_container/register.py, flytekit/clis/sdk_in_container/run.py, tests/flytekit/unit/cli/pyflyte/test_register.py
`pyflyte register` is now able to load images present in the config file. That sub-command also requires a version in non-fast case.
Changes to `pyflyte register`:
1. The output of the command now is more explicit about which serialization settings are used, which include the images allowed to be used.
2. Force version in non fast. The idea is to make it clear that this option requires the user to be deliberate about versions when registering entities using the non-fast option.
3. Allow for images present in a config file to be used during registration
_NA_
OR
=> Enable use of image stanza in `pyflyte register` and other small changes

flytekit/core/base_sql_task.py, plugins/flytekit-snowflake/tests/test_snowflake.py
Related to https://flyte-org.slack.com/archives/CP2HDHKE1/p1664792800827789?thread_ts=1663843915.889099&cid=CP2HDHKE1.
[snowflake docs](https://docs.snowflake.com/en/sql-reference/data-types-text.html#dollar-quoted-string-constants)
Replace "\n" to "\\n" to fix the 400 error.
^^^
_NA_
=> Handle special characters in snowflake query

docs/source/design/control_plane.rst
This PR updated the `control_plane.rst` doc
Updated the note and removed the bullet point.
https://github.com/flyteorg/flytekit/pull/1212#issuecomment-1271161085
_NA_
OR
=> Update control_plane.rst doc

tests/flytekit/unit/extras/pytorch/test_transformations.py
This loads the `python_val` from the test to match the device logic used in `to_python_value`. A check is done to handle the case of `PyTorchCheckpoint` which does not have a to method.
Fix two unit tests that fail when run on a system that has a GPU available.
The code in `PyTorchTypeTransformer.to_python_value` will automatically load an object onto the GPU if the device is available.
```python
if torch.cuda.is_available():
map_location = "cuda:0"
else:
map_location = torch.device("cpu")
return torch.load(local_path, map_location=map_location)
```
But the objects in the unit test default to being loaded on the CPU.  This makes equality comparisons fail with a `RuntimeError`.
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! …
=> Fix the failing tests when run on a system that has a GPU available.

flytekit/configuration/__init__.py, flytekit/configuration/internal.py, flytekit/remote/remote.py, tests/flytekit/unit/remote/test_remote.py
Signed-off-by: Andrew Dye <andrewwdye@gmail.com>
Emit explicit console endpoint from flytectl config, if available.
https://github.com/flyteorg/flytectl/pull/361 added an optional config section for `console.endpoint`, allowing for separate endpoints between console and admin (which is the case for sandbox). This change updates the config consumption and remote helpers to use this explicit endpoint, if available, when displaying the console url after launching a remote execution. If not available, falls back to the same logic as before.
NA
NA
=> Use console endpoint config if available

flytekit/core/local_cache.py, tests/flytekit/unit/core/test_local_cache.py
Generate local cache keys by using protobuf's stable representation + joblib hashing
In https://github.com/flyteorg/flytekit/pull/1126/ we started using joblib and a custom Hasher to produce cache keys. That change handled the case of top-level dictionaries, but not nested dictionaries. 
This PR takes a different approach. We leverage the stable representation produced by the protobuf library and use that string as input (instead of a more complex object) as an input to `joblib.hash` (which generates fixed-length strings).
https://github.com/flyteorg/flyte/issues/2924
_NA_
OR
=> Stable local cache keys even in the case of nested dictionaries

docs/source/plugins/dbt.rst, docs/source/plugins/index.rst, plugins/flytekit-dbt/flytekitplugins/dbt/__init__.py
Update the plugin docs to include the dbt plugin module.
Verified with the local testing for docs using "make html"
Fixes https://github.com/flyteorg/flyte/issues/2966
NA
=> DBT Plugin Api reference

flytekit/deck/renderer.py, tests/flytekit/unit/deck/test_renderer.py
pandas dataframe default renderer should be cheap to render
The [default deck renderer for pandas dataframes](https://github.com/flyteorg/flytekit/blob/master/flytekit/deck/renderer.py#L27) relies on pandas dataframe [to_html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_html.html), but big dataframes take a long time to return, so in this PR we set reasonable defaults for both the max number of rows and columns.
_NA_
OR
=> Set reasonable defaults for pandas dataframe default renderer

flytekit/core/type_engine.py
Swap steps 3 & 4 in `type_engine.py` to walk the inheritance hierarchy to check for a registered `TypeTransformer` before checking `is_dataclass`
We have internal tooling which generates dataclasses from OpenAPI specifications, which all include a `Generated` mixin and are guaranteed to have a `to_dict`/`from_dict` method. We'd like to register a singletype transformer for all classes which have the `Generated` mixin instead of taking an extra dependency on `dataclass-json`; however, this isn't possible with the present implementation since the type engine checks `is_dataclass` before walking the inheritance hierarchy to resolve the type transformer.
This PR swaps this behavior so we can successfully detect a type transformer for `Generated` rather than falling back to the default …
=> Walk inheritance hierarchy before checking `is_dataclass` in type_engine

dev-requirements.txt, requirements-spark2.txt, requirements.in, requirements.txt
Added a version constraint for `grpcio` and `grpcio-status` in order to prevent an incompatible verison of `protobuf`.
The latest version of `grpcio` (1.50.0) requires a version of `protobuf` >= 4.0 that is not compatible with this project.  This causes a failure when running `make dev-requirements.txt`.  To fix this, we add a version constraint on `grpcio` and `grpcio-status`.
This was fixed by adding version constraints for `grpcio` and `grpcio-status` in `requirements.in`.
This was originally discussed in [this slack thread](https://flyte-org.slack.com/archives/CREL4QVAQ/p1666148447450899).
This may be a temporary solution as there was mention of updating the protobuf dependency.
https://github.com/flyteorg/flyte/issues/3006
=> 3006 - Added a version constraint for grpcio and grpcio-status

flytekit/core/container_task.py, tests/flytekit/unit/test_translator.py
Signed-off-by: Felix Ruess <felix.ruess@roboception.de>
GPU resource request and limit were not passed on to container for `ContainerTask`. 
Actually pass gpu request/limit like for the other Python container tasks...
_NA_
_NA_
=> fix: pass gpu resource request and limit in ContainerTask

flytekit/tools/fast_registration.py
In the case when using a container with a non root user, the inflation dir for the code has to be specified. It is common practice to skip a trailing slash "/mypath`/`". so when the distribution is downloaded, it will instead write this to this filename
And this fails the tar logic, which loooks for a similarly named file under the destination path.
The solution simply enforces that the given destination path is actually a directory
https://github.com/flyteorg/flyte/issues/3022
=> Fixing Fast Registration for non root dirs

flytekit/core/base_task.py, flytekit/core/checkpointer.py, flytekit/core/context_manager.py, flytekit/core/interface.py, flytekit/core/launch_plan.py, flytekit/core/map_task.py, flytekit/core/node_creation.py, flytekit/core/promise.py, flytekit/core/python_auto_container.py, flytekit/core/python_customized_container_task.py, flytekit/core/python_function_task.py, flytekit/core/task.py, flytekit/core/tracker.py, flytekit/core/type_engine.py, flytekit/core/workflow.py, flytekit/types/directory/types.py, flytekit/types/file/file.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-spark/tests/test_wf.py, tests/flytekit/unit/core/test_interface.py, tests/flytekit/unit/core/test_promise.py, tests/flytekit/unit/core/test_type_delayed.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/core/test_workflows.py, tests/flytekit/unit/types/structured_dataset/test_bigquery.py
Signed-off-by: Ryan Nazareth <ryankarlos@gmail.com>
This PR fixes all the mypy Incompatible Types errors
This PR fixes the following mypy errors thrown when running  `make lint | grep Incompatible`
Additonally, mypy complains that  plugins/flytekit-kf-mpi` invalid package name -  the `__init__.py` has been removed 
in this PR as this should be a directory anyway  based on other plugins structures.
Addresses part of issue https://github.com/flyteorg/flyte/issues/1030
_NA_
=> MyPy Cleanup Incompatible Types Errors

dev-requirements.txt, doc-requirements.txt, flytekit/clients/raw.py, requirements-spark2.txt, requirements.txt, setup.py, tests/flytekit/unit/clients/test_raw.py
will make it so at least there is more information to help debug - goes with changeset in the flyeadmin pr with same issue number: https://github.com/flyteorg/flyteadmin/pull/487
Makes it so there is more data if a workflow already exists but with different structure. More data will appear in logs as well as in the raised exception in the console.
Added more data in the flyteadmin PR and then add on the more data to the exception details when raised as part of the `_handle_invalid_create_request` decorator in the raw client
Fixes https://github.com/flyteorg/flyte/issues/2522
_NA_
OR
=> Update to include request and error message fix #2522

flytekit/types/directory/types.py, flytekit/types/file/__init__.py, flytekit/types/file/file.py, plugins/flytekit-aws-sagemaker/flytekitplugins/awssagemaker/training.py, tests/flytekit/unit/core/test_realworld_examples.py, tests/flytekit/unit/core/test_type_engine.py
Do not use TypeVar to denote the extension of a Flytefile. Pylint was breaking in a couple of places. This fixes it.
Ran pylint and got the stackstrace. Fixed it and then ran again without the errors. details below.
`typing.TypeVar` requires that the name of the var it is assigned to is a match. meaning `T = TypeVar("T")` is ok but `C = TypeVar("T")` is not. So when we have a file extension like "tar.gz" there is no way to assign that as a `tar.gz` variable. So instead we are just switching it to str type.
I left the TypeVar on file extensions in https://github.com/flyteorg/flytekit/blob/master/flytekit/types/file/__init__.py#L28-L82 since they don't seem to break anything.
I searched the rest of the repo looking for any other regex matches for something like with a period in the file …
=> Remove use TypeVar to denote the extension of a Flytefile #2870

.github/workflows/pythonbuild.yml
The underlying github action we use to push codecoverage data is not the most reliable and since we don't really look into the coverage data unless we're focusing on a specific area, we shouldn't fail the tests if the act of just pushing the code coverage data fails.
_NA_
OR
=> Do not fail if push to codecov fails

.github/workflows/pythonpublish.yml, Dockerfile
Build arm64 images for flytekit and sqlalchemy
This change uses the `docker/build-push-action` and docker buildx multi-arch support to build images for amd64 and arm64 across all supported python versions.
Verified images successfully build in forked repo with mock releases. See [publish workflow](https://github.com/andrewwdye/flytekit/actions/runs/3390746403) and [images](https://github.com/andrewwdye/flytekit/pkgs/container/flytekit).
**Note**: Looks like there is a dependency regression in master. Attempting to run tasks with these images fails with
```
Message: 
local/lib/python3.10/site-packages/flytekitplugins/fsspec/persist.py", line 95, in get
fs = self.get_filesystem(from_path)
File "/usr/local/lib/python3.10/site-packages/flytekitplugins/fsspec/persist.py", line 64, in …
```
=> Build arm images

flytekit/core/container_task.py
Signed-off-by: Felix Ruess <felix.ruess@roboception.de>
add missing secret_requests to ContainerTask
Do the same as in other container tasks...
_NA_
=> add missing secret_requests to ContainerTask

dev-requirements.txt, doc-requirements.txt, requirements-spark2.txt, requirements.in, requirements.txt, setup.py
We have to restrict grpcio in setup.py otherwise we won't be able to bump requirements in plugins
Two main changes:
1. regenerate requirements
2. move restriction to `grpcio` and `grpcio-status` to `setup.py` so that we can regenerate requirements in plugins (otherwise plugins try to pull in latest `grpcio`, which has a restriction on `protobuf>=4.21.6` (and it's incompatible with [flyteidl](https://github.com/flyteorg/flyteidl/blob/master/setup.py#L18))
_NA_
OR
=> Bump requirements and restrict grpcio and grpcio-status

plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py, plugins/flytekit-k8s-pod/tests/test_pod.py
Let environment variables be defined in the pod spec
Up to now we only let environment variables to be defined at the task level (via setting the `environment` field in the call to @task). In other words, if users wanted to control the env vars via env vars, they would have to define them using this method, which is not very ergonomic. This PR lets users define env vars in pod specs.
https://github.com/flyteorg/flyte/issues/3059
_NA_
OR
=> Allow for environment variables to be defined in the pod spec

plugins/README.md, plugins/flytekit-huggingface/setup.py
Currently, we can't install the plugin with flytekit versions `>1.2.0` such as the current version `1.2.3`.
_NA_
OR
=> Relax max flytekit version constraint in Huggingface plugin

tests/flytekit/unit/cli/pyflyte/test_run.py
This is a temporary fix to comment out a failing test... under investigation.
Re-running old tests on master are now failing. Specifically this will pass:
```
python -m pytest -svv tests/flytekit/unit/cli/pyflyte/test_run.py::test_pyflyte_run_cli
```
but this will fail
```
python -m pytest -vv tests/flytekit/unit/cli/pyflyte/test_run.py::test_pyflyte_run_cli
```
which indicates a deeper problem not directly related to core flytekit code.
=> [ Temporary fix] Comment out click test

flytekit/core/node.py, tests/flytekit/unit/core/test_node_creation.py
Signed-off-by: Hongxin Liang <honnix@users.noreply.github.com>
Override node name.
More details are captured in #3092.
I tested this on our setup. Everything seems to work fine, except the `Nodes` tab of the execution detail view. While `Graph` and `Timeline` both show the overridden node name, `Nodes` tab still shows the original task name.
Also note that many changes were made by `black`.
https://github.com/flyteorg/flyte/issues/3092
_NA_
=> Override node name

docs/source/plugins/vaex.rst, plugins/flytekit-vaex/flytekitplugins/vaex/__init__.py, plugins/flytekit-vaex/flytekitplugins/vaex/sd_transformers.py, plugins/flytekit-vaex/tests/test_vaex_plugin_sd.py
This PR:
* Replaces `metadata=StructuredDatasetMetadata(structured_dataset_type=StructuredDatasetType(structured_dataset_type))` with `metadata=StructuredDatasetMetadata(structured_dataset_type=structured_dataset_type)` (thanks, @pingsutw!)
* Fixes a misspelled decoder
* Adds plugin API reference
_NA_
OR
=> bug fix: vaex plugin

MANIFEST.in, setup.py
Missed this when https://github.com/flyteorg/flytekit/pull/1088 went in.
We don't need to package plugins.  Those are packaged separately.
=> Remove plugins from flytekit core packaging

flytekit_scripts/flytekit_build_image.sh
Add new `TARGET_PLATFORM_BUILD` ENV var to set the target platform architecture to allow to build docker image on a machine with a different architecture than the docker image will be executed. 
_NA_
https://github.com/flyteorg/flyte/issues/3097
_NA_
=> Add support to choose docker build target architecture

flytekit/extras/sqlite3/task.py, tests/flytekit/unit/extras/sqlite3/test_task.py
Newlines in multiline string queries should be escaped in sqlite tasks. This improves ergonomics of `SQLite3Task`
_NA_
OR
=> Sanitize query template input in sqlite task

plugins/flytekit-ray/requirements.txt, plugins/flytekit-ray/setup.py
We should install `ray[default]` instead of `ray`. `ray[default]` contains ray dashboard dependency, which will be used when we creating ray cluster. If we don't install it, ray operator will failed to submit the job to ray cluster because it can't find the dashboard IP address.
https://docs.ray.io/en/latest/ray-core/ray-dashboard.html#getting-started
^^^
Might related to https://flyte-org.slack.com/archives/CP2HDHKE1/p1669843950108329
_NA_
=> Update ray plugin dependency

plugins/flytekit-aws-athena/setup.py, plugins/flytekit-aws-batch/setup.py, plugins/flytekit-aws-sagemaker/setup.py, plugins/flytekit-bigquery/setup.py, plugins/flytekit-data-fsspec/setup.py, plugins/flytekit-dbt/setup.py, plugins/flytekit-deck-standard/setup.py, plugins/flytekit-dolt/setup.py, plugins/flytekit-greatexpectations/setup.py, plugins/flytekit-hive/setup.py, plugins/flytekit-huggingface/setup.py, plugins/flytekit-k8s-pod/setup.py, plugins/flytekit-kf-mpi/setup.py, plugins/flytekit-kf-pytorch/setup.py, plugins/flytekit-kf-tensorflow/setup.py, plugins/flytekit-modin/setup.py, plugins/flytekit-onnx-pytorch/setup.py, plugins/flytekit-onnx-scikitlearn/setup.py, plugins/flytekit-onnx-tensorflow/setup.py, plugins/flytekit-pandera/setup.py, plugins/flytekit-papermill/setup.py, plugins/flytekit-polars/setup.py, plugins/flytekit-ray/setup.py, plugins/flytekit-snowflake/setup.py, plugins/flytekit-spark/setup.py, plugins/flytekit-sqlalchemy/setup.py, plugins/flytekit-vaex/setup.py
We need to make sure plugins do not bring in flytekit 1.3.0 unnecessarily in the 1.2 branch
Ran:
```
for f in $(ls **/setup.py); do sed -E -i "s/flytekit>(.*),<2.0.0/flytekit>\1,<1.3.0,<2.0.0/" $f; done
```
_NA_
OR
=> Add upperbound constraint in plugins to < 1.3.0

flytekit/models/execution.py, flytekit/models/node_execution.py, tests/flytekit/unit/models/test_execution.py
Adding created and updated at to ExecutionClosure model.
This is hopefully the last model change we'll be making before we wholesale drop the entire model directory.
Useful for performance querying.
=> Adding created and updated at to ExecutionClosure model

setup.py
Restrict numpy version before removing deprecated numpy aliases
In numpy 1.20.0 some type aliases were marked as deprecated and those were finallly removed in version 1.24.0, which was released last night and broke default installations of flytekit.
https://github.com/flyteorg/flyte/issues/3166
_NA_
OR
=> Restrict numpy due to deprecated aliases

flytekit/models/execution.py, flytekit/remote/remote.py
Signed-off-by: H. Furkan Vural <hfurkanvural@blackshark.ai>
Adding overwrite_cache parameter for remote and local execution calls.
Implemented cache overwrite feature is added on flytekit as well for the completeness. In order to support the cache eviction RFC,  an overwrite parameter was added, indicating the data store should replace an existing artifact instead of creating a new one on local calls. 
https://github.com/flyteorg/flyte/issues/2867
_NA_
=> Add overwrite_cache option the to calls of remote and local executions

flytekit/bin/entrypoint.py, tests/flytekit/unit/bin/test_python_entrypoint.py
The serialized context that's stored in the environment variable `_F_SS_C` is present for dynamic tasks and contains the values detected at serialization time.  We should not be overriding the project and domain here.
=> Remove project/domain from being overridden with execution values in serialized context

plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py
if primary_container name is not specified it should default.
_NA_
OR
=> PodSpec should not require primary_container name

flytekit/clis/sdk_in_container/register.py
`pyflyte register` currently lists `-d` as the short option for both `--domain` and `--destination-dir`, which can result in unexpected behavior (e.g., causing executions of workflows to crash because it's pointing at the `development` directory, which does not exist). 
Changed `-d` flag for `--destination-dir` to `-D`, left `-d` flag as valid short flag for `--domain`.
https://github.com/flyteorg/flyte/issues/3178
_NA_
=> fix(pyflyte register): change -d to -D for --destination-dir as -d is already used for --domain

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Add support for optional fields in the dataclass type transformer
Handle `Optional` in the dataclass transformer explicitly, both in serialization and deserialization of dataclasses. This affects any type that includes a non-trivial transformation (e.g. `FlyteFile`).
https://github.com/flyteorg/flyte/issues/3187
_NA_
=> Handle Optional[FlyteFile] in Dataclass type transformer

plugins/flytekit-deck-standard/requirements.txt, plugins/flytekit-deck-standard/setup.py
Failed to run the workflow with latest Flytekit image because `ipywidgets` module not found  
```bash
[0]: code:"UnknownError" message:"Pod failed. No message received from kubernetes.\r\n[f773f1ce96ea54485bd2-n0-0-0] terminated with exit code (1). Reason [Error]. Message: \nandler <flytekit.types.structured.basic_dfs.ParquetToArrowDecodingHandler object at 0x7f29ae5f4fa0> with format parquet as default for <class 'pyarrow.lib.Table'>, parquet already specified.\"}\n{\"asctime\": \"2022-12-26 06:20:50,244\", \"name\": \"flytekit\", \"levelname\": \"WARNING\", \"message\": \"Not using handler <flytekit.types.structured.basic_dfs.ParquetToArrowDecodingHandler object at 0x7f29ae5f4fa0> with format parquet as default for <class …
```
=> Update flyte deck plugin's dependency

flytekit/configuration/__init__.py
Add `FastSerializationSettings` to the API reference documentation.
The class in question was not documented.
NA
NA
=> add FastSerializationSettings to docs

plugins/flytekit-k8s-pod/flytekitplugins/pod/task.py, plugins/flytekit-k8s-pod/tests/test_pod.py
Related to https://github.com/flyteorg/flytekit/pull/1380
Adds more tests and an example
=> Added more pod tests and an example pod task

flytekit/clis/sdk_in_container/run.py, tests/flytekit/unit/cli/pyflyte/workflow.py
Failed to run the workflow with default dict because we didn't convert default value of dict to json string. Hence, `json.load` failed to read the data.
convert value to the json string in the pyflyte run.
^^^
https://unionai.slack.com/archives/C01HA7KQP7X/p1672209391849269
_NA_
=> Convert default value of dict to json string in pyflyte run

flytekit/types/structured/structured_dataset.py
Change the log level to debug. Otherwise, we will get lots of warnings about structured datasets while running the workflow 
```bash
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.PandasToParquetEncodingHandler object at 0x7fce624a8220> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."}
{"asctime": "2022-12-25 22:57:07,317", "name": "flytekit", "levelname": "WARNING", "message": "Not using handler <flytekit.types.structured.basic_dfs.PandasToParquetEncodingHandler object at 0x7fce624a8220> with format parquet as default for <class 'pandas.core.frame.DataFrame'>, parquet already specified."} …
```
=> Update log level for structured dataset

flytekit/clis/sdk_in_container/helpers.py, flytekit/configuration/__init__.py, tests/flytekit/unit/cli/pyflyte/test_register.py, tests/flytekit/unit/configuration/configs/good.config, tests/flytekit/unit/configuration/configs/nossl.yaml, tests/flytekit/unit/configuration/test_file.py, tests/flytekit/unit/configuration/test_internal.py, tests/flytekit/unit/configuration/test_yaml_file.py
Please see the other PR.
This one:
* Adds a test for false SSL for the old .ini style of config
* Adds a shortcut for the pyflyte run/register commands - if no files are detected at all, create for sandbox instead.  I think this is okay. The other option would be to fall back to checking the `~/.flyte/config-sandbox.yml` file but I think using the code option is a bit cleaner, even though it ties us closer to the flytectl demo port settings.
=> pr into #1384

flytekit/remote/remote.py
output a warning message if git is not installed.
^^^
_NA_
_NA_
=> Warning if git is not installed

flytekit/loggers.py
Not sure why we didn't do this to begin with... doesn't this make more sense?  Basically
* Change the channel to be wide open, debug level.
* Make the root logger warning, unless set by `FLYTE_SDK_LOGGING_LEVEL` or `FLYTE_SDK_LOGGING_LEVEL_ROOT`.
* Make all child loggers warning, unless set by the relevant environment variable
* Unless it's the user facing logger, in which case make it info by default.
See above.  I think this is cleaner.  Tested locally and it seems to be more what we want.
No issue but https://github.com/flyteorg/flyte/issues/3126 and things like it keep cropping up.
=> Flip the settings for channel and logger

flytekit/core/promise.py, flytekit/remote/lazy_entity.py, tests/flytekit/unit/remote/test_lazy_entity.py
In cases when the lazy fetch fails with an attribute error, the entire lazy entity will end up in a infinite recursive call. It is anyways a good practice to catch the underlying exception and bubble as a runtime error. This should not affect any users today, but this is potentially a bug waiting to be uncovered in the future.
=> Preserving Exception in the LazyEntity fetch

docs/source/clients.rst, docs/source/index.rst, flytekit/clients/__init__.py
Fix [SynchronousFlyteClient API reference #3095](https://github.com/flyteorg/flyte/issues/3095)
Added new 'Clients' section in Flytekit API docs that pulls in docstring from `flytekit.clients.friendly.SynchronousFlyteClient` and `flytekit.clients.raw.RawSynchronousFlyteClient`
https://github.com/flyteorg/flyte/issues/3095
_NA_
=> [Docs] SynchronousFlyteClient API reference #3095

flytekit/core/base_sql_task.py, flytekit/extras/sqlite3/task.py, plugins/flytekit-snowflake/tests/test_snowflake.py, plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py, plugins/flytekit-sqlalchemy/tests/test_task.py, tests/flytekit/unit/extras/sqlite3/test_task.py
There's a bug in `SQLAlchemyTask` where multi-line strings were not valid inputs.
Like the `SQLite3Task`, modify `SQLAlchemyTask` to sanitize the input string.
_NA_
_NA_
=> Sqlalchemy multiline query

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Fixes bug in guesses Union types from remote literal type
fixes https://github.com/flyteorg/flyte/issues/3294
=> Fixes guess type bug in UnionTransformer

flytekit/core/promise.py, tests/flytekit/unit/core/test_conditions.py
This PR rewrites the `get_primitive_val` logic to fix condition validation when the Promise includes an integer `0`, a boolean `False` or a float `0.0`.
Slack conversation: 
> Hey all, I believe I found a small bug. LMK if there is a better channel for this. During local execution, conditionals interpret a int variable with value 0 as None.
```python
@workflow
def _impl(
delta: int,
) -> Set[str]:
return (
conditional("terminal_case")
.if_((delta != -1) & (delta <= 10))
.then(end())
.else_()
.then(
iterate()
)
)
def cluster_distributed() -> Set[str]:
_impl(delta=0)
```
> Outputs an error comparing NoneType <= 10
When the value is validated against `None`, the function returns the correct value. …
=> Fix primitive decoder when evaluating Promise

setup.py
Fixes https://github.com/flyteorg/flyte/issues/3313, which allows users to install flytekit on python 3.11 but then come up against errors on import.
- ~~[ ] Unit tests added~~
- ~~[ ] Code documentation added~~
- ~~[ ] Any pending items have an associated Issue~~
This restriction was expressed softly in the `classifiers` tags but not programmatically enforced.
- Create a python virtual environment on python 3.11 (either with `pyenv` or `miniconda`)
- Go to the `flytekit` root repo
- `pip install -e .` to do an editable install
- Expected outcome: you should see an error:
```
ERROR: Package 'flytekit' requires a different Python: 3.11.0 not in '<3.11,>=3.7'
```
[https://github.com/flyteorg/flyte/issues/<number>](https://github.com/fl …
=> set maximum python version to 3.10

flytekit/core/base_task.py, tests/flytekit/unit/core/test_checkpoint.py
Support checkpointing in local mode from cached tasks
- There's an inconsistency in behavior for checkpoints between cached and uncached tasks
- Local non-cached tasks execute in a "sandbox" context, while cached tasks don't
- I added a simple repro case as a unit test
- I unified the two cases to a common base method in base_task
- Also added a comment to hopefully key future edits to use the shared code path
_NA_
_NA_
=> Support checkpointing in local mode from cached tasks

flytekit/configuration/default_images.py, tests/flytekit/unit/configuration/test_image_config.py
Use scarf images to collect usage for default flytekit images.
_NA_
OR
=> Use scarf images

flytekit/extras/pytorch/native.py, tests/flytekit/unit/extras/pytorch/test_transformations.py
This PR fixes type fetch for torch types.
The `guess_python_type` method has been moved to the subclasses without retaining it in the parent class. This will return the correct type when fetching the execution output via FlyteRemote.
https://github.com/flyteorg/flyte/issues/3148
_NA_
OR
=> Fix PyTorch transformer

flytekit/core/map_task.py, plugins/setup.py
To make flytekit comply with [PEP-561](https://peps.python.org/pep-0561/#packaging-type-information), Add `py.typed` to the module.
```bash
pip install git+https://github.com/flyteorg/flytekit.git@2da8e88c7113b9b8537df520addc165c030d06cd
mypy test.py
```
https://github.com/flyteorg/flyte/issues/2147
_NA_
=> Make flytekit comply with PEP-561

plugins/flytekit-duckdb/flytekitplugins/duckdb/task.py, plugins/flytekit-duckdb/tests/test_task.py
This PR supports string as a valid input for DuckDB queries. This is helpful when the list is complex.
_NA_
OR
=> add string as a valid input

flytekit/bin/entrypoint.py, tests/flytekit/unit/bin/test_python_entrypoint.py
This PR is in response to https://github.com/flyteorg/flyte/issues/3169 which was incorrectly patched in https://github.com/flyteorg/flytekit/pull/1378 and later reverted in https://github.com/flyteorg/flytekit/pull/1460 because of 
https://github.com/flyteorg/flyte/issues/3324
This is still not the complete fix.  For that we need to enable `flytectl` to update the serialized context.  (which means we'll probably make serialization settings a protobuf object.) 
This was tested with the test case in https://github.com/flyteorg/flyte/issues/3324 and the failure case repro'ed with [this branch](https://github.com/flyteorg/flytekit/blob/cb35b8e5518d178c5f353c20caa98282d3d44044/flytekit/bin/entrypoint.py#L273).
https://github.com/flyteorg/flyte/issues/3169
=> Add back attempt to use existing serialization settings when running

flytekit/core/map_task.py, plugins/setup.py
This reverts commit b3ad1584b210f145030b121ecbe953bb018eca4c.
The public flytekit decorators are not ready yet for public consumption
_NA_
OR
=> Revert "Make flytekit comply with PEP-561 (#1516)"

flytekit/exceptions/user.py
Failed to initialize FlyteInvalidInputException. should not use `self` in `super()`
```bash
Failed with Unknown Exception <class 'TypeError'> Reason: super() argument 1 must be type, not FlyteInvalidInputException
super() argument 1 must be type, not FlyteInvalidInputException
```
^^^
NA
_NA_
=> Failed to initialize FlyteInvalidInputException

plugins/flytekit-data-fsspec/flytekitplugins/fsspec/persist.py, plugins/flytekit-data-fsspec/tests/test_persist.py
use FLYTE_AWS_ACCESS_KEY_ID and FLYTE_AWS_SECRET_ACCESS_KEY via config if they exist instead of AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
so that user code can inject and use these default AWS creds env vars
flytekit will used the `AWS_ACCESS_KEY_ID` env var instead of the also existing `FLYTE_AWS_ACCESS_KEY_ID` env if the former exists in the container.... this made my task which needs to retrieve data from a different bucket with different creds (injected via secret) fail upon downloading/uploading flyte inputs/output.
_NA_
_NA_
=> prefer FLYTE_ prefixed AWS creds env vars

flytekit/tools/serialize_helpers.py, tests/flytekit/unit/cli/pyflyte/test_package.py
Skip remote entity when generating protobuf files.
cc @sonjaer 
We should not generate protobuf files for remote entities.
Closes https://github.com/flyteorg/flyte/issues/3386
_NA_
=> Filter out remote entity when generating pb

flytekit/types/schema/types.py
This moves the FlyteSchema deprcation message from a global warning to only get logged when a user initializes the FlyteSchema class or uses `FlyteSchema[TYPE]` in their code.
The global warning throws new users off, especially since they are (probably) not even using or aware of FlyteSchema.
NA
_NA_
=> move FlyteSchema deprecation warning to initialization method

flytekit/clients/auth/authenticator.py, flytekit/clients/auth_helper.py, tests/flytekit/unit/clients/auth/test_authenticator.py
This PR fixes a bug in the auth mechanism where locally defined `scopes` are ignored and the ones defined in the admin are always used.
If `scopes` are locally defined, use those for auth. This mirrors the reference implementation [here](https://github.com/flyteorg/flyteidl/blob/e1a667ef2536bbfc61331490b5417404f45ddc0b/clients/go/admin/token_source_provider.go#L67).
https://github.com/flyteorg/flyte/issues/3486
=> Pass locally defined scopes to RemoteClientConfigStore

flytekit/clients/auth/token_client.py, tests/flytekit/unit/clients/auth/test_token_client.py
With url unsafe characters in the secret, we were getting errors like
```
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. The client secret in the HTTP authorization header could not be decoded from 'application/x-www-form-urlencoded'.
```
url encode
=> url encode secret in client credentials flow

flytekit/clis/sdk_in_container/run.py, flytekit/remote/remote.py, flytekit/tools/script_mode.py, tests/flytekit/unit/tools/test_script_mode.py
Add support uploading multiple files if needed when using pyflyte run.
Consider the following example, we should copy `main.py`, `t1.py`, `t2.py` to the destination. 
`compress_scripts` will do 
1. copy the script to destination.
2. import module (script).
3. Iterate all the module in this script.
4. recursively run `compress_scripts()` if import flyte entity from other file.
Source:
```
├── __init__.py
├── other.py
├── wf1
│   ├── __init__.py
│   ├── main.py # import t1
│   └── t1.py # import t2
└── wf2
├── __init__.py
└── t2.py
└── t3.py
└── t4.py
```
Destination:
```
├── __init__.py
├── wf1
│   ├── __init__.py
│   ├── main.py
│   └── t1.py
└── wf2
├── __init__.py
└── t2.py
```
All of the below commands work for me
```bash
pyflyte run --remote root/wf1/main.py wf
pyflyte run --remote …
```
=> Python run multiple files

flytekit/clients/auth/keyring.py
Replace warning with debug logs for keyring.
_NA_
OR
=> fix: Silence keyring warnings by changing to debug

flytekit/core/context_manager.py, flytekit/models/security.py, tests/flytekit/unit/core/test_context_manager.py, tests/flytekit/unit/models/core/test_security.py
Support GCP secret style.  Make the key optional now in Secret since GCP doesn't have a key. But it does have a group version so add that to the env var and file path lookups.
Order is
group -> group version (if present) -> key (if present)
Backend PR https://github.com/flyteorg/flytepropeller/pull/547/
_NA_
OR
=> Support GCP secrets

Makefile, dev-requirements.in, flytekit/clis/flyte_cli/main.py, flytekit/core/tracker.py
Add `autoflake` to `make fmt`, it can remove unused import. 
https://pypi.org/project/autoflake/
^^^
_NA_
_NA_
=> Automatically remove unused import

flytekit/tools/serialize_helpers.py, tests/flytekit/unit/cli/pyflyte/test_package.py
This used to be a problem but is now less so.  In early iterations of flytekit, we would run into issues with multiple definitions of flyte entities.  They tended to have different definitions and so would trigger a 'duplicate entity with different definition' error in flyte admin.  This occurs much less frequently now and this check is causing an issue with map tasks.
We will investigate post 1.5 release how to cache map task definitions so that multiple map_task() declarations on the same underlying task do not result in a new object being created.
=> Remove duplicate reporting logic

.readthedocs.yml, docs/source/design/authoring.rst, flytekit/__init__.py
This PR improves the authoring structure documentation.
* Added graphviz package to render visualizations
* Edited content for clarity
_NA_
OR
=> Improve authoring structure documentation

setup.py
Add classifier for Python 3.11
It looks that flytekit now supports Python 3.11, so let's add the classifier
Closes https://github.com/flyteorg/flyte/issues/3594
_NA_
=> Add classifier for Python 3.11

flytekit/core/data_persistence.py, tests/flytekit/unit/core/test_data.py
Set cache_regions to circumvent an aiobotocore bug
According to https://github.com/fsspec/s3fs/issues/701#issuecomment-1480303225, setting `cache_regions=True` makes it so that `aiobotocore` does not hit the access denied bug.
_NA_
OR
=> Set cache_regions=True in the case of s3fs

flytekit/extras/tasks/shell.py
Fixes below errors in the CI, The test is failing because the latest python requires user to set `COMSPEC` in environment variable. 
For more detail, check https://github.com/python/cpython/issues/101283
```bash
FAILED tests/flytekit/unit/extras/tasks/test_shell.py::test_shell_task_no_io - FileNotFoundError: shell not found: neither %ComSpec% nor %SystemRoot% is set
FAILED tests/flytekit/unit/extras/tasks/test_shell.py::test_input_substitution_primitive - FileNotFoundError: shell not found: neither %ComSpec% nor %SystemRoot% is set
FAILED tests/flytekit/unit/extras/tasks/test_shell.py::test_input_substitution_files - FileNotFoundError: shell not found: neither %ComSpec% nor %SystemRoot% is set
FAILED tests/flytekit/unit/extras/tasks/test_shell.py::test_input_substitution_files_ctx - …
```
=> Set default ComSpec when running on Windows

plugins/flytekit-kf-mpi/flytekitplugins/kfmpi/__init__.py, plugins/flytekit-kf-mpi/flytekitplugins/kfmpi/task.py, plugins/flytekit-kf-mpi/tests/test_mpi_task.py
Implement horovod task in mpi plugin
https://github.com/flyteorg/flyte/issues/3567
=> Implement horovod task in mpi plugin

plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py, plugins/flytekit-deck-standard/tests/test_renderer.py
This PR adds a new renderer that makes it easy to save image files to a Flyte Deck. It works with both `PIL.Image.Image` and various `FlyteFile` types.
Also slight cosmetic change on using `import pandas as pd`.
_NA_
OR
=> Add ImageRender class for Flyte Decks

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Batchable lists of length 0 should produce empty lists
_NA_
OR
=> Handle batchable lists of length 0

flytekit/tools/script_mode.py, tests/flytekit/unit/tools/test_script_mode.py
Fix the bug that was reported in the community sync. 
```
AttributeError: 'ImperativeWorkflow' object has no attribute 
'instantiated_in'
```
^^^
_NA_
_NA_
=> pyflyte run imperative workflow

flytekit/clis/sdk_in_container/backfill.py, flytekit/remote/backfill.py, tests/flytekit/unit/cli/pyflyte/test_backfill.py
- Backfill was using incorrect arguments
- backfill should use the argument that user provides or none at all
https://github.com/flyteorg/flyte/issues/3599
=> Backfill should fill in the right input vars

flytekit/clis/sdk_in_container/backfill.py, flytekit/clis/sdk_in_container/build.py, flytekit/clis/sdk_in_container/constants.py, flytekit/clis/sdk_in_container/helpers.py, flytekit/clis/sdk_in_container/init.py, flytekit/clis/sdk_in_container/launchplan.py, flytekit/clis/sdk_in_container/local_cache.py, flytekit/clis/sdk_in_container/package.py, flytekit/clis/sdk_in_container/pyflyte.py, flytekit/clis/sdk_in_container/register.py, flytekit/clis/sdk_in_container/run.py, flytekit/clis/sdk_in_container/serialize.py, setup.py
pyflyte is used by thousands of developers, lets make it pretty
=> Pyflyte prettified

flytekit/clis/sdk_in_container/run.py, tests/flytekit/unit/cli/pyflyte/test_run.py
This allows pyflyte run to accept json files for json args
```bash
pyflyte run my_workflow --my-json path/file.json --other-input 1
```
OR
```bash
pyflyte run my_workflow --my-json '{"x":"y"}' --other-input 2
```
https://github.com/flyteorg/flyte/issues/3371
=> pyflyte run now supports json/yaml files

flytekit/image_spec/image_spec.py, plugins/flytekit-envd/flytekitplugins/envd/image_builder.py, plugins/flytekit-envd/tests/test_image_spec.py, tests/flytekit/unit/core/image_spec/test_image_spec.py
`is_inside` will check if current image is built from image_spec when running remotely. This function always returns true when running locally, which means it will import all the package in local execution.
```python
from flytekit import task, workflow, Resources
from flytekit.image_spec import ImageSpec
new_flytekit = "git+https://github.com/flyteorg/flytekit@db448b054533de52e3a2d7fdb08be31e7b8a5c7d"
tensorflow_image_spec = ImageSpec(packages=["tensorflow", new_flytekit], apt_packages=["git"], registry="pingsutw")
torch_image_spec = ImageSpec(packages=["torch", new_flytekit], apt_packages=["git"], registry="pingsutw")
if tensorflow_image_spec.in_container():
print("import tensorflow")
import tensorflow  # import tensorflow only when running t1
if torch_image_spec.in_container(): …
```
=> Add is_inside func to ImageSpec

flytekit/core/base_task.py, flytekit/core/context_manager.py, flytekit/core/data_persistence.py, flytekit/core/map_task.py, flytekit/core/python_auto_container.py, flytekit/core/type_engine.py, flytekit/core/utils.py, flytekit/deck/deck.py, flytekit/deck/html/template.html, flytekit/tools/fast_registration.py, plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py, plugins/flytekit-deck-standard/tests/test_renderer.py, plugins/flytekit-mlflow/tests/test_mlflow_tracking.py, tests/flytekit/unit/core/test_utils.py, tests/flytekit/unit/deck/test_deck.py
The concept involves measuring the time taken by each component when executing a task, including both Flytekit and user-defined parts. Users have the option to view a timeline graph by setting the `disable_deck parameter=False`. For example:
```python
from flytekit import task, Resources, workflow
from flytekit.core.utils import timeit
@task(
disable_deck=False,
limits=Resources(mem="4Gi", cpu="1"),
)
def t1():
import time
@timeit("Download data from s3")
def download_data():
time.sleep(1)
download_data()
with timeit("Test long string "*20):
time.sleep(1)
for i in range(10):
with timeit(f"Run small tasks {i}"):
print("hello world")     
@workflow
def wf():
t1()
wf()
```
Tests(also tested in sandbox):
Note:
- Setting the disable_deck parameter to True will only …
=> Measuring the time taken for each component when executing a task

flytekit/__init__.py, flytekit/configuration/__init__.py, flytekit/core/python_auto_container.py, flytekit/image_spec/image_spec.py, plugins/flytekit-envd/flytekitplugins/envd/image_builder.py, setup.py, tests/flytekit/unit/core/image_spec/test_image_spec.py, tests/flytekit/unit/core/test_python_function_task.py
Recreate PR because #1609 stuck at pending.
Skip building the image if failed to check if image exists, and we assume image already exists.
^^^
__NA__
_NA_
=> Skip the image building process if the check for its existence fails

plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py, plugins/flytekit-polars/tests/test_polars_plugin_sd.py
fixed https://unionai.slack.com/archives/C02CMUNT4PQ/p1683221575139199
Read polar dataframe without copying to local
^^^
https://unionai.slack.com/archives/C02CMUNT4PQ/p1683221575139199
_NA_
=> Read polar dataframe without copying to local

flytekit/clis/sdk_in_container/pyflyte.py
We were returning too early and not printing the actual error.  Now we do.
Also make things bold.
=> Include traceback in errors from admin

flytekit/clis/sdk_in_container/constants.py, flytekit/clis/sdk_in_container/run.py, flytekit/remote/remote.py, tests/flytekit/unit/cli/pyflyte/test_run.py
Fixes https://flyte-org.slack.com/archives/CP2HDHKE1/p1683114107382779
Add a new flag (--copy-all) to pyflyte run. it allows user to copy all the files in the source root directory to remote.
^^^
https://flyte-org.slack.com/archives/CP2HDHKE1/p1683114107382779
_NA_
=> Add support for copying all the files in source root 

plugins/flytekit-spark/flytekitplugins/spark/pyspark_transformers.py
This PR fixes [#3648](https://github.com/flyteorg/flyte/issues/3648)
_NA_
OR
=> Fix PipelineModel transformer issue 3648

flytekit/core/promise.py, flytekit/core/type_engine.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_workflows.py
merge into https://github.com/flyteorg/flytekit/pull/1605
=> Add support for using union type in subworkflow's input

plugins/flytekit-papermill/flytekitplugins/papermill/__init__.py, plugins/flytekit-papermill/flytekitplugins/papermill/task.py, plugins/flytekit-papermill/tests/test_task.py, plugins/flytekit-papermill/tests/testdata/nb-simple.ipynb, plugins/flytekit-papermill/tests/testdata/nb-types.ipynb
This is a first draft for allowing the papermill plugin to access more complex inputs. 
Right now the papermill plugin can't use `FlyteFile` or `StructuredDataset` because of a Papermill limitation that everything is json serializable.
My strategy is mostly copying `record_outputs`. These are the steps
1.  Reserializing the inputs and save to local disk
2. Add a helper function `read_input` where users must give the input type (maybe there is a smart fix)
3. `read_input` loads the protos and uses the type to convert it to the correct format
Basically I am using flyte to serialize the inputs locally (see comments), then you just need to do this. 
```python
pi = (filled in by papermill)
pi = read_input(pi, float)
```
https://github.com/flyteorg/flyte/issues/3617
_NA_
OR …
=> [Issue-3617] Enables FlyteFiles, FlyteDirectors, and StructuredDatasets inputs in papermill plugin

flytekit/core/task.py
Functions decorated by `flytekit.task` are not hinted as `PythonFunctionTask` as a result of its return typing, so there are spurious type errors when attempting to register such tasks on `FlyteRemote` objects.
Here you can see an explanation of the problem and the fix:
```python
import flytekit.configuration as flyte_config
import flytekit.remote
@flytekit.task
def my_task1() -> int:
return 0
@flytekit.task()
def my_task2() -> int:
return 0
@flytekit.task(task_config=5)
def my_task3() -> int:
return 0
my_task4 = flytekit.task(lambda: 0)
remote = flytekit.remote.FlyteRemote(...)  # type: ignore
serialization_settings = flyte_config.SerializationSettings(...)  # type: ignore
reveal_type(my_task1)  # Type of "my_task1" is "((...) -> Any) | PythonFunctionTask" …
```
=> Improve task decorator type hints with overload

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
Allow users to specify TypeTransformers via Annotation
This is a followup to conversation in https://github.com/flyteorg/flytekit/pull/1565 
=> add annotation option for serialization

flytekit/clients/auth/authenticator.py, flytekit/clients/auth_helper.py, flytekit/clis/sdk_in_container/helpers.py, flytekit/configuration/__init__.py
Adds support for URLs within API Keys to remove the need for a config file entirely.
This PR builds on the work in #1569. It adds another key in the encoded API Key (endpoint) to make it possible to get rid of the config file entirely for simple use-cases.
```bash
echo '{"client_id":"abc","client_secret":"def","url":"my-endpoint.com"}' | base64
FLYTE_CREDENTIALS_API_KEY=eyJjbGllbnRfaWQiOiJhYmMiLCJjbGllbnRfc2VjcmV0IjoiZGVmIiwidXJsIjoibXktZW5kcG9pbnQuY29tIn0K pyflyte run --remote my_wp.py wf
```
_NA_
OR
=> Support URLs in API Keys

flytekit/core/workflow.py
Currently, the `workflow` decorator is hinted as always returning a `WorkflowBase`, which is not true when `_workflow_function` is `None`; this leads to a spurious type error depending on how `workflow` is called; similar to #1631, I propose using `typing.overload` to differentiate the return type of `workflow` based on the value of `_workflow_function`.
Here is an example of the typing bug this fix addresses:
```python
import flytekit.remote
@flytekit.workflow
def my_workflow1() -> int:
return 0
@flytekit.workflow()
def my_workflow2() -> int:
return 0
my_workflow3 = flytekit.workflow(lambda: 0)
remote = flytekit.remote.FlyteRemote(...)  # type: ignore
reveal_type(my_workflow1)  # Type of "my_workflow1" is "WorkflowBase"
remote.register_workflow(my_workflow1)  # OK …
```
=> Improve workflow decorator type hints with overload

flytekit/image_spec/image_spec.py, plugins/flytekit-envd/flytekitplugins/envd/image_builder.py, plugins/flytekit-envd/requirements.txt, plugins/flytekit-envd/setup.py, plugins/flytekit-envd/tests/test_image_spec.py, tests/flytekit/unit/cli/pyflyte/test_run.py, tests/flytekit/unit/core/image_spec/test_image_spec.py, tests/flytekit/unit/core/test_python_function_task.py
Blocked by https://github.com/tensorchord/envd/pull/1582#pullrequestreview-1421521963
Add a new property (platform) in imageSpec to build different arch image.
^^^
_NA_
_NA_
=> Multi arch imageSpec

plugins/flytekit-spark/flytekitplugins/spark/task.py, plugins/flytekit-spark/tests/test_spark_task.py
nit: Add executor_path and applications_path to spark config
people may want to change python and application path in the driver and worker node when they use custom spark image.
^^^
_NA_
=> Add executor_path and applications_path to spark config

doc-requirements.txt, flytekit/clis/sdk_in_container/run.py, flytekit/models/common.py, flytekit/models/execution.py, flytekit/remote/remote.py, setup.py, tests/flytekit/integration/remote/test_remote.py, tests/flytekit/unit/cli/pyflyte/test_run.py
- Add env to flyteremoote.execute
- Add env to pyflyte run
```
pyflyte run --env {"foo": "bar"} ...
```
^^^
https://github.com/flyteorg/flyte/issues/2447
_NA_
=> Add support for env vars to pyflyte run

flytekit/remote/entities.py, flytekit/remote/remote.py
Fixes https://github.com/flyteorg/flyte/issues/3639
Instead of fetching flyte task entity from admin, we should get task interface from [DynamicWorkflowNodeMetadata](https://github.com/flyteorg/flyteidl/blob/5e89823156a3dd616f57d8c9ac7495bf15b8ede6/protos/flyteidl/admin/node_execution.proto#LL229C5-L229C32).
btw, the sub node data in the dynamic has been add into the `node_mapping`. we can directly get task interface from the node_mapping
```python
from typing import Dict
from flytekit import task, workflow, dynamic
from flytekit.configuration import Config, SerializationSettings, ImageConfig
from flytekit.remote import FlyteRemote
@task
print(a)
return a
@task
def t2(b: int) -> int:
print(b)
return b
@dynamic
def bayesopt(n_iter: int, concurrency: int) -> Dict: …
```
=> Fetch task executions in dynamic 

flytekit/clients/auth/authenticator.py, flytekit/clients/auth/token_client.py, flytekit/clients/auth_helper.py, flytekit/configuration/__init__.py, flytekit/configuration/internal.py, tests/flytekit/unit/clients/auth/test_authenticator.py, tests/flytekit/unit/clients/auth/test_token_client.py
1. Add http_proxy to oauth2 client because in on-prem cluster use cases, the client might not have access to the external network
2. Remove `verification_url_complete` because that field not exists in [azure ad](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#device-authorization-request) and the oauth2 standard.
3. Concat the scopes by white space per [the documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#device-authorization-request)
https://github.com/flyteorg/flyte/issues/3620
=> Add http_proxy to client & Fix deviceflow

flytekit/tools/repo.py
The name is not accurate. Rename it to improve readability
After `load_packages_and_modules`, the entities become **registrable**.
=> Change variable names to improve readability

flytekit/clis/sdk_in_container/run.py, tests/flytekit/unit/cli/pyflyte/test_run.py, tests/flytekit/unit/cli/pyflyte/workflow.py
This allows pyflyte run to accept pickle file. 
```python
from typing import Dict, Any
@task
def test(config: Dict[str, Any]) -> None:
print(config)
@workflow
def wf(config: Dict[str, Any]) -> None:
test(config=config)
```
```bash
pyflyte --config ~/.flyte/config-remote.yaml --verbose run --remote test.py wf --config '{"hello": "world"}'
```
^^^
https://flyte-org.slack.com/archives/CP2HDHKE1/p1684272325647759
_NA_
=> pyflyte run supports pickle

plugins/flytekit-envd/requirements.txt, plugins/flytekit-envd/setup.py
envd supports python 3.7, let's make the envd flytekit plugin in the 1.2 branch also support that
This is preventing us from generating the default docker images for the 1.2.12 [release](https://github.com/flyteorg/flytekit/actions/runs/5007729856/jobs/8975150027#step:7:668).
_NA_
OR
=> Enable envd plugin for python 3.7

.github/workflows/pythonpublish.yml
Wait for one the plugins to show up in PyPI instead of the main package
We introduced an explicit wait in https://github.com/flyteorg/flytekit/pull/1554, but it turns out that most of the failures (e.g. https://github.com/flyteorg/flytekit/actions/runs/5007729856/jobs/8974742807#step:7:659) we're seeing during releases are for the plugins (which are published in order). So, let's wait for the pod plugin instead of the main package.
_NA_
OR
=> Wait for the pod plugin instead of flytekit

flytekit/clients/auth/authenticator.py
To make deviceflow prompt more prominent
Note: for why `verification_url_completed` is removed, check https://github.com/flyteorg/flytekit/pull/1611
=> Beautify deviceflow prompt

flytekit/clients/auth/authenticator.py, flytekit/clients/auth/token_client.py, flytekit/clients/auth_helper.py, tests/flytekit/unit/clients/auth/test_authenticator.py, tests/flytekit/unit/clients/auth/test_token_client.py
Pass verify flag to all authenticators
=> Pass verify flag to all authenticators

flytekit/core/type_engine.py, flytekit/types/file/file.py, tests/flytekit/unit/core/test_flyte_file.py, tests/flytekit/unit/core/test_type_engine.py
This PR allows annotated FlyteFiles to be used as input arguments of a task, e.g., when calculating a custom hash using `Annotated[FlyteFile, HashMethod(...)]`.
See the discussion on [Slack](https://flyte-org.slack.com/archives/CP2HDHKE1/p1683635974841289) for additional details.
Using an annotated FlyteFile type as an input to a task was previously impossible due to an exception being raised in `FlyteFilePathTransformer.to_python_value`.
This MR applies the fix previously used in `FlyteFilePathTransformer.to_literal` to permit using annotated FlyteFiles as either inputs or outputs of a task (see MR #1544), by unwrapping the origin type of the annotated type.
https://github.com/flyteorg/flyte/issues/3424
_NA_
=> Allow annotated FlyteFile as task input argument

plugins/flytekit-sqlalchemy/flytekitplugins/sqlalchemy/task.py
Use root logger instead of print statement in sqlalchemy plugin
- [x ] Bug Fix
Just replaced the print statement with the root loggers info statement as suggested in the issue
https://github.com/flyteorg/flyte/issues/3651
=> Use logger instead of print statement in sqlalchemy plugin

flytekit/core/map_task.py, plugins/flytekit-papermill/flytekitplugins/papermill/task.py, plugins/flytekit-papermill/setup.py, plugins/flytekit-papermill/tests/test_task.py
This PR allows map over notebook task
```python
import os
import pathlib
import typing
from flytekit import kwtypes, task, workflow, ImageSpec, map_task
from flytekitplugins.papermill import NotebookTask
new_flytekit = "git+https://github.com/flyteorg/flytekit@022ade936d2fe1eb6a2d705c319cce7d2c66ade6"
new_papermill = "git+https://github.com/flyteorg/flytekit.git@022ade936d2fe1eb6a2d705c319cce7d2c66ade6#subdirectory=plugins/flytekit-papermill"
image = ImageSpec(registry="pingsutw", packages=[new_papermill, new_flytekit], apt_packages=["git"])
nb = NotebookTask(
name="simple-nb",
notebook_path=os.path.join(
pathlib.Path(__file__).parent.absolute(), "nb-simple.ipynb"
),
render_deck=True,
inputs=kwtypes(a=float),
outputs=kwtypes(square=float),
container_image=image,
)
@workflow
def wf(a: …
```
=> Map over notebook task

setup.py
pyflyte commands hang if grpcio 1.55.0 is installed
More details in the linked issue.
https://github.com/flyteorg/flyte/issues/3718
_NA_
OR
=> Skip grpcio 1.55.0

flytekit/core/node.py, tests/flytekit/unit/core/test_node_creation.py
This PR allows people to override image by using `with_overrides`
^^^
https://flyte-org.slack.com/archives/CP2HDHKE1/p1683934828365009
_NA_
=> Add support image overriding

flytekit/core/promise.py, tests/flytekit/unit/core/test_promise.py
```python
from flytekit import task, workflow, Workflow
from dataclasses_json import dataclass_json
from typing import Optional
@dataclass_json
@dataclass
class Config:
lr: float = 0.1
@task
def func(cfg: Optional[Config] = None) -> None:
print(cfg is None)
wf = Workflow(name="foo")
wf.add_entity(func, cfg=None)
wf()
```
This code snippet works up to flytekit version `1.5.0`. It does not work in `1.6.0` (change introduced in [this](https://github.com/flyteorg/flytekit/commit/4037fa0135b8faf078f0be652eb6abd486c570ce) commit), failing with this error:
```console
╭──────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────╮
│ …
```
=> Fix ability to pass None to task with Optional kwarg, add test

flytekit/clis/sdk_in_container/pyflyte.py, flytekit/configuration/file.py
Also when running `pyflyte -c cfg.yaml package ...`, if a user has `Config.auto()` in their code, `cfg.yaml` should get used.
_NA_
OR
=> FLYTECTL_CONFIG env var should take highest precedence

flytekit/clients/auth_helper.py
Please see issue for a detailed explanation.
Tested with a user, got past the error in the issue, but still timing out.
https://github.com/flyteorg/flyte/issues/3715
=> Root cert should be byte string when loading from caCertFilePath

tests/flytekit/unit/core/test_type_conversion_errors.py
Hypothesis tests sometimes take more than the default 200ms to run
For example https://github.com/flyteorg/flytekit/pull/1678
_NA_
OR
=> Set a less strict deadline for hypothesis tests

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py, plugins/flytekit-kf-pytorch/setup.py
In https://github.com/flyteorg/flyteidl/commit/5a3a44f13415bf5ed8ac57cc5814b7277a85825f the kubeflow training operator plugins' protos where refactored.
In this PR I update the task to use the new `flyteidl.plugins.kubeflow.pytorch_pb2.ElasticConfig` instead of the legacy `from flyteidl.plugins.pytorch_pb2.ElasticConfig` (notice the addional `kubeflow`).
Without this fix, registration fails with this error:
```
│ /home/fabiogratz/miniconda3/envs/dev/lib/python3.9/site-packages/flytekitplugins/kfpytorch/task.py:371 in get_custom                               │
│                                                                                                                                                    │
│ ❱ 371 │   │   │   job = pytorch_task.DistributedPyTorchTrainingTask( …
```
=> Dep: Use protos of new `kubeflow.pytorch` plugin instead of legacy `pytorch` plugin

flytekit/bin/entrypoint.py, flytekit/core/base_task.py, flytekit/core/data_persistence.py
This PR:
-  allows users to view the remote URL for uploading and downloading in the time line deck
-  The process of "generating the timeline HTML file" has been moved to a later stage, allowing for the inclusion of more time-specific information. In the previous implementation, the user could not see the remote URL storing the 'output.pb' and 'deck.pb' files because the HTML file was generated too early. This adjustment ensures these important details are visible in the timeline.
https://github.com/flyteorg/flytekit/blob/c8433ea2d2ecf362815b1ee63554549ced9acd75/flytekit/bin/entrypoint.py#L159
Tested in the sandbox. We are now able to see the remote url in time line deck.
=> More time info for time line deck

flytekit/bin/entrypoint.py
the file 'deck.html' is always uploaded regardless of the deck setting in my previous [PR](https://github.com/flyteorg/flytekit/pull/1680). This PR fix this issue by modifying the upload logic to only upload 'deck.html' when the deck setting is enabled.
_NA_
OR
=> Upload 'deck.html' only when the deck is enabled

flytekit/image_spec/image_spec.py, plugins/flytekit-envd/flytekitplugins/envd/image_builder.py, plugins/flytekit-envd/tests/test_image_spec.py, tests/flytekit/unit/cli/pyflyte/test_run.py, tests/flytekit/unit/core/image_spec/test_image_spec.py, tests/flytekit/unit/core/test_python_function_task.py
Currently, we are unable to specify the pip index URL during package installation, although it is supported by envd. 
The purpose of this PR is to enable configuring the custom pip index url.
https://github.com/flyteorg/flyte/issues/3765
=> Support configuring pip index url with the image spec

flytekit/bin/entrypoint.py
Remove CalledProocessError, and only show user error
Before:
After:
Here is an example to reproduce it.
```python
import torch
@task
def t1():
print("helloee")
@workflow
def wf():
t1()
if __name__ == '__main__':
wf()
```
_NA_
_NA_
=> Improve error message for pyflyte-fast-execute

flytekit/__init__.py
In `flytekit==1.6.0` rich tracebacks were introduced (#1582).
Before, exceptions were shown like this:
After, they are shown like this:
This happens as long as `import flytekit` is called somewhere in the imported code base, also when not directly working with flyte.
---
Style ultimately is a question of taste but several of our engineers have complained about this change:
> When/Why did the stacktrace get so <s>ugly</s> colorful. It takes up way too much space and pycharm cannot create crosslinks to the files anymore for me :see_no_evil: And long lines are truncated
> I feel the same, does not help me
> Can we configure this
> I wanted to complain about this too :smile:
> The tracebacks contain way more (white space) characters, meaning I can paste a lot less of them into chat gpt …
=> Feat: Allow disabling rich tracebacks via env var

flytekit/core/interface.py, flytekit/core/type_engine.py, flytekit/types/pickle/pickle.py, tests/flytekit/unit/core/test_flyte_pickle.py, tests/flytekit/unit/core/test_interface.py, tests/flytekit/unit/core/test_type_engine.py
Fixed https://flyte-org.slack.com/archives/CP2HDHKE1/p1686574457772509.
This pr also allows users to use pickle in the dataclass.
`get_transformer` returns a pickle transformer if the type is unsupported
_NA_
=> get_transformer returns pickle transformer if type is unsupported 

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
With `@task(task_config=Elastic(...))` one can perform training with torch elastic launch (`torchrun`).
This works both locally as well as in a cluster with a kubeflow `PyTorchJob`.
When executing a workflow locally, i.e. `python workflow.py`, but setting e.g. `Elastic(nnodes=2)`, the rendezvous of the workers will timeout because the workers wait for the non-existing workers from the non-existing 2nd node to join.
One would have to set the log level to debug in order to see that torch is waiting for the rendezvous to complete. By default, the workflow appears to not do anything.
I thins PR I add a warning log message that informs the user about this.
I check for an environment variable that is set by the kubeflow training operator. If this is not set but the user set `nnodes>1`, the …
=> Feat: Warn when doing local torch elastic training with nnodes > 1

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py, plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
When using `@task(task_config=flytekitplugins.kfpytorch.Elastic())`, the task function is started in a number of worker processes using torch `elastic_launch` (`torchrun`). The processes can be created using fork or spawn which is controlled by the arg `Elastic(start_method=...)`.
When using `fork`, the child process inherits a copy of the parent process' stack including the flyte context and the user facing execution parameters `ctx = flytekit.current_context()`.
When spawning, however, fresh processes are started and the flyte context and the execution parameters are not transferred to the child process currently. This means that within a task with ``@task(task_config=Elastic(start_method="spawn"))` the execution id and the checkpoint cannot be accessed from the execution parameters. …
=> Fix config of user facing execution parameters in spawning elastic tasks

flytekit/core/map_task.py, tests/flytekit/unit/core/test_map_task.py
Fixes https://github.com/flyteorg/flyte/issues/3794. 
Fail registration if output isn't Optional when using map tasks with min_success_ratio < 1
^^^
https://github.com/flyteorg/flyte/issues/3794
_NA_
=> Fail registration if output isn't Optional when using map tasks with min_success_ratio < 1

flytekit/core/base_task.py
this [PR](https://github.com/flyteorg/flytekit/commit/06d95b805d36998b58cce93f3837f0bd0ec0b945) breaks it, because it moves `_outpu_deck` to `entrypoint.py` . we use `entrypoint.py` only when we run the workflow remotely.
^^^
https://unionai.slack.com/archives/C02CMUNT4PQ/p1687268923664029
_NA_
=> Generate decks at local execution

flytekit/core/base_task.py, flytekit/core/map_task.py, flytekit/core/task.py, flytekit/core/workflow.py
=> Improve task type hint

flytekit/core/promise.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/core/test_workflows.py
Upstream nodes were not correctly being detected in cases where the inputs were behind a {} or a [].  For example, `n1` here
```
def my_wf(a: int, b: str) -> (int, str):
x, y = t1(a=a)
d = t2(a={"key1": b, "key2": y})
return x, d
```
would not have picked up `n0` as an upstream node because we weren't correctly traversing the structure.
Found while implementing the now rejected generalized container types https://github.com/flyteorg/flytekit/pull/1700/files
Instead of iterating through the kwargs again, save nodes found while traversing the bindings from the promises.
Also get rid of the mostly duplicate `binding_from_flyte_std`
NA
=> Detect upstream nodes from container nested promises

flytekit/clis/sdk_in_container/serialize.py, flytekit/configuration/__init__.py, tests/flytekit/unit/cli/pyflyte/test_run.py, tests/flytekit/unit/core/test_context_manager.py
If not, if i do `pyflyte register --image custom=blah:latest ...` and i have non-"custom" tasks, registration fails.
Also this PR streamlines the behavior between `pyflyte serialize --image` ... and `pyflyte package --image ...`  (see the issue below for more information)
https://github.com/flyteorg/flyte/issues/3800
=> Always a default image and streamline image handling serialize vs package

flytekit/core/promise.py, flytekit/core/type_engine.py, flytekit/core/workflow.py, tests/flytekit/unit/core/test_promise.py, tests/flytekit/unit/core/test_type_conversion_errors.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/extras/sklearn/test_transformations.py
The ensure_literal call in workflow.py was a duplicate that we just didn't realize was a duplicate.  Removing and updating the existing function in promise with the correct union handling behavior.
This was discovered while implementing the now-defunct https://github.com/flyteorg/flytekit/pull/1700
NA
=> Remove ensure literal

flytekit/image_spec/image_spec.py
Cache the name of built images locally in order to have strong consistency. Otherwise, flytekit might rebuild the same image because some registries don't have strong consistency.
_NA_
OR
=> add imagespec cache

flytekit/bin/entrypoint.py
Fixes https://github.com/flyteorg/flyte/issues/3841
https://github.com/flyteorg/flytekit/pull/1693 introduced a bug in task templates like `SQlite3Task`. This PR fixes an issue in the execution entrypoint that assumes the all task objects have the `disable_deck` attribute.
Use the `getattr` function to get `disable_deck`, and return `False` if not present.
[https://github.com/flyteorg/flyte/issues/<number>](https://github.com/flyteorg/flyte/issues/3841)
=> use getattr to access task_def.disable_deck in entrypoint

flytekit/types/structured/__init__.py, flytekit/types/structured/basic_dfs.py, flytekit/types/structured/structured_dataset.py, tests/flytekit/unit/core/test_structured_dataset_handlers.py, tests/flytekit/unit/types/structured_dataset/test_structured_dataset_workflow.py
- [*] Feature
- [*] Code completed
- [*] Smoke tested
- [*] Unit tests added
add an encoder and decoder for pandas <-> CSV transformation
_NA_
OR
=> Csvtransform

flytekit/core/local_cache.py, tests/flytekit/unit/core/test_local_cache.py
Until now, the hash of a literal map is not carried over into the representative literal map entering the cache key computation, despite the code clearly stating so.
This commit enables carrying hashes from `LiteralMap`s over by explicitly setting the hashes on the representer literal map.
Also fixes a shadowing bug in the key-value loop over the literal map, which happened since the value argument and the input name were both `literal`.
This came up during internal tests, where it broke existing tests when I changed from a single `Literal` to a `LiteralMap` in a type transformer with an explicitly set hash value.
Minimal reproducer:
```py
from flytekit import Literal
from flytekit.core.local_cache import _recursive_hash_placement
from flytekit.models.literals import LiteralMap, Scalar, …
```
=> Carry over hash from literal maps in cache key computation

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py
* This PR fixes a small bug that made it more difficult to find the original exception in the stack trace that made an elastic task worker process crash.
* The PR also adds a warning that users should to use the retry mechanism of torch elastic launch instead of the retry mechanism of flyte when it comes to exceptions raised within the worker processes.
Let's consider this minimal task:
```python
@task(
task_config=Elastic(
nnodes=1,
nproc_per_node=1,
),
)
def train():
raise FooException("foo")
```
This currently results in this stack trace:
```console
FlyteScopedUserException:
…
raise FooException("foo")
FooException: foo
============================================================
During handling of the above exception, another exception occurred:
…
729  return …
```
=> Fix: Improve error handling in elastic tasks

flytekit/core/interface.py, flytekit/core/map_task.py, tests/flytekit/unit/core/test_interface.py, tests/flytekit/unit/core/test_map_task.py
Modify the interface of a map_task where min_success_ratio is set
Modify the interface of a map_task where min_success_ratio is set, instead of erroring during registration. 
https://github.com/flyteorg/flyte/issues/3794
_NA_
=> Detect if min_success_ratio is set and adjust interface of map_task accordingly

tests/flytekit/unit/bin/test_python_entrypoint.py
Don't do a network call to gcs in the unit tests
- ~~[ ] Code documentation added~~
- ~~[ ] Any pending items have an associated Issue~~
Unit tests were failing locally because it was trying to make a network call to gcs. Not sure how these were passing in CI, but added a patch to the `google.auth.compute_engine._metadata` module so network calls aren't make.
NA
_NA_
=> don't make network calls in unit tests

flytekit/deck/deck.py, tests/flytekit/unit/deck/test_deck.py
Use `utf-8` to encode flyte deck, and catch the error during generating the deck file to prevent the entire task from failing)
Fixes https://github.com/unionai/cloud/issues/3733
^^^
_NA_
_NA_
=> Use utf-8 to encode flyte deck

flytekit/extras/tasks/shell.py, tests/flytekit/unit/extras/tasks/test_shell.py
Improve the error returned by `ShellTask`. As of now, `ShellTask` error message is not helpful since it doesn't capture the `stderr` from the subprocess. Additionally, the error thrown by `ShellTask` is currently classified as system error instead of user error.
- Raise `FlyteRecoverableError` from `ShellTask` so that it's classified as user's error and the retry policy specified in the task is respected. 
- Improve the error message captured by `ShellTask`. As of now the error message generated by `ShellTask` in flyteconsole looks as follows. Notice that it doesn't contain any details of the failed command. 
```
[3/3] currentAttempt done. Last Error: SYSTEM::Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/flytekit/exceptions/scopes.py", line 165, in …
```
=> Improve error handling in ShellTask

flytekit/core/context_manager.py, flytekit/deck/deck.py, tests/flytekit/unit/deck/test_deck.py
Use default width settings for timeline deck
Before this change, the timeline deck will occupy 1400px of width on any of the mediums it's rendered in. For example, if we turn on execution on some of the flytesnacks docs pages, we get:
This PR will just use the default plotly settings, which will occupy the maximum width inside whatever container the plotly graphs are contained in.
_NA_
OR
=> use default settings for timeline deck width

.github/workflows/pythonbuild.yml, .gitignore
Optimize for quicker feedback in CI by runnning flytekit tests first and then the plugins
This PR also forces dependencies to be installed successfully before running tests. We've had multiple instances where dependencies failed to install but tests still ran (and invariably failed due to the missing dependencies).
_NA_
OR
=> Fail CI tests faster

.github/workflows/pythonbuild.yml, tests/flytekit/unit/cli/pyflyte/test_run.py
as title
Github docs for the list of environment variables set during CI runs: https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
_NA_
OR
=> Run unit tests on macos-latest

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py, plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
Adds `rdzv_configs` to `flytekitplugins.kfpytorch.Elastic` for[ additional rdzv configs](https://github.com/pytorch/pytorch/blob/main/torch/distributed/launcher/api.py#L45C18-L45C18).
=> add rdzv_configs to kfpytorch elastic

flytekit/__init__.py, flytekit/loggers.py
In https://github.com/flyteorg/flytekit/pull/1695 I introduced an environment variable called `FLYTE_SDK_RICH_TRACEBACKS` which, when set to 0, disables rich tracebacks.
Setting this environment variable turns this
back into:
However, in this PR I overlooked that a `RichHandler` is added to the flytekit logger which also produces output in rich format. When executing this workflow
```python
@task
def train():
raise Exception("This is a test")
@workflow
def wf():
train()
wf()
```
with `FLYTE_SDK_RICH_TRACEBACKS=0 python test.py`, the output still looks as follows:
This PR disables this logger as well when the above mentioned environment variable is set.
_NA_
_NA_
=> Fix: Disable rich logging handler when env var `FLYTE_SDK_RICH_TRACEBACKS=0` is set

flytekit/core/base_task.py, flytekit/core/condition.py, flytekit/core/context_manager.py, flytekit/core/gate.py, flytekit/core/map_task.py, flytekit/core/node_creation.py, flytekit/core/promise.py, flytekit/core/python_function_task.py, flytekit/core/reference_entity.py, flytekit/core/workflow.py, flytekit/remote/remote_callable.py
Address https://github.com/flyteorg/flyte/issues/3734 that nested Tasks/Workflows is not warned. 
In order to detect entities that are nested inside `@task`:
1. During local execution, create a new `FlyteContext` with `LOCAL_TASK_EXECUTION` for `@task`,and `LOCAL_WORKFLOW_EXECUTION` if it is `@workflow`.
2. If `flyte_entity_call_handler` is invoked inside `LOCAL_TASK_EXECUTION` or `TASK_EXECUTION`, that means it is called inside `@task`, warn the users of nested `@tasks/@workflows`.
Created a helper function `is_local_execution()` to shorthand the checks.
https://github.com/flyteorg/flyte/issues/3734
The __call__() function in remote_callable and reference_entity duplicates and can be replaced with `flyte_entity_call_handler` as well in the future.
=> Throw warning for nested @Task functions

doc-requirements.txt, setup.py
Remove dependency on responses
As reported in https://github.com/flyteorg/flyte/issues/3895, there is no need to depend on `responses` package.
https://github.com/flyteorg/flyte/issues/3895
Closes https://github.com/flyteorg/flyte/issues/3895
=> Remove dependency on responses

setup.py
Constrain grpcio to a working version while we investigate the weird "Stream removed" issue
_NA_
OR
=> Restrict grpcio<1.53.1

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_type_engine.py
As title
Hi community,
This is my first pr in Flyte. I have followed the contribution guide and if there is anything I missed, feel free to leave a comment.
I added a simple transformer for datetime.date.
The `to_literal_transformer` convert datetime.date to datetime.datetime.
The `from_literal_transformer` convert datetime.datetime to datetime.date.
Also, I add corresponding tests to test_type_engine.
https://github.com/flyteorg/flyte/issues/3026
Add datetime.date to https://docs.flyte.org/projects/cookbook/en/latest/auto_examples/type_system/flyte_python_types.html#flytekit-to-flyte-type-mapping
=> Add type transformer for datetime.date

flytekit/clis/sdk_in_container/run.py
- identify a task or a workflow
- task or workflow help menus show types and use rich to beautify
Before:
After:
=> Beautified pyflyte run even for every task and workflow

flytekit/remote/remote.py, tests/flytekit/unit/remote/test_remote.py
This PR fixes an issue causing `pyflyte run --remote`  to fail when using Azure. 
- [] Any pending items have an associated Issue
The PUT call to Azure Blob Storage returned an HTTP 400 Error: 
```
<?xml version="1.0" encoding="utf-8"?>
<Error>
<Code>MissingRequiredHeader</Code>
<Message>
An HTTP header that's mandatory for this request is not specified.
RequestId:ebd5dfbc-f01e-001d-5074-cb4f26000000
Time:2023-08-10T10:24:58.6553767Z
</Message>
<HeaderName>x-ms-blob-type</HeaderName>
</Error>
```
This is a starting point that unblocks me, but there's a discussion to be had regarding where you would like to handle such cases. Some open questions:
1. Should this be done on the client? And if yes, is that the right place?
2. Or should the response that contains the signed URL also specify …
=> Add Azure-specific headers when uploading to blob storage

flytekit/core/condition.py, flytekit/core/promise.py, tests/flytekit/unit/core/test_type_hints.py
This removes the `ref` property in the default NamedTuple object that gets used when a user want to name outputs.  This is done so that some can use an output named "ref" if they wanted to.  Previously it was getting co-opted by this property.
The property iterates through the list of outputs, and returns the first `NodeOutput` it sees, and the node gets extracted from that.  Instead of doing this, just store the Node object in the Case object, upon construction.
https://github.com/flyteorg/flyte/issues/3923
=> Remove ref in output

flytekit/configuration/__init__.py, flytekit/core/type_engine.py, flytekit/extras/pytorch/checkpoint.py, flytekit/extras/tensorflow/record.py, flytekit/types/directory/types.py, flytekit/types/file/file.py, flytekit/types/schema/types.py, flytekit/types/structured/structured_dataset.py, plugins/flytekit-aws-batch/flytekitplugins/awsbatch/task.py, plugins/flytekit-dbt/flytekitplugins/dbt/schema.py, plugins/flytekit-dolt/flytekitplugins/dolt/schema.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/schema.py, plugins/flytekit-greatexpectations/flytekitplugins/great_expectations/task.py, plugins/flytekit-kf-pytorch/tests/test_elastic_task.py, plugins/flytekit-onnx-pytorch/flytekitplugins/onnxpytorch/schema.py, plugins/flytekit-onnx-scikitlearn/flytekitplugins/onnxscikitlearn/schema.py, plugins/flytekit-onnx-tensorflow/flytekitplugins/onnxtensorflow/schema.py, plugins/flytekit-papermill/tests/testdata/datatype.py, tests/flytekit/unit/cli/pyflyte/default_arguments/dataclass_wf.py, tests/flytekit/unit/cli/pyflyte/workflow.py, tests/flytekit/unit/core/test_complex_nesting.py, tests/flytekit/unit/core/test_dataclass.py, tests/flytekit/unit/core/test_local_cache.py, tests/flytekit/unit/core/test_promise.py, tests/flytekit/unit/core/test_type_delayed.py, tests/flytekit/unit/core/test_type_engine.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/extras/pytorch/test_checkpoint.py, tests/flytekit/unit/extras/tasks/test_shell.py
When we use the `dataclass_json` decorator, the dataclass constructors are obscured, and we get pyright errors just instantiating them:
```python
import flytekit.configuration as flyte_config
fast_serialization_settings = flyte_config.FastSerializationSettings(
enabled=True,
destination_dir=".",
distribution_location=".",
)
```
[As it says in the dataclasses-json README](https://github.com/lidatong/dataclasses-json/blob/89578cb9ebed290e70dba8946bfdb68ff6746755/README.md?plain=1#L111-L129), we can inherit from `dataclasses_json.DataClassJsonMixin` instead for improved static type checking.
This one change eliminates 467 of the 1715 existing pyright errors (27.2%) from the `flytekit` module.
```python
@dataclass_json
@dataclass
class EntrypointSettings:
...
```
now becomes
```python …
```
=> Inherit directly from DataClassJsonMixin instead of using @dataclass_json for improved static type checking

flytekit/core/context_manager.py, tests/flytekit/unit/core/test_context_manager.py
If the secrets are a base-64 encoded string, `SecretsManager.get` will raise exception. So add `encoded_mode` to the function here to fix and help to load and return bytes.
_NA_
OR
=> Enable SecretsManager.get to load and return bytes

flytekit/__init__.py, flytekit/core/data_persistence.py, flytekit/core/type_engine.py, flytekit/types/directory/types.py, tests/flytekit/unit/core/test_type_engine.py
s3fs will try to read all the files in the directory into memory by default. we can specify the batch size for `s3fsFileSystem.put`, and it will dramatically reduce memory consumption.
Before: 
After (batch size = 100):
```python
from typing_extensions import Annotated
import os
from memory_profiler import profile
from flytekit import BatchSize
directory = "/tmp/test"
@task
@profile
def generate_files(num_files: int, filesize_mb: int) -> Annotated[FlyteDirectory, BatchSize(100)]:
os.mkdir(directory)
for i in range(num_files):
file_path = os.path.join(directory, f"file_{i}.txt")
with open(file_path, "w") as f:
f.write(str(os.urandom(filesize_mb * 1024 * 1024)))
return FlyteDirectory(directory, …
```
=> Batch upload flyte directory

flytekit/core/node.py, flytekit/core/resources.py, flytekit/core/tracker.py, tests/flytekit/unit/core/test_resources.py, tests/flytekit/unit/core/test_type_hints.py
This PR improves error messaging and disallows illegal operations in the following cases
- using incorrect type of overrides
- using incorrect type for resources
- using promises in overrides
https://github.com/flyteorg/flyte/issues/3990
=> Better error messaging for overrides

doc-requirements.txt, flytekit/core/condition.py, flytekit/core/promise.py, flytekit/core/type_engine.py, flytekit/models/core/condition.py, setup.py, tests/flytekit/unit/core/test_conditions.py, tests/flytekit/unit/models/core/test_workflow.py
Add support `is_none` in the condition
```python
import random
import typing
from flytekit import conditional, task, workflow
@task
def coin_toss(seed: int) -> typing.Optional[bool]:
r = random.Random(seed)
if r.random() < 0.5:
return True
return None
@task
def failed() -> int:
return -1
@task
def success() -> int:
return 0
@workflow
def wf(seed: int = 5) -> int:
result = coin_toss(seed=seed)
return conditional("test").if_(result.is_none()).then(success()).else_().then(failed())
if __name__ == '__main__':
wf()
```
https://github.com/flyteorg/flyte/issues/3514
_NA_
OR
=> Add is none function

flytekit/core/context_manager.py, flytekit/core/python_function_task.py
Fix https://github.com/flyteorg/flyte/issues/3995. Created a new execution state for dynamic execution, we don't throw warnings if we execute tasks inside a @dynamic execution. Ideally we should create a separate type for @dynamic. Validated in local Flyte cluster.
[https://github.com/flyteorg/flyte/issues/<number>](https://github.com/flyteorg/flyte/issues/3995)
With the fix
``` 
❯   pyflyte run --image localhost:30000/flytekit:2 --remote example.py workflow
```
Without the fix
```
❯ pyflyte run  --remote example.py workflow
```
=> Dynamic workflow should not throw nested task warning

flytekit/core/data_persistence.py
This change enables flytekit to make use of aks enabled workload identities. Before this change, reading and writing data to a storage account was only possible with setting env variables for the storage account key. With setting `anon` to False, the Default Credentials, which are provides by aks workload identities can be used. [See](https://github.com/fsspec/adlfs/blob/main/adlfs/spec.py#L193)
I tried the change myself by following this [guide](https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity). IMO, using workload identities should be default on azure since when connecting to other Azure Services like Key Vaults, workload identities are the way to go as well. 
[3962](https://github.com/flyteorg/flyte/issues/3962)
_NA_
=> Enable Azure Workload Identity for `fsspec` in `flytekit`

flytekit/core/type_engine.py, tests/flytekit/unit/core/test_structured_dataset.py
See issue for a description
Make lists and dicts skip the first check.
https://github.com/flyteorg/flyte/issues/3989
=> Fix list of annotated structured dataset

flytekit/core/tracker.py, plugins/flytekit-papermill/tests/test_task.py, plugins/flytekit-sqlalchemy/tests/test_task.py, tests/flytekit/unit/cli/pyflyte/test_register.py
Failed to register a shell task since extract_task_module returns the wrong module.
```python
from flytekit.extras.tasks.shell import ShellTask
t = ShellTask(
name="test",
script="""
echo "Hello World"
""",
)
```
^^^
_NA_
_NA_
=> Fix extract_task_module

flytekit/remote/__init__.py
=> Make FlyteRemote example slightly more copy/pastable

flytekit/clis/sdk_in_container/build.py, flytekit/clis/sdk_in_container/constants.py, flytekit/clis/sdk_in_container/launchplan.py, flytekit/clis/sdk_in_container/register.py, flytekit/clis/sdk_in_container/run.py, flytekit/clis/sdk_in_container/utils.py, flytekit/remote/remote.py, flytekit/tools/repo.py
register now supports a new option
```bash
pyflyte register module.py --activate-launchplans
```
It is also ofcourse possible to deactivate a launchplan
```bash
pyflyte launchplan every_min_installer --deactivate
```
https://github.com/flyteorg/flyte/issues/3109
=> Pyflyte register optionally activates schedule

.github/workflows/pythonbuild.yml
Not too often see failures in 3.9/3.10 but not in 3.8 or 3.11.  plugins are the exception, some more thought may need to go into that - may need to add some back.
=> Remove versions 3.9 and 3.10

flytekit/extend/backend/agent_service.py
Update agent metric name to follow the naming convention. 
https://prometheus.io/docs/practices/naming/
^^^
_NA_
=> Update agent metric name

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py, plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
Currently, Flyte decks don't work with the elastic tasks. This PR fixes this.
The reason is that the elastic task starts worker processes (as `torchrun` does). When a user creates a deck, this deck is appended to `flytekit.current_context().decks` *in the worker processes*. However, the upload of the deck happens based on the `ctx` in the parent process where these decks are never appended. The decks are, thus, never shown in the UI.
This PR fixes this by returning the list of decks from the worker processes and, for rank `0`, attaches those decks to the parent processes context.
_NA_
_NA_
=> Fix: Make sure decks created in elastic task workers are transferred to parent process

flytekit/clis/sdk_in_container/backfill.py, flytekit/remote/backfill.py, flytekit/remote/remote.py, tests/flytekit/unit/remote/test_remote.py
Adds new --no-fail-fast option to use `WorkflowFailurePolicy.FAIL_AFTER_EXECUTABLE_NODES_COMPLETE`
=> Backfill command now supports failure-policy

flytekit/core/context_manager.py
User gets confused as error message is missing useful prompts when they did not add secret_requests in task config to get secrets, this PR adds more clear error message.
_NA_
OR
=> Add more clear error  message when fetching secrets

flytekit/clis/sdk_in_container/run.py, flytekit/interaction/click_types.py, tests/flytekit/unit/cli/pyflyte/test_run.py, tests/flytekit/unit/cli/pyflyte/workflow.py
Prior to this PR, `pyflyte run` didn't support workflows with a default `None` value.
- ~~[ ] Code documentation added~~
- ~~[ ] Any pending items have an associated Issue~~
Updates the `pyflyte run` command to handle `None` values in the literal type converter.
NA
NA
=> Pyflyte run workflows correctly handles Optional[TYPE] = None

plugins/flytekit-mlflow/setup.py
Remove upper python constraint on flytekit-mlflow to allow for installation on 3.11, in line with other plugins.
_NA_
_NA_
_NA_
=> make mlflow plugin work with python 3.11

flytekit/configuration/__init__.py, flytekit/configuration/internal.py, flytekit/core/data_persistence.py, flytekit/types/structured/basic_dfs.py, plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py, tests/flytekit/unit/core/test_data.py, tests/flytekit/unit/core/test_data_persistence.py, tests/flytekit/unit/core/test_structured_dataset_handlers.py
Support Azure blob storage for storing metadata and raw data including structured datasets, without interrupting other standard Azure authentication. Also ensure `storage_options` are set consistently for all uses of fsspec. 
Its debatable. The original github issue was a bug for fixing Azure authentication but it could be argued that Azure blob storage support is a new feature. 
Added a new component to `DataConfig` for Azure similar to the ones for S3 and GCS. This allows configuring the flytekit's  storage account without disrupting other Azure auth that may be used by flyte task implementations. This is done by setting the environment variables `FLYTE_AZURE_STORAGE_ACCOUNT_NAME`, `FLYTE_AZURE_STORAGE_ACCOUNT_KEY`, `FLYTE_AZURE_TENANT_ID`, `FLYTE_AZURE_CLIENT_ID`, …
=> Better Azure blob storage support 

plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py, plugins/flytekit-snowflake/tests/test_agent.py
1. Update agent uri format
2. update the read private key with .pem
[Flyte Agent Ecosystem](https://github.com/flyteorg/flyte/issues/3936)
=> Update agent uri format

flytekit/exceptions/system.py, flytekit/extend/backend/agent_service.py, flytekit/extend/backend/base_agent.py, plugins/flytekit-mmcloud/tests/test_mmcloud.py, tests/flytekit/unit/extend/test_agent.py
Label request_failure metric with error_code to distinguish failure from an error.
^^^
_NA_
=> Label request_failure metric with error_code

plugins/flytekit-envd/setup.py
Starting with envd 0.3.37, pip install fails with
```
Downloading envd-0.3.37.tar.gz (328 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 328.6/328.6 kB 10.1 MB/s eta 0:00:00
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [41 lines of output]
WARNING:root:.GIT_TAG_INFO not found
File "<string>", line 37, in build_envd_if_not_found
File "/usr/local/lib/python3.11/subprocess.py", line 389, in call
with Popen(*popenargs, **kwargs) as p:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File …
```
=> Pin because not installing

flytekit/clients/auth/auth_client.py, flytekit/clients/auth/keyring.py
Fixes error caused when refresh token is expired. This is intermittent.
Problem of type
```
❯ pyflyte run --remote  test2.py wf --n 10
Running Execution on Remote.
E1004 23:00:53.300669000 8616083776 hpack_parser.cc:853]               Error parsing metadata: error=invalid value key=content-type value=text/html
E1004 23:00:53.790464000 8616083776 hpack_parser.cc:853]               Error parsing metadata: error=invalid value key=content-type value=text/html
E1004 23:00:53.863833000 8616083776 hpack_parser.cc:853]               Error parsing metadata: error=invalid value key=content-type value=text/html
E1004 23:00:53.937017000 8616083776 hpack_parser.cc:853]               Error parsing metadata: error=invalid value key=content-type value=text/html
Failed with Exception Code: SYSTEM:Unknown …
```
=> Fixes Auth issue, where refresh token is expired

tests/flytekit/unit/core/test_map_task.py
Closes: [4035](https://github.com/flyteorg/flyte/issues/4035)
Updated the examples to use `with_overrides(requests=Resources(...), limits=Resources(...))` instead of what was defined in the older version of flytekit.
https://github.com/flyteorg/flyte/issues/4035
_NA_
OR
=> [Docs]Updated examples for customizing resources

plugins/flytekit-snowflake/flytekitplugins/snowflake/agent.py
change key path to SNOWFLAKE_PRIVATE_KEY
[Flyte Agent Ecosystem](https://github.com/flyteorg/flyte/issues/3936)
=> change key path to SNOWFLAKE_PRIVATE_KEY

plugins/flytekit-identity-aware-proxy/setup.py
The flytekit identity aware proxy plugin introduced in https://github.com/flyteorg/flytekit/pull/1787 requires changes in flytekit's authentication logic which were introduced in the same PR. At the moment, the flytekit version is not pinned in the new plugin's `setup.py` though. In this PR I pin it to `>=1.10`, the next release that will contain those changes to the auth logic.
=> Dep: Pin min required flytekit version in IAP plugin

flytekit/clis/sdk_in_container/register.py
Remove a duplicate option.
The `@domain_option_dec` already handles domain.
=> Remove duplicate click option

flytekit/core/array_node_map_task.py
import of type `Any` in `flytekit/core/array_node_map_task.py:9` is not supported for the `typing_extensions` libraries previous versions. This version range should fix it, otherwise dependency resolution might cause the following error:
```
/usr/local/lib/python3.8/dist-packages/flytekit/__init__.py:240: in <module>
from flytekit.sensor.sensor_engine import SensorEngine
/usr/local/lib/python3.8/dist-packages/flytekit/sensor/__init__.py:1: in <module>
from .base_sensor import BaseSensor
/usr/local/lib/python3.8/dist-packages/flytekit/sensor/base_sensor.py:12: in <module>
from flytekit.extend.backend.base_agent import AsyncAgentExecutorMixin
/usr/local/lib/python3.8/dist-packages/flytekit/extend/__init__.py:47: in <module>
from flytekit.tools.translator import …
```
=> Update `typing_extension` Any import to typing due to `typing_extension` version compatibility

flytekit/core/base_task.py, flytekit/core/task.py, tests/flytekit/unit/deck/test_deck.py
Add an enable_deck parameter to `@task`
_NA_
OR
=> Add enable_deck to task decorator

dev-requirements.in, flytekit/core/type_engine.py, flytekit/experimental/eager_function.py, flytekit/types/file/image.py, plugins/flytekit-deck-standard/flytekitplugins/deck/renderer.py, plugins/flytekit-kf-pytorch/tests/test_elastic_task.py, plugins/flytekit-mlflow/README.md, plugins/flytekit-mlflow/tests/test_mlflow_tracking.py, tests/flytekit/unit/types/file/test_image.py
Add an image transformer, so the task can return PIL.Image.Image as an output,
My example:
```python
import io
from typing_extensions import Annotated
import requests
import PIL.Image
new_flytekit = "git+https://github.com/flyteorg/flytekit.git@da9f6645bb5e99580e38d89ef6824b81a1054279"
image_spec = ImageSpec(base_image="python:3.8-slim-buster", packages=[new_flytekit, "pillow"], apt_packages=["git"], registry="pingsutw")
@task(enable_deck=True, container_image=image_spec)
def t1() -> PIL.Image.Image:
url = "https://miro.medium.com/v2/resize:fit:1400/1*0T9PjBnJB9H0Y4qrllkJtQ.png"
response = requests.get(url)
image_bytes = io.BytesIO(response.content)
im = PIL.Image.open(image_bytes)
return im
@workflow
def wf():
t1() …
```
=> Add image transformer

flytekit/remote/remote.py
1. add default project domain in execute launch plan
2. add name as a parameter
When I executed a launch plan with FlyteRemote, it didn't run with default project domain of the remote but needed specified project domain. So, I fixed it with if there is no specified project domain, use default project domain of the remote.
https://github.com/flyteorg/flyte/issues/4249
_NA_
=> add default project domain in execute launch plan

flytekit/core/tracker.py
This PR fixes an issue reported [here](https://github.com/flyteorg/flyte/issues/4245) where `pyflyte` and other executables were trying to be loaded by the `tracker.py` module when finding trackable instances.
- ~~[ ] Smoke tested~~
- ~~[ ] Unit tests added~~ (will be added subsequently)
- ~~[ ] Code documentation added~~
- ~~[ ] Any pending items have an associated Issue~~
The [eager workflow](https://github.com/flyteorg/flytekit/pull/1579) PR introduced a bug that caused breakages in `@dynamic` workflows and agents. The underlying reason is that eager workflows need to be able to load task/dynamic/workflow functions as `InstanceTrackingMeta` instances so that it can execute them via `FlyteRemote`. The issue is that, before `1579`, `InstanceTrackingMeta` did not support loading entities …
=> Fix module loading bug in instance tracker class

plugins/flytekit-airflow/flytekitplugins/airflow/task.py
A flyte context has an [attribute](https://github.com/flyteorg/flytekit/pull/1912/files#diff-a1d44bc50c6abe11f7528e5162fe0140184607314e1a71ee2916a5e17977a5ccR75), but dynamic tasks override the current context, so airflow agent cannot get the attribute.
With this PR, `_flyte_operator` will return a flyte task if it fails to get the attribute from the flyte context.
```bash
File "/usr/local/lib/python3.10/site-packages/flytekit/exceptions/scopes.py", line 206, in user_entry_point
return wrapped(*args, **kwargs)
File "/root/flyte-example/airflow_example/bash_operator.py", line 15, in d1
b = BashOperator(task_id=f"airflow_bash_operator", bash_command="echo hello")
File "/usr/local/lib/python3.10/site-packages/flytekitplugins/airflow/task.py", line 55, in …
```
=> Use Airflow task insdie dynamic workflow

plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/error_handling.py, plugins/flytekit-kf-pytorch/flytekitplugins/kfpytorch/task.py, plugins/flytekit-kf-pytorch/tests/test_elastic_task.py
For some failures, users might want to retry a flyte task, for other failures not.
Flyte tasks can be marked as retriable by raising a `FlyteRecoverableException`.
Torch's `elastic_launch` (which is used by flytekit's `Elastic` task type) always raises a `ChildFailedError` even if in the worker process e.g. a `FlyteRecoverableException` was raised.
This means that Flyte's retry mechanism cannot be used for user errors in elastic tasks.
Elastic tasks offer `torchrun`'s retry mechanism by specifying `max_retries`. However, this retry mechanism (which doesn't restart the pod but the worker processes within the pod) will retry *all* exceptions which is not always desireable.
This PR makes elastic tasks work with Flyte's retry mechanism by propagating `FlyteRecoverableException` up from the …
=> [WIP] Fix: Allow elastic tasks to be recoverable

Dockerfile.dev
apply the same change as in https://github.com/flyteorg/flytekit/blob/master/Dockerfile#L24 to dev dockerfile because some pkgs implicitly create files under home
=> Make sure `$HOME` is writable in dev image

flytekit/core/promise.py, tests/flytekit/unit/core/test_references.py
Improve error message when, in a workflow, one omits to pass an optional kwarg to a task.
---
In python, the following is perfectly valid:
```python
def foo(bar: int=1) -> int:
return bar
def wf() -> int:
return foo()
```
In Flyte, the following workflow (which only adds task/workflow decorators) is not:
```python
@task
def foo(bar: int=1) -> int:
return bar
@workflow
def wf() -> int:
return foo()
```
The user is confronted with this error message:
```console
flytekit.exceptions.user.FlyteAssertion: Error encountered while executing 'wf':
Input was not specified for: bar of type <FlyteLiteral simple: INTEGER>
```
Many Flyte users are ML engineers that are not necessarily aware of the following ([source](https://docs.flyte.org/projects/cookbook/en/stable/getting_started/tasks_and_workflows. …
=> Improve error message when omitting task kwarg in workflows

Dockerfile, Dockerfile.agent
Disable caching of packages in images
Pass the `--no-cache-dir` flag in invocation of `pip install` in dockerfiles. This will have a bigger impact in the agent image, since currently we are using about ~800MB:
```
 docker run --rm -it ghcr.io/flyteorg/flyteagent:1.10.0 du -kh --max-depth=1 /root/.cache
813M    /root/.cache/pip
813M    /root/.cache
``` 
_NA_
OR
=> Do not cache packages in images

setup.py
Set protobuf to <4.25.0.
Some of unit tests are failing due to the changes in the latest protobuf. https://github.com/flyteorg/flytekit/actions/runs/6741354377/job/18325816188?pr=1918
^^^
_NA_
_NA_
=> Set protobuf to <4.25.0

flytekit/clis/sdk_in_container/fetch.py, flytekit/remote/data.py, flytekit/remote/remote.py
This makes it possible to use download in remote now! So fire away the jupyter notebooks. This still does not use streaming data, that has to be done using the underlying file system object!
=> Adds download command to remote.

flytekit/clients/auth/auth_client.py
The PKCE `AuthorizationClient` automatically opens a browser tab/window with the `/authorize` endpoint in order to receive the authorization code.
When ssh-ing into VMs, the browser window cannot be automatically opened. If one port-forwards the port used by the callback server, a pkce flow could still be done if only the authorization endpoint could be opened in the user's browser.
In this PR I change the `AuthorizationClient` so that it first tries to open the browser window automatically - as is already the case - but if this is not successful, simply asks the user to open the link.
_NA_
_NA_
_NA_
=> Feat: If PKCE AuthorizationClient cannot open browser, ask user to do so manually

dev-requirements.in
Failed to run lint test when using [latest mypy](https://pypi.org/project/mypy/#history). Temporarily set the upper bound for mypy.
^^^
_NA_
_NA_
=> Fix lint test

plugins/flytekit-polars/flytekitplugins/polars/sd_transformers.py, plugins/flytekit-polars/tests/test_polars_plugin_sd.py
When trying to use `flytekitplugins-polars` I would get the error:
```
Message:
Could not open Parquet input source '<Buffer>': Parquet file size is 0 bytes
User error.
```
Checking out the code, the `PolarsDataFrameToParquetEncodingHandler` actually places the parquet file at '{location}/00000', but it tries to read it at '{location}'
I think this is the easy solution, but maybe `PolarsDataFrameToParquetEncodingHandler` should be returning the '{location}/00000' instead of the parent directory?
=> Fix bug in polars parquet decoding handler

.github/workflows/pythonbuild.yml, Makefile, dev-requirements.in, dev-requirements.txt, tests/flytekit/unit/core/test_conditions.py, tests/flytekit/unit/core/test_type_hints.py, tests/flytekit/unit/core/test_workflows.py
Support `pytest-xdist` and enable it in the CI.
`pytest-xdist` uses `__channelexec__` as the top level environment so the function names are prefixed with `__channelexec__`.
Closes https://github.com/flyteorg/flyte/issues/4446
=> MAINT Adds support for pytest-xdist and enables it in the CI

.github/workflows/build_image.yml, .github/workflows/pythonbuild.yml, .github/workflows/pythonpublish.yml
This PR updates the GitHub actions to their latest versions. The workflows has been raising warnings:
=> MAINT Updates github actions to their latest versions

dev-requirements.txt, doc-requirements.txt, plugins/flytekit-aws-sagemaker/scripts/flytekit_sagemaker_runner.py, setup.py, tests/flytekit/integration/remote/mock_flyte_repo/workflows/requirements.txt
This PR removes the natsort dependency.
From reading the example, the prefix `__FLYTE_CMD_` is always followed by an integer:
https://github.com/flyteorg/flytekit/blob/28612676b3820c73fb0ae8c4f2f4457dedf16651/plugins/flytekit-aws-sagemaker/scripts/flytekit_sagemaker_runner.py#L22-L27
Thus, we can cast the string into an integer for sorting purposes.
Towards https://github.com/flyteorg/flyte/issues/4418
=> MAINT Remove natsort dependency

flytekit/remote/remote.py
This PR handles the case for gate nodes while fetching an execution using flyte remote, preventing the `AttributeError: 'FlyteGateNode' object has no attribute 'interface'` error.
fixes https://github.com/flyteorg/flyte/issues/4398
_NA_
OR
=> add support for gate nodes in `sync_node_execution`

flytekit/core/base_task.py, tests/flytekit/unit/deck/test_deck.py
This PR adds a deprecation warning so users can be informed and migrated their code to use `enable_deck`.
Follow up to https://github.com/flyteorg/flytekit/pull/1898
I was about to open an issue for this feature, but I found that it was already implemented. 
This PR uses a `FutureWarning` because it is shown by default. `DeprecationWarning` are hidden in most situations and requires a user to explicitly convert them to errors to see them.
=> Adds deprecation warning for disable_deck and point to enable_deck
